### ISSUE TITLE
[Bug] Playerships not Spawnable Szenario Empty

### ISSUE THREAD

**Issue by TolotosRhodan** [daid/EmptyEpsilon#1008]
At the EE-2020.08.07 Windows Version, after you Select the "Empty" game Szenario and try to select/Spawn a Playership you get the message of 
"table: 0b79b5b0 nil" on the debug screen, and no Playership appears. Even as GM it's not possible to spawn a Playership.

**Comment by TolotosRhodan** [comment]
I quess it's something with the:

onNewPlayerShip(
    function(ship, index)
        print(ship, index)
        ship:destroy()
    end
)

part, causing an error.

**Comment by capt-t** [comment]
The `nil` is a bug in the script, the callback seems to have only the parameter `ship`.
```c++
	gameGlobalInfo->on_new_player_ship.call(P<PlayerSpaceship>(this));
```

This leaves the question whether the `destroy` is the intended behavior of this scenario.

**Comment by capt-t** [comment]
The `nil` is a bug in the script, the callback seems to have only the parameter `ship`.
```c++
	gameGlobalInfo->on_new_player_ship.call(P<PlayerSpaceship>(this));
```

This leaves the question whether the `destroy` is the intended behavior of this scenario.

**Comment by capt-t** [comment]
The `nil` is a bug in the script, the callback seems to have only the parameter `ship`.
```c++
	gameGlobalInfo->on_new_player_ship.call(P<PlayerSpaceship>(this));
```

This leaves the question whether the `destroy` is the intended behavior of this scenario.
