### ISSUE TITLE
CpuShip with 0 hull

### ISSUE THREAD

**Issue by capt-t** [daid/EmptyEpsilon#1009]
`CpuShip`s still fly with 0 (probably point something) hull points.

It is not really a bug, but 0 hull usually means destroyed.

**Comment by StarryWisdom** [comment]
it would be nice if the science screen did the equvialent of min(1,hullstrength) before displaying it, I think that is the only place where it is seen

**Comment by capt-t** [comment]
That would also be a solution.

**Comment by StarryWisdom** [comment]
fixed in 51be1e2d
