### ISSUE TITLE
Shield state feedback.

### ISSUE THREAD

**Issue by zorilya** [daid/EmptyEpsilon#101]
Playing Empty Epsilon last night the way in which Info about the shields is fed back to players is a little lacking.

I would like to suggest potential improvements.

<B>Engineering / damage control screen:</B>
This screen is one of the only places where there is any representation of the ship and I think this might be a good place to include something like a visual representation of the shield arcs like this 

(=H=) 

where =H= is the current damage control display and the brackets are the shields arcs wrapping around the ship. They could change colour depending on strength of course and perhaps be a flashing grey when re calibrating. 

I think this kind of visual feedback would resulting in less time wondering "why are we losing energy so fast.... oh damn it ... shields have been on this whole time guys ... my bad" and give a better feel to taking shield hits. Red is a scary colour when it's on your shields after all, much scarier that a readout that says 20%. Think how intimidating both combined would be.

<B>Other stations:</B>
There is of course the Idea that we might have the shield state indicators wrapped around the ship in helm and weapons but honestly I think It would be great to have the info (or atleast detailed info) on shields with the engineer anyway... perhaps have the option to display shields only with damage control or with both damage control and helm/weapons.

**Comment by daid** [comment]
The latest version has shields visible around ships. I just added that this shield for the player disappears when the shields are offline. Will make it very visible for both helms and weapons when the shields are on/off.

So now I just need to add an indicator on engineering.

**Comment by zorilya** [comment]
Great work man. I'll give it a try :)
