### ISSUE TITLE
Flatpak for Linux

### ISSUE THREAD

**Issue by Bloodaxe95** [daid/EmptyEpsilon#1021]
Not sure if this is the right place to post this. But I've had a few issues with EmptyEpsilon on Linux, primarily with different distros keeping the game updated at different paces.

I'm unfortunately not the most tech-savy individual, but maybe releasing a version on Flathub would make it easier for non-techsavy Linuxusers to stay up-to-date with everyone else? Just a proposition ofc, not a demand 😁

**Comment by jstsmthrgk** [comment]
Done: https://flathub.org/apps/io.github.daid.EmptyEpsilon (I guess the issue can be closed now)
