### ISSUE TITLE
bug: ship control codes not working

### ISSUE THREAD

**Issue by Piglit** [daid/EmptyEpsilon#1030]
When a ship control code is set via the game master tweak menu,
clients can not connect anymore. They are always shown the "wrong code" message.

**Comment by StarryWisdom** [comment]
I think this is related to case sensitivity.

based on a quick look I think the control code on the tweak menu keeps case and the input for the control code converts everything to upper case.

Its somewhat harder to be 100% sure as empty epsilons font is only upper case.

In the mean time it can be worked around with using all upper case on the tweak menu.
