### ISSUE TITLE
feature request: Options submenu to change keybindings

### ISSUE THREAD

**Issue by Piglit** [daid/EmptyEpsilon#1034]
A in-game menu to change keybindings would be nice.
Not every player is able to edit options.ini.

Joystick buttons and axis should be considered, too.

**Comment by oznogon** [comment]
#1050 is merged, adding a keybindings menu to the Options menu. It isn't designed to remap joystick controls at present, and I don't have a joystick to test against.

**Comment by muerteFR** [comment]
@gcask  Maybe close it?

**Comment by gcask** [comment]
Fair point, but I do not yield this much power :)
