### ISSUE TITLE
Bug: maximum impulse is 99% when using joystick axis

### ISSUE THREAD

**Issue by Piglit** [daid/EmptyEpsilon#1035]
A player in my crew used his joystick to control the impulse drive.
He noticed, that the impulse slider displayed max. 99% when he pushed the joystick.

I do currently not know if this is an issue within the game, or with the joystick axis configuration.

Can someone confirm or prove this wrong?

**Comment by gcask** [comment]
Looks like you're right: From what I can see it seems the deadzone mechanics is messing sligthly with the axis range: Currently it cannot reach 100% (stuck at 99.75)
