### ISSUE TITLE
FEATURE REQUEST: NPC ship command "go to"

### ISSUE THREAD

**Issue by ElectricErger** [daid/EmptyEpsilon#1044]
# Synopsis
When GMing there's a limit to how many types of missions you can create with the base tools. One tool that would enable various scenarios would be the ability to tell ships to "go to this point" or "follow this ship".

## Details
While not an exhaustive list, the following types of missions could be planned/would benefit from this feature:
- Escort
- Station assault
- Transport ship raids

## Workarounds
I've gotten pretty far by just changing the faction to `Independent` and literally dragging the ship along for escort missions. As for assault missions, I've been able to keep the ships close enough, but far enough away to make it possible for my PCs to get to the point (if they try hard enough). 

# Ask
When a(n NPC) ship is selected, in orders, a new button for "goto" (point) and/or "follow" (object).

**Comment by daid** [comment]
Right click does exactly this...

**Comment by nallath** [comment]
As daid already said; You can right click on another ship when you have one or more ships selected. At that point it will get the "defend target" order (and it will stay close to that target)
