### ISSUE TITLE
gui_autolayout and destroy

### ISSUE THREAD

**Issue by StarryWisdom** [daid/EmptyEpsilon#1047]
if an GuiElement is destroyed from within a GuiAutoLayout the next frame it is spaced as if it is present (but correctly is not rendered), the frame after that it is all rendered correctly.

A quick grep seems to imply this is not done in the current code base, but its possible I missed it.

gui2_autolayout.cpp:80 is responsible for advancing the location, it doesn't take destroyed status into account, gui2_container.cpp:21 is renders/manages the destroyed status, currently they are run in the reverse order.

gui2_autolayout.cpp:80 could be fixed via wrapping it in a check of the destroyed flag (after it being exposed or friended), this was tested locally and works.

the order of the calls could be changed probably, I have not looked at that, I have also not looked to see if other gui elements are effected.

I do not have a minimal test case to ensure fixes are correct, there is a possibility that this only happens when called from within onDraw.

**Comment by czenker** [comment]
I think I have seen the behavior you describe with custom buttons. Maybe this is the test case you have been looking for:

````lua
-- Name: Test
-- Description: For testing

function init()
    local player = PlayerSpaceship():setFaction("Human Navy"):setTemplate("Atlantis")
    local stateOn, stateOff

    stateOn = function()
        player:removeCustom("state_off")
        player:addCustomButton("helms", "state_on", "On", stateOff)
    end
    stateOff = function()
        player:removeCustom("state_on")
        player:addCustomButton("helms", "state_off", "Off", stateOn)
    end

    stateOn()
end

function update()
end
````
Thanks for digging in so deep to find the root cause of the issue. Did you fix it in the mean time? At least on the master branch the issues with the flickering buttons still exists.
