### ISSUE TITLE
BUG - Station Screen going blank

### ISSUE THREAD

**Issue by matthiaswlkp** [daid/EmptyEpsilon#105]
Yesterday we tried to play the latest version and apparently only me, running the server, was experiencing a weird graphic glitch - occasionally my screen was going blank and I had to return to station selection screen and back. Sometimes that didn't help and had to repeat that several times. It seemed that it usually happened when the ship was going to warp, but not only then.

**Comment by daid** [comment]
Most likely it's the post processing shader for warp giving issues. It works fine on my machine, our random-laptop setup at the office also had issues.

Workaround is setting disable_shaders to 1 in the options.ini, but this also disables mainscreen view.

**Comment by matthiaswlkp** [comment]
After restarting the game, it worked fine, so it was incidental. I will monitor it and if it comes back, I'll try to see if there is a pattern.
