### ISSUE TITLE
Mission scripting organisation

### ISSUE THREAD

**Issue by zorilya** [daid/EmptyEpsilon#107]
I have been looking though the mission scripts and I can't help but notice that things like distance functions and rounding functions are defined at the end of every mission script where the are utilized.

Is there no support for something like Include statements for a library of functions that you maintain elsewhere?

**Comment by Fouindor** [comment]
The LUA "require" command is disabled in the scripting engine, so as of now, there is no "common library".

**Comment by daid** [comment]
I disabled the "module" that delivers "require" out of security reasons. As it's possible to "break out of the box" per default. Which would make it possible for "virus" mods.

**Comment by daid** [comment]
I've added a custom implementation of the require function. Not tested it yet, but it should allow to build an util.lua module that we can use in other files to build a set of utility functions.

**Comment by Wrongtown** [comment]
That sounds great, I've been thinking that the timer I needed help with the other day is a candidate for this type of thing.

**Comment by daid** [comment]
I've been working on actual tutorials. So utility functions will help on this area as well.

**Comment by Wrongtown** [comment]
Yeah I noticed the tutorial work, good stuff! Though I haven't had time to compile and check it out it seems like you've implemented a way to show messages straight to the stations? Will be great to have some proper tutorials, and I liked the vibe of the sections I read.

**Comment by daid** [comment]
I've implemented a special "tutorial" button on the main menu. This creates the tutorial script, and gives it access to extra functions, like forcing the player to a certain station, showing a message with or without a "next" button.

So far it is 1 linear tutorial. Starting with basic stuff on the radar, and then going trough each station explaining the basics. I do want to add that you can select which station tutorial you want to view. But first I rather write all the basic tutorials.

**Comment by Wrongtown** [comment]
Sounds like a solid approach :)
