### ISSUE TITLE
FEATURE REQUEST: Allow joystick buttons to trigger hotkeys

### ISSUE THREAD

**Issue by fiskn** [daid/EmptyEpsilon#1070]
For custom consoles, it would be very useful if device's acting as joystick buttons could trigger actions in EE. I'm thinking about a big red button for jumping...etc

Happy to have a stab at this, if I can be pointed in the right direction. I can see in the code (Helm screen for example) where it checks for Joystick axis position [HelmsScreen::onJoystickAxis], but it doesn't look like it's checking for button status. I can also see some of the SFML code for setting up the joystick elsewhere, but I'm missing the link as to how the [HelmsScreen::onJoystickAxis] function is getting passed the current joystick status to be able to code in button support.

**Comment by fiskn** [comment]
I've looked closer at the code and I can now see that this has already been implemented and you need to place the joystick button in the format of [B0] for joystick button0. I will look to submit a PR for updating the wiki with this as I couldn't see information on how to configure this anywhere.

**Comment by daid** [comment]
The wiki can just be updated without a PR.
