### ISSUE TITLE
Multiples game masters

### ISSUE THREAD

**Issue by AlanFonderflick** [daid/EmptyEpsilon#1085]
Hi there,

I would like to know if there is currently a way (or scripting way) to have at least to game masters in a server. It would enable a better game mastering when multiple player teams are involved. 
Is it too hardcoded in server launching system ?

**Comment by tdelc** [comment]
Hi,

It is available in my fork : https://github.com/tdelc/EmptyEpsilon

And with this PR : https://github.com/daid/EmptyEpsilon/pull/965

But I don t know if there is still some difficulty to include it. All work great, excepting tweak which is only available from server.

**Comment by amir-arad** [comment]
> All work great, excepting tweak which is only available from server.

Also, in the server (and not on client GM) you can see line indicators for the AI's directives / pathfinding. meaning, where each ship is going. it is mostly very hard to notice, one need a good screen.

**Comment by AlanFonderflick** [comment]
Thanks for your responses, it will help us organize some roleplaying game around this with several crew at once ;)

**Comment by amir-arad** [comment]
@AlanFonderflick a Fellow larp developer! good luck sir! you should keep track of @tdelc 's fork, as it is designed to be a long term solution for EE larps.

**Comment by AlanFonderflick** [comment]
Then I will do so, sir.
