### ISSUE TITLE
Case-sensitive typo causing Linux builds to fail on scanprobe.h

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#110]
Beginning on commit e792f72 will not build on Linux due to being case-sensitive for new include in file _src/screens/crew6/scienceScreen.h_
```#include "spaceObjects/scanprobe.h"```

Should be
```#include "spaceObjects/scanProbe.h"```

(scanprobe.h does not exist, where scanProbe.h does)

**Comment by kwadroke** [comment]
Should build fine on Windows as it is case-insensitive.

**Comment by Fouindor** [comment]
Woops, thanks for the heads-up ^^
