### ISSUE TITLE
REQUEST - Language system

### ISSUE THREAD

**Issue by Corbi** [daid/EmptyEpsilon#112]
Hi,

I'm from spain, and I was trying to edit files to translate the game in Spanish for play with some friends, but it's too dificult at this time.

¿Could you develop some kind of translation system with a string modification file per example?

Thanks and sorry for my bad english.

**Comment by Fouindor** [comment]
Hello, I'm currently working on the french and spanish translations of the basic GUI (see #46). However, script files would remain language-dependant.

**Comment by polikarpovst** [comment]
@Fouindor Hello! I would like to make a russian translation for EE. Did you fix a utf-8 string problem for your french translation?

**Comment by gcask** [comment]
This feels done? https://github.com/daid/EmptyEpsilon/wiki/Translation-and-Localization
