### ISSUE TITLE
Request - Explanation on how to destroy and respawn with GM function

### ISSUE THREAD

**Issue by Jhovall** [daid/EmptyEpsilon#113]
Dear All,

I have got a question. I want the option to destroy every object in the game, besides the GM-spawned stuff and the player, and respawn it. For this I would like to use the GM-function option and untill now I cannot figure out how to do it.

I have tried the following test-code but I could not get it working, could anyone help me? The reason I want this, is because I am coding for a larp and the GM's have some influence over the enemy ships. But last test-larp the GM accidentally destroyed the wormhole, which leads to the script not working anymore due to my destroy all and go to the next level -  function. 

function init()
    targetx = -500000
    targety = -500000
    addGMFunction("Destroy and Respawn All", function()

```
--destroyObjects()
-- for n=1,#memObjects() do
    -- if memObjects[n,#,#] == 1
    -- table.insert(Objects, Nebula():setPosition(x1+x2, y1+y2))
-- end

for n=1,#Objects do
    Objects[n]:destroy()
end
Objects = {}

for n=1,#memObjects() do
    klasse =   memObjects[n][0]   
    x =  memObjects[n][1]    
    y =  memObjects[n][2]       

    table.insert(Objects,  klasse():setPosition(x, y))
end
end)
--Set the initial mission state to go to next state

mission_state = missionStartState
```

end

function  missionStartState(delta)
    --insert the first area here. A wormhole is required to target x and target y.

```
table.insert( Objects, WormHole():setPosition(-1000, -1000):setTargetPosition(targetx,targety))

memObjects = Objects;
```

end

**Comment by daid** [comment]
One way of doing it, is instead of adding a GM function, is constantly checking if your most vital objects are there:
```
function init()
    ensured_object_list = {}
    other_object_list = {}
    
    createWorldA()
end

function createWorldA()
    resetWorld()
    table.insert(ensured_object_list, {nil, function()
        return WormHole():setPosition(-1000, -1000):setTargetPosition(5000,5000)
    end})
    table.insert(ensured_object_list, {nil, function()
        return Nebula():setPosition(3000, 1000)
    end})
    table.insert(other_object_list, CpuShip():setTemplate('Fighter'):setPosition(5000, 5000):orderRoaming())
end

function resetWorld()
    for _, data in ipairs(ensured_object_list) do
        if data[0] ~= nil and data[0]:isValid() then
            data[0]:destroy()
        end
    end
    for _, data in ipairs(other_object_list) do
        if data:isValid() then
            data:destroy()
        end
    end
    ensured_object_list = {}
    other_object_list = {}
end

function update(delta)
    --Check if all ensured objects are still there.
    for _, data in ipairs(ensured_object_list) do
        if data[0] == nil or not data[0]:isValid() then
            data[0] = data[1]()
        end
    end
end
```

What I did here, is I created an array, in which each element contains 2 values. The first one is the "pointer" to the object, the second one is the function that can create that object.
The update function checks if the object is destroyed or still needs to be created, and creates is then it's not there.
It also keeps track of a 2nd array with objects that it needs to destroy when a new world is created, but does not check if these objects are destroyed at runtime.

You could also link the update to a GM function instead.
The GM functions can just call different "createWorld" versions with this code, as this clears out and resets the list.

(untested code)

**Comment by Jhovall** [comment]
I get it, thanks a lot! 

Now I am wondering, I created a random space generator, for the 'boring' part of space travel, could I also recall those random spaces? It is something like this.

function createRandomSpace(nrOfClusters, xOffset, yOffset)
	for n=1,nrOfClusters do
		local x1 = random(-80000, 80000) + xOffset
		local y1 = random(-80000, 80000) + yOffset
		
		-- Create some random nebulas
		for n=1,random(1, 5) do
			local x2 = random(-20000, 20000)
			local y2 = random(-20000, 20000)

			table.insert(Objects, Nebula():setPosition(x1+x2, y1+y2))
			--table.insert(memObjects, 1, x1+x2, y1+y2)
		end
		
		-- create some visual random asteroids
		for n=1,random(0, 100) do
			local x2 = random(-60000, 60000)
			local y2 = random(-60000, 60000)
			table.insert(Objects, VisualAsteroid():setPosition(x1+x2, y1+y2))
			--table.insert(memObjects, 2, x1+x2, y1+y2)
		end
		
		-- create some random asteroids
		for n=1,random(0, 30) do
			local x2 = random(-20000, 20000)
			local y2 = random(-20000, 20000)
			table.insert(Objects, Asteroid():setPosition(x1+x2, y1+y2))
			--table.insert(memObjects, 3, x1+x2, y1+y2)
		end
		
		
    end
end
