### ISSUE TITLE
Bug - Mines only do system damage

### ISSUE THREAD

**Issue by Jhovall** [daid/EmptyEpsilon#114]
I have noted that mines currently only do system damage and no hull or shield damage, is this a bug or a feature?

**Comment by Fouindor** [comment]
On which version ? Tested it on both 16/01/16 and latest version and mines do normal damage. Is there a particular set of condition to make it happen ?

There was a version last month where mines were bugged, see 40af9d0768fa7538dba2879dda5c8a3c009b0a79

(But what you describe could be added as a feature, something like EMP mines)

**Comment by Jhovall** [comment]
It is the version from the site. (21-12 , but I see there is an update now)
 (Combined with some alterations, but which 'should' not influence anything).

**Comment by daid** [comment]
Fixed in: https://github.com/daid/EmptyEpsilon/commit/40af9d0768fa7538dba2879dda5c8a3c009b0a79
