### ISSUE TITLE
Bugs in scenarios when language=fr in options.ini

### ISSUE THREAD

**Issue by muerteFR** [daid/EmptyEpsilon#1155]
From the latest online version Win32_EmptyEpsilon_EE-2020.11.23.zip installed on Windows 10 I encounter several bugs when language = fr in options.ini.
I was afraid that it was with my modifications of fr.po but not at all, it already does it on the original file without any modification.

Example 1: For the Basic scenario (none variation), at the start of the game, the game is already over and indicates VICTORY.

Example 2: For the Borderline fever scenario, an error appears, (see image)

**3. "RESOLVED"**  
Example 3: for the Scurvy Scavenger scenario, when I click on START SCENARIO, go back by clicking on SCENARIO SELECTION and click again on START SCENARIO, the game crashes.

![Bugs fr Borderlinefever](https://user-images.githubusercontent.com/61491656/100553861-eabf0a00-3290-11eb-90ad-67eda821f2a9.jpg)

**Comment by oznogon** [comment]
Logs would help. Separate issues for each scenario might also, because these won't have the same causes in each instance.

For example, the log from reproducing this behavior on scenario_00_basic:

```
[ERROR] LUA: init: [string "scenario_00_basic.lua"]:193: unknown variation, could not set enemy_group_count
```

Relevant code in the scenario: https://github.com/daid/EmptyEpsilon/blob/c4788e4ebf84da67502f18ce51f2011911bc8db3/scripts/scenario_00_basic.lua#L183-L193

The number of enemy waves is determined by a literal string comparison of the Variant name. The variant names have been translated to French and no longer match. The comparison fails, doesn't fall back onto a default, and results in the `assert`. If there's no value for `enemy_group_count`, then there are no enemies, so therefore the victory condition is met.

The fix might be to wrap these string values in `_()`. Or it might be to not set the enemy wave count in this manner.

**Comment by muerteFR** [comment]
1st problem:
Here is the log file after launching the Basic scenario with language = fr 
But I don't understand how "The variant names have been translated to French and no longer match." while the scenario_00_basic.lua file is not modified with _ ()?
I'm not a developer, just curious.
 

[INFO]  Loaded: packs/Angryfly.pack with 166 files
[INFO]  Loaded: packs/Asteroids.pack with 30 files
[INFO]  Loaded: packs/msgamedev.pack with 96 files
[INFO]  Loaded: Tokka_WalkingMan.png with 6 sprites
[INFO]  Loaded shader: glitch
[INFO]  Loaded shader: warp
[INFO]  OpenGL version: 4.6
[INFO]  Load script: model_data.lua
[INFO]  Load script: shipTemplates.lua
[INFO]  Load script: factionInfo.lua
[INFO]  Model data: AdlerLongRangeScoutGrey is not used by any ship template
[INFO]  Model data: AdlerLongRangeScoutWhite is not used by any ship template
[INFO]  Model data: AtlasHeavyFighterBlue is not used by any ship template
[INFO]  Model data: AtlasHeavyFighterGreen is not used by any ship template
[INFO]  Model data: AtlasHeavyFighterGrey is not used by any ship template
[INFO]  Model data: AtlasHeavyFighterWhite is not used by any ship template
[INFO]  Model data: HeavyCorvetteBlue is not used by any ship template
[INFO]  Model data: HeavyCorvetteGrey is not used by any ship template
[INFO]  Model data: HeavyCorvetteWhite is not used by any ship template
[INFO]  Model data: LaserCorvetteBlue is not used by any ship template
[INFO]  Model data: LaserCorvetteGrey is not used by any ship template
[INFO]  Model data: LaserCorvetteWhite is not used by any ship template
[INFO]  Model data: LaserCorvetteYellow is not used by any ship template
[INFO]  Model data: LightCorvetteBlue is not used by any ship template
[INFO]  Model data: LightCorvetteGreen is not used by any ship template
[INFO]  Model data: LightCorvetteWhite is not used by any ship template
[INFO]  Model data: LightCorvetteYellow is not used by any ship template
[INFO]  Model data: LindwurmFighterGreen is not used by any ship template
[INFO]  Model data: LindwurmFighterGrey is not used by any ship template
[INFO]  Model data: LindwurmFighterRed is not used by any ship template
[INFO]  Model data: LindwurmFighterWhite is not used by any ship template
[INFO]  Model data: MineLayerCorvetteBlue is not used by any ship template
[INFO]  Model data: MineLayerCorvetteGreen is not used by any ship template
[INFO]  Model data: MineLayerCorvetteGrey is not used by any ship template
[INFO]  Model data: MineLayerCorvetteRed is not used by any ship template
[INFO]  Model data: MineLayerCorvetteWhite is not used by any ship template
[INFO]  Model data: MineLayerCorvetteYellow is not used by any ship template
[INFO]  Model data: MissileCorvetteBlue is not used by any ship template
[INFO]  Model data: MissileCorvetteGrey is not used by any ship template
[INFO]  Model data: MissileCorvetteRed is not used by any ship template
[INFO]  Model data: MissileCorvetteWhite is not used by any ship template
[INFO]  Model data: MissileCorvetteYellow is not used by any ship template
[INFO]  Model data: MultiGunCorvetteBlue is not used by any ship template
[INFO]  Model data: MultiGunCorvetteGreen is not used by any ship template
[INFO]  Model data: MultiGunCorvetteGrey is not used by any ship template
[INFO]  Model data: MultiGunCorvetteRed is not used by any ship template
[INFO]  Model data: MultiGunCorvetteWhite is not used by any ship template
[INFO]  Model data: MultiGunCorvetteYellow is not used by any ship template
[INFO]  Model data: SensorBuoyMKI is not used by any ship template
[INFO]  Model data: SensorBuoyMKII is not used by any ship template
[INFO]  Model data: SensorBuoyMKIII is not used by any ship template
[INFO]  Model data: WespeScoutBlue is not used by any ship template
[INFO]  Model data: WespeScoutGreen is not used by any ship template
[INFO]  Model data: WespeScoutGrey is not used by any ship template
[INFO]  Model data: WespeScoutWhite is not used by any ship template
[INFO]  Model data: ammo_box is not used by any ship template
[INFO]  Model data: artifact1 is not used by any ship template
[INFO]  Model data: artifact2 is not used by any ship template
[INFO]  Model data: artifact3 is not used by any ship template
[INFO]  Model data: artifact4 is not used by any ship template
[INFO]  Model data: artifact5 is not used by any ship template
[INFO]  Model data: artifact6 is not used by any ship template
[INFO]  Model data: artifact7 is not used by any ship template
[INFO]  Model data: artifact8 is not used by any ship template
[INFO]  Model data: battleship_destroyer_2_upgraded is not used by any ship template
[INFO]  Model data: shield_generator is not used by any ship template
[INFO]  Model data: small_frigate_1 is not used by any ship template
[INFO]  Model data: small_frigate_2 is not used by any ship template
[INFO]  Model data: space_frigate_6 is not used by any ship template
[INFO]  Using "OpenAL Soft on Mixage stéréo (Realtek High Definition Audio)" for voice communication
[INFO]  hardware.ini not found. Not controlling external hardware.
[WARN]  Discord not installed or not running. Not using discord rich presence
[INFO]  Loaded: gui/BackgroundCrosses with 0 sprites
[INFO]  Loaded: logo_full with 0 sprites
[INFO]  Loaded: gui/TextEntryBackground with 0 sprites
[INFO]  Loaded: gui/ButtonBackground with 0 sprites
[INFO]  Loaded: mouse.png with 0 sprites
[INFO]  Loaded: gui/ButtonBackground.hover with 0 sprites
[INFO]  Loaded: button.wav of 0.15 seconds
[INFO]  Loaded: gui/LabelBackground with 0 sprites
[INFO]  Loaded: gui/SelectorBackground with 0 sprites
[INFO]  Loaded: gui/SelectorArrow with 0 sprites
[INFO]  Loaded: gui/ButtonBackground.active with 0 sprites
[INFO]  Loaded: gui/ScrollbarBackground with 0 sprites
[INFO]  Loaded: gui/ScrollbarSelection with 0 sprites
[INFO]  Loaded: gui/PanelBackground with 0 sprites
[INFO]  Load script: science_db.lua
[INFO]  Load script: scenario_00_basic.lua
[ERROR] LUA: init: [string "scenario_00_basic.lua"]:193: unknown variation, could not set enemy_group_count
[WARN]  Failed to open game state log file: logs/game_log_01-01-2021_15.02.57.txt
[INFO]  Loaded: gui/icons/station-helm with 0 sprites
[INFO]  Loaded: gui/icons/station-weapons with 0 sprites
[INFO]  Loaded: gui/icons/station-engineering with 0 sprites
[INFO]  Loaded: gui/icons/station-science with 0 sprites
[INFO]  Loaded: gui/icons/station-relay with 0 sprites
[INFO]  Loaded: gui/ButtonBackground.disabled with 0 sprites
[INFO]  Loaded: Nebula3.png with 0 sprites
[INFO]  Loaded: Nebula2.png with 0 sprites
[INFO]  Loaded: radartrace_largestation.png with 0 sprites
[INFO]  Loaded: radartrace_mediumstation.png with 0 sprites
[INFO]  Loaded: radartrace_smallstation.png with 0 sprites
[INFO]  Loaded: Nebula1.png with 0 sprites
[INFO]  Loaded: radar_dread.png with 0 sprites
[INFO]  Loaded: redicule.png with 0 sprites
[INFO]  Loaded: gui/KeyValueBackground with 0 sprites
[INFO]  Loaded: gui/SliderBackground with 0 sprites
[INFO]  Loaded: gui/SliderKnob with 0 sprites

**Comment by oznogon** [comment]
"None" is translated. `resources/locale/fr.po`:

```
#: src/menus/serverCreationScreen.cpp:217
#: src/menus/serverCreationScreen.cpp:223
#: src/menus/serverCreationScreen.cpp:235
msgctxt "variation"
msgid "None"
msgstr "Aucune"
```

"None" is passed to the scenario in English, "Aucune" in French.

When the scenario tries to find a match for "Aucune" in this table:

```
 local counts = { 
     ["Extreme"] = 20, 
     ["Hard"] = 8, 
     -- default: 
     ["None"] = 5, 
     ["Easy"] = 3, 
     ["Empty"] = 0 
 } 
```

it fails, resulting in the error:

```
 assert(enemy_group_count, "unknown variation, could not set enemy_group_count") 
```

Rewriting the `assert` to report the passed value:

```diff
-    assert(enemy_group_count, "unknown variation, could not set enemy_group_count")
+    assert(enemy_group_count, "unknown variation " .. getScenarioVariation() .. " could not set enemy_group_count")
```

Confirms that is the case:

```
[ERROR] LUA: init: [string "scenario_00_basic.lua"]:193: unknown variation Aucune could not set enemy_group_count
```

**Comment by muerteFR** [comment]
ok thanks for the explanation

**Comment by muerteFR** [comment]
While waiting for this to be changed, I removed the None translation in fr.po

**Comment by Xansta** [comment]
For the Borderline Fever issue, the query against the science database for "Ships", "Frigate" yields a nil most likely because these entries have been translated to something else. Then, the script tries to reference a database entry that is normally part of the science database and Lua throws the "attempt to index a nil value" error on the local variable frigate_db.

I'm not sure how to resolve this

**Comment by oznogon** [comment]
The Italian translation is also affected by the instant-victory bug on Waves and Basic, also because the "None" variation option is translated: https://github.com/daid/EmptyEpsilon/blob/a73e13342fa7b9c1f288388f43d2e12094722142/resources/locale/it.po#L441

**Comment by oznogon** [comment]
Filed #1284 for the Scurvy Scavenger issue because it is not related to localization.
