### ISSUE TITLE
reputation can be obscured via comms

### ISSUE THREAD

**Issue by StarryWisdom** [daid/EmptyEpsilon#1162]
On a non wisdescreen aspect ratio the reputation number if covered up via open comms windows.

It is annoying as often  comms costs reputation and not being able to see how much you have is awkward.

at a ratio of 4:3 it is covered, at 16:9 it is visable, I did not check when it is first visable.

This may be as simple as left justifying the text - a majority of the label is visable just not the number that wants to be seen.

**Comment by Xansta** [comment]
Alternative solution: put the number on the left followed by the label "Reputation"

**Comment by oznogon** [comment]
Another alternative: Put the current reputation in the comms text or responses, since that's where it's most relevant. That would also make the reputation visible on the comms-only station and main screen comms.

**Comment by gcask** [comment]
Here's a screenshot that describes the issue:
![image](https://user-images.githubusercontent.com/53709079/118896807-141f3100-b8d7-11eb-81f3-a1f4d13beb5b.png)

On the left hand side, both the reputation and clock are obscured by the comms window.
