### ISSUE TITLE
FEATURE REQUEST: transferPlayersAtPositionToShip to also specify destination crew position

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#1166]
transferPlayersAtPositionToShip lets you transfer a player from one player ship to another in a particular crew position. Can the function have an optional 3rd parameter to specify what crew position they transfer to on the new ship? Alternatively, can there be a function to transfer a player from one crew position to another crew position on the same ship?

**Comment by daid** [comment]
Would be a huge pain to implement.

**Comment by Xansta** [comment]
Not that big a deal. It's kind of an edge case
