### ISSUE TITLE
REQUEST - Please tag the builds that get posted

### ISSUE THREAD

**Issue by mhjacks** [daid/EmptyEpsilon#117]
Hello,

I'm interested in building Linux packages for EE; it would be a lot easier to do this if there were tags corresponding to the build artifacts posted on the download site at http://daid.github.io/EmptyEpsilon/#tabs=5.

**Comment by daid** [comment]
I've updated to do this with the next build.

**Comment by daid** [comment]
Build of 2016.02.29 has been tagged properly.
