### ISSUE TITLE
UnicodeDecodeError from compile_script_docs.py

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#1177]
EmptyEpsilon compilation might fail due to an error generating the script reference:

```
[  3%] Building C object libopus/CMakeFiles/opus.dir/celt/entenc.c.obj
Traceback (most recent call last):
  File "/home/.../EmptyEpsilon-build-scripts/EmptyEpsilon/compile_script_docs.py", line 302, in <module>
    dg.readScriptDefinitions()
  File "/home/.../EmptyEpsilon-build-scripts/EmptyEpsilon/compile_script_docs.py", line 140, in readScriptDefinitions
    for line in open(filename, "r"):
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 16: invalid start byte
make[2]: *** [CMakeFiles/script_reference.dir/build.make:61: script_reference.html] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/script_reference.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Re-attempting the compilation fails again when reading other files.

Reproduced with Python 3.7, but does not affect Python 2.

**Comment by daid** [comment]
I think the real issue is that it is using python3 while the script was written for 2. Your proposed changes break python2

**Comment by oznogon** [comment]
I revised the changes to import and use the `codecs` module, which implements the features built into Python 3. This passes builds with Python 3, builds running Python 2, and this site's CI running Python 2.7: https://github.com/daid/EmptyEpsilon/runs/1616428964

```
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
...
[ 99%] Built target EmptyEpsilon
Scanning dependencies of target script_reference
[100%] Building script reference documentation.
Failed to find parameters for ScienceDatabase:getKeyValues
Failed to find parameters for SpaceObject:setPosition
Failed to find parameters for SpaceObject:getPosition
Failed to find parameters for SpaceObject:setRotation
Failed to find parameters for SpaceObject:getRotation
Failed to find parameters for SpaceObject:getVelocity
Failed to find parameters for SpaceObject:getAngularVelocity
Failed to find parameters for ScriptStorage:get
Failed to find parameters for ScriptStorage:set
Failed to find parameters for Script:run
Failed to find parameters for Script:setVariable
[100%] Built target script_reference
```

**Comment by oznogon** [comment]
The only Python versions that should be incompatible with this solution are 2.3 and earlier. The `errors` argument was added to `codecs` in Python 2.4.

**Comment by oznogon** [comment]
Notably: https://github.com/actions/virtual-environments/issues/1816

> Ubuntu-20.04 is ready to be the default version for the “ubuntu-latest” label in GitHub Actions and Azure DevOps. This change will be rolled out over a period of several weeks beginning on November, 30. (December, 22 - January, 4 will be a migration break due to holidays)

> Python2 is absent on Ubuntu 20, but required for some packages to install. Can be installed via apt-get install python-is-python2 or via toolcache

cicd.yml points to ubuntu-latest. So either the script needs to be updated to Python 3 compatibility, CI needs to point to an OS with Python 2 installed by default, or CI will break when this cutover to Ubuntu 20.04 happens until cicd.yml is updated to install Python 2.

**Comment by oznogon** [comment]
Another potential workaround would be to use `io.open` instead of `codecs.open`, which would also be equivalent to Python 3's default behavior, should work in both Python 2.6 and newer as well as Python 3, and would also add `encoding` and `errors` arguments to `open()`.
