### ISSUE TITLE
Players can join and play as a template-less PlayerSpaceship

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#1179]
In a scenario file, add a `PlayerSpaceship()`, but don't add a `setTemplate("...")` function.

OR

With a running scenario, use the HTTP API to execute `PlayerSpaceship()` without a template.

**Expected behavior**

A script error prevents the template-less PlayerSpaceship from being created, because a template is required.

OR

A template-less PlayerSpaceship can be created, but it does not show up on the list of joinable ships to clients, and cannot be joined by players, until it has a template applied to it.

**Observed behavior**

A ship with no template is created and listed as a class-less Human Navy player ship. It can be joined by the Helms, Science, and Relay stations on all clients, including the client running as the server. Helms can pilot the ship with impulse, warp, and jump drives, Science can scan enemy ships, and Relay can launch probes and hail stations and ships.

If a player joins the Weapons or Engineering stations on the server's client, the server crashes on a segfault. Clients not running as the server can join the Weapons station, but crash when attempting to join the Engineering station.

The templateless ship is visible on the GM screen as a small purple dot, with a generated `PL`-prefixed callsign. The GM can select the ship and move it. Attempting to tweak it crashes the server.

While any templateless ship is active, the console logs flood with a line that repeats every tick:

```
[ERROR] Failed to find ship template:
```

<img width="582" alt="Screen Shot 2020-12-28 at 7 20 59 PM" src="https://user-images.githubusercontent.com/19192104/103256787-56a19a80-4943-11eb-9fe1-015b1c477c07.png">
<img width="1192" alt="Screen Shot 2020-12-28 at 7 21 21 PM" src="https://user-images.githubusercontent.com/19192104/103256790-57d2c780-4943-11eb-8f89-4e747b2fa91d.png">
<img width="1188" alt="Screen Shot 2020-12-28 at 7 26 51 PM" src="https://user-images.githubusercontent.com/19192104/103256795-599c8b00-4943-11eb-9a2c-cf7ed3a4c279.png">

**Comment by daid** [comment]
Not setting a template on a ship is essentially undefined behavior. So, it might kill your cat if you do that.

**Comment by oznogon** [comment]
Is it intentionally allowed? If not, would a PR to prevent them from being created be accepted? If not, would a PR that tries to limit the ways it could be used to crash clients or servers be accepted?

**Comment by daid** [comment]
Not sure how you would prevent it, but yes.
