### ISSUE TITLE
Rendering Code Refactor

### ISSUE THREAD

**Issue by kfprimm** [daid/EmptyEpsilon#122]
Hi,

I've been working on getting the game running on iOS. It builds fine and executes, but crashes immediately due to some asset issues. Hopefully I'll sort that out soon.

In the course of patching, had to add `#define FEATURE_3D_RENDERING 1` because of the lack of ES compatibility in the GL code. Obviously, the same limitation applies to the android build as well.

@daid, would you be open to a patch that adds an abstract `Renderer` class and consolidates all the loose GL code into a neat little `GLRenderer` subclass? This would be the first step in later implementing a GLES1 & GLES2 renderer for embedded targets.

Any thoughts would be appreciated. I don't think it will be a huge undertaking, but it will require a bit of effort. So, I don't want to start without checking with you first.

Thanks!

**Comment by daid** [comment]
Actually, I'm mixing OpenGL 1.1 and >2.x calls. Which is the start of the troubles. If everything would be converted to use vertex buffer objects and shaders, then you're 90% there for GLES rendering.

Then only glTranslate and friends are missing for GLES, but I think there is a compatibility library for that somewhere (as that's just all matrix operations)
