### ISSUE TITLE
Distance Function in Lua Utils

### ISSUE THREAD

**Issue by Sorrento110** [daid/EmptyEpsilon#126]
I could not manage to get the distance function (in utils.lua) working in my script.  I am also trying to use it to output to a log.  For some reason, when I open my log file (using file = io.open("log", "r+") and file:write) and call it through the update(delta) function it returns an error having to deal with an IO global exception.

As an additional question, what would you recommend as the best way to write an environmental logger (that would be returning distances, amount of overheats, when weapon tubes are loaded, location of spaceship etc.)?  Would you recommend writing in in C++ and compiling it or writing a logger script in Lua and calling it through my scenario script.

**Comment by daid** [comment]
The IO library is not accessible for security reasons. If you run the game from a command line shell, you get log output, and you can use the "print" function to write to that.

If you want to log data you can write something that uses the http API to query the game state. (In any language)

So far the only script that is using the distance function is the tutorial script. But in that one it works fine. You do need to add ```require("utils.lua")``` at the top before you can use the distance function.

**Comment by Sorrento110** [comment]
Thank you! I got the function working correctly now.

What is the URL that the server runs on? I am using the Server IP (in addition to trying http://localhost:[Server IP]) to try and connect via http API and it doesn't return anything.

**Comment by daid** [comment]
http://localhost:8080 runs the API

It serves files from the "www" directory in the main program path (you can store html and javascript files here if you want)

You can also run lua snippets with:
http://localhost:8080/exec.lua, it requires the lua code as post data.

Or, query the "main" player spaceship with:
http://localhost:8080/get.lua?hull=getHull()&nukes=getWeaponStorage("nuke")
See the script reference on spaceships on what functions you can use here.


(I know all this stuff is currently undocumented)

**Comment by Sorrento110** [comment]
Thank you! This works as intended. I appreciate your help.
