### ISSUE TITLE
REQUEST - Differentiate Spacestations

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#127]
Right now there are no real differences in the stock space stations other than model & size.

I suggest making them different in the "services" they provide. This would increase the desire to keep these all the bases from being destroyed. This will also make ships have to travel between different stations.
These should all be configurable in the shipTemplate.lua file and/or via scenario scripting.
## Configuration
- Large Base
  - Only has Homing, Mines
  - "Large Reactor" for faster charging time
  - Most expensive items (Rep)
- Medium Base
  - "Medium Reactor", medium recharge time
  - Has Homings, Mines
  - Medium expense (Rep)
- Small Base
  - "Small reactor", slow recharge time
  - Only has homings, HVLI, EMP
  - Cheapest expense (Rep)
## Alternative
- Large base
  - only has nukes, Homing
    - No Mines, EMP, HLVI
- Medium base
  - only has EMP, Mines, Homing
    - No Nukes, HVLI
- Small base 
  - only has HVLI, Homing
    - No Nukes, EMP, Mines

**Comment by kwadroke** [comment]
Without breaking current scripts, it might be best to create these as new/renamed stations.

**Comment by daid** [comment]
Good idea. I do not fear breaking current scripts that much. I have a few ideas on how to implement this, without adding too much complexity.

I still need to add that you can buy HVLI rounds :-)

**Comment by lunerfox** [comment]
In support of this. Perhaps a consistent way to implement this would be to create stationTemplates similar to shipTemplates, allowing for thematic descriptions of various stations types (Mining Colony, Research station, Military installation, Trade Hub...etc), each with their own types of services available.

If random missions make it into Empty Epsilon in the future, this would be a good foundation to go from, too :)

**Comment by daid** [comment]
Ok, what I've done, is I've reworked the station comms.

You can now set properties per station. This is all handled with just the scripting engine, no game code has been changed (proving that the scripting is pretty powerful)

The following set of properties I created:
```
        supplydrop = "friend",
        reenforcements = "friend",
        weapons = {
            Homing = "neutral",
            HVLI = "neutral",
            Mine = "neutral",
            Nuke = "friend",
            EMP = "friend"
        },
        weapon_cost = {
            Homing = 2,
            HVLI = 2,
            Mine = 2,
            Nuke = 15,
            EMP = 10
        },
        reputation_cost_multipliers = {
            friend = 1.0,
            neutral = 2.5
        },
        max_weapon_refill_amount = {
            friend = 1.0,
            neutral = 0.5
        }
```
What you can do, is this:
```
    neutral_station = SpaceStation():setTemplate("Large Station"):setPosition(0, -15000):setRotation(random(0, 360)):setFaction("Independent")
    -- Setup the neutral station to supply supplydrops to anyone, but mines no-one.
    -- And allow the station to refill up to 100% of your stock even if you are neutral with the station (default is 50%)
    neutral_station.comms_data = {supplydrop = "neutral", weapons = {Mine = "none" }, max_weapon_refill_amount = { neutral = 1.0 }
```

**Comment by kwadroke** [comment]
That's pretty cool. Will have to play with it.

**Comment by kwadroke** [comment]
Closing old issue that can be "fixed" with LUA scripts
