### ISSUE TITLE
Italian translation issues

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#1275]
Post-#1272, there are some UI issues with strings.

- Some new strings include accented characters, which don't render (#293).
- Some longer strings overflow their GUI elements.

<img width="758" alt="Screen Shot 2021-01-14 at 7 26 06 PM" src="https://user-images.githubusercontent.com/19192104/104677512-625cc300-569e-11eb-8476-3236a2d81bce.png">
<img width="452" alt="Screen Shot 2021-01-14 at 7 25 45 PM" src="https://user-images.githubusercontent.com/19192104/104677517-62f55980-569e-11eb-9405-a00c5fe3b3ab.png">
<img width="604" alt="Screen Shot 2021-01-14 at 7 25 35 PM" src="https://user-images.githubusercontent.com/19192104/104677518-638df000-569e-11eb-9287-7e4b638c6a76.png">
<img width="127" alt="Screen Shot 2021-01-14 at 7 24 40 PM" src="https://user-images.githubusercontent.com/19192104/104677519-638df000-569e-11eb-8147-74ebdc39ce0d.png">
<img width="857" alt="Screen Shot 2021-01-14 at 7 24 35 PM" src="https://user-images.githubusercontent.com/19192104/104677520-638df000-569e-11eb-82b5-0e54967c3599.png">
<img width="249" alt="Screen Shot 2021-01-14 at 7 23 42 PM" src="https://user-images.githubusercontent.com/19192104/104677522-638df000-569e-11eb-89ef-cc9d10ec247d.png">
<img width="389" alt="Screen Shot 2021-01-14 at 7 23 37 PM" src="https://user-images.githubusercontent.com/19192104/104677523-64268680-569e-11eb-952b-0738c99ad620.png">
<img width="320" alt="Screen Shot 2021-01-14 at 7 23 32 PM" src="https://user-images.githubusercontent.com/19192104/104677524-64268680-569e-11eb-8370-160b576bbacd.png">
<img width="421" alt="Screen Shot 2021-01-14 at 7 23 28 PM" src="https://user-images.githubusercontent.com/19192104/104677526-64268680-569e-11eb-8b9b-76d19bde7951.png">
<img width="251" alt="Screen Shot 2021-01-14 at 7 23 04 PM" src="https://user-images.githubusercontent.com/19192104/104677528-64bf1d00-569e-11eb-8070-74e13fc26294.png">
<img width="431" alt="Screen Shot 2021-01-14 at 7 22 35 PM" src="https://user-images.githubusercontent.com/19192104/104677529-64bf1d00-569e-11eb-9a16-1a7a2829df4d.png">
<img width="576" alt="Screen Shot 2021-01-14 at 7 22 23 PM" src="https://user-images.githubusercontent.com/19192104/104677530-64bf1d00-569e-11eb-9161-6cf0e613b76a.png">

**Comment by muerteFR** [comment]
I encountered the same problem for the French translation. I removed all the accents and adapted the size of the translations so that they no longer protrude from the buttons.

**Comment by hemmond** [comment]
In CZ translation I also replaced accented characters with their ASCII counterparts (I even made python script to check my cz.po file) and tried to adapt the sizes of translation as well. But honestly, on weapons the "LOCK" button is too small to fit anything there. :D I need at least 3 more letters.
