### ISSUE TITLE
Scurvy Scavenger can enter infinite loop

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#1284]
**Steps to reproduce**

Run EmptyEpsilon as a server and launch the Scurvy Scavenger scenario on any settings and default difficulty.

**Expected behavior**

The scenario loads and the server starts.

**Observed behavior**

Sometimes, but not always, the game hangs indefinitely. The process must be terminated manually. It does not crash the game, and does not generate a crash dump log. Logs do not indicate where the scenario is crashing.

If it doesn't crash the first time, sometimes — but again not always — the game can crash if you exit the scenario and then try to restart it. It can take several attempts to reproduce, but is consistently reproducible with effort.

After uncommenting `print()` statements already in the scenario file, the hang occurs after printing:

```
init: place first station
pick station name
init: place first enemy station
```

After adding `print()` statements to echo each line in that loop, it's evident that at random the scenario enters an infinite loop during the `repeat...until(far_enough)` statement, specifically in the second iteration of the for loop that contains it:

```
init: place first enemy station
init: after exuari_station = {}
init: after local exuari_station_angle = first_station_angle + random(-20,20)
init: after local enemy_station_distance = random(11000,15000)
init: after cnx, cny = vectorFromAngle(exuari_station_angle,enemy_station_distance-2500)
init: after concealing_nebula = Nebula():setPosition(fsx+cnx,fsy+cny)
init: after nebula_list = {}
init: after table.insert(nebula_list,concealing_nebula)
init: for: after for i=1,math.random(2,2+difficulty*2) do, iteration 1
init: for: after local ref_x, ref_y = nebula_list[#nebula_list]:getPosition()
init: for: after local far_enough = true
init: for: after local expand_distance = 0
init: for: after local new_x, new_y = vectorFromAngle(random(0,360),random(4000,20000+expand_distance))
init: for: in repeat
init: for: repeat: after new_x, new_y = vectorFromAngle(random(0,360),random(4000,20000+expand_distance))
init: for: repeat: after new_x = new_x + ref_x
init: for: repeat: after new_y = new_y + ref_y
init: for: repeat: for: iteration 1
init: for: repeat: for: after if: far_enough = false
init: for: repeat: after for
init: for: repeat: after expand_distance = expand_distance + 1000
init: for: after repeat
init: for: after local new_nebula = Nebula():setPosition(new_x,new_y)
init: for: after table.insert(nebula_list,new_nebula)
init: for: after for i=1,math.random(2,2+difficulty*2) do, iteration 2
init: for: after local ref_x, ref_y = nebula_list[#nebula_list]:getPosition()
init: for: after local far_enough = true
init: for: after local expand_distance = 0
init: for: after local new_x, new_y = vectorFromAngle(random(0,360),random(4000,20000+expand_distance))
init: for: in repeat
init: for: repeat: after new_x, new_y = vectorFromAngle(random(0,360),random(4000,20000+expand_distance))
init: for: repeat: after new_x = new_x + ref_x
init: for: repeat: after new_y = new_y + ref_y
init: for: repeat: for: iteration 1
init: for: repeat: for: if: distance(nebula_list[j],new_x,new_y) < 4000 then
init: for: repeat: for: after if: far_enough = false
init: for: repeat: for: iteration 2
init: for: repeat: for: after if: far_enough = false
init: for: repeat: after for
init: for: repeat: after expand_distance = expand_distance + 1000
init: for: in repeat
... (repeats forever) ...
```

There does not appear to be a way for `far_enough` to become `true` if it is set to `false` during the `repeat...until(far_enough)` loop.

https://github.com/daid/EmptyEpsilon/blob/eb6ed7bde9acd770196a6e1d01fc0ffcdb70df90/scripts/scenario_47_scavenger.lua#L140-L158

**Comment by oznogon** [comment]
This was raised in #1155 but it occurs with any language setting, including the default/`language=en`.

**Comment by gcask** [comment]
@Xansta I think this would be right up your alley?

@oznogon is definitely onto something there - in the `repeat / until (far_enough)` part, if `far_enough` toggles to false in the distance check, that's an infinite loop :/

**Comment by Xansta** [comment]
Absolutely. I just have not gotten around to examining it yet. Mea Culpa

**Comment by daid** [comment]
(you don't want to know how long I've had this on my "I should quickly fix this" list...)
