### ISSUE TITLE
Missing Object Getters?

### ISSUE THREAD

**Issue by Sorrento110** [daid/EmptyEpsilon#130]
This is probably more of a documentation issue than an actual issue, but when dealing with http API what is the equivalent of getPlayerShip(int) for CPU ships?  The example given in httpScriptAccess is just _OBJECT_=someObjectGetter and I am unclear on where the other object getters besides getPlayerShip(int) are declared?

Thanks in advance!

**Comment by daid** [comment]
There is no way to directly get CpuShips, as they are not stored in a list, they are just objects somewhere in the world. Player ships are stored in a list for a few reasons. Having quick access to them from scripts is a side-effect of that.

As a workaround, you can use the "getObjectsInRadius" function, with a large radius. And then filter on CpuShip types.
For an example, see what I do to find probes in the tutorial script:
https://github.com/daid/EmptyEpsilon/blob/master/scripts/tutorial.lua#L425

**Comment by Sorrento110** [comment]
I am trying to run this in my post request but no ships seem to be storing. I must be missing something obvious. If you could help me with syntax or mechanics here I would appreciate it greatly.


`ships={}

for _, obj in ipairs(getObjectsInRadius(100000, -100000, 50000)) do
    if obj.typeName == "CpuShip" then
        ships[_]=obj
        print "Ship stored successfully"
    end
end

function getShips(a)
    return ships[a]
end`

**Comment by daid** [comment]
{"__ptr": "[OBJECT]"} actually is an object. So I think this should work:
```
ships={}
i=1
for _, obj in ipairs(getObjectsInRadius(10000, 10000, 50000)) do
if obj.typeName == "CpuShip" then
ships[i]={callsign = obj:getCallSign(), scanned = obj:isScanned()}
i = i + 1
end
end
return ships
```

**Comment by Sorrento110** [comment]
Thank you! This works.
