### ISSUE TITLE
[fixed-pipeline] figure out why the shaders subfolder does not end up in the bundle on mac

### ISSUE THREAD

**Issue by gcask** [daid/EmptyEpsilon#1317]
@oznogon was the first to notice the issue.

Hopefully they can help me on this one?

I would suspect something silly, since all other folders under resources seem to end up in the bundle as expected...

**Comment by oznogon** [comment]
I'm willing to close this. I had a friend try it on their Mac, with and without my build scripts, and they couldn't reproduce it. `shaders` winds up in the right part of the bundle's directory tree and EE doesn't have any issues with it. I'll nuke my local repo and see if I can somehow get into a state where this starts happening, but it's likely just sloppiness on my part.
