### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by FooBarDude** [daid/EmptyEpsilon#1330]
I'm trying to do a build of EE-2020.11.23, but this fails in strange ways.

I'm using a Ubuntu 20.04.2 LTS and these Instructions: https://github.com/daid/EmptyEpsilon/wiki/Build%5CLinux%5CDebian

If I try to build EE-2020.11.23 directly it fails with:

```
[249/430] Building CXX object CMakeFiles/EmptyEps...ousProton/src/Box2D/Collision/b2DynamicTree.cpp.o
/home/leonard/EE_Bulid/SeriousProton/src/Box2D/Collision/b2DynamicTree.cpp: In constructor ‘b2DynamicTree::b2DynamicTree()’:
/home/leonard/EE_Bulid/SeriousProton/src/Box2D/Collision/b2DynamicTree.cpp:29:56: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct b2TreeNode’; use assignment or value-initialization instead [-Wclass-memaccess]
   29 |  memset(m_nodes, 0, m_nodeCapacity * sizeof(b2TreeNode));
      |                                                        ^
In file included from /home/leonard/EE_Bulid/SeriousProton/src/Box2D/Collision/b2DynamicTree.cpp:19:
../../SeriousProton/src/Box2D/Collision/b2DynamicTree.h:28:8: note: ‘struct b2TreeNode’ declared here
   28 | struct b2TreeNode
      |        ^~~~~~~~~~
[400/430] Building script reference documentation.
Failed to find parameters for ScriptStorage:get
Failed to find parameters for ScriptStorage:set
Failed to find parameters for ScienceDatabase:getKeyValues
[430/430] Linking CXX executable EmptyEpsilon
```

But if I first checkout the Master branch and try to build it (this fails at the moment) and then use:
```
gitt checkout EE-2020.11.23
cd _build
ninja
```
without cleaning up the old files it produces a working version

If I delete the _build files and build again it fails again.

I tried some older versions of EE and SP too, but couldn't get them to build repeatedly either.

**Comment by gcask** [comment]
Seeing this in your log:
```
[430/430] Linking CXX executable EmptyEpsilon
```

Is a strong indicator it _actually worked_.

The `Failed to find parameters (...)` are only something relevant to script documentation generation (afaik) and can be safely ignored.

Can you check that you do have a `EmptyEpsilon` binary in the `_build` folder? If you run it following the instructions from the wiki page you linked, does it work?

**Comment by oznogon** [comment]
```
Failed to find parameters for ScriptStorage:get
Failed to find parameters for ScriptStorage:set
Failed to find parameters for ScienceDatabase:getKeyValues
```

These can be safely disregarded. We should fix them, but they won't block building EE.

**Comment by FooBarDude** [comment]
Oh, you are right of course. I just assumed that if I get errors the build wasn't successful.
Thanks a lot!
