### ISSUE TITLE
Question about "background" nebulas from the GameGlobalInfo

### ISSUE THREAD

**Issue by gcask** [daid/EmptyEpsilon#1331]
Background nebulas from the GameGlobalInfo object are the last non-debug item using glBegin/glEnd (for #1319).

However... Looking at the code, I'm... actually not sure it does anything meaningful nowadays?

Looking at the [blame](https://github.com/daid/EmptyEpsilon/blame/master/src/screenComponents/viewport3d.cpp#L205), it seems to be really old.

All the information there is randomly generated and does not line up with script-generated nebulas - looks more like an older system that was just there for effect?

I tried disabling the loop and couldn't notice any difference (I even scrapped the starbox just to be really sure - it's pitch black all around).

So the questions are:
 * Are they still in use?
 * If not, okay to scrap?

**Comment by oznogon** [comment]
to test, I added a keybind to the main screen to toggle the background nebula rendering code in viewport3d, and I cannot see any differences with it on or off. I wasn't aware there were ever supposed to be background nebulae, and I don't know what they'd look like

**Comment by gcask** [comment]
Filed #1335 .

Since this is part of the work for #1319, I'll close this.
