### ISSUE TITLE
issues building for widows

### ISSUE THREAD

**Issue by FooBarDude** [daid/EmptyEpsilon#1336]
Now that I found out what I was doing wrong to building for Linux I tried building for windows and am stuck again...

I'm using these instructions:
https://github.com/daid/EmptyEpsilon/wiki/Build%5CWindows-on-Linux

And I fixed the discord issue (https://github.com/discord/gamesdk-and-dispatch/issues/100) or at least it's not showing up as error anymore.

The build process completes and produces a .zip file, but when I start the built EE on a Windows machine it fails after a few seconds with the error code: 0xc0000005

When comparing my generated files with the windows build from the homepage I noticed that mine lacks four .dll's and the .yes file.

Can anyone point me in the right direction what I'm doing wrong?

**Comment by gcask** [comment]
If you did follow the instructions, you should have built against master - which already has the fix for the Discord issue.

There are a lot of steps involved between building and running, even more so when cross-compiling :)

* Are you building against master or another tag/branch?
* Can you tell us which DLLs are missing?
* Do you have any additional details besides "0xc0000005"?

And I think [.tinyci#L16](https://github.com/daid/EmptyEpsilon/blob/7f5be275414bc10997eddfff93f44faf541a048f/.tinyci#L16) is the exact command used to generate the windows package (afaik, could be wrong)

**Comment by daid** [comment]
Be sure to extract the zip somewhere on windows? Running from within the zip is just some kind of freak show that Microsoft created to cause pain on everyone.

**Comment by FooBarDude** [comment]
Ah right, I built against EE-2020.11.23. master wasn't working with Linux at the moment, so I figured a fixed point where I know it worked for others would be the best starting position.

The files are:
- dbghelp.dll
- exchndl.dll
- mgwhelp.dll
- symsrv.dll
- symsrv.yes
I also tried to copy the missing files over from the official build, and just copying my built .exe over the official one. Both didn't work, so it's clearly not just an issu with the missing DLLs. (might not even have to do anything with my problem, its just the one clue that I found)

The error message says (back translation from German): The Application couldn't be started correctly (0xc0000005) click on "OK" to close the Application

**Comment by daid** [comment]
Those files are only needed if you enable the crash logger.

**Comment by FooBarDude** [comment]
Ah ok, so that's unrelated then.

I Tried to make a build with debug info in the hope to get better error messages but -DCMAKE_BUILD_TYPE=RelWithDebInfo doesn't seem to change anything. It doesn't include the DLLs and in the build logs the message "ENABLE_CRASH_LOGGER is OFF" stays the same

Any other ideas how I could get to the bottom of the problem?
I've attached the commands I used to build and the Output. There's Errors, but as far as I see these are the same as in the Linux build which is working.
[build_printout.txt](https://github.com/daid/EmptyEpsilon/files/5954645/build_printout.txt)

**Comment by gcask** [comment]
> master wasn't working with Linux at the moment

Can you elaborate "master wasn't working on linux at the moment"? I tested on debian only a few days ago...
what's not working?


As for the build output it looks fine.
The only thing that pops is you're building an x64 exe (the current release exe is a 32bit image) - that could give you trouble if you're running on a old hardware/windows version... or you have a mismatched dll (using a 32bit one where a 64b version is expected).

**Comment by aBlueShadow** [comment]
In your EmptyEpsilon folder, is there a file EmptyEpsilon.RTP ? If yes, this is generated by the crash logger, and could contain more information.

**Comment by FooBarDude** [comment]
Not sure what it was before, I assumed that the master branch isn't stable and moved to EE-2020.11.23. I tried master again today and it works on Linux. (Though curiosity EE now needs sudo rights to run, otherwise it will crash at the start)

Hm, how do you configure if you build a 32bit or 64bit Version?
I'm testing it on a Windows 10 with current patch level.

There's no EmptyEpsilon.RPT generated.

I also did a windows Build with the current master branch (12.2.2021 9:30) It's also not working, but generates a different error message (see attached) 
![error](https://user-images.githubusercontent.com/17055814/107747198-5a348980-6d17-11eb-889b-e6abdc8f4ef3.png)
This translates roughly to: "The procedure inex list from EXCLUDE_SYSTEM32 wasn't found in the DLL EmptyEpyslon.exe"

**Comment by gcask** [comment]
> Though curiosity EE now needs sudo rights to run
It definitely does not - this looks like a permission issue in your setup (building as root and trying to run as an unprivileged user for instance).

Circling back to:
>The error message says (back translation from German): The Application couldn't be started correctly (0xc0000005) click on "OK" to close the Application

I can get this error if I try using 32b libraries with a 64b exe (which I suspect is your case).
This would also explain why copying your exe to the 'official' build, or the official build's dll to the exe wouldn't work (it's a 32b exe, with 32b dll, you're building a 64b exe, you need 64b dlls).

**Comment by FooBarDude** [comment]
Hm ok, I thought it's always a 32bit application. I don't know how to change from 64 to 32bit

I've now set up an old pc with a new Debian and there it's working. I really don't know what I'm doing wrong with the Ubuntu machine, but I guess I can work around it like that.

**Comment by NinjaSpectre** [comment]
Adding the two lines below after this part in the `mingw.toolchain` should force a 32bit build
https://github.com/daid/EmptyEpsilon/blob/39d6d7bc65f36d53eea39a68d0cd3d816dbc7642/cmake/mingw.toolchain#L3-L5
set(CMAKE_C_FLAGS -m32)
set(CMAKE_CXX_FLAGS -m32)
