### ISSUE TITLE
Performance regression with f58757f

### ISSUE THREAD

**Issue by gcask** [daid/EmptyEpsilon#1348]
f58757f (using radar range for AI targeting) introduced a noticeable slowdown in the update phase.

Apparently it's coming from a few ranges which have been inflated.

From the discord:
> there's some diffs like new_target = findBestTarget(position, long_range); instead of new_target = findBestTarget(position, 8000); for roaming aI
and relay range is not exactly long range * 2 ? it means 60000 instead of 50 000 ?
or at least there is a 30 000 substitued for long range, then a 50 000 substitued for long range also

Proposed fix is:
> It should only use long range if it currently doesn't have a target, if it searches for a potential target switch it shouldn't use more then short range * 1.5 or so.

**Comment by daid** [comment]
Note, I didn't check if that change improves the performance, it's just a very good guess ;-)

**Comment by gcask** [comment]
You may not have, but I did verify it hehe
