### ISSUE TITLE
Unable to autoconnect when more than 3 player ships in shipTemplates.lua

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#135]
If there are more than 3 player ships in shipTemplates.lua and autoconnect is configured in options.ini on the clients, consoles sit on "Waiting for Ship". 

Reproduce by copying template for Player Fighter and change the name to Player Fighter 2. Configure clients to autoconnect in options.ini. Start server & a game, doesn't matter which ship is selected. Start Clients.

**Comment by Jhovall** [comment]
Note: I do not have this problem with our version of empty epsilon for sevcol. Last weekend we had four player ships and everything worked perfectly.

**Comment by kwadroke** [comment]
What version where you using?

**Comment by Jhovall** [comment]
https://github.com/Quispel/EmptyEpsilonLive

I think?

**Comment by kwadroke** [comment]
Getting a 404 on that link. Not finding anything with EmptyEpsilonLive on GitHub either.

I need to test with a newer version of EE. Think I was using 2016-02-29. Could have been fixed and not know it. Will try next week.

**Comment by kwadroke** [comment]
Closing old issue as I believe this has been fixed.
