### ISSUE TITLE
Cinematic view only for first player ship

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#1354]
If you have more than one player ship, even when you go to the second or 3rd player ship, the cinematic view is of the first ship in the list. I believe the same thing applies to the top down view

**Comment by oznogon** [comment]
Do you have steps to reproduce?

https://user-images.githubusercontent.com/19192104/109417806-fbf3e180-7979-11eb-8f7e-3d199f264baf.mov

**Comment by Xansta** [comment]
1) Start Borderline Fever
2) Spawn 4 player ships (Crucible, Maverick, Phobos, Player Missile Cruiser)
3) Connect a client to the server. Subsequent steps on client
4) Board the Crucible (the first player ship spawned)
5) Send the Crucible off in a direction away from the blue neutral zone at full impulse
6) Board the Player Missile Cruiser (the 4th ship spawned)
7) Select cinematic view.
8) You'll see the cinematic view of the Crucible, not the Player Missile Cruiser as expected

**Comment by gcask** [comment]
Looks like the cinematic view [does not honor the selected ship](https://github.com/daid/EmptyEpsilon/blob/9e7e394f8fea21cdc74e573e56b15d263046e151/src/screens/cinematicViewScreen.cpp#L27) (always picks zero).

I reckon feeding the selection from the ship selection screen should do (just need to figure out what's the right id :) )

**Comment by Xansta** [comment]
The ship ID could be passed in as a parameter and if the parameter is missing o null/nil, use zero as is currently done. You have to determine which ship (if any) has been selected on the left hand side of the screen.
