### ISSUE TITLE
Move setCallsign() to spaceObject

### ISSUE THREAD

**Issue by lunerfox** [daid/EmptyEpsilon#137]
Right now, setCallsign is assigned to ShipTemplate Based Object, but getCallsign is assigned to SpaceObject. It would be nice to have the ability to name various anomalies in game (Wormholes, Blackholes, or Artifacts, in particular) for theming.

**Comment by daid** [comment]
This has historical reasons. But I'll see what I can do here. One of the reasons for this is that only the rendering of ships and stations actually draw the callsigns, while everything else does nothing with it.

**Comment by oznogon** [comment]
^ #307 moves setCallSign, and I've confirmed that it allows arbitrary spaceObjects to have callsigns that appear on radar views. It doesn't implement a way to set callsigns from the GM screen, but they respond to scripts and the API.

For example, this `exec.lua` script sets the callsign of any object selected on the GM screen, including black holes, nebulas, and asteroids.

``` lua
objs = getGMSelection()
objs[1]:setCallSign("NGC 9047")
return {obj = objs[1]:getCallSign()}
```

The callsign doesn't appear in the GM screen key/value list, but it appears on player radars.
