### ISSUE TITLE
getSystemPower() seems to not work.

### ISSUE THREAD

**Issue by Sorrento110** [daid/EmptyEpsilon#139]
Using HTTP API, power=getSystemPower("[System]") doesn't work. The game console returns "attempt to call a nil value (method 'getSystemPower' ).

It seems to be the only one out the three (getSystemHeat and getSystemHealth as well) that won't work.

In addition, getSystemEffectiveness doesn't seem to be usable in HTTP API functions and I would like to see that become usable.

**Comment by daid** [comment]
I'm pretty sure the script function itself works, as I'm using it during the tutorial.

Do you properly reference a ship? The full call is:
```
ship:getSystemPower("reactor")
```

**Comment by Sorrento110** [comment]
I am currently using it with an HTTP API get call which defaults to getPlayerShip(-1) for the ship in question.  All of my assignments using getSystemHeat and getSystemPower work.  Here are sample calls that work and the sample call that does not work.

Working:
`http://10.0.25.208:8080/get.lua?heat=getSystemHeat("Maneuver")&sector=getSectorName()&health=getSystemHealth("Maneuver")`

Not working:
`http://10.0.25.208:8080/get.lua?power=getSystemPower("Maneuver")&heat=getSystemHeat("Maneuver")`

Thank you for your time.

**Comment by daid** [comment]
It works on the latest dev build. Are you using the latest release? This function was added in the same release as the tutorial was added.

**Comment by daid** [comment]
It works on the latest dev build. Are you using the latest release? This function was added in the same release as the tutorial was added.

**Comment by Sorrento110** [comment]
I was one version behind, and getSystemPower() was in the source code. It works perfectly now. Apologies! Thanks!

**Comment by daid** [comment]
Note, as of recent versions, the game comes with a "scriptReference.html" file. This file contains all the functions that are exposed.
