### ISSUE TITLE
Treating first person ship window as Main Screen

### ISSUE THREAD

**Issue by lunerfox** [daid/EmptyEpsilon#140]
Is it possible to add an option to use the 1st person ship window as a main screen variant?

First Person Main Screen (FP Main Screen) would allow the use of Main Screen Controls to switch to 90, 180, 270 degree views, as well as switching to Long and Short range Radar.

**Comment by kwadroke** [comment]
Should this be closed with 7269cd7 ?

**Comment by daid** [comment]
Yes. Did that work in the train, so did not have the issue number at hand.

Main screen can be switched to a first person view with the 'F' key.

**Comment by kwadroke** [comment]
I do see one problem with this. It renders the ship in front of you when you go to warp. 
It also shows parts of the ship when you change to left, right & rear views. This is especially evident on slower computers running the main screen (or a VM in my case)

Suggest hiding the ship model when in First person view.
