### ISSUE TITLE
Text cannot be translated in GM

### ISSUE THREAD

**Issue by muerteFR** [daid/EmptyEpsilon#1417]
I reopen the issue regarding some entries in GM which cannot be translated because the tags cannot be added as is.
These are issues 7 and 8 of this issue: https://github.com/daid/EmptyEpsilon/issues/1256

Oznogon had responded regarding these issues. The question is: Is it possible to modify this to allow translation?

"Where to translate in the GM console always: the indications at the top right? "Callsign", "Shield", "Hull", "position", "Orders" Some are already translated as "Time elapsed" ... Still in GM, the orders at the bottom right are translated but at the top right they are not : ("roaming", Idle", "Defend location" etc."

This is the selection_info object in GameMasterScreen:
EmptyEpsilon/src/screens/gm/gameMasterScreen.cpp Lines 295 to 334 in 0a40f22 :

"The information comes from SpaceObject::getGMInfo(), which is used only by the GM screen. For ships, the pertinent override is in ShipTemplateBasedObject, which returns an unordered_map of non-localized strings, and are keyed on those strings as well (some of which are hardcoded in English):"

EmptyEpsilon/src/spaceObjects/shipTemplateBasedObject.cpp Lines 255 to 266 in 5c37189 :
"selection_info relies on at least one hardcoded English-language string as a key (selection_info["Position"])."

**Comment by gcask** [comment]
>Still in GM, the orders at the bottom right are translated but at the top right they are not : ("roaming", Idle", "Defend location" etc."

Would you mind splitting that into a new issue? It's a different can of worms :)

**Comment by muerteFR** [comment]
OK I will do it
