### ISSUE TITLE
Show long range sensors area around the player ship on the Relay & Strategic map

### ISSUE THREAD

**Issue by FaramosCZ** [daid/EmptyEpsilon#1460]
Right now, Relay & Strategic map only see an area around their own player ship of a distance of their short range sensors.
Yet I strongly believe it makes a very good sense to draw the area of long range sensors.

Even though only the short range sensors are is being drawn, it is drawn in a way of long range sensors.
Stuff that would be normally visible on short range sensors (beams ranges, projectiles, shields, inside of nebulas) aren't drawn.

Are there any specific reasons why is the shown area limited in such a way ?

**Comment by daid** [comment]
For gameplay reasons, relay just has a different "view" on the world then other stations. Each station is unique in some way. If relay could see long range sensor range, it would make science mostly redundant.

As for not showing beam ranges/shields/etc, the idea of relay is to have a general overview, not a detailed set of info.
