### ISSUE TITLE
Please consider using the external glm package instead of downloading it

### ISSUE THREAD

**Issue by yurivict** [daid/EmptyEpsilon#1470]
Here: https://github.com/daid/EmptyEpsilon/blob/master/CMakeLists.txt#L109

```glm``` packages exist in virtually all distros: https://repology.org/project/glm/versions

**Comment by daid** [comment]
https://github.com/daid/SeriousProton/commit/32509f2db91a58b9528aeb1bb505e9426b52b825
Now first tries to find the system installed version and else downloads it. Same as we do for SFML.
