### ISSUE TITLE
Cancel Docking

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#148]
I've had an issue where when trying to dock with a station, another docked ship can get in the way. This can cause the ship to be in perpetual docking status.
Currently, there's not a way to cancel docking. I've tried moving away from the station, but when coming to a stop, the ship is brought back to the station.
Requesting a Cancel Dock button, or click on the current _Docking..._ button to cancel.

Reproduce: Start docking with a station, move away at warp, then stop. You will then be pulled back to the base.

**Comment by Fouindor** [comment]
I've noticed similar behavior with CPU ships getting stuck. I'll see what I can do.

**Comment by Fouindor** [comment]
#149 
However, player ships should not be able to engage in warp if they are docked, I'll see what I can do.

**Comment by nicklecoder** [comment]
Docking should definitely only ever be active/possible within docking range of a station. If this is not the case, I would consider this a bug.

**Comment by Fouindor** [comment]
Maybe another useful thing to add is a timer for docking, if the ship has not docked in, I don't know, 20s, it will try again from another angle. This may prevent CPU ships from getting stuck.

**Comment by kwadroke** [comment]
Looks like #149 allows docking to be canceled. 

Is 20s enough time for a ship to dock? 30s might be better.

**Comment by Fouindor** [comment]
I said a number at random, 30s seems a bit high, but ok (it's a value, we can always modify it :) ). I did not thought about how to implement it exactly, butt will be on my to-do list, as I'm working on another update :)

**Comment by daid** [comment]
It depends on the speed and rotational speed of the ship. But it's more of a safety measure in case things go wrong.

The reason why docking could not be canceled before was a bit of a gameplay reason. The idea was that docking became a tactical decision. However, I've never seen my players go to that length, and thus canceling docking won't have a huge impact on that area.
