### ISSUE TITLE
Engineering: Self Destruct Button Blocking Rear shield status

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#151]
With a recent commit (not sure which), the Self Destruct button is on top of the Rear Shield display on the Engineering console.

Screen shot of problem
![](http://bridgesim.net/files/EE/20160330/sd_issue.png)

Scaling the Window does not fix the problem.

Need to move the self destruct button down or to another position.

**Comment by Fouindor** [comment]
Well spotted, submitted #152 to address this issue.

**Comment by kwadroke** [comment]
Simple enough change. #152 looks good.
