### ISSUE TITLE
Ubutnu X11 crashing on first start with mirrored monitors

### ISSUE THREAD

**Issue by Obsnold** [daid/EmptyEpsilon#1521]
I just compiled the game from commit 4da7fdf15c39558c095528d7b76229930f87eabc
I have a laptop with an additional monitor set to mirror.

When first starting the game I got an error.
This is what I have written down:
X Error of failed request: BadMatch (invalid parameter attributes)
RRSetCrtcConfig

I think the full error was:
X Error of failed request: BadMatch (invalid parameter attributes)
Major opcode of failed request:  140 (RANDR)
Minor opcode of failed request:  21 (RRSetCrtcConfig)
Serial number of failed request:  150
Current serial number in output stream:  150

I tried starting the game several times and even rolled back to an older commit but I got the same error.

I first tried disconnecting my monitor and it worked just on my laptop screen.
I then tried connecting the monitor and setting to extend and it also worked.
Oddly I then set it back to mirror and it started working!

Now I can't replicate the error....
I tried rebuilding and restarting but it doesn't seem to happen again.

Not too sure how useful this is but thought I'd post it anyway just in case someone else encounters this issue.

**Comment by daid** [comment]
You could check if SFML has any issue related to this: <https://github.com/SFML/SFML/issues> as that's what we currently as platform independed layer. Would not be surprised if it was some kind of edge case in it.

**Comment by Obsnold** [comment]
Thanks!
I can't see anything obvious in SFML but did see a few issues related to multi monitor setups on Linux so it is probably some edge case like you say.
I just had another go but it seems what ever was causing the issue on my system isn't coming back. I'll keep an eye out and see if I can replicate it.

**Comment by daid** [comment]
Currently working to switch away from SFML to SDL2, which is much more stable for these kinds of edgecases.
