### ISSUE TITLE
Provide distinct button designs for various states

### ISSUE THREAD

**Issue by InterestingJohn** [daid/EmptyEpsilon#153]
Design the following states for buttons:
- [x] Normal
- [x] Disabled
- [x] Hover (mouse over it)
- [x] Active (For toggle buttons and lists)

Design the following states for text input:
- [x] Normal
- [x] Focused (latest clicked)

@daid I'll work up some basic designs for each of them using the Docking button as a model, once we're happy with the concepts I'll add some new images to the GUI folder and let you take it from there (I'm more than willing to do what I can to understand how you implement the changes).

Does that sound good?

As an aside, the current buttons/icons seem to invert the color of the icon and text when they are active (or hovered, I can't remember), would it be preferable for me to add an alternate image file for this state? Maybe with .active added to the file names? e.g. docking.active.png

Edit: Updated task lists

**Comment by daid** [comment]
The colors are controlled by the colors.ini file.
I can easly setup different images for different states. Currently I've only done for the buttons "active" state.

Focused is mostly interesting for the text-entry field, as you can only type in it when it has focus.

**Comment by InterestingJohn** [comment]
So buttons should probably have:
- Normal
- Disabled
- Hover
- Active

And Text entry should probably have:
- Normal
- Focused

Does that sound right? Because I can definitely figure out something for those, I've already got an idea for the text entry UI element.

**Comment by daid** [comment]
Sounds right. Don't worry too much if an image isn't used right now, changing that code is very easy.

**Comment by InterestingJohn** [comment]
And here's some input concepts:

Normal
![input-normal](https://cloud.githubusercontent.com/assets/10858190/14159415/ae540b84-f68a-11e5-8d17-a3ed945168a6.png)
_(Similar to info displays except that it has a stroke on all sides instead of just the top and bottom)_

Focused
![normal-focused](https://cloud.githubusercontent.com/assets/10858190/14159416/ae6307d8-f68a-11e5-958d-756279e871f9.png)
_(Following the same style as the hover effect on the buttons the vertical edges take on a bit of a glow)_

Thoughts?

**Comment by daid** [comment]
For the disabled button, color in the color.ini can be specified with an alpha value, like: #RRGGBBAA
So no need to modify the code for that.

I like the input focus and hover concepts. They are nice and subtle.

**Comment by InterestingJohn** [comment]
So should I generate an image for the disabled button state then? and then just set the color in the color.ini file?

**Comment by daid** [comment]
If you set the color in the ini file, then you can also set the proper alpha for the text. So I think that's the best way to go.

**Comment by InterestingJohn** [comment]
#156 Adds the required images. What's the next step to adding them to the UI?

**Comment by InterestingJohn** [comment]
I'm fairly certain we wrapped this one up in a nice bow, so I'll close the issue.
