### ISSUE TITLE
AI chatter

### ISSUE THREAD

**Issue by Fouindor** [daid/EmptyEpsilon#154]
I've thought about letting the AI ships informing us about what they are doing, to create a bit of a more "living world" feeling. To do so, I've created a addFactionBroadcast functions, which "broadcasts" a message to all Player ships of non-enemy factions (i.e. add in Ship Log). For now, they are informing about new AI order they receive (like attacking : (nameofemitter) : "Targeting (nameoftarget)", ...). Some of the possible additions would be add a message when killing an enemy, being killed...

For the most crowded scenarii, like Battlefield, it can get quite hectic, so the Ship Log should be extended beyond 100 entries.

Do you think it should be added ? Thoughts ?

**Comment by Wrongtown** [comment]
I quite like this, it reminds me of something I was working on (which I'm now going to raise as a separate issue for people to say whether they think it's a good idea).

**Comment by kwadroke** [comment]
I like the idea of random radio chatter. For your idea, Is it only going to to the Ship's log or is relay going to be able to "listen in" on it?

**Comment by Fouindor** [comment]
For now, it's not random and it goes directly to the Ship Log. Each ship will broadcast its actions, as taking new orders and being killed.

However, as only non-enemy factions will receive updates, we can imagine some kind of "spy" module available to Relay in the future (something like a mini-game that will allow to recieve all enemy broadcasts during 15 seconds for instance).

**Comment by kwadroke** [comment]
Random isn't quite the best word for that then. 
Sounds like relay would be jumping back and forth between the 2 screens. Might be best for relay to run 2 monitors for that. That or have some sort of Indicator that a message has come in so they can check the log.

**Comment by nallath** [comment]
Could be something for the web guys right? If the API exposes this, this would be an ideal candidate for a browser based screen.

**Comment by Fouindor** [comment]
Maybe change the label from "Ship Log" to "Ship Log [!]" when having new messages.

**Comment by InterestingJohn** [comment]
We could certainly have a specific UI state for "unread" ship log messages.

**Comment by Fouindor** [comment]
It would be the best solution :)

**Comment by Fouindor** [comment]
As per #165, a first version of this system has been implemented. AI now informs on taking new orders, and a addBroadcast(int threshold, string message) has been added to the Spaceship class. Threshold is :
- 0/FVF_Friendly : Communicate to allies only
- 1/FVF_Neutral : Communicate to allies and neutral
- 2/FVF_Enemy : Communicate to everyone, including enemies

This function is usable by script :
http://i.imgur.com/kL2QnNH.png
http://i.imgur.com/x0uQ2Sn.png

For now I'm leaving this open as there is more to do in my opinion : 
- Add a visual indication that incoming message.
- Make AI use more this command to inform about other things.
- Build a spy module system, maybe ? :)
