### ISSUE TITLE
[SDL-Regression] Custom science image is tiny

### ISSUE THREAD

**Issue by aBlueShadow** [daid/EmptyEpsilon#1587]
When a custom image is added to the science database, it is shrinked to icon size.
![k-sdl2](https://user-images.githubusercontent.com/25465934/139558633-9fe62f27-894a-47b7-8d6d-2e7c699f46db.jpg)

**Comment by gcask** [comment]
Looks like it's coming from 744ae6e9: the image size has been [forced to be 32x32](https://github.com/daid/EmptyEpsilon/blob/744ae6e9/src/screenComponents/databaseView.cpp#L166)

**Comment by gcask** [comment]
Looks like 292322b3 might fix it?

**Comment by aBlueShadow** [comment]
Unfortunately, the rendering is kinda wrong
![k-sdl2](https://user-images.githubusercontent.com/25465934/139585267-be97315a-d69a-4d90-acf1-ec7265d7d823.jpg)
This is what it used to look like:
![k-sfml](https://user-images.githubusercontent.com/25465934/139585370-317544db-9025-4cf2-9603-90218cf2ac3c.jpg)

**Comment by aBlueShadow** [comment]
Seems to be fixed now. Alignment is now centered instead of top left, but that's probably not a bis issue
![kessler1](https://user-images.githubusercontent.com/25465934/175614129-b91553e7-9a7d-4084-b5ff-10ab08c1936b.png)
.
