### ISSUE TITLE
BUG: When Main Screen is in First Person mode, Ship Hull becomes partially visible during Combat Manoeuvres

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#159]
When the Main Screen is set to First Person mode (great idea by the way) and the Helm uses Combat Manoeuvre, occasionally parts of the Hull move into view.

*Steps to Replicate*

1. Log in a view set as Main Screen.
2. Log in as as Helm.
3. Use Combat Manoeuvres.

**Comment by kwadroke** [comment]
This also happens at Warp as stated on closed incident #140
