### ISSUE TITLE
Getting stuck in weapons tutorial

### ISSUE THREAD

**Issue by FooBarDude** [daid/EmptyEpsilon#1607]
You can get stuck in the weapons tutorial, where you learn how to activate the shield.  If you get hit before you activate the shield the next dialogbox never appears

**Comment by gcask** [comment]
It did go through for me after I got hit a second time with the shields up.
Even with the shield up, it would only progress after an attack...

Wondering if https://github.com/daid/EmptyEpsilon/blob/d1b9641a296468bdf351d0fe89fea94008f7c55d/scripts/tutorial/00_all.lua#L156 should read `return player:getShieldsActive()` instead?

I'm not 100% clear about how the tutorial intends to progress there, whether it really wants to wait on a hit or not.

**Comment by aBlueShadow** [comment]
I always thought that the point was that the tutorial wants you to see the difference of a shield hit and a hull hit (without seeing the hull integrity like engineering). After all, you do not really have a chance to raise the shields before taking the first hit.
However, that part of the tutorial is pretty tedious, for two reasons: The typical fighter hit-and-run behavior and the fact that the rear shield has to be hit. So you are just staring at the screen, waiting until the fighter is finally circling back and hits the now shielded rear again.
Alternative options would be to change the ship AI (stand ground orders did not work for fighter AI last time I checked) or at least allow a hit at the front shield as alternative progress conditon.

**Comment by NinjaSpectre** [comment]
```lua
    shieldCurrent = player:getShieldLevel(0) + player:getShieldLevel(1)
    shieldMaximum = player:getShieldMax(0) + player:getShieldMax(1)
    return shieldCurrent < shieldMaximum
```

**Comment by aBlueShadow** [comment]
be3c3395c107629b3f4755dbe281b8792e62fa0c solves this problem. When I checked, even after about two minutes, the enemy was still right behind the player ship. So activating the shields continues the tutorial almost immediately.

**Comment by muerteFR** [comment]
I did not experience this issue, despite being hit several times without activating the shields. The dialog box always comes up.
If the ship came from further away it might be better. This part of the tutorial, in my opinion, is only for knowing how to activate shields. In addition, the calibration of the shields is present, which can confuse beginners.
