### ISSUE TITLE
BUG! No damage to subsystems unless Engineering pushes power consumption.

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#166]
If Helm pushes Warp or Combat Manoeuver without coolant being applied they can easily get related subsystems (Warp, Impulse and Maneuvering) to maximum heat, but there's no penalty for continuing to push those systems hard (no damage to the subsystems occurs).

It seems that damage only occurs to subsystems if their heat is 100% _and_ Engineering pushes more than 100% power into the system.

Is this intentional? Seems to me that if you're running at Warp 4 for long periods without any coolant you should expect to see damage?

*Steps to Replicate*
1. Log in as Helm on a ship with Warp Drive (having a view on Engineering is helpful).
2. Push Warp up to Warp 4 and fly around at speed until the Overheating alert is displayed.
3. Continue with Step 2 until you get tired of it, observing that there is no loss of performance or damage the the Warp drive.

**Comment by nallath** [comment]
Yep, that's a bug. All heat should cause damage.
