### ISSUE TITLE
Question - How to provide new screenshots for emptyepsilon.org?

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#167]
Hi all,

Since the new update is so very very pretty (did I mention it's pretty?) I was thinking we should have fresh screenshots up on emptyepsilon.org (For example [new Engineering](http://sargeincharge.wrongtown.org/images/thumb/7/76/2016-04-02_EmptyEpsilon-Engineering.png/799px-2016-04-02_EmptyEpsilon-Engineering.png) looks very different to [old Engineering](http://daid.github.io/EmptyEpsilon/screenshots/engineering.png)).

I don't mind staging and taking the shots, but have no idea where I would send/save them?

**Comment by Fouindor** [comment]
In the gh-pages branch, there is a screenshot folder.

**Comment by Wrongtown** [comment]
Cheers!
