### ISSUE TITLE
android shows mouse cursor

### ISSUE THREAD

**Issue by StarryWisdom** [daid/EmptyEpsilon#1671]
On android since the switch to SDL a mouse cursor is present at the top left of the screen, even if a mouse isnt attached.

Tested on both an old samsung note 3 (android 5.0) and a more recent borrowed samsung (A52? android 11?).

**Comment by StarryWisdom** [comment]
I missed that this was fixed yesterday

**Comment by daid** [comment]
Didn't check if it is fixed, but most likely that patched fixed it indeed.
