### ISSUE TITLE
Allow color options in colors.ini for KeyValue

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#1681]
You can change the colors for almost everything in the UI except the KeyValue items (on Helm, Weapons screens mostly). 
I'd like to have the ability to change the Text Color as well as the background like I'm able to do in colors.ini for other GUI items.

**Comment by daid** [comment]
Note that I changed how the gui styling is done, there is now a gui theme that allows for more flexibility:
https://github.com/daid/EmptyEpsilon/blob/master/resources/gui/default.theme.txt#L99

I just added that you can style the keyvalue elements as well from it.
