### ISSUE TITLE
Noticable hitching in the Server Browser Menu when switching from Internet to LAN

### ISSUE THREAD

**Issue by edave64** [daid/EmptyEpsilon#1693]
It's no a showstopper, but a little ugliness.

Steps to reproduce:
- On the Main Menu, press "Start client"
- Select "Internet"
- Select "LAN" again

The switch doesn't take super long, but enough to very noticeable.

My C++ knowledge is limited, but here is what I believe is going on:

The UI waits on `ServerScanner::scanLocalNetwork`, which in turn waits on `master_server_scan_thread` to join. On my system, the `masterServerScanThread` fails very quickly to request the master server, but afterwards, the [thread sleeps for a second](https://github.com/daid/SeriousProton/blob/377a0e29b5650eee4c51c2f4fef0938f0ab9f28f/src/multiplayer_server_scanner.cpp#L214) and thus freezes the UI.

If I locally change the sleeping to

```c++
        for(int n=0;n<100 && !isDestroyed() && master_server_url != ""; n++)
            std::this_thread::sleep_for(std::chrono::duration<float>(0.1f));
```

To sleep 100 times for 0.1 seconds instead of 10 times for 1 second, the UI delay becomes unnoticeable, but it might be optimal to wait for one frame (0.016f) 600 times.

Probably the correct solution would be to just kill the thread outright and not even wait for potential network delays or to decouple the server list scanner from the UI entirely, but I don't know how to do that or if that even is easily possible.

**Comment by daid** [comment]
You cannot just kill a thread in C++ (would cause memory leakage, and mutex issues)

The sleep loop is a simple solution. A more complex solution would involve a `std::condition_variable` to wake up the thread
