### ISSUE TITLE
Inconsistent sorting of elements in the script_reference.html

### ISSUE THREAD

**Issue by edave64** [daid/EmptyEpsilon#1708]
Under python3, the contents of the `script_reference.html` are essentially sorted randomly every time the `compile_script_docs.py` is executed. This is probably because python3 hashes are seeded randomly, and the list of files is stored in a hash set.

But even in python2, it relies on the order of `os.listdir`, which does not guarantee ordering.

Also, the ordering of classes is different from the from the table of contents above, since they are not ordered by base class.

**Comment by daid** [comment]
Note, if you are making a fix anyhow, I dont require that you make an issue as well. Just a PR will so.
Less work for you :)
