### ISSUE TITLE
[Request] DB missing informations

### ISSUE THREAD

**Issue by muerteFR** [daid/EmptyEpsilon#1718]
Would it be possible to add various information to the DB such as : 
- The description of the 4 types of stations
- Hacking countermeasures
- Science radar signatures (biological, electrical, gravitational)
This would make this information visible to the player and to develop the interest of the DB in Roleplay.

**Comment by oznogon** [comment]
> The description of the 4 types of stations

To be clear, is this referring to space stations, or crew positions like Helms, Weapons, etc.?

**Comment by muerteFR** [comment]
This refers to the 4 types of space stations
https://github.com/daid/EmptyEpsilon/blob/daa9087f21bbefb138207b712229ff11f9cc9b75/scripts/shiptemplates/stations.lua#L1

**Comment by muerteFR** [comment]
For the Science radar signatures, I don't know if there is an English text but there is a French text describing the 3 types of signatures :

item = physics_principle:addEntry('Signature radar')
item:setLongDescription([[
La signature est l'ensemble des éléments qui permettent de caractériser la présence, le type, ou l'identité d'un objet par un capteur.
Elle dépend donc des phénomènes physiques utilisés (ondes électromagnétiques - hertziennes, visibles, infra-rouge, etc.- ou mécaniques -acoustiques, etc.), du type de traitement effectué (imagerie 1-D, 2-D ou 3-D, analyse en bande large ou en bande étroite, extraction automatique, etc.) et du principe de fonctionnement du capteur (actif -illuminant la cible et analysant le signal réfléchi ou réémis-, passif -utilisant une illumination naturelle ou un signal émis spontanément- ou interception -espionnant le signal émis par un capteur de la cible).

La plupart des vaisseaux spatiaux actuels sont actuellement équipés de trois capteurs radar : rouge, vert et bleu. Ces trois capteurs permettent de repérer trois phénomènes à travers de longues distances :

- La signature biologique peut être captée via les capteurs rouge et vert
- La signature électrique peut être captée via les capteurs rouge et bleu
- La signature gravitationnelle affecte tous les capteurs, mais essentiellement les capteurs vert et bleu.
]])

**Comment by muerteFR** [comment]
And regarding Hacking countermeasures, An old discussion from January 2021 on USN discord talks about it, with @aBlueShadow  among others.
