### ISSUE TITLE
Request: Option to remove radar on 

### ISSUE THREAD

**Issue by lunerfox** [daid/EmptyEpsilon#172]
Related to issue #140.

A typical application of using the first person screen is to simulate the forward ship window on the bridge. It would make sense from an immersion standpoint to have no additional HUD when using this view.

![main_screen_radar_option](https://cloud.githubusercontent.com/assets/3700635/14259533/e4987be6-fad9-11e5-8f19-0a9a3a3dc225.png)

**Comment by daid** [comment]
On the "alternative options" for stations, there is the "window" option. I think this does exactly what you want. It just opens a viewport in first person view in the direction you want. You could even setup multiple beamers/big screens in different directions to have actual viewports out of your ship.
