### ISSUE TITLE
Prerelease Banner on top down view

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#1722]
Prerelease 20220223
If the banner text from `setBanner()` has a new line, when displayed on the top down view, it scrolls the middle of both lines. I would expect the top line, the bottom line or the two lines one after the other.
![Screen Shot 2022-03-07 at 9 45 17 AM](https://user-images.githubusercontent.com/35241832/157067922-ef8f1247-1e67-45c4-b7c1-726c3eccdc0c.png)

**Comment by daid** [comment]
Then... Dont put in newlines?...

**Comment by Xansta** [comment]
It works well on main screen (new line between lines)
![Screen Shot 2022-03-07 at 2 02 40 PM](https://user-images.githubusercontent.com/35241832/157109304-565ace86-7b7d-4e7b-82a8-ae93f266fbb6.png)
)

**Comment by Xansta** [comment]
I created a version without the newline characters for the banner text
