### ISSUE TITLE
[Request] Main Screen Exposition Text Box

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#1724]
On the main screen, can we have a large text box designed for story exposition? 

We currently have `globalMessage()` which allows for one line of text to appear briefly on the main screen. You can shove more lines in there if you insert newline in the text. During the game, though, all this text only stays visible for so long and the more you add, the more challenging it is to read. At the end of a scenario, you can put lots of stuff on screen using this function along with newline characters, but it looks ugly and you have to work around the large Victory or Defeat text box in the middle if you want more information to appear.

I propose a function like `globalExposition(string,duration in seconds)` that places a larger text box on screen. Its position would be under the large "Victory" or "Defeat" boxes for those times that the exposition box might be used at the end of the scenario to show final scenario story information or statistics. During the scenario, the script writer can set the duration of the exposition box. There should be a default duration if duration is not specified and the exposition box should be overwritten if another exposition box call is made.

This could be a way to provide scenario background information without having to rely on the Relay officer to receive messages or gather messages from stations or ships. Think of it as the start of Star Wars where that text crawls up into the distance telling you about what's happened and what's going to happen. Alternatively, it could be the text version of "Captain's log, stardate blah blah blah...". I know the ship log sort of serves that function already, but many times the Relay officer fails to read out that information to the group (at least in the LAN parties I've participated in).

**Comment by daid** [comment]
We could add an 2nd optional parameter to globalMessage for the duration.

Also, with the new code, I have better options to get the size of text and to automatic line-wrapping. So I can most likely auto-scale the message box, and prevent overlap with the victory box as well in some way.

**Comment by Xansta** [comment]
Those sound like viable options. I've got two purposes in mind: block of story telling text and end scenario statistics. If it's easier to put both of those in `globalMessage`, that's great.

**Comment by Xansta** [comment]
I like the new global message box with expansive capabilities. Thanks
