### ISSUE TITLE
Keyboard shortcut bleedthrough

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#1727]
When selecting multiple consoles, keyboard shortcuts defined for one console operate another console. For example, if I have helm and engineering selected, when I am on helm and I use the up arrow to increase the impulse engine speed, whatever system I last selected on engineering has its power increased since the up arrow is defined there to raise the power level. Can the check for keyboard shortcuts take into account the foreground or active console rather than just whether or not you have the console selected? If this keyboard shortcut bleedthrough is a desired feature, can we at least have an option to confine keystrokes to the foreground console if desired?

I observed this on the prerelease version 20220223

**Comment by Xansta** [comment]
I know that the workaround is to define unique keyboard shortcuts across all consoles. I infer that this has been a problem for a while since the default warp settings are not 1,2,3 and 4 so that they don't conflict with weapons missile type selections when one is running Tactical. Considering the mix of functions in Tactical and other similar mixes, addressing this issue may be a challenge.

**Comment by Xansta** [comment]
I have not been looking at master. My apologies. If master is semi-stable, maybe another pre-release is in order

**Comment by daid** [comment]
No problem, just making you aware that I tried to address it already.

**Comment by Xansta** [comment]
Problem does not show in the 2022.03.16 release
