### ISSUE TITLE
UI: Missing icons on Tactical & Single Pilot

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#175]
Tactical & Single Pilot missing icons for Energy, Heading, Speed & Shields.
Items such as Homing, Nuke, Mine & EMP shows their proper icons. No purple box showing missing image file.

My guess is that it has not been coded yet.

**Comment by Fouindor** [comment]
Lock also. I'll look into this.

**Comment by daid** [comment]
Thanks Fouindor

**Comment by kwadroke** [comment]
Update looks good except one thing: Tactical has the Speed icon for Shields. 

Line 85 in src/screens/crew4/tacticalScreen.cpp

```shields_display->setIcon("gui/icons/speed")->setTextSize(20)->setPosition(20, 220, ATopLeft)->setSize(240, 40);```

Should be:

```shields_display->setIcon("gui/icons/shields")->setTextSize(20)->setPosition(20, 220, ATopLeft)->setSize(240, 40);```

**Comment by kwadroke** [comment]
That fixed it.

**Comment by Fouindor** [comment]
Woops ! ^^
