### ISSUE TITLE
F11 Fullscreen - Add as keybinding to allow changing the key used for fullscreen.

### ISSUE THREAD

**Issue by JonathanILevi** [daid/EmptyEpsilon#1750]
Anyway F11 can be made to toggle fullsceen?  Having a shortcut is handy, and it's the universal-standard shortcut for that.  (Try it in any browser, media player, or basically any program which supports full-screen.)

**Comment by daid** [comment]
Alt+enter does full screen toggle, which is the classic standard for it.

**Comment by JonathanILevi** [comment]
Oh, shoot, that is an old standard.  None of the applications I use regularly work with it.  It appears to have been an standard shortcut on older Windows', which got [removed in Windows 10](https://answers.microsoft.com/en-us/windows/forum/all/altenter-keyboard-shortcut-is-not-working-the-same/96dde0d8-868b-48b6-9761-b52f104dea42).

Only some games apparently still use it (since games don't use GUI libraries like .net which handle the full-screening).
