### ISSUE TITLE
Weapons officer load button: missile icon on the button now only points in one direction:straight ahead

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#1751]
The missile icons used to point in the direction they would fire. For example, tubes pointed at -90 or 270 would have the icon pointed to the left. The text still says left, but the icon points straight ahead (direction zero). The icon rendering algorithm was even smart enough that if the missile tube pointed at an angle, the icon would mimic that angle.

Was there a change recently that intentionally made all missile icons point straight ahead regardless of the angle of the tube? I liked the angled missile icon. If there was a reason for the change, please point me to the pull request or explain the reasoning.

Thanks

**Comment by daid** [comment]
This got unintentionally lost when I reworked the rendering code.
