### ISSUE TITLE
macOS Assertion failure at initOpenGL

### ISSUE THREAD

**Issue by pixelclef** [daid/EmptyEpsilon#1756]
Building EmptyEpsilon on macOS still results in an assertion failure when the app is run.

`Assertion failure at initOpenGL (~/Desktop/ee/SeriousProton/src/graphics/opengl.cpp:165), triggered 1 time:
'glad_glGetError() == 0'`

<img width="372" alt="image" src="https://user-images.githubusercontent.com/7457571/179357634-366dabba-4e28-4ebf-8cc7-cc653f87030d.png">

-----

macOS 12.4
AMD Radeon Pro 5700 XT 16 GB
cmake version 3.23.2
sdl2 version 2.0.22

**Comment by pixelclef** [comment]
None of the options in the Assertion Failed dialog result in success. At best, I get a completely blank window.

**Comment by pixelclef** [comment]
At the end of the `make` sequence there's a warning in the output. Related?

`ld: warning: dylib (/usr/local/Cellar/sdl2/2.0.22/lib/libSDL2.dylib) was built for newer macOS version (12.0) than being linked (10.15)`

**Comment by coderobe** [comment]
exporting `SP_GL_PROFILE` as `COMPAT` should be sufficient, it fails on the core profile that is created by default. This should be fixed in the source but that'll do in the meantime

**Comment by pixelclef** [comment]
Should I put `export SP_GL_PROFILE=COMPAT` before the build process, or when I run the app?
