### ISSUE TITLE
Segfault on Debian 11 (bullseye), stable+bpo+fasttrack, IF wireguard interface is present

### ISSUE THREAD

**Issue by someone-somenet-org** [daid/EmptyEpsilon#1761]
I cant start the game in any mode, not even in tutorial, as long as there is a wireguard interface there. The game will simply segfault and close.

``systemctl stop wg-quick.target`` solves the issue, but then i lose all my wg tunnels. :/

Im using: Debian 11 stable+bpo+fasttrack and the official .deb release.

Terminal output looks similar to #1741

**Comment by daid** [comment]
Ah, that's a good pointer.
My suspicion is then that there is an issue with this function:
https://github.com/daid/SeriousProton/blob/master/src/io/network/address.cpp#L87

Can you see if it works if you make that function empty? (so delete lines 124 to 149)

**Comment by someone-somenet-org** [comment]
When I check out the tag ``EE-2022.03.16`` in EmptyEpsilon and SomethingProton and compile with

+ ``git clean -ffdx; cmake -DCPACK_PACKAGE_VERSION_MAJOR=2022 -DCPACK_PACKAGE_VERSION_MINOR=03 -DCPACK_PACKAGE_VERSION_PATCH=16; make -j8`` it crashes.

+ ``git clean -ffdx; cmake -DCMAKE_BUILD_TYPE="Debug" && make -j8`` it crashes.

When I check out the master branch, it seems to work with both kinds of compilation - I did not change anything.

**Comment by daid** [comment]
In debug builds, esc is a quick&hard exit. But you can use the home key instead

**Comment by someone-somenet-org** [comment]
Seems to work with latest release and debian12 <3
