### ISSUE TITLE
position = 0,0 when undocking from internal dock

### ISSUE THREAD

**Issue by Piglit** [daid/EmptyEpsilon#1767]
When docking with a ship on a carrier that uses the internalDockClass for that class of ship, undocking from the ship resets the position of the no longer docking ship to (0,0).
As long as the ship is docked, the position is correct.

Tested with current master (85bdda6) and a Kiriya as carrier and a Hornet as fighter.
OS: Debian 10

**Comment by daid** [comment]
I still need to investigate, but I think I know why this might happen. I think the position might be resetting as soon as I attach a collision shape to the object.

Changing this code to:
https://github.com/daid/EmptyEpsilon/blob/master/src/spaceObjects/spaceship.cpp#L672
```
        else if (ship_template) {
            auto p = getPosition();
            ship_template->setCollisionData(this);
            setPosition(p);
        }
    }
```
Should be able to confirm that, it's not a proper fix, but identifing the cause first is important.

**Comment by Piglit** [comment]
I can confirm, with this code the bug does no longer occure.

**Comment by daid** [comment]
Thanks, I'll work out a proper fix, also because rotation most likely will have the same issue.
