### ISSUE TITLE
Ships, space objects in viewscreen appear closer than they should

### ISSUE THREAD

**Issue by thundnuis** [daid/EmptyEpsilon#1768]
Unless there's something weird about the way my game was installed, space stations and asteroids are visible on the viewscreen / ship window from many U away, long before they show up on long-range sensors, and they hardly get any bigger as the player approaches them.  This gives the player the feeling that the distances between objects on the map could be measured in feet rather than lightyears.
Is there a way to resize objects in the game to correct this?

**Comment by daid** [comment]
try different values of `main_screen_camera_fov` in the options.ini to see if that matches your expectations better. 90 might work better for widescreen monitors then the default 60.

**Comment by aBlueShadow** [comment]
> This gives the player the feeling that the distances between objects on the map could be measured in feet rather than lightyears.
Only if they expect the ships being just a few inches tall.
Imho, it is more like kilometers (actually, originally the unit was called "km" and was replaced later to hide that fact a bit.
To change the measurement to even come close the lightyears, that would require some bigger changes in the game, and you'd also need some different/dynamic scales, to make sub-ftl navigation feasible.

**Comment by thundnuis** [comment]
Thank you, I appreciate your quick responses.
Adjusting the fov to 90 was very helpful, but I think I figured out how to get precisely what I had in mind.
In case you're curious:
In scripts\model_data.lua, I changed the setScale and setRadius of each model, to 1/5 of their original values.  This makes space stations very difficult to see until they're less than 5 U away, and it makes their apparent growth in size as I approach them much more dramatic, particularly in first-person view, giving me more a sense that I've traveled a great distance to get to them, which was the immersive experience I was going for.
It also quintuples the size of asteroids and planets in relation to ships, which furthers this immersion, for me.
Of course, the drawback of this kind of hyper-realism is that other spaceships are almost impossible to make out with the naked eye on the viewscreen, even when just 2 or 3 U away. I think this is realistic for how space combat would actually work (sensors would always be more informative than looking out the window), but I can see why it wouldn't be to everyone's taste.

**Comment by daid** [comment]
As for realistic space combat. As far as I know "Children of a Dead Earth" is the only real realistic space combat game. Everything else is just space "soup", or, a submarine simulator with a space skin.

EE never tried to be realistic, but just a fun space game. However, I did try to make it easy to modify, so I'm glad you found your way around the files and got the result you where looking for. That's one of the EE goals :D

**Comment by thundnuis** [comment]
Thanks for the recommendation, I might check that out. I've been enjoying
the hell out of EE though.
I really appreciate how accessible and transparent the scripts are. I'm a
couple weeks into my very first coding class and I was able to make the
exact changes I wanted with almost no effort.
By the way, my partner is so impressed that they're going to start telling
their CS students to check out EE as an example of a good open source
community :)
