### ISSUE TITLE
Alert Level Not changing

### ISSUE THREAD

**Issue by kp1780** [daid/EmptyEpsilon#1786]
Alert level can highlight 'Normal, Yellow Alert, and Red Alert' but the selection just selects a point on the map instead of selecting an alert menu option.

**Comment by daid** [comment]
I most likely broke it here:
https://github.com/daid/EmptyEpsilon/commit/abc2f02e7652dfb7a28d2da1018a1c3dfa86911d
I think I see what I did wrong, but haven't put the effort in to test&fix.
