### ISSUE TITLE
Where is the changelog?

### ISSUE THREAD

**Issue by CurePindal** [daid/EmptyEpsilon#1788]
Where is the changelog?
CHANGELOG.md is outdated for over 2 years.
Any pointers?

**Comment by daid** [comment]
That was always community maintained, it has fallen in disarray.

Changes of the latest release as posted on discord:


Change Summary

Enhancements
  * Warp Jammer range getter
  * Warp Jammer hull getter/setter
  * Function formatTime available in utils.lua
  * Button in Cinematic View to cycle through ships
  * Scenario: The Omicron Plague (contact Xansta with issues)
  * New hot keys
  * Scripting Reference Document
    - Print class name with each member
    - Better information for onNewPlayerShip function
    - Remove non-font dependencies

Translations
  * DE (German)
    - What the Dickens (Mission)
    - Defender Hunter (Replayable Mission)
    - Training: Cruiser (Basic)
    - Surrounded (Basic)
    - Empty (Development)
    - Battlefield (Development)
    - Supply drop (internal communications)
    - Place station utility (internal mission utility)

Bug Fixes
  * Glow effect interpolation
  * Training: Cruiser scenario locale fix
