### ISSUE TITLE
Beacon of Light description

### ISSUE THREAD

**Issue by hemmond** [daid/EmptyEpsilon#1792]
Beacon of Light lists `EmptyEpsilon.org` in description (and therefore in translation files). 
Relevant line: `The Beacon of Light scenario, built from the series at EmptyEpsilon.org.`

The series referenced in that description (that probably once was on the website) is no longer there and I am unable to find it on `archive.org`. 

So this issue should address 2 things: 
1. Replace `EmptyEpsilon.org` with `https://daid.github.io/EmptyEpsilon/` (or just EmptyEpsilon webpage)
2. Either find the referenced series or remove the mention entirely from mission description. 

I am unable to do that properly since I have not yet played Beacon of Light, so I don't have any idea on what's going on in that scenario.

**Comment by daid** [comment]
Changed to proper URL. It's just referencing the scripting tutorial, where the beginning of the mission is based on.

**Comment by hemmond** [comment]
> Changed to proper URL. It's just referencing the scripting tutorial, where the beginning of the mission is based on.

I'd in that case use wording `mission scripting tutorial` instead of just `tutorial`. And in that case I'd replicate updated description to that tutorial (since on the website is still EmptyEpsilon.org) - see [EE website](https://daid.github.io/EmptyEpsilon/#tabs=4,scripting-tabs=0).
