### ISSUE TITLE
Possible to exceed warp and jump limits with PlayerSpaceship:commandWarp()/Jump()

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#1805]
Through the UI, player ships can only set a target warp level of 4, but `PlayerSpaceship:commandWarp()` allows any value. For instance, `player:commandWarp(99)` works:

![image](https://user-images.githubusercontent.com/19192104/209454991-80478335-e49a-4a00-b937-28e79d6f6a3c.png)

`PlayerSpaceship:commandJump()` also allows any value, such as `player:commandJump(999999999999999)`. This results in a negative jump drive charge.

![image](https://user-images.githubusercontent.com/19192104/210156687-664476a9-edc1-496b-a07c-fd50991822eb.png)

**Comment by daid** [comment]
Added clamping.
