### ISSUE TITLE
Callback functions don't work when added via exec.lua API

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#1807]
GM functions and `onGMClick` events work as expected when added to a scenario script, but not when added via the exec.lua HTTP API endpoint to a scenario in progress.

Steps to reproduce:

1. Launch a scenario on an EE server with `httpserver` set to a port
2. POST to localhost:port/exec.lua a script with `addGMFunction()` or `onGMClick()` callbacks, such as `addGMFunction("Do something", function() print("something") end)` or `onGMClick(function(x,y) print(x,y) end)`
3. Click the new GM function button, or click the GM console background

Expected behavior:

The callback runs.

Observed behavior:

The callback doesn't run. The GM function button appears but doesn't flash or visibly register being clicked, and nothing happens when clicked. `onGMClick` mode is visibly enabled (the "Create..." button state changes to "Cancel") but clicks don't appear to run the function.

**Comment by oznogon** [comment]
This appears to affect any scripting function that defines a callback.

**Comment by daid** [comment]
Note that this was by design. Not saying it is a good design, but it is intentional
