### ISSUE TITLE
[Android] Low color contrast, blending/layering issues make GL lines difficult to discern

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#1814]
Reproduced with:

-    2022.10.28 official build
-    master branch build

Reproduced on:

-    Samsung Galaxy S6 running Android 7
-    Google Pixel 6a running Android 13
-    Google Pixel 3a running Android 12
-    Amazon Fire HD 10 9th-generation
-    Amazon Fire 7 5th-generation

Steps to reproduce:

1. Start a server
1. Select any scenario with scannable targets, and options. (Used Battlefield to test)
1. Select a player ship (create one if necessary)
1. Select Science or Operations stations
1. Select a scannable target and attempt to scan it

Expected behavior:

The scanning interface displays the colored beams that must be aligned by moving the slider.

Observed behavior:

The colored bands are nearly invisible and unusable in play.

![PXL_20221230_204132064](https://user-images.githubusercontent.com/19192104/210113239-5bee48f3-71e4-413c-aae4-0ce7c92ad812.jpg)

**Comment by oznogon** [comment]
Ran into additional similar issues:

On Android, the radar border, heading ticks, unit range circles, and missile targeting lines are so faint that they're barely visible in screenshots and not visible on the actual device:

![image](https://user-images.githubusercontent.com/19192104/223573830-e16c0d6b-705e-444b-bea6-ed68aa9c4944.png)

Compare to this Windows desktop shot, where the lines are all clearly visible and opaque white or blue:

![image](https://user-images.githubusercontent.com/19192104/223574079-92d05043-ab4d-49eb-b1fb-c1ad02b9b356.png)

On Science, similar issues. Sector borders aren't visible, but sector names are. Signal bands and shield/beam frequency damage graphs are nearly invisible:

![image](https://user-images.githubusercontent.com/19192104/223574655-553814dd-562b-47a6-8608-312d78117c63.png)

Windows desktop comparison:

![image](https://user-images.githubusercontent.com/19192104/223574835-ec6c2e7b-58ce-421f-bb63-939276dcad9b.png)

Also note that the background on desktop is lighter, and that sprites, beam ranges, and shield segments seem unaffected on Android.

This doesn't seem to be specific to any device; these screenshots are from a 2019 9th-gen Fire HD 10, and I've now also observed it on a 5th-gen Fire 7, Pixel 3a, and OnePlus Nord N10 running a variety of flavors and versions of Android.

The behavior, along with #1813, suggests to me some potential layer and alpha blending issues specific to Android. The lines are being rendered, but either with faint transparency or with a dark translucent layer over them.

**Comment by oznogon** [comment]
Relay with a normal alert level, master branch Android armv7 build. Note no visible sector gridlines or dots, how the friendly radar appears darker rather than lighter than the fog of war, and the heading numbers rendering over the controls (#1813):

![Screenshot_20230307-181105](https://user-images.githubusercontent.com/19192104/223602328-cb74c8ec-8eb4-49f6-9fd5-20c8ab92ff53.png)

Windows desktop, master branch:

![image](https://user-images.githubusercontent.com/19192104/223602519-4b168d9a-fde5-4162-97c7-9f09fe145664.png)

Relay with a red alert overlay, master branch Android armv7 build. Note how much darker the radar view becomes - no color blending:

![Screenshot_20230307-181116](https://user-images.githubusercontent.com/19192104/223602122-9df4a098-0b36-4075-b591-a76696057d06.png)

Windows desktop, master branch:

![image](https://user-images.githubusercontent.com/19192104/223602250-cfd133f1-c161-449e-a460-426ba247d2e7.png)

**Comment by oznogon** [comment]
Alert overlays are implemented in src/screenComponents/indicatorOverlays.cpp via `sp::RenderTarget::drawRectColorMultiply`, which is just:

```cpp
void RenderTarget::drawRectColorMultiply(const sp::Rect& rect, glm::u8vec4 col
or)
{
    finish();
    glBlendFunc(GL_DST_COLOR, GL_ZERO);
    fillRect(rect, color);
    finish();
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
}
```

GL_BLEND is enabled in the constructor, and so is `glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)` . So this function just changes the blending function to a color filter, draws the rectangle in the given color, and goes back to the prior blending function.

It feels like only the desktop renderer understands the blend modes/GLES needs a shader to blend?

**Comment by oznogon** [comment]
It looks like the Android color and alpha blending are technically working as expected, for a narrow definition. The resulting colors are transforming exactly as you'd expect considering the _inputs_ are wrong.

The alert overlay color rect that's being blended should be 255, 192, 192, 255 for red alert - the light pink in the desktop build above. On Android without `glEnable(GL_BLEND)`, the rect's measurable color is 62, 46, 47, or if each value was multiplied by about 0.75.

![image](https://user-images.githubusercontent.com/19192104/229668092-8e619b4a-0058-4c19-8888-262164726c73.png)

So doing a `GL_DST_COLOR` blend on the UI with a 62, 46, 47 rect _should_ look like this:

![image](https://user-images.githubusercontent.com/19192104/229668196-dc8ce97b-94e2-4ad4-ae7b-b57bad4a6fa3.png)

The question is, what's changing that color? Is a layer out of order?

Also with `glBlend` not enabled, that 75% darker color transformation is also still happening on anything in the radar background - the sector gridlines, range circles, - as well as scan dialog waveforms and the radar signal waveform ring. Those things are rendered 75% darker, but sprites, text, and UI elements aren't. Meanwhile, the base radar background itself isn't as dark on Android as on desktop, so fog of war is washed out. 

Android hardware above via `scrcpy`, desktop below, with `glEnable(GL_BLEND)` commented out of `sp::RenderTarget`'s constructor:

![image](https://user-images.githubusercontent.com/19192104/229668293-a778f12b-b6a6-458a-8e2f-6c202be74b94.png)

**Comment by daid** [comment]
Maybe the fillrect has some issue on android? It uses a single color pixel in the texture to get a solid white. There could be a few issues at play:
* Texture coordinate issues of this pixel
* Texture compression causing alpha bleed from the pixels next to it.

**Comment by oznogon** [comment]
@daid I don't know why, but reducing the atlas size from 2k to 1k seems to fix this. https://github.com/daid/SeriousProton/pull/234
