### ISSUE TITLE
Autoconnect for Main Screen and Ship Windows

### ISSUE THREAD

**Issue by kpanic23** [daid/EmptyEpsilon#1816]
We're currently running a completely overdone setup:
We have three clients set up as Ship Windows in offset angles, with three projectors creating a giant panoramic viewport.
I've read into the options.ini preferences file, but unfortunately there doesn't seem to be an option to autoconnect as Ship Window or dedicated Main Screen.
It's extremely tedious having to manually re-setup every single non-player station every time the ship blows up, especially for the Ship Windows, with their fiddly angle selection.
It would be great if the autoconnect function could be extended to those extra screens. If possible, with predefined viewport angle for the windows.

**Comment by daid** [comment]
Main screen can be done, you need -1 as station value

**Comment by kpanic23** [comment]
Thanks, that's a start! I added it to the wiki.

**Comment by kpanic23** [comment]
Hm. I just tried it. Doesn't work, unfortunately. A value of -1 connects as Helms. Apparently the "-" gets ignored.

**Comment by kpanic23** [comment]
I've built a current master with your patches cherry-picked into it, and it seems to work pretty well. There once was an issue where two of the three windows were sitting infinitely on "waiting for player ship", but besides that it went really well this long weekend! 

https://twitter.com/kpanic/status/1667628307934851072

![FySbGxNWYAASfav](https://github.com/daid/EmptyEpsilon/assets/15244315/ca4252c9-627e-4fd7-8744-a939c6636ca0)
