### ISSUE TITLE
BUG: Neutral Station is not light blue in tutorial

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#182]
I'm making some spelling/word corrections to tutorial.lua and noticed while running the tutorial that the neutral station isn't coloured as such (it's grey instead). 

I tried the following (which seems to work for the ships) but the station still doesn't count as scanned.

> addToSequence(radarTutorial, function() prev_object = SpaceStation():setTemplate("Medium Station"):setFaction("Human Navy"):setPosition(5000, 0) end)
> addToSequence(radarTutorial, function() prev_object2 = SpaceStation():setTemplate("Large Station"):setFaction("Independent"):setPosition(5000, 5000)**:setScanned(true) end) --Still not showing up light blue, not sure what to do here.**
> addToSequence(radarTutorial, function() prev_object3 = SpaceStation():setTemplate("Large Station"):setFaction("Independent"):setPosition(5000, -5000):setScanned(false) end)
> addToSequence(radarTutorial, function() prev_object4 = SpaceStation():setTemplate("Huge Station"):setFaction("Kraylor"):setPosition(5000, -10000) end)

I've been looking through script_reference.html for the vital difference between the ships and stations but I think I must be missing something.

**Comment by Fouindor** [comment]
Light blue is friendlies, like Arlenians.

**Comment by daid** [comment]
This was done differently for stations then ships. Fixed it.
