### ISSUE TITLE
Suggestion/Request: Some kind of update when new versions are released

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#184]
Whether it's an RSS Feed, an email subscription or whatever, I imagine it would be handy to let people know that a new version has landed. 

I feel that at the moment there's a lot of good work being done leading to fairly rapid release of new code which is great. However with this comes the increased risk that people will be using older releases without realizing and may be finding/raising bugs that no longer exist which requires the lead contributors to context-switch more than would otherwise be necessary. As such I think we're rapidly approaching a situation where the investment in a better notification system for new releases is justified.

For what it's worth (though I'm sure people have their favourite alternative services) I could see a Dropbox Directory with the latest (unzipped) Windows application and the .apk alongside it being useful for people who don't do their own modding. I would be happy to try to maintain this myself if people are interested. Then again I can always give @daid write access ;)

**Comment by daid** [comment]
Currently I'm not really seeing enough users to see this as a huge problem.

**Comment by Wrongtown** [comment]
No worries.
