### ISSUE TITLE
Suggestion/Request: Ship layout oriented so "up" = "forward"

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#185]
A minor quibble but it makes more sense to me, rather than arbitrarily having all ship schematics facing to the right. I imagine I'm not alone in that the I see players are overwhelmingly viewing the ship from the rear on the main screen. 

If nothing else it would be nice if when looking at the damaged areas of the ship engineering could inform the crew that they're taking a pounding on their port side, without having to first rotate the image 90 degrees in their head.

An Engineer is a lot like drummer; they're often working a lot harder than we appreciate, and if they're doing it well you don't tend to notice. If they're not doing it well... :wink:

**Comment by daid** [comment]
In engineering? Simple reason, screens have more width then height.

**Comment by Wrongtown** [comment]
Okay, I do see that. Especially if schematics are expected to get a lot bigger then there's more room to grow. 

Counterpoint would be that the main cruiser schematic is a little less than 13% longer than it is wide, and honestly seems a little long compared to the default model if you're worried about not having space.

If you simply don't like the suggestion that's fine too, it's your project.

**Comment by daid** [comment]
Also, FTL did it this way :P pretty much copied it from that.

**Comment by Wrongtown** [comment]
Ah, well if it's a homage then it is sacrosanct :wink:

**Comment by Jhovall** [comment]
Hey Wrongtown, it is easy to make it different yourself. Just change the ShipTemplates.ini file in the scripts.
It is really easy to understand.

**Comment by Wrongtown** [comment]
Thanks @Jhovall, I know I can do that for myself easily enough, I was just making the suggestion thinking it might be a good move in general :smile: I meant to close this earlier, must have clicked Comment instead of Close and comment!
