### ISSUE TITLE
REQUEST - Make package List when pack_gen.py is used

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#187]
So modders/scenario makers know what's available inside *.pack files, have _pack_gen.py_ in _/packs_ create a text file with the contents of the generated .pack files.

Also, please include listing of files for the current _AngryFly.pack_ & _msgamedev.pack_ files until they are regenerated in the future.

**Comment by daid** [comment]
Actually, everything in those packs (except for a few unused textures) is listed in the model_data.lua already.

**Comment by kwadroke** [comment]
For new packs created by others, they might not have them in the model_data.lua (or even provide the file). This can also help with troubleshooting since we can't open the packs directly to see what's in them.

I will probably using this to pack the models for my Star Trek mod so it's easier to install.

**Comment by daid** [comment]
A different advantage of the pack files is the 3D models load faster, as they are in a pre-processed format.

**Comment by oznogon** [comment]
It doesn't take much to [grab the filename as it writes the packs](https://github.com/oznogon/EmptyEpsilon/commit/e8af1d73faa7b9b6ff9e1ebd6f4c4eb054a2393d) and dump them into a log, but I don't know if this is something that's meant to be added?

**Comment by daid** [comment]
I have no problem with it.
