### ISSUE TITLE
combat maneuver damage/power warnings overlapping

### ISSUE THREAD

**Issue by StarryWisdom** [daid/EmptyEpsilon#1892]
If you have both maneuver and impulse systems on a player ship damaged, at low power or at no power then the warnings will overlap making them all awkward to read.

The most important of these probably should stop the less important ones from displaying.
Alternatively the UI could be changed so they dont overlap, but that seems more effort than its worth.

![image](https://user-images.githubusercontent.com/37894123/216957307-24315eb0-23c8-4bd9-9a5d-a9462417c487.png)

**Comment by oznogon** [comment]
`GuiCombatManeuver` has two `GuiPowerDamageIndicator`s, one each for strafe and boost, and tied respectively to maneuvering and impulse systems:

```
    (new GuiPowerDamageIndicator(slider, id + "_STRAFE_INDICATOR", SYS_Maneuver, sp::Alignment::CenterLeft))->setPosition(0, 0, sp::Alignment::BottomLeft)->setSize(GuiElement::GuiSizeMax, 50);
    (new GuiPowerDamageIndicator(slider, id + "_BOOST_INDICATOR", SYS_Impulse, sp::Alignment::BottomLeft))->setPosition(0, 0, sp::Alignment::BottomLeft)->setSize(GuiElement::GuiSizeMax, 50);
```
