### ISSUE TITLE
missmatch between asteroid visual size and hitbox

### ISSUE THREAD

**Issue by StarryWisdom** [daid/EmptyEpsilon#1893]
Since the SDL change there seem to be a lot more occasions where the hitbox of asteroids seem wrong.
Its sadly somewhat hard to confirm what people really see when the collisions happen (as after the asteroid no longer exists)

This is also harder to identify than one would hope due to not being able to see easily the hitbox of ships

With some testing it looks like it is worse with larger sized asteroids, and much worse with asteroids that are larger than the gm screen can create.

Looking at the code - the 32 and 64 in this function look suspicious (though they may just be correcting for radius/diameter)
https://github.com/daid/EmptyEpsilon/blob/3489f30940ce2c5c1c3b3d1653d4805e94c99123/src/spaceObjects/asteroid.cpp#L83

I have not tested if this resolves the miss match observed.

**Comment by oznogon** [comment]
Excerpted diff of f5c39aa7e:

```diff
-    sf::Sprite object_sprite;
-    textureManager.setTexture(object_sprite, "radar/blip.png");
-    object_sprite.setRotation(getRotation());
-    object_sprite.setPosition(position);
-    object_sprite.setColor(sf::Color(255, 200, 100));
-    float size = getRadius() * scale / object_sprite.getTextureRect().width * 2;
+    float size = getRadius() * scale / 64.0f;
     if (size < 0.2)
         size = 0.2;
-    object_sprite.setScale(size, size);
-    window.draw(object_sprite);
+    renderer.drawSprite("radar/blip.png", position, size * 32.0f, sf::Color(255, 200, 100));
```

**Comment by oznogon** [comment]
Excerpt from diff f5c39aa7e:

```diff
-void Asteroid::drawOnRadar(sf::RenderTarget& window, sf::Vector2f position, float scale, float rotation, bool long_range)
+void Asteroid::drawOnRadar(sp::RenderTarget& renderer, glm::vec2 position, float scale, float rotation, bool long_range)
 {
     if (size != getRadius())
         setRadius(size);

-    sf::Sprite object_sprite;
-    textureManager.setTexture(object_sprite, "radar/blip.png");
-    object_sprite.setRotation(getRotation());
-    object_sprite.setPosition(position);
-    object_sprite.setColor(sf::Color(255, 200, 100));
-    float size = getRadius() * scale / object_sprite.getTextureRect().width * 2;
+    float size = getRadius() * scale / 64.0f;
     if (size < 0.2)
         size = 0.2;
-    object_sprite.setScale(size, size);
-    window.draw(object_sprite);
+    renderer.drawSprite("radar/blip.png", position, size * 32.0f, sf::Color(255, 200, 100));
```

**Comment by oznogon** [comment]
```
asteroid getRadius(): 117.71, scale: 0.01, size: 0.02
size < 0.2: true
getRadius() * scale / 64.0f: 0.02
size * 32.0f: 0.53

asteroid getRadius(): 117.71, scale: 0.09, size: 0.17
size < 0.2: true
getRadius() * scale / 64.0f: 0.17
size * 32.0f: 5.30

asteroid getRadius(): 157.00, scale: 0.09, size: 0.22
size < 0.2: false
getRadius() * scale / 64.0f: 0.22
size * 32.0f: 7.07

asteroid getRadius(): 500.00, scale: 0.09, size: 0.70
size < 0.2: false
getRadius() * scale / 64.0f: 0.70
size * 32.0f: 22.50
```

Asteroid radius 10 on GM screen at max zoom:

![image](https://user-images.githubusercontent.com/19192104/220193607-21e3275d-1004-44b9-88ca-cb485d335886.png)

Radius 500:

![image](https://user-images.githubusercontent.com/19192104/220193402-a5a29552-083b-4e30-96bd-9c541519e91b.png)

At radius 500/GM screen max zoom, I'd expect the asteroid radius to be at least 16px larger.

Doubling the drawSprite size factor from 32 to 64 results in larger asteroids sized closer to expectations on tighter zoom but also increases the minimum rendered size of asteroids regardless of radius or zoom. Radius 10 and 500:

![image](https://user-images.githubusercontent.com/19192104/220196548-f4b18f60-c1dc-488c-b4e9-8385603264f1.png)

Adding a `drawCircleOutline` call to draw the asteroid radius:

```diff
     renderer.drawSprite("radar/blip.png", position, size * 32.0f, glm::u8vec4(255, 200, 100, 255));
+    renderer.drawCircleOutline(position, getRadius() * scale, 2.0, glm::u8vec4(255, 255, 255, 64));
 }
```

Also reveals the disparity. Radius 10, 150, 500 from left to right:

![image](https://user-images.githubusercontent.com/19192104/220202098-87726a08-b39e-4814-a0d3-847580188679.png)

**Comment by oznogon** [comment]
With 93181b4:

![image](https://user-images.githubusercontent.com/19192104/220208445-043b9851-5c8d-4127-8936-a23f54ed23e4.png)

![image](https://user-images.githubusercontent.com/19192104/220208512-751f2b5d-0ab7-4ea1-8869-4f328899fb67.png)

In a debug build, with an extra circle drawn at the actual radius:

![image](https://user-images.githubusercontent.com/19192104/220208312-69de1b49-b25f-4c6d-b0b5-361f8cac53b2.png)

![image](https://user-images.githubusercontent.com/19192104/220208383-85ea10b3-9439-457a-87f6-631c30257a89.png)
