### ISSUE TITLE
Parts from disabled ships

### ISSUE THREAD

**Issue by ErikDeBruijn** [daid/EmptyEpsilon#19]
Not every blast will disintergrate a spaceobject.

If a large ship gets destroyed by minor damage, it would make sense that debris from the ship could still have some integrity. These objects could be usable weapons or people that could become prisoners of war (to be exchanged for reputation at space station) or weapons to be fitted on player's ship.
Fitting a weapon ideally should preoccupy engineering and should take time decided by the amount of crew working in the section of the ship. Also, parts could have more or less damage depending on enemy hull integrity versus impact.

**Comment by hemmond** [comment]
This can be done in LUA now. Here is example code on how you can play with it. It does not make sense now to implement it into the game itself. If it is interesting for mission author, he has the means to do it. 

[https://github.com/hemmond/EE-Scenario-snippets/blob/main/scenario_00_item_drop_on_destroy.lua](https://github.com/hemmond/EE-Scenario-snippets/blob/main/scenario_00_item_drop_on_destroy.lua)
