### ISSUE TITLE
Enhancement: Improved black hole & wormhole images.

### ISSUE THREAD

**Issue by MyrddinE** [daid/EmptyEpsilon#190]
![radarblip](https://cloud.githubusercontent.com/assets/435613/14454941/853d7a1e-0062-11e6-9977-2ac6ea43296a.png)
![wormhole1](https://cloud.githubusercontent.com/assets/435613/14454943/8540f3e2-0062-11e6-9f56-168ded353b5c.png)
![wormhole2](https://cloud.githubusercontent.com/assets/435613/14454940/853bd7e0-0062-11e6-8792-19792ec6eb5b.png)
![wormhole3](https://cloud.githubusercontent.com/assets/435613/14454942/853f6612-0062-11e6-9ea3-f2b84f65fb59.png)

Some friends of mine (I'm not claiming credit for the work) edited the wormhole and black hole images to reduce game artifacts.

Now, the wormhole could probably have been fixed with a simple change to its blend mode rather than a new PNG, but we could fix the image faster than finding the place in the code to fix the blend mode.

The Black Hole (radarBlip.png) was upscaled to 128x128, and radial lines added for a slight texture. The other places that image is used are too small to see the radial lines, so it works out well. A better long term solution is a unique black hole texture, but this is a drop-in enhancement.

Thank you for all your work Daid, this is an amazing game.

**Comment by nallath** [comment]
Merged it :)

**Comment by OldDragon2A** [comment]
Actually decided to create a separate image just for the black hole instead of replacing RadarBlip.png.  Then I fumbled the commit and left out the new file.  So that image is in its own pull request.
