### ISSUE TITLE
GM comms chat window jumps around the screen when moved. 

### ISSUE THREAD

**Issue by hemmond** [daid/EmptyEpsilon#1914]
When moving chat window on GM screen it moves pretty much all around the screen at random. You need to keep the left button held for a few seconds after so the window ends on where GM wants it. 

Steps to reproduce:

1. Have scenario with at least one player ship and one NPC ship that is on player ship's short-range radar.
2. On GM screen toggle on "Intercept all comms"
3. On Relay, open comms to the NPC ship. 
4. On GM screen move mouse cursor on the chat window header (top part of chat window), press left mouse button and move the window. It will starts jumping all over the place. 

Tested on latest stable release version, Kubuntu 20.04.

**Comment by oznogon** [comment]
Could not reproduce on a Windows master branch build.

https://user-images.githubusercontent.com/19192104/221377907-18012431-354a-4ee0-81fc-8e2283aa2585.mp4

**Comment by daid** [comment]
I might have fixed this already, I remember an issue like this.

**Comment by oznogon** [comment]
#1754

**Comment by hemmond** [comment]
I can confirm that this issue is not present on current GIT Master, therfore I am closing this issue.
