### ISSUE TITLE
[translation, regression] Main menu screen no longer shows translated texts. 

### ISSUE THREAD

**Issue by hemmond** [daid/EmptyEpsilon#1922]
When starting EE, main menu screen is in english no matter what language was selected. Other screens are in specified language, but main screen stays in english. Doesn't matter if EE was launched with different language or set in options, EE main menu screen is still in english. 

Observed on current GIT Master (commit: eb5135b83b41041bbfed5e63483c82f4a6e75bb8 ), issue is NOT present on latest release (2022.10.28).

**Comment by oznogon** [comment]
Just built off master and launched EE in French, and the main menu is in French. Ubuntu 22.04, invoked running `./EmptyEpsilon language=fr`, and Windows 11 invoked running `./EmptyEpsilon.exe language=fr`:

![image](https://user-images.githubusercontent.com/19192104/222315620-5dd94951-5f58-418a-a68c-191b5b32d626.png)

If I go into options and change the language to English, the main screen is in English. If I then go back into options and change the language back to French, the main screen is in French again.

I wonder if there's an issue or change in the .po files. I haven't and generally don't regenerate those when I rebuild EE, but I suspect you do. My resources/locale/*.po files were last built Feb 22, and the last commit before that date is 35d5c8da4855fbb53887eef1865db78e6416de84; the last commit changing the main screen is 1f75a8a3f39ec6bf46fb5d115bd4008dd3ab0ee1 on Jan 31 (#1884).

**Comment by oznogon** [comment]
Or maybe your .pos are out of date? #1884 added the `main_menu` context to all main menu strings.

**Comment by hemmond** [comment]
That is definitely possible. It's true that I checked only with `cz` language. I will check it again and if this is the problem, I will update czech .po files and file a PR.

**Comment by oznogon** [comment]
Indeed, #1884 manually updated only the French .pos with the new context, so this is probably "broken" on all languages _but_ French and English. @daid would have to run update_locale.py, which is a significant change, and running it myself seems to remove the `mainMenu` context, so I'm not sure what the correct path forward is.

**Comment by hemmond** [comment]
After this is applied to `main.en.po`, then it should be easy to apply it to other languages as well, so it would be prefered if either your updated `main.en.po` is applied on other languages or that your PR will not close this issue.

**Comment by oznogon** [comment]
https://github.com/daid/EmptyEpsilon/wiki/Translation-and-Localization#adding-translations-of-game-text:

> ## Adding translations of game text

> Translations of the EmptyEpsilon interface and non-scenario game text are stored in gettext catalog (.po) files in the resources/locale directory, currently copies of https://github.com/daid/EmptyEpsilon/blob/master/resources/locale/main.en.po with different filenames for each translated language. You can use [Poedit](https://poedit.net/), a free and [open-source](https://github.com/vslavik/poedit) translation editor, to add and edit translations in such files.

> After someone changes or adds a feature in the EmptyEpsilon user interface involving a string, **the game's main English translation file must be updated first. Copies can then be made for other language translations to update.**

> To update the main English translation file, run the Makefile target "update_locale" (make update_locale). **However, please do not update the main English locale file in pull requests. This will be done by a project maintainer directly on the master branch.** ([Example](https://github.com/daid/EmptyEpsilon/commit/8b6ed3a796a5277f0f71b95ee11ff3e5c83aad0c))

After someone with more privileges than me either merges #1927 and runs `update_locale.py` or runs the `update_locale` build task on the repo, it will be applied automatically to all other languages along with all other .po updates made to scenarios, other Lua scripts, and the game code, 

This is why I notified @daid on #1927.

**Comment by oznogon** [comment]
CC @muerteFR 

This is why I try to stay out of localization issues. :)

**Comment by muerteFR** [comment]
:-)
I don't have time to check at the moment but indeed when someone adds translation tags or even translation contexts (me to standardize everything, most of the time) in the lua files, you have to update the en.po and xx.po files. As Daid doesn't want we push PR with the updated en.po files, I do it locally on my pc and this allows me to check that there is no error and also allows me to update the fr.po files (even if the en.po files are not yet updated on the Daid branch).

**Comment by oznogon** [comment]
Confirmed that https://github.com/daid/EmptyEpsilon/commit/c982b886d34666225d7c9bda744d73f9545bc87a fixes this for all languages I tested (fr, cz, de).
