### ISSUE TITLE
LOW VALUE BUG: Elements of Damage Control underneath Station Switching buttons in Engineering

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#193]
Ironic considering my suggestion that the ships could be oriented differently included the argument that we aren't out of space!

The top-most elements of the Cruiser schematic are partially obscured by the Station Switching buttons. It's quite a bit worse if you're running a ship with both jump and warp drives as you're adding an extra row to the Power/Coolant controls.

Only an issue if the Engineer is running several stations of course, if they're just an Engineering station alone then they won't HAVE buttons across the top of the screen.

It does mean if you ever dream up an additional system which needs power/coolant management the schematics may need looking at. They could probably afford to be smaller without significant impact on PC but that gets worse on tablets/phones.

**Comment by kwadroke** [comment]
I've seen this issue as well this morning during testing. Think it's been an issue for a while.

**Comment by daid** [comment]
https://i.imgur.com/uRhtBnS.png
Not seeing this problem anymore ;-)

**Comment by kwadroke** [comment]
Here's what I see. Not a major problem if only playing Engineering, but, can be for those running more than one station.
http://bridgesim.net/files/EE/20160413/ee_ss-1.png

**Comment by daid** [comment]
I changed the station selection to the right corner yesterday ;-)

**Comment by Wrongtown** [comment]
Ah so is it like a combo-box/drop-down containing whatever stations you've got active when you select it?

**Comment by kwadroke** [comment]
Ok, I'm not seeing it in the latest git pull.
Has that code been pushed up to Github?

**Comment by daid** [comment]
It is now (I work in the train quite often on EE code, cannot push then)

**Comment by kwadroke** [comment]
Ok, I see it now :) But it is partially on top of the Main Screen button. 
http://bridgesim.net/files/EE/20160413/ee_ss-2.png

**Comment by daid** [comment]
Yes, fixing that next :P
