### ISSUE TITLE
Suggestion: On Role Selection, Show Counts

### ISSUE THREAD

**Issue by MyrddinE** [daid/EmptyEpsilon#194]
It would be far easier to set up ships, avoid multiple people accidentally entering the same view, and coordinate role changes if the Role Selection screen showed the number of users who have selected that role next to the role button, and the ships showed the number of users ready on that ship.

This is the simplest version of the suggestion... there could be enhancements. For example, this version would not show any difference between five people choosing five different roles, and one user choosing five positions (except the ship count wouldn't match the role count). But this would help Internet groups get set up, which is currently far more confusing and tedious than it is in person when you can just hand them a tablet set for Helm.

![ee-readycount](https://cloud.githubusercontent.com/assets/435613/14579118/50e4181e-0363-11e6-94e4-35be3276eabf.png)

**Comment by OldDragon2A** [comment]
Having the player set a name when they join and showing a list of players on a ship would also be nice.  Would make it easier for the captain to know if there is someone who is lost.

**Comment by MyrddinE** [comment]
There are a lot of user enhancements possible... this one would require no extra UI beyond this page. I'd like to aim low at first; easy, achievable feature requests. :D
