### ISSUE TITLE
Warp Jammer is invisible in 3D views

### ISSUE THREAD

**Issue by nigelkennington** [daid/EmptyEpsilon#1944]
Warp jammers in the latest release (20221029) are invisible. They appear in the previous version (20210623).

Log shows an error in loading:
`[CRITICAL]: Bad vertex texcoord line: vt 0.0593 0.6199 0.0000
[CRITICAL]: Failed to parse mesh/various/Shield bubble generator.obj`

but the exact same model works in the previous release.

Steps to replicate:

- Launch latest release (20221029) 
- Launch server and mission "empty space"
- As games master, spawn Kraylor Warp Jammer
- Spawn standard player atlantis and launch with main screen, helm and weapons
- Warp Jammer will appear on helm and weapons display, can be selected and destroyed with beams, but is invisible in main screen view.

![warpjammerbug](https://user-images.githubusercontent.com/14282301/225293000-42aa001f-4440-4e08-b78d-b307fcbaecf8.png)

**Comment by daid** [comment]
Fixed by: https://github.com/daid/EmptyEpsilon/commit/03b72fd4c6eca7c4eba1738cbcd4d1c299af3bd1
