### ISSUE TITLE
Bug: Numeric keypad period does not work when entering host IPs - win32

### ISSUE THREAD

**Issue by MyrddinE** [daid/EmptyEpsilon#195]
Mitigated by upcoming server browser.

**Comment by Fouindor** [comment]
Works for me, on WIn7 64 bits, 12/04 version. On which version are you on ?

**Comment by daid** [comment]
See the same problem on the numeric keypad. The period/delete key is always seen as delete, and cannot be distinguished from the normal delete key.
Problem with SFML.

**Comment by MyrddinE** [comment]
Can you read the status of the Num Lock flag, and do the translation yourself?

That is a shitty SFML bug though.

**Comment by daid** [comment]
Then the normal delete button would suddenly look like an dot as well depending on the numlock state.

**Comment by JonathanILevi** [comment]
For me the numpad delete key comes up as `Unknown` (same with the numpad delete) for me.  Is this a change or just my system?

**Comment by daid** [comment]
Could be something in SFML depending on your OS. The keyboard handling with SFML isn't that great for these kinds of things...

**Comment by JonathanILevi** [comment]
On my rig the decimal dot is the keycode `Unknown` but it still sends the correct unicode for the key.
[This](https://github.com/JonathanILevi/SeriousProton/tree/decimalFix) fixes it for me, does this fix it for you?

@MyrddiinE

**Comment by daid** [comment]
SDL2 branch fixes this.
