### ISSUE TITLE
Pressing delete while at the end of a text entry box crashes the game

### ISSUE THREAD

**Issue by nigelkennington** [daid/EmptyEpsilon#1971]
To duplicate:

- Launch EE 2022.10.28
- Click to place the cursor at the **end** of "Your name:" entry box on main screen
- Press delete
- Game will close immediately.

Tested on multiple screen's entry boxes.

**Comment by muerteFR** [comment]
Is this still the case with the new release?

**Comment by daid** [comment]
Don't think so. A fix on .substr handling in seriousproton fixed it.
