### ISSUE TITLE
Database don't refresh

### ISSUE THREAD

**Issue by elptito** [daid/EmptyEpsilon#199]
Hi,

I try to make a scenario with a update of the database for the scientist.
When players dock to a station, i put a script like that : 

`history = ScienceDatabase():setName('history')
	item = history:addEntry('Clue1')
	item:setLongDescription([[Some clue about the scenario]])`

Unfortunately, the scientist have to quit and reload his station to see the new database entry.

Could it be possible to refresh automatically the database ?

Thanks in advance,
Thomas

**Comment by daid** [comment]
Right now the database is intended as static and created at startup of the game.

**Comment by elptito** [comment]
Thanks for your answer.
I interstand. But I think that, for a RP goal and to raise the role of the scientist, refresh could be fun, like almost everything in EE.
I don't know if other users think like me.

**Comment by daid** [comment]
Note, I might do this one day. But right now all clients have their own local copy of the database. And due to how the network code is made, making this client->server would put unneeded extra load on the server which I rather want to avoid right now.

**Comment by kwadroke** [comment]
I'd like to be able to add to the DB during game play. Mostly for when a multi-scenario type game is being played and update it with current mission parameters.

**Comment by elptito** [comment]
I didn't think about that, all my tests was with the same computer.
