### ISSUE TITLE
Missile trajectory lines glitching

### ISSUE THREAD

**Issue by CurePindal** [daid/EmptyEpsilon#1996]
Issue:
I often notice that the missile trajectory lines are glitching (side-mounted launchers). The lines are flickering between showing the proper aim trajectory and the default non-aimed line of a side-mounted launcher. And its not just corner-cases where the trajectory just loses LOS/aim. Very annoying. 
Expected: Proper trajectory shown without flickering between states.

**Comment by muerteFR** [comment]
I don't know if we are talking about the same thing but I recently noticed aiming problems with self-guided missiles on double scanned targets with very advantageous angles and yet the missiles were not locked. I don't know what caused it, I didn't understand.
