### ISSUE TITLE
UI: Console selection button on top of Mainscreen Controls

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#200]
The button to select Helm, Weapons, Science, etc is still on top of the main screen controls.
Recommend moving it to the top left corner where the first console selection button was located in previous versions.

Reproduce by selecting more than one console  at the ship/console selection screen (Helms & weapons for example)

**Comment by elptito** [comment]
In the same way, i think that it will be better if the ship log stay directly available for the relay. Now, he has to click on relay to choice ship log.
