### ISSUE TITLE
[Scenario issue] "The Black Wall" from Dyrian

### ISSUE THREAD

**Issue by muerteFR** [daid/EmptyEpsilon#2001]
Here are the problems encountered after several tests concerning the scenario The Black Wall. This scenario had already been revised by Xansta which had solved several problems.
All these problems concern only the end of the scenario. SPOILER WARNING!!!
Here is the script link: https://discord.com/channels/206597597455056898/784527257044910080/1045462265752715324

**RESOLVED 1.**
When upgrading the ship on Wall Base, the shields are not increased and remain at 150. The same for the engines, they are reduced from 120 to 105.

**RESOLVED 2.**
The Defendor ship is very far, it should move faster or leave from Wall Base and not from Home station, at the same time as the other support ships. It's a long wait for nothing. Especially since in the text it's indicated that It's Defendor who observes the link between the Ghost base and its Battlestations, but he is far behind us.

**RESOLVED 3.**
If we give orders to Defendor, he forgets his mission.

**RESOLVED 4.**
When we have to overheat our shields to deactivate the shields of the Ghost station, if we are not close enough to the Ghost Station, less than 3 or 4 units, we have no message even if we are at -100% in our overheated shields.

**RESOLVED 5.**
If Defendor is eliminated (tested after having overheated the engines), you dont receive the following message "Defendor has been destroyed. You are on your own to destroy the Ghost Station" which you would normally receive.

**RESOLVED 6.**
If we eliminate the base ourselves, and even all the enemies, whether Defendor is alive or not, there is no end.

 **RESOLVED 7.**
Science DB shortcut button does not work with some French language ships. I have to retest this point.

**Comment by Xansta** [comment]
I'm looking at the code for Black Wall. 

For item 1, above: 

The Player Cruiser by default has a maximum shield setting of 80 front and back. The only way to get 150 shields is to take the upgrade. Similarly, the default impulse speed max for the player cruiser is 90. The shield/impulse takes you to 105. Now, what may be confusing is that you are temporarily upgraded to a scout ship before you get to choose your "upgrade" at the Wall Base. While you are a scout ship, you have 120 speed and 150 front and back shields. So, in reality, you're quickly being restored to your normal ship where you have only 80 front and rear shields and 90 speed then given you upgrade back to 150 shields and your impulse of 105. I'm surprised you didn't complain about not getting your jump drive back, that's what I'd be asking for (that, or a warp drive).

Item 1 is working as designed. Talk to Dyrian if you don't like the player ship parameters. Unless you make an alternate argument, I'm considering item 1 closed.

**Comment by Xansta** [comment]
For item 2, above:

I agree that Defend0r moves slowly. Big powerful ships are designed to move slowly. However, the player kind of needs to clear out the enemies near the Ghost defense platforms to help protect the big ship if the players want to actually use the take down the Ghost shields mechanism by matching then launching the device. Having Defend0r move slowly makes that a little easier. The players often have to do without Defend0r anyway, so I'm not inclined to make the trip any shorter either by starting it sooner or giving it a faster speed. There are plenty of things for the players to worry about without having to wait on Defend0r.

However, some exposition allowing the players to choose whether or not to wait for Defend0r might be warranted. The instructions tell the players to protect the Defens0r, a definite role reversal. We might change that to make waiting for the Defen0r optional at least in terms of the instructions.

If we're going to start changing the basic structure of the scenario, I'm inclined to add a 3rd defense platform to cover the gaping hole in the defenses on the northeast side of the Ghost station. I think the scenario author was thinking too linearly. The first thing I did was go around to the other side to get a clear shot at the Ghost station.

**Comment by muerteFR** [comment]
> For item 1, above:
Ok, I understand. Dyrian hasn't responded for years, otherwise the scenario would be integrated into EE :-)

**Comment by muerteFR** [comment]
> For item 2, above:
I have another opinion on this point. The scenario calls for escorting Defendor to Ghost Station. The 2 beginners crews who played this scenario wanted to go back to escort it in the nebulae, which takes a long time. They shouldn't wait for him fighting near the Ghost station. I find it more interesting and challenging to escort the ship to its destination, rather than cleaning the place and waiting for it, It's not the "spirit" of Dyrian's scenario I think. If the crew follows the story, they are supposed to turn around. It's this U-turn that I find too long and weird with the Defendor which starts from the Home Station and not from the Wallbase. The fact that it moves slowly is very good though, it makes escorting this ship more realistic and stressful. The interest of this end of scenario is precisely to use this strategy of protecting the bomb until it arrives. 

For the text saying that it is Defendor which detects the link between the combat stations and the Ghost base, we can easily modify the text to say that it is the Wallbase which detected this, to resolve this inconsistency.

The less experienced crews did not try/thought to circumvent the battle stations, there is space to pass between the 2. And since they don't necessarily expect such long laser beams on a ship they don't understand who's attacking them if they haven't done a deep scan. This is what happened to me the very first time I discovered this scenario :-). Which is very nice. On the other hand I find it very interesting to add a 3rd one, it would make the use of the bomb and Defendor even more important.

I don't wish this scenario to become more difficult, I find it completely suitable for a good mission with twists, escort, combat etc for an unconfirmed crew.

**Comment by Xansta** [comment]
For item 3, above:

I added code to override default ship comms for various Human Navy ships. I also added code to "remember" what the mission orders are. Finally, I added code to give the player the option to tell the ship to follow its mission orders. It's on the https://github.com/Xansta/EEScenarios repository

**Comment by Xansta** [comment]
For item 4, above:

I raised the minimum distance between Serenity and the Ghost station when checking for overheated shields from 4 to 10 units. It's on https://github.com/Xansta/EEScenarios

**Comment by Xansta** [comment]
For item 5, above:

I made a global variable for the name of the Defend0r so that it could be referenced after it is destroyed. This should address the problem. It's on https://github.com/Xansta/EEScenarios

**Comment by muerteFR** [comment]
@daid this issue can be closed. @Xansta resolved it :-)
