### ISSUE TITLE
Game won't start with current version on OpenSuSe 15.4

### ISSUE THREAD

**Issue by michd89** [daid/EmptyEpsilon#2012]
I used to play the game with version EE-2022.03.16 on OpenSuSe 15.3 which worked fine. Today I upgraded my OS to 15.4 and the older game version is still working. However when I start the game with the new version EE-2023.06.17 I get the following terminal output:

```
INFO: Starting...
INFO: Using /home/myHome/.emptyepsilon as configuration path
./EmptyEpsilon: symbol lookup error: ./EmptyEpsilon: undefined symbol: SDL_RWread
```

Is there anything I have to look after?

edit: I should also tell you that I had to copy the executable `EmptyEpsilon` from `bin` to `shared/emptyepsilon` and execute it from there. Otherwise it doesn't find certain files.

**Comment by daid** [comment]
Not sure how, but it is related to you distro/install and multiple SDL versions and conflicts between those.

**Comment by michd89** [comment]
@daid I managed to run the game by compiling it myself.

I did the following
- Follow the instructions at https://github.com/daid/EmptyEpsilon/wiki/Build%5CLinux%5COpenSuSE
- Download the Debian package https://github.com/daid/EmptyEpsilon/releases/download/EE-2023.06.17/Linux_EmptyEpsilon_EE-2023.06.17.deb
  - Go to `data.tar.gz`, then `usr/local/share/emptyepsilon`
    - Copy the content of it to `builddir`
- Start the game in the `builddir` directory with `./EmptyEpsilon`
