### ISSUE TITLE
transfert objects in a sub-script

### ISSUE THREAD

**Issue by elptito** [daid/EmptyEpsilon#203]
Hi,

I try to do a general script which call some sub-missions.

I can "transfert" variables by the command setVariable, but i cannot "transfert" objects.

So, if I create a spacestation in the main script, I cannot use it in the sub-script.

Do you know how to fix it, or am I wrong somewhere ?

**Comment by daid** [comment]
Most likely you are using the "script" object, instead, you can use the "require" function, this includes the other script in the same "environment" as the original script, and thus can access everything from there.

**Comment by elptito** [comment]
Indeed I use the script object.
I thinked that it's more convenient for the organisation of my script : one regular mission, with some extra mission which could appear sometimes.
I will check if the require function could be better.
