### ISSUE TITLE
build/MacOS Needs Update

### ISSUE THREAD

**Issue by bischofftep** [daid/EmptyEpsilon#2036]
Current instructions for building on MacOS X as a package generate errors having to do with SDL2's include path.

Current releases of SDL2 include a version of "sdl2-config.cmake" that, if pointed to instead of the custom one the user is advised to write in the build instructions, will fix these errors.

I'd suggest editing the build instructions to point at the sdl2-config.cmake distributed with SDL2.

**Comment by daid** [comment]
The wiki is user maintained, so if you have improvements on the MacOS build instructions, you can edit those.
