### ISSUE TITLE
error when running from command line

### ISSUE THREAD

**Issue by TemporalClepsydra** [daid/EmptyEpsilon#2039]
When I run EE from windows explorer or from the taskbar shortcut it works fine, but when I run it from the command line I get this error:
![image](https://github.com/daid/EmptyEpsilon/assets/110496018/4b989d0d-fbed-4b20-9009-595dedd33a29)
Any idea what is going on?
**Computer version:** Windows 11 Home 23H2
**Empty Epsilon version:** 2022.10.28

**Comment by gwaland** [comment]
Make sure from the command line that you have changed into the directory where empty epsilon is installed.

**Comment by daid** [comment]
Yep, your working directory needs to be where the `resources` folder is located, else you get this error.
