### ISSUE TITLE
Unable to complete the weapons tutorial

### ISSUE THREAD

**Issue by laalsaas** [daid/EmptyEpsilon#2040]
Hi, I'm unable to complete the weapons tutorial because of something that is either a bug in the gameplay or a bug in the tutorial. At some point, it spawn's a ship behind my ship that I should target using homing missiles. However, it doesn't seem possible to get the missiles "to home". When I select the enemy ship, the flight path of the missile doesn't change, no matter if I've locked or unlocked aim. I also played some games and wasn't able to make the homing missiles fly to the enemy. I'm a fairly new player (discovered the game yesterday and it's awesome!) so I don't have a perspective on how things used to be etc.

I'm on Version 20230617.

**Comment by aBlueShadow** [comment]
> Hi, I'm unable to complete the weapons tutorial because of something that is either a bug in the gameplay or a bug in the tutorial.

It is actually neither, but maybe the tutorial text could be a bit clearer. You have to combine what you have learned in the past two tutorial steps: Select the target, and manually aim behind your ship. The flight indicator won't quite reach the target, but the homing capability will do the rest.
