### ISSUE TITLE
REQUEST - Aft missile tubes display below Fore missile tubes

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#206]
The different icons indicate which way a tube faces clearly enough, but I feel the UX is a bit "wrong" when the rear tubes are at the top of the list (as seen on the older default cruiser - it doesn't appear to matter what order the tubes are declared in *shipTemplates_OLD.lua*, the rear-facing tube is always at the top of the list).

I propose that forward-facing tubes should be presented above rear-facing tubes. I'd say ideally the closer to 0 the tube faces, the higher it should be... this logic could get a little gnarly for ships with lots of broadside tubes.

![2016-04-30_183919](https://cloud.githubusercontent.com/assets/16337876/14935403/fb816ab0-0f02-11e6-9950-44397c9b70ec.jpg)

**Comment by oznogon** [comment]
For what it's worth, I"m not seeing this on the current builds using the old default Player Cruiser. The tube order appears to be set by tube ID (the first parameter in tube functions, `0` below), starting with `0` at the top of the list:

    template:setTubeDirection(0,180)

This sets the tube at the top of the list (tube 0) to point toward heading 180.

For example, if we have three tubes, and we want the top two tubes to point forward and the bottom tube to point backward:

    template:setTubeDirection(0, -5):weaponTubeDisallowMissle(0, "Mine")
    template:setTubeDirection(1, 5):weaponTubeDisallowMissle(1, "Mine")
    template:setTubeDirection(2, 180):setWeaponTubeExclusiveFor(2, "Mine")

**Comment by daid** [comment]
I indeed swapped the order. In the latest code.

The order is tube "0" at the top, and then going down.
