### ISSUE TITLE
Regular releases?

### ISSUE THREAD

**Issue by someone-somenet-org** [daid/EmptyEpsilon#2062]
This project seems very much alive, but unfortunately doesnt have regular releases.

Would it be possible to get regular releases?
Like one release per quarter or every half a year?
Please? :)

**Comment by daid** [comment]
A release should be soon. I am just waiting for the translators to get a chance to update a few things.

**Comment by daid** [comment]
New pre-release is up now: https://daid.github.io/EmptyEpsilon/#tabs=5,download-tabs=1
And if no big issues are found, there will be a main release next week.
