### ISSUE TITLE
[Android] Shader Error

### ISSUE THREAD

**Issue by DansDesigns** [daid/EmptyEpsilon#2116]
Hey all!
Loving Empty-Epsilon!
I'm getting multiple Shader errors, it may be that the Android tablet I am using is not able to run EE..

Cube U30GT Android 4.1.1 

able to install both armeabi-v7a and arm64-v8a apks
but when running either version of the game I get the following errors:
1:19:L0001: Expected token ';', found 'uniform' (appears twice)
1:20:L0001: Expected token ';', found 'uniform'
1:31:L0001: Expected token ';', found 'uniform' (appears twice)
1:27:L0001: Expected token ';' found 'const'

clicking 'ok' on each error box brings up the next error, then after the last the game just shows a black screen..
anyone have any ideas?

thank you!

**Comment by daid** [comment]
There was a missing `;` in a conditional path that only happens on low-end devices. And looks like you are the first to do this low :)

How critical is it for you to have it working on this device? As in, how long can you wait for a release?

(if the shader fails to compile, then a black screen totally makes sense)

**Comment by DansDesigns** [comment]
hey thanks for the reply, 
its not essential, just testing the lower limits really :)

I have a couple of Android 4.01 and 4.1.1 Tablets laying around and was hoping to find a use for them.. 
Is it possible to build EE for these lower version devices?

I imagine lots of people have older tablets and phones just sitting in draws, might be a good way to bring some life back into them?

**Comment by daid** [comment]
My lowest device I had access to at the time I added android support was an Samsung S3, which has android 4.4

I would not be surprised if lower versions are possible. But there are a bunch of things to this:
* How much effort are you willing to put into this, building for android requires quite a bit of setup, but is explained at https://github.com/daid/EmptyEpsilon/wiki/Build-%E2%80%90-Android (you do need a linux system to build on)
* Depending on the device, you might have an ARMv5 or MIPS device, which requires an older SDK and a different ANDROID_ABI setting. And might need an older SDL2 version as well.
* OpenGL ES 2.0 is required, some older devices might only support OpenGL ES 1.x, which would require rewriting most of the rendering code, not really feasible.
* After all this builds, it might not run, and you'll need to debug on the device or check the android logs with logcat.

**Comment by DansDesigns** [comment]
Ahh i see, thank you that's alot of good bits of information!

After some digging the specs of the tablets that failed to run:
Cube U30GT - Android 4.1.1 - RK3066 CPU with Mali 400 - OpenGL ES 2.0, OpenGL 1.1
GoClever A972BK - Android 4.0.4 - Allwinner A10 Mali 400 - OpenGL ES 2.0, OpenGL 1.1 - (wont install - prob due to being a sun4i based cpu)

**Comment by daid** [comment]
Ok, so in theory they could work, but do require custom builds.

**Comment by DansDesigns** [comment]
> Ok, so in theory they could work, but do require custom builds.

Ah ok, good to know.. I may try and build for them at somepoint, have a linux pc but not built for android before, most of my experience is with Arduino and esp32s 😄

On a related note. Where are the script files n such located on android? I couldn't see any folders related to EE in sdcard/Android/..

**Comment by daid** [comment]
On android everything is packed into the app assets

**Comment by DansDesigns** [comment]
haha ok, that would be why i couldnt find any script files!
