### ISSUE TITLE
Potential Error in Windows MSVC Build Process

### ISSUE THREAD

**Issue by Dravid346** [daid/EmptyEpsilon#2117]
While following the [build instructions in the wiki](https://github.com/daid/EmptyEpsilon/wiki/Build-%E2%80%90-Windows-with-MSVC), I encountered an error when using CMake. In step 6, when I clicked "Configure", I got errors saying "Permission Denied". I was able to find a simple solution online, but I believe addressing the potential error and providing a fix within the wiki would help developers more easily build the game from source. I propose adding the following line under step 6:

    * You may get "Permission Denied" errors. If this happens, try running CMake as administrator.

If this is acceptable, I'd like to add it myself as my first contribution.

There's also a typo in line 16 where "with" is spelled "whith".

**Comment by daid** [comment]
The wiki build instructions are community driven, you are free to edit those.
I also just added a note that MSVC builds are not something I put effort in to support. People are free to do so, and I will accept patches if something is broken for MSVC specifically, but I won't go out of my way to test this specific build platform.

The recommended/supported method of building on/for windows is the [cross compile on WSL](https://github.com/daid/EmptyEpsilon/wiki/Build-%E2%80%90-Windows-on-WSL) method.
