### ISSUE TITLE
Headless server playing audio

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#212]
When you run Empty Epsilon with the ``headless=scenario_01_waves.lua`` parameter, audio (music) is played, even without starting a client.

In my opinion, the Main Screen client should play the music files, not the headless server.
(I'm wanting to run this as dedicated server for events and Internet play.)

To replicate:
Run ```EmptyEpsilon.exe headless=scenario_01_waves.lua``` in windows
or
```./EmptyEpsilon headless=scenario_01_waves.lua``` on Linux (untested)

**Comment by oznogon** [comment]
Confirmed that the music begins playing on OS X by running `./EmptyEpsilon headless=scenario_01_waves.lua` from `EmptyEpsilon.app/Contents/MacOS`.

**Comment by daid** [comment]
As intended, the server is running the music. Else you would have two sets of music when you have two main screens.

**Comment by gguillotte** [comment]
So the workaround/solution is to turn the music volume to nil on the headless server?

**Comment by oznogon** [comment]
So the workaround/solution is to set the music volume to 0 when running headless?

**Comment by kwadroke** [comment]
So, what about if you are GM'ing a game? Since the GM is has to run the server, I doubt the GM would care about the music.

**Comment by MyrddinE** [comment]
This is actually the issue we are running in to for our online games. The GM hears music... 6 clients hear nothing. While the option makes perfect sense for LAN play, it's not very good for Internet usage. Perhaps a Music button that clients can click? With a musical note on it? And potentially a server option to block clients from seeing the button when on LAN (or conversely, hide it by default and only show it when the server enables it) so you don't get competing music playing when unwanted.

**Comment by oznogon** [comment]
The combat/ambient music switch is triggered on the server by changes to the threat level, which is [determined by and occurs on the server](https://github.com/daid/EmptyEpsilon/blob/68451f9317f377a65c99ab88b3aab20e84807df1/src/epsilonServer.cpp#L18-L23). Those `threat_level_low` and `threat_level_high` functions trigger music playback in the server only, so it assumes the server is always part of the game presentation (probably as the main screen).

Running `headless`, however, means the server itself probably isn't part of the presentation. GMs on the server also might not want music on their station, but instead only the main screen client.

If it's possible for the `threat_level_low` and `_high` functions to trigger a function on screens in addition to the server, and if screens are capable of playing music, it should be possible to play and change music:

-   Add a `music` option to `options.ini` and the preferences screen, with valid values of true, false, or default, and a default value of default.
-   During gameplay, the server retrieves the threat levels of player ships as it does now.
    -   The server sets an appropriate value (in playerInfo?), such as `player_threat_level = (high|low)`.
    -   If the server's `music` option is set to true or default, or if its `headless` and `music` options are set to true:
        -   Play the appropriate set of music on the server.
        -   Else, don't start playing music on the server.

For the screens:

-   If a screen isn't on Android (which doesn't have the music files):
    -   If the screen is not the server, and the screen's `music` option is set to true:
        -   If `player_threat_level` has changed, play the appropriate set of music.
        -   Else, don't start playing music on the screen.
    -   Stop playback on client disconnection.
    -   (Alternatively, add `CMD_PLAY_LOW_THREAT_MUSIC` and `CMD_PLAY_HIGH_THREAT_MUSIC` commands to `playerSpaceship.cpp`, and add a `setPlayerMusic` function to `playerInfo.cpp` that toggles music changes.)

This would resolve this issue (a server that's `headless` would not play music by default), as well as @MyrddinE 's (clients capable of playing music could set `music` to true, and ambient/combat music playback changes would still be controlled by the server).

I might play around with implementing this.

**Comment by daid** [comment]
The threat level estimate object can run fine on clients, so that makes it easier.

My previous comment was just to mark that it's not a bug, it's intended design. But the game has grew past that design.

**Comment by kwadroke** [comment]
Gotcha. Removed the _bug_ text from issue

**Comment by oznogon** [comment]
Sorry for the GitHub noise.
