### ISSUE TITLE
REQUEST - Headless server network select & server name option

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#213]
Since we have the master server now, there's not a way to make a headless server register with the master.

Needs to be an option to allow the headless server to register with the master server like you can through the GUI. Without the option, the default should be LAN. Should be able to save this setting in option.ini.
Also need to be able to give the server a name via the command line/option.ini & save it if entered in the GUI.

**Comment by Fouindor** [comment]
With 77bac36 , more headless options are added, you can add to options .ini :
- headless_name, which sets the server's name (if not present, default is still "Server")
- headless_password,  which sets the server's password (if not present, default is no password)
- headless_internet, if set as 1, creates an internet game. As I'm most of the time on a "locked" network however, I was not able to test this setting. If someone can confirm it works, it would be great :)

**Comment by kwadroke** [comment]
I've confirmed that headless_internet, & headless_name works. Haven't tried the password yet.

**Comment by kwadroke** [comment]
Password works. These are all being called from the command line. Haven't tried to use it via options.ini yet.

**Comment by oznogon** [comment]
These all appear to work for me, both as flags and in `options.ini`.

**Comment by kwadroke** [comment]
I'll close this then.
