### ISSUE TITLE
[Documentation] Wiki Helms page has 2 typos/grammar issues. 

### ISSUE THREAD

**Issue by LeoSantich** [daid/EmptyEpsilon#2134]
The Helms page in the project wiki has 2 typos.  I read and understand the contributor rules regarding one pull request for one issue, but they're both within the same file, and they're not coding issues, so attempting to submit as one issue.  They're contained in the url attached here:
https://github.com/daid/EmptyEpsilon/wiki/Helms

The first typo is in the Short Range Radar section.  In the 'missiles' bullet, the sentence reads as, "[missiles](https://github.com/daid/EmptyEpsilon/wiki/Weapon-Types) within the short-range radar's range, which appear as small arrows that indicate their type by color (yellow for homing, orange for nuke, blue for EMP, and gray for HVLI) and their facing".  Proposing the sentence should simply read as, [missiles](https://github.com/daid/EmptyEpsilon/wiki/Weapon-Types) within the short-range radar's range, which appear as small arrows that indicate their type by color (yellow for homing, orange for nuke, blue for EMP, and gray for HVLI) and their facing _weapons tubes_."  Could also perhaps use 'missile tubes', though I feel weapons tube would be more consistent from reading the other documentation.  

The second typo is in the fourth paragraph of the Jump drive section.  The sentence reads, "A blind jump could land the ship far from from its intended destination, or even in the middle of asteroid or mine fields, a black hole, or formations of enemy ships."  Proposing the sentence should remain the same other than removing one of the 'from' words out of the sentence.

- I'm just posting this issue as an assignment for school.  It is not a dealbreaker or showstopper in any way whatsoever.  
- I'm not expecting much at all from this pull request.  If it gets accepted, I would be more than happy to fix the issue.  Would love to fix more issues perhaps if this goes well.  
- The only thing happening is a couple typos in a doc.  I have read much documentation and this is the only thing I've found, so consistency could be the only good reason to address this issue.
- This issue should be affecting all Operating Systems though it is possibly only a cosmetic issue if that.

**Comment by daid** [comment]
Wiki pages are community maintained, so free free to clean up any typos.
