### ISSUE TITLE
ECS prerelease 2024-10-03: math.pow fails

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#2181]
I get this error on the Waves scenario:
![Screenshot 2024-10-03 at 7 45 39 AM](https://github.com/user-attachments/assets/cebc8c0b-2783-4546-a9ef-3d5ea863b065)
It looks like it's failing on this line of code:
`totalScoreRequirement = math.pow(waveNumber, 1.3) * 10`
I seem to recall reading in Lua documentation somewhere that math.pow has been deprecated. The same thing should be able to be accomplished with x^y which would be something like
`totalScoreRequirement = waveNumber^1.3 * 10`
in this case.

**Comment by daid** [comment]
Note to self, set `LUA_COMPAT_MATHLIB` on lua library to fix.
