### ISSUE TITLE
ECS Prerelease 2024-10-03: Freeze on Allies and Enemies

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#2183]
EE freezes when I try to start the Allies and Enemies scenario:
![Screenshot 2024-10-03 at 8 18 54 AM](https://github.com/user-attachments/assets/96dd1f6c-406d-43ba-9689-f196525af3c7)
Start server > Start server > Replayable Mission > Allies and Enemies > Start scenario > Start scenario
I made no changes to the Enemies configuration widget (left it defaulting to normal), just tried clicking the final Start scenario button. I have to hard kill EE.

_Note:_ At this point, I'm just running EE prerelease 2024-10-03 under Wine on Mac. I have not built it on Mac, nor have I built it on my Linux box. I would not think that would make a difference, but I want to be sure I provide potentially pertinent diagnostic information. This is also true of #2182 and #2181

**Comment by Xansta** [comment]
Similar freeze for scenario Borderline Fever

**Comment by Xansta** [comment]
Similar freeze on scenario Unwanted Visitors

**Comment by daid** [comment]
You have a `repeat` `until(#kraylorStationList >= 5 and #humanStationList >= 5 and #exuariStationList >= 5 and #arlenianStationList >= 5)` in the init which never seems to end.


Your scenario is a bit to large and complicated to diagnose completely for me. But, I do see that you use objects as keys in tables, which I'm surprised even works in the first place, and will very likely cause problems with the ECS branch...

**Comment by daid** [comment]
As you where checking if things where in the right zone, and that implementation was missing, the scenario refused to place stations and ended in an endless loop. That part is fixed now.
