### ISSUE TITLE
ECS Prerelease 2024-10-03: onTakingDamage callback error

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#2189]
Scenario Locust Swarm gives me this error:
![Screenshot 2024-10-03 at 1 02 58 PM](https://github.com/user-attachments/assets/bcaa9056-946b-4d4a-aefc-c6faa834841d)
This is the line of code:
`if self.components.hull then self.components.hull.on_taking_damage = callback end`
in the `Entity:onTakingDamage(callback)` function.

I think it might be useful to have one more line in the pop-up console. I think there may be more error information in the line just above the "stack traceback" line (not included in the console pop-up).

**Comment by aBlueShadow** [comment]
You can scroll up by selecting the text

**Comment by Xansta** [comment]
Thanks @aBlueShadow 
Here's a bigger picture:
![Screenshot 2024-10-03 at 3 43 34 PM](https://github.com/user-attachments/assets/6540441d-7834-40e8-bb25-deb161239b78)

**Comment by daid** [comment]
Note that the console window is a read-only text field, so it allows coping the data from it, no need for screenshots.

**Comment by Xansta** [comment]
Thanks. I did not know that at the time I took the screen shots for this issue.
