### ISSUE TITLE
ECS Prerelease 2024-10-03: Default player heading at spawn has changed

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#2191]
When a player ship is spawned, it used to default to heading 90. Now it's randomized. I noticed this on scenario Deliver Ambassador Gremus. When I wrote this scenario back in 2018, I specifically placed the player head to head with enemies. Now, that confrontation often does not take place because of the random heading of the player ship.

Relevant code in scenario:
```
	playerCallSign = "Carolina"
	player = PlayerSpaceship():setFaction("Human Navy"):setTemplate("Flavia P.Falcon")
	player:setPosition(22400, 18200):setCallSign(playerCallSign)
```

At the time I wrote Deliver Ambassador Gremus, I had problems figuring out heading vs rotation, so I just took the default and worked with it. Now, the scenario can probably be modified to point the ship in the 90 degree direction. This may be the only scenario that relies on the default player heading.

**Comment by daid** [comment]
It used to be inconsistent, cpu chips and stations have a random rotation. And player ships from the GM screen and ship selection screen also had a random rotation. Only those created by a script had the default.

So I made it consistent (and easier code wise) and I think it would be easier to fix the scenario.

**Comment by Xansta** [comment]
Updated scenario in #2198
