### ISSUE TITLE
QUESTION: Does the CMake build system allow overrides of things like version numbers?

### ISSUE THREAD

**Issue by mhjacks** [daid/EmptyEpsilon#221]
Hello,

I'm working on Linux packaging for Empty Epsilon.  I've worked with build systems before, but CMake is new to me.

I assumed that "cmake .. -DSERIOUS_PROTON_DIR=$PWD/../../SeriousProton/ -DCPACK_PACKAGE_VERSION="2016.05.07" -DCPACK_PACKAGE_VERISON_MAJOR=2016 -DCPACK_PACKAGE_VERSION_MINOR=05 -DCPACK_PACKAGE_VERSION_PATCH=07 -DVERSION_NUMBER=20160507" would be enough to force the variable versions to the right values for interoperation with the official downloads.  It worked yesterday, but yesterday was, exactly, 201600507.

My builds today are coming out with 20160508 as the version, which leads me to believe the variables I'm passing are not being honored.  I can get the desired results by hand-editing the intermediate files with sed or something.  Am I using CMake wrong?

I should note:  These builds are on Raspbian 8 (Jessie) on a Raspberry Pi 2.

**Comment by daid** [comment]
That is the proper way to set the variables in CMake, however, the CMake script overrules them with these lines:
```
string(TIMESTAMP CPACK_PACKAGE_VERSION_MAJOR "%Y")
string(TIMESTAMP CPACK_PACKAGE_VERSION_MINOR "%m")
string(TIMESTAMP CPACK_PACKAGE_VERSION_PATCH "%d")
```
So you could comment out those lines.

You could also comment out this line:
```
add_definitions(-DVERSION_NUMBER=${CPACK_PACKAGE_VERSION_MAJOR}${CPACK_PACKAGE_VERSION_MINOR}${CPACK_PACKAGE_VERSION_PATCH})
```
Which will remove the version number from the build, and make it version 0. Version 0 is accepted by any other version. For debugging.


Finally, I tried it on the Pi2 with the new open source OpenGL driver, I had crashes every few minutes, and the performance was just below acceptable.

**Comment by kwadroke** [comment]
I had it running on a Pi 2 & 3 back in March. I too had some problems with crashes. Haven't dug into why as of yet. I did run it with disable_shaders=1. If I remember correctly, it seemed to help. I'll test it again  and bring up the FPS.

**Comment by mhjacks** [comment]
I've done this in the latest version of my build script:

`sed -i "s/string(TIMESTAMP CPACK_PACKAGE_VERSION_MAJOR \"%Y\")/set(CPACK_PACKAGE_VERSION_MAJOR \"$MAJOR\")/i" CMakeLists.txt
sed -i "s/string(TIMESTAMP CPACK_PACKAGE_VERSION_MINOR \"%m\")/set(CPACK_PACKAGE_VERSION_MINOR \"$MINOR\")/i" CMakeLists.txt
sed -i "s/string(TIMESTAMP CPACK_PACKAGE_VERSION_PATCH \"%d\")/set(CPACK_PACKAGE_VERSION_PATCH \"$PATCH\")/i" CMakeLists.txt
`

with $MAJOR, $MINOR and $PATCH set elsewhere.

**Comment by r-barnes** [comment]
#941 shows the version number as part of cmake's output, to provide early warning signs of misconfiguration.
