### ISSUE TITLE
REQUEST : visual beams

### ISSUE THREAD

**Issue by elptito** [daid/EmptyEpsilon#222]
As visual asteroid enhance the visual of the game, could it be possible to add visual beams during combat ?

I think about beams above or below the ships between two real beams, to look like space fight in star wars for exemple.

**Comment by daid** [comment]
Not sure what you mean? The current beams are a direct result of weapons being fired...

**Comment by elptito** [comment]
Yes, but I think that it is very realistic and spectacular : only few beams are fired, and they always strike their target. I find that, between two "regular" beams, a dozen of fake baems could be see only in the main screen (not in the weapons stations) which miss the target. The visual of the fight could be more impressive.

something like that : 
[image](https://awesomewallpapers.files.wordpress.com/2009/10/the_battle_of_endor_by_goyney.jpg)

**Comment by nallath** [comment]
In star-wars it works because the beams are not really beams. They are more like projectiles.

**Comment by elptito** [comment]
You dare challenge my physics knowledge about star wars universe ! :)
More seriously, I only think about something more visual in the main screen, For me, fights are a little too statics and it's possible to solve it without using 3D. It is the same logic for the visual asteriod after all.

**Comment by kwadroke** [comment]
Being that most Bridge Sims are based on Star Trek than Star Wars, I think the current way is more accurate. Perhaps if a ship is moving and the beams targets the last location of the ship to produce a beam missing its target, that could produce closer to what I think elptito is asking about.

**Comment by elptito** [comment]
Kwadroke, I think your idea leads to a more difficult game, and It is not what I suggest. I think that the current system of fights is very nice, and it was only a matter of visual. If you don't think it could be interesting, it is not a big deal (it was more a suggest than a request, sorry about the title of the post).

And, indeed, I realise now that I am more a Star Wars fan than a Star Trek one :)

**Comment by daid** [comment]
I don't think it fits with the current game, where you also have other indications of beams firing (color of the beam arcs)

If beams could miss, that's a whole different thing.

**Comment by kwadroke** [comment]
I'm both a Star Trek and a Star Wars Fan. One of things I want to do after I finish my Star Trek Mod for EE, is to create a Star Wars mod. I'm in the 501st Legion (Star Wars bad guys costuming group), so I want a way for my Star Wars friends to play EE in that universe.

**Comment by oznogon** [comment]
I think there'd be no functional difference, only that when firing beams, the main-screen visual would be a stream of small projectile-looking blasts within the beam path instead of a single ray for each fire. The beam fire, hit, and damage rates would be the same.

**Comment by CaptLapadite** [comment]
Another option could simply be to add more beams to a ship, decrease it's recharge time and damage. 
Voilà, a bunch of lasers in air-less space ! 
"piew piew"

**Comment by elptito** [comment]
Thanks CaptLapadite for your idea, indeed it can be enough, I will test it !

**Comment by lunerfox** [comment]
@elptito Keep in mind to raise total ship power accordingly, since all beams use a hard-coded amount of energy per shot.

**Comment by CaptLapadite** [comment]
Hummm really? 
Shouldn't be that the energy cost is related to the base damage of the beam ? It seems strange that a high damage beam cost the same amount as a a less deadly one.

**Comment by MyrddinE** [comment]
@CaptLapadite Well, that sounds like a good enhancement request to put in. :-)

I agree with the idea, because otherwise ships with many lasers will have no energy issues ever when dealing with the other parts of the ship, which have a mostly fixed energy cost.

**Comment by daid** [comment]
You can configure the amount of heat and energy per beam

template:setBeamWeaponEnergyPerFire(index, amount)
template:setBeamWeaponHeatPerFire(index, amount)
