### ISSUE TITLE
AppImage is possible

### ISSUE THREAD

**Issue by vpelss** [daid/EmptyEpsilon#2234]
This is not an issue, but a suggestion for another way to package and distribute.

I have successfully packaged EmptyEpsilon in the AppImage format.
It is pretty easy to do.

I see you have recently added on flatpak. 
So perhaps the AppImage format is no longer required. 
But it might be something to consider.

vpelss 
@ 
gmail

if interested or questions.

**Comment by jstsmthrgk** [comment]
could you post your build process into this issue? (or a link to repo with the build process in it)

**Comment by vpelss** [comment]
https://github.com/vpelss/EmptyEpsilon_AppImage/blob/main/instructions.txt

and a github actions generated version is here:

https://github.com/vpelss/EmptyEpsilon_AppImage/actions/runs/11806939056

It has not been extensively tested but it looks to be running on a newer ubuntu (WSL)
