### ISSUE TITLE
QUESTION - Is setCommsScript considered as obsolete ?

### ISSUE THREAD

**Issue by Fouindor** [daid/EmptyEpsilon#224]
As there is the much more convenient setCommsFunction, is setCommsScript considered as obsolete ?

If yes, maybe we should phase it out.

**Comment by daid** [comment]
The supply ship (from the generic station comms) is still depended on it. And setting "no script" is currently also only possible by this method.

**Comment by Fouindor** [comment]
Ok, thanks, I wasn't sure if the function is to be discarded in the future.
