### ISSUE TITLE
[Feature Suggestion/Question] Dockerfile / Containerfile Addition?

### ISSUE THREAD

**Issue by Da-Geek** [daid/EmptyEpsilon#2240]
Well, as the suggestion/question states,

I have been using EE exclusively on Linux (Red Hat Based Operating Systems/Fedora/CentOS and so on) to run the Headless Dedicated Servers.

I created a Containerfile (Most people know it as a Dockerfile) to allow me to run the Headless
server, repeatedly but most importantly, cleanly each time.
I supply multiple Environment Vars, and it runs really nicely.

I wondered if this would be a useful/helpful addition to the project?
I am not 100% happy with how I have done it so far, and I need to clean-up some
of the Syntax of the Containerfile, but I could create a PR if needed/wanted by the Project.

Maybe even add an GitHub Image Build Workflow to the release and make it available via ghcr.io

If it is not needed/wanted I will just use it myself.

**Comment by daid** [comment]
I think it's great that you are doing this, but, I don't want to put it in the repository. As that will imply that I will maintain it, and I have no intention to maintain it.
