### ISSUE TITLE
[Scenario issues] varied

### ISSUE THREAD

**Issue by muerteFR** [daid/EmptyEpsilon#2258]
Some problems noted recently on different @Xansta scenarios and files.
I will add here as I go along.

**1. Surf up!**
 I don't know if it's normal that the reinforcements offered in a station are not the same as those displayed in the DB information.
![Owen](https://github.com/user-attachments/assets/b2cab634-9176-441d-9ba5-3a5600bfa5c7)

![Owen 2](https://github.com/user-attachments/assets/dc5de335-9b1c-4d09-bef9-b1e302245e23)

**2. comms_scenario_utility**
Is it possible to add a translation tag line 757 to be able to specify "Sector" in front of the sector name? It is useful for French translation.
![Secteur](https://github.com/user-attachments/assets/b7f52c55-ed65-4678-964a-7a711b541f13)

**3. Shoreline** The Settings cannot be translated. It's "Variation" again.

**4. Liberation**
The menu of transactions with a freighter is strangely done. The question “Do you sell freight?” » is located at the same level as the purchase buttons for goods sold by this ship. “Buy %s for %i rep” for example.
![freighters](https://github.com/user-attachments/assets/4b85a95b-be60-4f74-92fa-9a55eb6a6c2f)

**5. Surf up !**
When the enemy base has defense platforms, if the base is destroyed, the defense platforms will self destruct after the rest of the enemy ships are destroyed. The message that should appear in Shiplog after about 60s appears well with Xansta but not with me despite several tests.
Xansta
![4](https://github.com/user-attachments/assets/07d825bb-9262-4f3f-a2a8-3e97f21cfa36)

muerte
![1](https://github.com/user-attachments/assets/1599ca73-3248-43b1-95e4-e0b22fac4c7d)
![3](https://github.com/user-attachments/assets/03e7e0d5-2a95-4944-9592-aaf26ba5acc5)
![2](https://github.com/user-attachments/assets/f77a227a-90f1-4aff-ad72-da9c708dec66)

Edit : BlueShadows tried in DE and it works. The problem comes from me.
![error](https://github.com/user-attachments/assets/ccdbf2b3-5c49-4ffe-a467-ddc05faf75da)

**Comment by Xansta** [comment]
These are nicely numbered here in this single issue and the screenshots and descriptions are great. It would be even nicer if they could be broken out into individual issues in github with a title that reflected the issue observed. Correlating fixes and comments to issues is harder if several issues are in a single github entry.

Examples:
Issue number 1: 
issue title: Surf's Up scenario - reinforcements info in science DB does not match comms report

Issue number 2: 
issue title: Comms scenario utility - add context translation tag for 'Sector' 
(this one may already be addressed btw)

Issue number 3:
issue title: Shoreline scenario - settings cannot be translated (they are still 'variations')

issue number 4:
issue title: Liberation scenario - weird freighter comms

issue number 5:
issue title: Surf's Up scenario - defense platform self destruct message not appearing in ship log
