### ISSUE TITLE
[Request] Lasers as turreted systems

### ISSUE THREAD

**Issue by lunerfox** [daid/EmptyEpsilon#227]
As a separate but related idea in #226 , Laser beams could be designed as being turreted. 

As it stands, an enemy ship is either Inside the firing arc, or outside. This leaves little room to do any sort of "Evasive Maneuvers" , where a ship is inside the firing arc, but actively avoiding being shot at.

My suggestion is to think of the firing Arc as the possible range and angle that a gun is **able** to hit, but the turret needs time to actually bring the guns to bear. The actual angle that a gun is pointed at can be shown via a line, similar to the way the missile trajectories are shown.

When an enemy ship is targeted, all turrets will attempt to turn towards the heading. as long as the line passes through the ship, the gun is trained on the ship and can fire normally.

Not sure if firing lines from other ships should be visualized, or if so, how to visualize them.

Each gun can have a default turret turn speed, but should be modifiable via script (Large Capital ships should have big guns that take a long time to turn, while fighters should have turrets that turn almost instantly.

**Comment by lunerfox** [comment]
I liked to see the idea of turreted beam weapons (especially with the discussion of some variety in beam weapons such as #241 , so I made a basic implementation showcasing how it would work to spur some discussion.

First, I changed the UI to show the arc as an outline, and added a line extending to the edge of the beam's maximum range. The line represents the beam's current direction. Atlantis X23 has 2 guns, so there are 2 line. They are white because they are currently not locked onto any target.
![turret1](https://cloud.githubusercontent.com/assets/3700635/15347694/e08d2f68-1c78-11e6-8513-83c1be040953.png)

The 2nd screenshot shows my ship being chased by 2 enemies, 1 of which is fully scanned. The fully scanned ship shows the turret's heading.
![turret2](https://cloud.githubusercontent.com/assets/3700635/15347739/4bb0a860-1c79-11e6-8c59-92bfe3de6fbc.png)

Turning the ship around in the 3rd screenshot, I target an enemy ship. Turrets will move towards targeted ships as best they could, either reaching the required firing position or reaching the maximum arc of the gun. The rate of how fast the turret is able to turn can be edited.
![turret3](https://cloud.githubusercontent.com/assets/3700635/15347800/9130bd44-1c79-11e6-8300-9aa3a17b586a.png)

Firing the guns will change the line's color from Red back to Green to visualize the cooldown.

The 4th screenshot shows the key idea of why turrets are interesting; It is possible to be within a ship's firing arc, but not get hit. Here, I've finished firing on SS2 and changing my target to CV5. The gun is ready to fire (As evidenced by the line being green), but since the turret has not physically moved to the correct position, it will not fire.
![turret4](https://cloud.githubusercontent.com/assets/3700635/15347824/c9b5c088-1c79-11e6-936b-b62f05c9d17f.png)

Having something like this would dovetail nicely with the idea of adding more diversity with the beams, creating small but quick turning "Point Defense" guns for close range, Medium beams, and huge "Death rays" that cause massive amounts of damage but very slow to turn. 

Small ships can use their speed and numbers as an advantage to avoid the beams, getting in close...etc.

**Comment by nallath** [comment]
I agree with you here. We already have a few ships that use systems like this, but then we simply lowered the turning speed of the ship to get to that point. 

The starHammer for instance is a good example for it. The ship should have a big ass laser that can't turn very fast, but once it locks it can dish out a lot of damage. 
Ships that are especially designed to combat fighters should have point defence turret emplacements. This would be cool for the larger ships as well, as they could have "holes" in their point defense turrets.

In the case of larger ships, it would be better to see the circles in which the point defence can shoot, because the lines wouldn't give enough info (or just display the arc + line).
