### ISSUE TITLE
Collision detection is off for really large ships

### ISSUE THREAD

**Issue by vslotman** [daid/EmptyEpsilon#23]
When I add a really large ship to the game (for example a Battlestation) and let AI-ships attack it, the AI-ships jump back and forth very fast when they are close to the Battlestation. 
And it might by by design, but a Battleship cannot use its beams when its target is too close.

**Comment by daid** [comment]
The battlestation is currently unfinished, there are quite some AI issues when you add this one to the game, it's more a showpiece then a gamepiece right now.
