### ISSUE TITLE
[Issue] Don't work on Galaxy Tab (1) 10.1 

### ISSUE THREAD

**Issue by elptito** [daid/EmptyEpsilon#234]
Hi,

I recently restore my old tablet Galaxy Tab 1 (10.1), and I tried to install EE on it. EE could not be installed with the official build so I install a CM mod version 10 (http://download.cyanogenmod.org/?device=p4wifi).
Now I can installed the release but when I launch the game, I have only a black screen.
Does anybody have an idea about this issue ? Can I miss something ?

Thanks in advance

**Comment by oznogon** [comment]
I have the same issue on a 2012 Nexus 7 running stock Lollipop 5.1.1. I think older tablets might not support the requisite OpenGL features.

**Comment by kwadroke** [comment]
Android itself doesn't support regular OpenGL. It requires OpenGL ES.
Daid's builds (should) disable the parts that use OpenGL.

I just tested 2016.05.07 on a Samsung Note 3 with Android 4.4.2 and it seems to work fine. I don't have a way to test it by connecting to a client, but the game launches fine.

**Comment by oznogon** [comment]
@kwadroke Older tablets lack GPUs that meet some of the GLES requirements. The 2012 Nexus 7 doesn't support GLES 3.0, for instance.

**Comment by kwadroke** [comment]
It's probably an issue with SFML or the way it's being used then.
I don't think it's using GL/GLES, but, daid can better answer that.

**Comment by daid** [comment]
SFML is using OpenGL ES 1.1, so that's not the issue. However, SFML support for Android isn't perfect yet, and there are quite a few glitches.

**Comment by elptito** [comment]
My tab has now Jelly bean (4.2.2) with CM, but I cannot have a newer update. And, I try to install previous release, but nothing work. I think my device is (very) too old.

**Comment by elptito** [comment]
I give a last try with Lollipop 5.1.1, without suceess. I'm giving up. thanks for your message
