### ISSUE TITLE
[REQUEST] modification of the Game Master station

### ISSUE THREAD

**Issue by elptito** [daid/EmptyEpsilon#236]
Could it be possible to show the coordinates of the pointer when the GM explore the map ? I think this could help to script mission.

And, in the same way, could it be possible to add a button to find easier the playership (for exemple the first) ?

**Comment by daid** [comment]
If you have an object selected it shows the coordinates.
And there is the "hidden" feature, if you press F5 in the GM screen, it places a script on the clipboard, that can be executed to re-create about the same world as that you have at that point in time.

I'll think about some player-ship indicators.
