### ISSUE TITLE
possible bug, hit by invisible ships

### ISSUE THREAD

**Issue by ErikDeBruijn** [daid/EmptyEpsilon#24]
While playing with the physical consoles we kept getting hit by beam weapons by a ship that wasn't even visible on radar. Also things appeared to be in different places on different stations. The lack of laptop resulted in my macbook running the latest build (20150227) for windows through wine. This laptop was the server. The other laptops had not been manually updated since Thursday. Another windows laptop ran the main screen and it showed no objects, only nebulae. Even though a ship was right in front of us on the radar.

Do you think its related to the different versions running? Can/should I upgrade the Linux systems manually, or would a bug be there on more stations in that case?

**Comment by daid** [comment]
Yes, this is related to different running. Manual builds will report version 0, and version 0 is allowed to connect to everything, but no guarantee on anything working.
