### ISSUE TITLE
Combat maneuver as a single control

### ISSUE THREAD

**Issue by lunerfox** [daid/EmptyEpsilon#243]
Right now, combat maneuver is based on 2 sliders; A forward booster and a side-to-side booster. Since multi-touch is not supported, only 1 of the 2 sliders can be used at the same time.

It would be nice to have finer control of the boosters. Would it be possible to implement the combat maneuver bars as a semi-circle? The resulting vector can be used to determine the total amount of thrust in the forward and side-to-side directions. The heat generation rate would be the magnitude of the vector.

**Comment by nallath** [comment]
Good one. This enables a lot nicer maneuvring. It shouldn't be hard to implement either.

**Comment by Wrongtown** [comment]
Any reason not to make it a circle? The ships can fly backwards so it makes sense that they can boost backwards as well.

**Comment by oznogon** [comment]
Except for reverse boost (which looks like it'd require modifying the combat maneuver functionality to implement), this appears to be added to the crew6 controls as of a7fe16e76771e90d516c09a33993d35369a44c39, and to the crew4 and crew1 controls in a4d963f0ef821e72d55578ca18e6f8272b85ef18 and da82078f8fa0808a0aed05011e0a272edb9b0a7a.

**Comment by nallath** [comment]
The combat maneuvers are now a single control.
