### ISSUE TITLE
REQUEST - Mask server password entry

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#245]
There are two problems when a client enters a server password in the server selection UI:
1.  The password is case sensitive, but the font used to display the password is all caps, which can be confusing if the password uses a mix of upper and lowercase letters.
2.  The password is visible on the client while entering it.

Masking the password (showing \* instead of the letter, for instance) could be a workaround to both issues.

**Comment by JonathanILevi** [comment]
This is at least half solved?

**Comment by lambdaTotoro** [comment]
I think this can definitely be closed, the password is masked by now.
