### ISSUE TITLE
[BUG] Science station lags when too many nebula

### ISSUE THREAD

**Issue by elptito** [daid/EmptyEpsilon#258]
We tryed to spawn a lot of nebula, but this slow down the science station.
According to our tests : 
100 or less -> good
100 - 500 -> little slow down
1000 -> very slow down

it happens even if nebulas are far far away from the player space ship. This problem does not happen with relay of GM station. So I think that Science takes into account all nebulas and their effects on the view, and I think it is not necessary. Is it possible to solve that ?

**Comment by nallath** [comment]
I'd say the problem here is that hit detection is a difficult thing to do right. The science station needs to do ray casting to every nebula to check if it's visibility is effected in some way.

**Comment by Fouindor** [comment]
Seems to me that the problem is precisely that the drawNebulaBlockedAreas() function draws every Nebula. It should do only the nebulae in range (that is to say closer to the scan point than the radar distance + nebula radius).

**Comment by daid** [comment]
Note that spawning a shitload of nebula is still intensive for the game. As every "blocked by nebula" check checks all nebula. The patch from Fouindor does fix the most intensive rendering part of the science station problems. But you could still have general slowdowns if you have lots of ships and lots of nebula.
