### ISSUE TITLE
Joystick interface for fighter pilots

### ISSUE THREAD

**Issue by ErikDeBruijn** [daid/EmptyEpsilon#26]
I've played a bit with SFML and joysticks and I can easily implement a Logitech RumblePad 2. If one or more fighter ships are added I want them to be able to be controlled by the Rumblepad (or equivalent).

Daid mentioned a concern about joystick input feeling "off" because the server is the master of the game state, not a fighter (usually a client). For low latency control that feels right, we could decide to let the server accept the joystick input as it can handle several Rumblepads through a USB Hub.

Also, the Rumblepad can vibrate on impact (e.g. inbound missiles, collisions or beams), although that might be a bit harder to implement as I'm using the standard SFML joystick agnostic implementation to avoid adding more code than needed.

**Comment by ErikDeBruijn** [comment]
I've completed basic joystick support. See this pull request https://github.com/daid/EmptyEpsilon/pull/28 

If I say so myself, I think it really adds to the gaming experience. Especially if the player has a headset and can only hear the captains orders through relay.

**Comment by amir-arad** [comment]
I think this issue is closeable 
@daid
