### ISSUE TITLE
BUG - Multiple repair crews can occupy the same position

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#261]
Multiple repair crews can be in the same position on a ship, effectively stacking themselves into a single spot. This allows engineers to place more repair crews into a room than it should hold. For instance, with this bug it's possible to fit three crew members into the two-position rooms on an Atlantis X23.

To reproduce:

- On the Engineering station, select a repair crew, then click a position in the ship.
- Before the crew reaches its destination, select another crew and click the same position.

Expected result:

- The second crew to arrive either finds an open position in the same room or stops in an empty position outside of that room.

Observed result:

- The second crew stacks on top of the first crew to occupy the same position.

Here's two crews stacked in this manner between the reactor and jump drive rooms.

![crewpos](https://cloud.githubusercontent.com/assets/19192104/15631264/88551bcc-2514-11e6-960f-bcd37dd1114a.png)

**Comment by kwadroke** [comment]
I've seen that problem myself occasionally.

**Comment by daid** [comment]
Yep, can happen. It's more fun if you use the player version of the Flavia (light transport), as it has a lot of repair crew. And a layout that can require quite a bit of walking.
