### ISSUE TITLE
REQUEST - Loopable sound effects

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#274]
Can sound effects be looped? It looks like only the music channel loops.

If SFX could be looped, that would open up options for engine noise and shield hum, repeating alarm klaxon sounds, and ambient system sounds. Engine and shield feedback in particular would help provide some passive feedback about when those systems are active.

**Comment by daid** [comment]
Sound is currently a bit of a mess. I'm not even sure why it seems to work properly for shield up/down effects right now :-)

**Comment by lunerfox** [comment]
+1 on this; Would be even better if sound effects can be triggered like in hardware.ini

**Comment by CaptLapadite** [comment]
Just a note: we have a sound designer working a the moment to improve the different sounds of the game. 

Improving the support for ambient sound, jump and warp sound, and incoming communications will be nice in the future :)

**Comment by AlexBail** [comment]
If there was some coding for looping sound, i could work on the ship engine movement (some pitch shifting could be really nice for when the vehicule is going faster or slower) Some ambient sound could be added on the side. We could even add some different stuff for the engineer "fader" etc.
