### ISSUE TITLE
BUG - Helm's tube indicators appear on other screens

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#277]
I haven't figured out how to consistently reproduce this, but the weapon tube indicators added to the Helms station eventually appear on other stations.

Here they are on Science after about 5 minutes of Battleground scenario play:

![science](https://cloud.githubusercontent.com/assets/19192104/15800950/9b9752fa-2a3b-11e6-8e02-c4ac3040c4f9.png)

On probe view, they move off the ship and in the opposite direction of the ship, relative to the probe:

![probe](https://cloud.githubusercontent.com/assets/19192104/15800953/acf219fe-2a3b-11e6-880d-b8799d4385e5.png)

On Relay, it appears as though it was on a different Z coordinate than the map objects:

![relay](https://cloud.githubusercontent.com/assets/19192104/15800958/c4ddcafe-2a3b-11e6-8e89-09eca8338e5d.png)

**Comment by daid** [comment]
Should be an easy fix, just an uninitialized variable (which contains a random value)
