### ISSUE TITLE
REQUEST - Use user library on OS X for settings and app data

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#286]
On OS X, use `~/Library/Logs/EmptyEpsilon/` for app and game logs, and `~/Library/Application Support/EmptyEpsilon/` for options.ini, hardware.ini, user resource directories like `resources/mods`, and the `www` directory for the HTTP server.

Also, if the log viewer and `www/index.html` API example page don't exist, copy them into the respective logs and app support directories on OS X. They're not bundled by CMakeLists, and it's unclear where to put them manually.

**Comment by daid** [comment]
Feel free to patch, but know that OSX is not a primary target and can break at any time.

I discovered that Apple is simply hostile towards developers so I do not want to spend my free time to support this OS.

**Comment by oznogon** [comment]
Will do, thanks.
