### ISSUE TITLE
REQUEST - Sound distance

### ISSUE THREAD

**Issue by AstroManu** [daid/EmptyEpsilon#287]
Issue : 
Sound does not seem to be bound by distance. 
It seems to be bound to the player's sight areas, including all allies in the same faction. 
Resulting in having explosions sounds coming from a battle happening 80U away. 

Suggestion : 
Bind sound to distance, with a volume decrease based on distance.

**Comment by daid** [comment]
I'm using positional sound, which OS are you running on?
https://github.com/daid/EmptyEpsilon/blob/master/src/spaceObjects/explosionEffect.cpp#L105

It could be that the parameters are slightly wrong, but it does seem to work for me.

**Comment by daid** [comment]
Note, if you replaced the sounds, they need to be single channel (mono), else positional sound does NOT work.
http://www.sfml-dev.org/tutorials/2.0/audio-spatialization.php

**Comment by CaptLapadite** [comment]
I guess this is the problem. 

I'll check this out and come back to you.

**Comment by oznogon** [comment]
I noticed this on Basic on HEAD builds. On the server with the main screen running, I could hear enemy beam weapons fire at full volume against a station 25U away from my ship. It sounded like my ship was firing.
