### ISSUE TITLE
Text on space stations textures are mirrored

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#294]
The text is mirrored on the textures. Not sure if it's the original textures themselves or the way EE handles them. 
This has been around probably since the space stations were added. Not a huge deal, but, might make things look more polished.

**Comment by daid** [comment]
The actual models are mirrored, not sure why.

**Comment by kwadroke** [comment]
That would explain it. Are the source models that way?

**Comment by daid** [comment]
Nope, so something, somewhere is flipping them. However, if I just mirror them, then the winding order is wrong as well.
