### ISSUE TITLE
How to make pull request (how to keep it focussed to a single change)

### ISSUE THREAD

**Issue by vslotman** [daid/EmptyEpsilon#31]
I'm currently doing a lot of stuff in both EmptyEpsilon and SeriousProton. I'm working on query-string support, permissions for the web interface, and later on some GUI- and controller-things. 
As a result my branch starts to diverge quite a bit from daid's master. This makes it quite a challenge to adhere to the 'single pull-request' rule, since a lot of what I'm doing is dependent on each other. 

When I make a pull-request, Git wants to send _everything_, so I have to hack and slash in my code to get to distill this single change. 
Is there an easier way to do this?

**Comment by daid** [comment]
Send pull requests early and often. And as dependencies go, send a pull for the first thing that's needed first.

In your example, it's clearly the ParseUrl patch, which doesn't depend on other things. Also, making an issue with just explaining what your doing, and a link to your fully changed source tree will help, as I will make comments on what I like and not. (And I can be a bit of an annoying person :) )

**Comment by IvanSanchez** [comment]
@vslotman: You might want to rebase your branch against master. Usually this is not needed but will make pull requests nicer & tidier.
