### ISSUE TITLE
[Issue] I cannot compile anymore

### ISSUE THREAD

**Issue by elptito** [daid/EmptyEpsilon#319]
Hi,

I have a bug when I want to compile (linux). I think it's about SFML.

Here is a part of my log, when the bug begin : 

`[ 98%] Building C object CMakeFiles/EmptyEpsilon.dir/home/thomas/EE/SeriousProton/src/lua/lgc.c.o

[ 99%] Building C object CMakeFiles/EmptyEpsilon.dir/home/thomas/EE/SeriousProton/src/lua/lbitlib.c.o
[ 99%] Linking CXX executable EmptyEpsilon
/usr/local/lib/libsfml-audio.so : référence indéfinie vers « vorbis_analysis »
/usr/local/lib/libsfml-audio.so : référence indéfinie vers « vorbis_info_clear »
/usr/local/lib/libsfml-graphics.so : référence indéfinie vers « FT_MulFix »
/usr/local/lib/libsfml-graphics.so : référence indéfinie vers « FT_Init_FreeType »
/usr/local/lib/libsfml-audio.so : référence indéfinie vers « FLAC__stream_encoder_set_sample_rate »`

Here is a part of my compile code (thanks to @kwadroke) related to SFML:

`
if [ -e SFML-2.3 ]; then
 echo Already have SFML-2.3. Not updating since it could break things
else 
 sudo git clone https://github.com/SFML/SFML.git -b 2.3.x SFML-2.3
fi

cd $BUILDHOME/SFML-2.3
 if [ ! -d lin32 ]; then
  sudo mkdir lin32
 fi
 cd lin32
sudo cmake .. 
sudo make  
sudo make install 

 cd $BUILDHOME/EmptyEpsilon
sudo rm -r lin32

 if [ ! -d lin32 ]; then
 sudo mkdir lin32
 fi
 cd lin32
 sudo cmake -DSERIOUS_PROTON_DIR=$BUILDHOME/SeriousProton/ -DSFML_ROOT=$BUILDHOME/SFML-2.3 ..
 sudo make
 sudo make install
` 

I don't understand, it worked yesterday...
Do you have any advices ?

Thanks,
Tito

**Comment by oznogon** [comment]
I'm not having any problems building on an Ubuntu 16.04 VM, a fresh Ubuntu 16.04 VPN instance, or on OS X 10.10.5. SFML hasn't committed anything to the 2.3.x branch since August 2015.

The excerpt isn't enough for me to try to reproduce anything with it. Can you point me to the entire build script that you're using, or post it to a gist and link to it here?

**Comment by kwadroke** [comment]
have you installed any other version of SFML, say from a package manager?

**Comment by daid** [comment]
Rebuild SFML, your package manager most likely updated libraries that SFML depends on (these are errors that SFML cannot find functions in other libraries, namely libFreetype2, libVorbis and some Flac lib that I do not know)

**Comment by elptito** [comment]
Ok, I found the problem. I tried to install SFML via githut and via wget, and I think it caused conficts.
rebuild SFML was not enough, I deleted the folder /usr/local/lib and rebuild all the packages, and now it works.

Thanks for your answers.
