### ISSUE TITLE
BUG - Crash on Odin

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#335]
VIa @elptito on #332:

I have a crash when I use the Odin, when I try to display the beam range :

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abandon (core dumped)
```

**Comment by oznogon** [comment]
@elptito Which OS? Where were you displaying the beam range, on a radar? The GM screen?

**Comment by elptito** [comment]
Linux, with helm and with GM screen (when the zoom is high)

**Comment by elptito** [comment]
I have no problem with other ship, and the beam turret works (and it is awesome !)

**Comment by elptito** [comment]
I test with windows, and I have no issue. It's just with linux, and I remenber that I didn't have this issue before your add-on.

**Comment by oznogon** [comment]
@elptito Thanks! That's really useful. I'll do a clean Linux build later to see if I can reproduce it.

**Comment by oznogon** [comment]
I was able to reproduce on OS X, with this error message

```
[INFO]  Opened game state log: logs/game_log_23-06-2016_15.48.43.txt
libc++abi.dylib: terminating with uncaught exception of type std::length_error: vector
```

**Comment by oznogon** [comment]
Wow... that's a weird one.

[spaceship.cpp L336](https://github.com/daid/EmptyEpsilon/blob/2e03c83847a76a6354ffd7bfba20b9745171ff09/src/spaceObjects/spaceship.cpp#L336) appears to trigger it:

```
            sf::VertexArray turret_line(sf::LinesStrip, turret_points);
```

... and removing `#include <iostream>` from beamTemplate.cpp, which I only added for some makeshift debugging output, fixes it (at least on OS X). I'll put up a PR for it.

**Comment by oznogon** [comment]
Found it, filed #336. beamTemplate didn't initialize arc values to 0, and If I understand what happened (and I'm not certain that I do), Odin's many beams somehow caused it to spontaneously sprout turret arcs with invalid values, which in turn broke VertexArray when it tried to draw the arc.

Will build and test in Linux, but fixing that should hopefully prevent these crashes.

**Comment by oznogon** [comment]
I can't reproduce the issue on an Ubuntu 16.04 VM with this fix, but I also couldn't consistently reproduce it _without_ this fix. I'm also really curious about why this doesn't happen at all on Windows.

**Comment by daid** [comment]
Uninitialized memory is always very random, as it usually initializes on 0, but not always.

The tool "Valgrind" on linux really helps in tracking these down.

**Comment by oznogon** [comment]
@elptito can you confirm that this fixes things for you?

**Comment by elptito** [comment]
Yes, it works ! Thanks you
