### ISSUE TITLE
Unable to complete Birth of the Atlantis scenario

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#338]
I get as far as _shipyardGammaComms()_ (Dock with JC-88 for the 1st time) and the ship doesn't Jump. 

I don't see anything looking for _mission_state == phase2WaitForJump_

**Comment by kwadroke** [comment]
Should be fixed with d0b9b73.
Leaving open until tested, unless Daid wants to close.

**Comment by daid** [comment]
I tested it, works now :-)
