### ISSUE TITLE
Little bug in science screen

### ISSUE THREAD

**Issue by elptito** [daid/EmptyEpsilon#340]
When I first select a waypoint, and then click on a other object, I select both the object and the waypoint : 
![image](https://cloud.githubusercontent.com/assets/13868149/16330889/d66dd366-39ec-11e6-91ba-e24186d736ff.png)

If I select first the object and then the waypoint, I don't have this issue.

It appends with Windows and Linux.

**Comment by Fouindor** [comment]
Tested also happens with latest source on windows, it's just graphic and does not seem to impact gameplay. I'll try to look into that.
