### ISSUE TITLE
ISSUE - Top down view not following player

### ISSUE THREAD

**Issue by CaptLapadite** [daid/EmptyEpsilon#341]
ISSUE
- When you open TopDown, it correctly place the ship in the middle.
- But TopDown view does not follow ship as supposed. 

REQUEST 
- Add a zoom button (or scroll zoom) on topdown screen as in Relay view.

**Comment by oznogon** [comment]
PR #278 resolves this by automatically centering the top down view on the first player ship when it's started.

As of at least the 6-23 build, pressing H on the Top Down view exposes a player ship selector and camera lock toggle that lets you choose which player ship to center the view on.

**Comment by oznogon** [comment]
See the comments on PR #267 for an explanation of why there is no visible UI on the top-down view.

**Comment by CaptLapadite** [comment]
thanks ! 

SUGGESTION 
- add a message popup when opening the top-down view indicating the different shortcuts possible.

**Comment by oznogon** [comment]
Yeah, I've been looking into how to add an in-game help overlay. @daid has also talked about revising how the keyboard controls work in general.

**Comment by CaptLapadite** [comment]
Why not just something like in the tutorial : 

function init()
    Top down view:showMessage([[ 
Press H : Select playership view.
Press R : Zoom in
Press F : Zoom out
Press I : toggle info screen
text ]]
end

**Comment by oznogon** [comment]
^ broke that out into a separate ticket.
