### ISSUE TITLE
BUG - multiplayerIds persist after the end of a scenario

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#343]
I don't know if there's a potential functional issue with this, but for what it's worth:

1.  Launch a server.
2.  Launch a scenario.
3.  Exit the scenario by returning to the scenario selection screen on the server.
4.  Launch a new scenario.

## Expected behavior

MultiplayerIds are reset. For instance, callsigns are derived from multiplayerIds (PL + getMultiplayerId), so auto-assigned callsigns for ships in a scenario start from 0. A player ship created near the start of a scenario would have callsign PL3.

## Observed behavior

MultiplayerIds are not reset. For instance, auto-assigned ship callsigns start from the largest multiplayerId of the previous scenario. A player ship created near the start of a scenario might have callsign PL673, and after repeating the steps would have callsign PL1343, and again would have PL2010, and so on.

**Comment by daid** [comment]
This is by design, the multiplayer code cannot account for reuse of IDs on a single service instance. If you want this number to restart, restart the server.
