### ISSUE TITLE
Energy spent by Shields not display

### ISSUE THREAD

**Issue by elptito** [daid/EmptyEpsilon#344]
In the engeneer station, if the shields are on, the energy decreases but the energy variation is not known : 

![image](https://cloud.githubusercontent.com/assets/13868149/16359268/df6ae9b2-3b2d-11e6-9a2a-82d5b9c31561.png)

I could be great to have this information to adapt the power of the reactor.

**Comment by oznogon** [comment]
For reference, active shields use 1.5 energy/second per [playerSpaceship.h line 34, constant `energy_shield_use_per_second`](https://github.com/daid/EmptyEpsilon/blob/master/src/spaceObjects/playerSpaceship.h#L34).

**Comment by oznogon** [comment]
So this is a little more involved than expected... active shields draw power separately from the function that calculates power draw (and also provides the number to Engineering). In other words, the energy draw of active shields isn't factored into a ship's total energy draw in the same manner as other systems.

Further complicating things is the fact that shield energy draw is calculated differently from system energy draw, namely that system draw is reduced to 1/12.5 before being subtracted, but shield energy draw isn't.

#347 works around this by adding shield energy draw directly to the Engineering screen value updates, but now I'm not sure what the expected or desired behavior of active shield energy draw should be. It definitely isn't 1.5/second, despite the constant's name, but also the value on the Engineering screen doesn't represent power draw per second, either. A value of 1.0 doesn't result in gaining 1 energy per second.

**Comment by oznogon** [comment]
Opened #350 to fix this closer to the root of the issue.
