### ISSUE TITLE
Impulse works when energy = 0

### ISSUE THREAD

**Issue by elptito** [daid/EmptyEpsilon#351]
Even when there is no energy, Impulse works and can be boosted. Maneuver and Missiles too. Jump, shields and beam are off.

I think that maneuver can remain on, but Impulse and missile should be off.

![image](https://cloud.githubusercontent.com/assets/13868149/16405301/d0f4d9da-3d06-11e6-81f5-105dc986ff3f.png)

**Comment by daid** [comment]
While they remained working, the did only work at a maximum of 10% efficiency.
Patch from oznogon fixes this, as well as fixing a problem of the reactor being less efficient when there is a low power situation, making it all worse. (We're not simulating the complexity of a reactor needing power to keep the reaction stable :) Play "Rogue System" if you want this)

**Comment by elptito** [comment]
It is a good way ! Yes, i am agree with you, disable all systems is a
little too hard to play :)
