### ISSUE TITLE
BUG - Keyboard input doesn't work

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#373]
As of d43f1af6e9c2627d50d76b1cb74b9a0bb8df0bfa, no keyboard input is recognized. There's no way to exit a screen or menu, and text input fields don't work.

**Comment by daid** [comment]
Be sure to update seriousproton as well, as everything seems to work here...

**Comment by oznogon** [comment]
I am on the HEAD of both SP and EE.

The following work:
-   H, J, K, L on top-down and cinematic views
-   DEL on the GM screen to delete an object

The following do not work:
-   All text input fields, including GM screen tweak menus and control code entry
-   P to toggle pause on any server screen

The following work only intermittently:
-   ESC to exit from some stations, including GM screen, Helm/Weapons/Eng/Sci/Relay

**Comment by oznogon** [comment]
Confirmed that 5eb1413 fixes text inputs. I'm assuming P is going to be implemented separately.

I'll try to get the ESC failures to crop up again and find a way to reproduce them. I did notice that when ESC stops working, Home still works.

**Comment by oznogon** [comment]
Filed #378 to fix the hotkeys for switching to the helms and weapons station.
