### ISSUE TITLE
Main Screen Controls crashes clients

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#381]
This weekend at a convention we ran into problems with adding the main screen controls on clients. 
When the clients could try to change the main screen by clicking on the button, it would crash the game on that machine.
This was using the 2016.06.24 release on several Windows 8 & 10 PCs, as well as source code compiled for Linux using the EE-2016.06.24 tags for EE & SP.
Usually a restart would let you use the main screen controls again, but not always. We've seen the issue repeat more often on Engineering and Science. 

I don't have the RPT files readily available. I can get those uploaded next week.

**Comment by kwadroke** [comment]
I'll try to get those tomorrow.

**Comment by daid** [comment]
Note, there is a crash related bug that I haven't been able to track down yet, but it seems to very rarely corrupt some of the GUI code, causing a crash. Usually on button presses or key presses.

**Comment by codesmithKarl** [comment]
I've run into this same bug in Linux clients. Specifically using the Science station and the Main Window Controls. Hitting the Main Window button at the science station (after connecting to the server) crashes the client.

**Comment by oznogon** [comment]
Still haven't been able to reproduce this in Windows or macOS builds.

**Comment by kwadroke** [comment]
Being that this issue is 4 years old, and probably not the case anymore; I'm going to close it.

**Comment by aBlueShadow** [comment]
Actually, I just was able to reproduce it on linux, recent master. Clicking on the Main Screen Control button on the station caused a segfault.

**Comment by oznogon** [comment]
Any logs or details? Linux distro and version? On the server or on a client?

**Comment by gwaland** [comment]
This is the bug I keep trying to get logs for in my PXE 2 bridge setup.  It's been really hard getting useful log output for it.

**Comment by oznogon** [comment]
I can try to stand up an environment to reproduce if I know the distro and distro version. Otherwise I'll try it on Ubuntu 18.04 as that's the box I have handy. I'm also assuming it's the client and not the server that's segfaulting.

**Comment by aBlueShadow** [comment]
No additional log, so, rather typical for a segfault. Here the issue occurred on MX Linux 19. It is both on client and server.

**Comment by oznogon** [comment]
Current release of MX Linux 19 is Debian 10 Buster under the hood, which doesn't have SFML 2.4 in its repos, if you have specific install steps it might help. I'll see if I can reproduce on Ubuntu 18.04.

Does this happen at any time? Is it consistently reproducible by some specific steps you can provide?

Here's what I've tried across Windows, macOS, and Android without being able to reproduce:

1. Open EE
2. Start a server
3. Select the Basic scenario and start it
4. Select the player ship Atlantis
5. Join Helms, Weapons, Science, Relay, and add Main Screen Controls
6. Open Science
7. Select Main Screen Controls

I've also tried

1. Open EE
2. Start a server
3. Select the Basic scenario and start it
4. Open another EE
5. Start a client
6. Join the server
7. Select the player ship Atlantis
8. Join Helms, Weapons, Science, Relay, and add Main Screen Controls
9. Open Science
10. Select Main Screen Controls

I've also tried doing the above steps with a server running Ubuntu 18.04 on a VPS and clients running Windows, macOS, and Android, and both with and without a Main Screen running on the server or another client.

**Comment by aBlueShadow** [comment]
I just use the the normal build instructions in the wiki. You are right, buster don't have sfml 2.4, but 2.5, which also works fine. But I double checked it with MX Linux 17/debian stretch and sfml 2.4, which has caused the same issue. 
It is not 100% reproducable, but most of the time.

1. Open EE
2. Start a server
3. Select the Basic scenario and start it
4. Select the player ship Atlantis
5. Join Helms and add Main Screen Controls
6. Click on "Ready"
7. Unpause
8.  Select Main Screen Controls -> segmentation fault

**Comment by oznogon** [comment]
I think I've got it reproducing in Ubuntu 18.04. It's not fully consistent but it's happening. Got a core dump, recompiling now with debugging symbols

1. Launch EE as a headless server (`EmptyEpsilon headless=scenario_00_basic.lua`)
2. Launch another EE as a client with autoconnect & main screen controls (`EmptyEpsilon autoconnect=4 autocontrolmainscreen=1`)
3. Click Main Screen in the client

Core dump attached from a debug build off the 2020.03.22 tag

[core.0.2127.1586121041.gz](https://github.com/daid/EmptyEpsilon/files/4434912/core.0.2127.1586121041.gz)

**Comment by oznogon** [comment]
Rebuilt from master with @daid 's commit 8e25b30 and still reproduced it

**Comment by daid** [comment]
In that case, I hope the backtrace provides better information. As there where uninitialized pointers in there, which is always fun.
Core dump are only useful with the exact debug executable that was used to run it.

**Comment by aBlueShadow** [comment]
@oznogon that's interesting, because I can't seem to reproduce it anymore with 8e25b30f070b5fff7dc349f255a4ceb72343e8d8

**Comment by daid** [comment]
Maybe there are 2 different bugs ;-)

**Comment by oznogon** [comment]
I'll take others' reports of this fix working over my failures, I'm testing in a VM where input behaviour in general isn't stable

--
Garrett Guillotte
garrett@oznogon.com
