### ISSUE TITLE
REQUEST: Adding energy to a player ship from GM Screen

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#383]
During last week's convention we tried to add some energy to a player ship via the GM screen and noticed that there wasn't a way to directly do this. We had to over drive the reactor and reduce the heat. 

I suggest adding a way to control energy to a player ship via a slider.

**Comment by daid** [comment]
I think you mean energy levels?

**Comment by kwadroke** [comment]
Yes, that is what I meant.

**Comment by oznogon** [comment]
Implemented in 0f1e8e7372995b23419efba1a7bfb7ea691f1650.

![screen shot 2016-08-09 at 12 09 23 pm](https://cloud.githubusercontent.com/assets/19192104/17529901/0a785cec-5e2a-11e6-86f3-7a8865654d4c.png)

**Comment by kwadroke** [comment]
Nice. That should work

**Comment by kwadroke** [comment]
Is there a way to do this via the set.lua & get.lua web/json calls? I'm not seeing anything in the source code or the generated script_reference.html file. (Of course I could be just blind and not seeing it)

Something Like this:
* getEnergy()
* getEnergyMax()
* setEnergy()
* setEnergyMax()

I can open a new Issue if needed.

**Comment by daid** [comment]
There does not need to be an API for this yet. Should be easy to add.

**Comment by kwadroke** [comment]
Nice. Working through the API now. I can start work on my Engineering web dashboard.

**Comment by Wrongtown** [comment]
I've made no time lately to do anything but dream, but I have a crazy idea
of building a physical engineering board with sliders (motorized ones in
the case of coolant) along a similar vein to a sound or lighting board.
