### ISSUE TITLE
Can't get OSX or Linux build to connect to Windows server (causes crash)

### ISSUE THREAD

**Issue by emacsen** [daid/EmptyEpsilon#386]
Two weeks ago we had an EE game with one Linux user (me) and one OSX user. Neither could get their client to connect to the Windows server. Neither of us had a firewall issue. Connecting to the server caused the server to crash.

We tried using both the current head and the last tagged release on git- same issue.

**Comment by kwadroke** [comment]
Were all 3 running the same version? (as displayed on the Main screen - under the Empty Epsilon logo) If these don't match, there can be connection problems. It's usually the build date, unless set to 0.
It's best not to mix releases with versions from git unless you "back date" the builds from tagged releases.

**Comment by emacsen** [comment]
Yes, we made sure all of them were on the same release. The server was running the precompiled binary.

**Comment by kwadroke** [comment]
ok. For the Windows build you should hopefully have an _EmptyEpsilon.RPT_ file. Daid will need that to look into the issue.

**Comment by emacsen** [comment]
Sadly we don't have the original, but I should be able to reproduce it on my systems and come back.  I don't have an OSX box so we'll have to see if it's the same issue.

**Comment by oznogon** [comment]
Can't reproduce with the server running on Windows, OS X, Linux, or Android and clients on Windows, OS X, Linux, or Android, when all are running either current HEAD (cc7efc0) or 2016.06.24. Could use some more information, and especially a RPT from the server.

**Comment by daid** [comment]
Note, this is how I usually run EE, Windows server with Linux clients, running the latest master.

I'm not saying it cannot crash, but it can work.

**Comment by emacsen** [comment]
Sorry for the long delay here.  I ran this at a friends's house and it crashed. At home I can't reproduce. My apologies.

More bugs forthcoming though :)
