### ISSUE TITLE
Forum to discuss EE

### ISSUE THREAD

**Issue by emacsen** [daid/EmptyEpsilon#387]
The forum that's linked on the EE page is broken (their ReCapcha is broken). A mailing list, or IRC channel, or slack, or something, would be awesome.

**Comment by kwadroke** [comment]
Are you talking about over at BridgeSim.net? I'm the Admin over there. What problems are you having?

**Comment by oznogon** [comment]
At http://bridgesim.net/entry/register?Target=discussions, the security check is broken:

> Security Check
> To use reCAPTCHA you must get an API key from https://www.google.com/recaptcha/admin

**Comment by kwadroke** [comment]
Thanks. I'll get that fixed.
How are you trying to register (Facebook, Twitter, Google, etc) ?

**Comment by oznogon** [comment]
It's the "register" button on the home page.

![screen shot 2016-08-16 at 10 09 03 am](https://cloud.githubusercontent.com/assets/19192104/17708378/8cc36ee8-6399-11e6-91f9-8104d2a45a8b.png)

**Comment by kwadroke** [comment]
I fixed the security check, but,  realized that I didn't set it to only allow SSO via Social Media; which was the way it was set before the server move.

**Comment by kwadroke** [comment]
It will require a Service such as Facebook, Google, OpenID or Twitter to login.

**Comment by kwadroke** [comment]
It should work now with regular registration. If too many spammers try to sign up, I may have to disable it again.

**Comment by kwadroke** [comment]
It will require approval from me before I grant access, but since @emacsen doesn't appear to be a bot, it should be fine :)

**Comment by kwadroke** [comment]
Ah, will need to fix the SMTP authenication error. Working on that now

**Comment by kwadroke** [comment]
Fixed.

**Comment by daid** [comment]
To prevent me from checking a lot of different locations, I'm only using the issue tracker and the bridgesim.net forums. Yes, the forums have occasional problems, but Kwadroke is quick to step in and fix them. Overal this has been working great for us the past year.
