### ISSUE TITLE
Turning models

### ISSUE THREAD

**Issue by Jhovall** [daid/EmptyEpsilon#39]
Hey Guys, I am importing my own models and it seems like I can't turn my own models around. I can set them on the X,y,z, axis and adjust the scale. But I cannot turn the models around. I have to use an suboptimal external program to turn the ships in the right position. Can you implement this (or am I missing something)?

**Comment by daid** [comment]
The models are assumed to be in the proper location and coordinate system. I generally move/rotate them in blender.

**Comment by Jhovall** [comment]
Yeah, some models somehow crashes empty epsilon, after I rotated them in blender. Before it is not a problem, and it performs as desired.

**Comment by daid** [comment]
Make sure you export the models with UV coordinates, for some reason blender has that disabled by default in the export (and EE doesn't like that, as my code is sloppy in the model loading)

**Comment by Jhovall** [comment]
Did I tell you... you are my hero?... I have been at this problem for 3 hours now. Thanks!
