### ISSUE TITLE
Compilaton problem

### ISSUE THREAD

**Issue by elptito** [daid/EmptyEpsilon#394]
Hi,

I try to use netboot installation. It worked perfectly yesterday (thanks a lot Daid, this tool is perfect !), but I don't understand why today I have a issue during the compilation.

Do you some tips to help me ?

Here is the compilation command : 

`chroot ${TARGET_NFS_DIR} sh -c 'cd /root/EmptyEpsilon/_build && cmake .. -DSERIOUS_PROTON_DIR=$HOME/SeriousProton/ && make -j 3'
`

Here is the log : 

`[ 12%] Building CXX object CMakeFiles/EmptyEpsilon.dir/src/screens/cinematicViewScreen.cpp.o
/root/EmptyEpsilon/src/menus/shipSelectionScreen.cpp: In member function 'void ShipSelectionScreen::updateCrewTypeOptions()':
/root/EmptyEpsilon/src/menus/shipSelectionScreen.cpp:440:51: error: no matching function for call to 'GuiToggleButton::setVisible(P<GameServer>&)'
         game_master_button->setVisible(game_server);
                                                   ^
/root/EmptyEpsilon/src/menus/shipSelectionScreen.cpp:440:51: note: candidate is:
In file included from /root/EmptyEpsilon/src/screenComponents/viewport3d.h:4:0,
                 from /root/EmptyEpsilon/src/screens/topDownScreen.h:6,
                 from /root/EmptyEpsilon/src/menus/shipSelectionScreen.cpp:8:
/root/EmptyEpsilon/src/gui/gui2_element.h:68:17: note: GuiElement* GuiElement::setVisible(bool)
     GuiElement* setVisible(bool visible);
                 ^
/root/EmptyEpsilon/src/gui/gui2_element.h:68:17: note:   no known conversion for argument 1 from 'P<GameServer>' to 'bool'
CMakeFiles/EmptyEpsilon.dir/build.make:767: recipe for target 'CMakeFiles/EmptyEpsilon.dir/src/menus/shipSelectionScreen.cpp.o' failed
make[2]: *** [CMakeFiles/EmptyEpsilon.dir/src/menus/shipSelectionScreen.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/EmptyEpsilon.dir/all' failed
make[1]: *** [CMakeFiles/EmptyEpsilon.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by elptito** [comment]
It's easer to read with this picture : 

![capture du 2016-09-04 16 38 12](https://cloud.githubusercontent.com/assets/13868149/18231626/b2bf12a8-72be-11e6-9c16-f6cf5ce811fa.png)

**Comment by daid** [comment]
Forgot to push the related change in EE.

Note that this change is extremely important as it does prevent a certain type of bug which is very hard to trace.
