### ISSUE TITLE
Mouse pointer is hard to see on static filled screen

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#395]
The black and white pointer is very hard to see when the ship has been destroyed screen that is filled with black and white static.

Recommend adding another color to help users see the pointer.

**Comment by InterestingJohn** [comment]
Would it be possible to change the state of the cursor when the screen is filled with static?

**Comment by CaptLapadite** [comment]
Another simple way would be to change the "noise" screen. 

I've created 3 that work pretty well with the game and that have a good contrast with the mouse. 
I would recommend changing the original file. 

![noisea](https://cloud.githubusercontent.com/assets/18233357/18692256/e9f0fa70-7f66-11e6-8bc3-293b9d7a5b35.png)
![noiseb](https://cloud.githubusercontent.com/assets/18233357/18692255/e9f06c90-7f66-11e6-8406-96697854fab4.png)
![noisec](https://cloud.githubusercontent.com/assets/18233357/18692257/e9f512cc-7f66-11e6-873d-16cc5a17cb04.png)

**Comment by CaptLapadite** [comment]
for exemple : 
![screen shot 2016-09-20 at 6 54 37 pm](https://cloud.githubusercontent.com/assets/18233357/18692366/980fc83e-7f67-11e6-837f-533ee2eed5a1.png)

**Comment by aBlueShadow** [comment]
One other way would be to use a screen-darkening overlay for the destroyed message. That would also be consistent, as most other game-interrupting messages (defeat, victory, pause) also darken the screen. With the same overlay as for the other messages, It will be dark enough to make the cursor clearly visible.

I am a bit hesitant to do a PR though, as I'm not sure if @daid had done this exception on purpose .

**Comment by daid** [comment]
Nah, main reason it's like this is because we play on touch screens without a mouse cursor :-)
