### ISSUE TITLE
Dynamic Science Database

### ISSUE THREAD

**Issue by elptito** [daid/EmptyEpsilon#398]
Hi,

I want to do a dynamic database without a whole change of the code. I think about adding a isVisible() function for FactionInfo() and for ShipTemplate() and use it in the file "databaseView.cpp", just to check if this function return true of false before show it in the database. But I am not sure where to place it.
Do someones have some advices to do that ?

**Comment by daid** [comment]
> I want to do a dynamic database without a whole change of the code.

Then you are out of luck. Problem is that this data is not send trough clients and thus changing it dynamically on the server does not change it on the clients.

**Comment by elptito** [comment]
Ok, I will make some categories "do not touch !". For now I will be ok :)
