### ISSUE TITLE
Fighter docking to main ship 

### ISSUE THREAD

**Issue by ErikDeBruijn** [daid/EmptyEpsilon#4]
It would be cool if a solo pilot could dock his/her fighter at a larger ship.

The engineer could then do repairs, refuel and resupply weapons or transfer arbitrary cargo.

The ship should have launch bays present for docking/releasing or the fighter would be boarding the larger vessel. 

When boarding an enemy ship, the boarding party would be able to rig the ship with explosives (which engineers could find) or create a warp core meltdown) by sabotaging the cooling system.

**Comment by ErikDeBruijn** [comment]
Or when docking a hostile relay could order marines security detail to board with force.

And engineer should be able to sabotage the enemy vesell so it has no power or that it releases a weapons subsystem (which becomes a supply drop near the system)

**Comment by amir-arad** [comment]
#593
