### ISSUE TITLE
Please add .desktop file and icons so that desktop users can see EmptyEpsilon in the menu

### ISSUE THREAD

**Issue by yurivict** [daid/EmptyEpsilon#405]

**Comment by jcc10** [comment]
You could always add those files manually.

I will have some examples in a day or two.

**Comment by FaramosCZ** [comment]
Here is the .desktop file being created for RPMs for Fedora
https://pkgs.rpmfusion.org/cgit/nonfree/EmptyEpsilon.git/tree/EmptyEpsilon.spec#n54

**Comment by yurivict** [comment]
Desktop files should be installed by the project itself because they are needed on all systems, and should look uniformly on all systems.

Additionally, project name translations are in .desktop file. This can only be done by the project itself.
