### ISSUE TITLE
REQUEST Configurable Keyboard/joystick inputs

### ISSUE THREAD

**Issue by jngreene** [daid/EmptyEpsilon#413]
It would be nice to have a setup screen (and config file) to allow mapping of inputs to actions. 
Recognizing that there are digital and analog actions (Throttle and movement type functions being analog).  It could allow analog functions to be assigned to keys, joystick buttons and/or Joystick Axis functions (multiple input mapping allowing up to 2 keys or 1 key and 1 axis would be optimal)   while only allowing keys and joystick buttons to be assigned to actions not identified as analog.
example: Impulse throttle assigned to a joystick axis and the W/S keys for increase/decrease. Fire tube 1 could be  joystick button 1 and keyboard key 1 (SFML is rather broken for accessing numpad keys last I checked)

**Comment by Wrongtown** [comment]
This would bring me great joy also. Pun not intended.

**Comment by paddatrapper** [comment]
This would also make building custom consoles much easier
