### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by thorgod** [daid/EmptyEpsilon#416]
Sorry I did not take notes when the crashes happened during our gaming session. But I have attached the RPT file. Two of the crashes was maybe when two people were switching the main screen. I will also take a deeper look into it, just want you to be aware.

[EmptyEpsilon.txt](https://github.com/daid/EmptyEpsilon/files/639730/EmptyEpsilon.txt)

**Comment by thorgod** [comment]
-------------------

Error occured on Sunday, December 4, 2016 at 12:16:05.

EmptyEpsilon.exe caused an Access Violation at location 0057B485 in module EmptyEpsilon.exe Reading from location 00000030.

Loading symbols... done.

Registers:
eax=0e558210 ebx=0076478c ecx=0e59dc48 edx=00000000 esi=0028f334 edi=0e63a198
eip=0057b485 esp=0028f22c ebp=0028f298 iopl=0         nv up ei pl zr na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210246

AddrPC   Params
0057B485 0028F33C 0075D6A0 0075E3C0  EmptyEpsilon.exe!isFriendly  [/home/daid/ee/EmptyEpsilon/src/spaceObjects/spaceObject.cpp @ 279]
004AC697 07EB0FC8 43924000 44C80000  EmptyEpsilon.exe!onDraw  [/home/daid/ee/EmptyEpsilon/src/screens/crew6/relayScreen.cpp @ 256]
00567DB4 00000000 00000000 44C80000  EmptyEpsilon.exe!drawElements  [/home/daid/ee/EmptyEpsilon/src/gui/gui2_container.cpp @ 50]
00553B0D 07EB0FC8 00001668 0028F4D8  EmptyEpsilon.exe!render  [/home/daid/ee/EmptyEpsilon/src/gui/gui2_canvas.cpp @ 26]
00604F2C 07EB0FC8 00001668 0028F558  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/Renderable.cpp @ 21]
00604E00 07EB0FC8 00001668 0028F5D8  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/Renderable.cpp @ 18]
00604E00 07EB0FC8 00001668 0028F658  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/Renderable.cpp @ 18]
00604E00 07EB0FC8 00000002 0CAEDB00  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/Renderable.cpp @ 18]
005EDE7D 07EB0FC8 0028F8FC 0028F8FC  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/postProcessManager.cpp @ 42]
005EDE7D 07EB0FC8 00000014 00000014  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/postProcessManager.cpp @ 42]
0064FF78 3C75A965 00000000 FFFFFFFF  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/windowManager.cpp @ 31]
0064EDC0 02140001 07F42594 0000000D  EmptyEpsilon.exe!runMainLoop  [/home/daid/ee/SeriousProton/src/engine.cpp @ 148]
0070BA46 07FD95E0 0000005B 00000001  EmptyEpsilon.exe!main  [/home/daid/ee/EmptyEpsilon/src/main.cpp @ 281]
004013E0 7EFDE000 0028FFD4 772D9902  EmptyEpsilon.exe!__tmainCRTStartup  [/build/buildd/mingw-w64-3.1.0/build/i686-w64-mingw32-i686-w64-mingw32-crt/../../mingw-w64-crt/crt/crtexe.c @ 332]
750F336A 7EFDE000 774C3977 00000000  kernel32.dll!@BaseThreadInitThunk@12
772D9902 004014E0 7EFDE000 00000000  ntdll.dll!___RtlUserThreadStart@8
772D98D5 004014E0 7EFDE000 00000000  ntdll.dll!__RtlUserThreadStart@8

EmptyEpsilon.exe
ntdll.dll   	6.1.7601.23569
kernel32.dll	6.1.7601.23569
KERNELBASE.dll	6.1.7601.23569
exchndl.dll 	0.7.7.0
mgwhelp.dll 	0.7.7.0
dbghelp.dll 	6.3.9600.17029
msvcrt.dll  	7.0.7601.17744
ADVAPI32.dll	6.1.7601.23569
sechost.dll 	6.1.7601.18869
RPCRT4.dll  	6.1.7601.23571
SspiCli.dll 	6.1.7601.23571
CRYPTBASE.dll	6.1.7601.23571
PSAPI.DLL   	6.1.7600.16385
SHELL32.DLL 	6.1.7601.23537
SHLWAPI.dll 	6.1.7601.17514
GDI32.dll   	6.1.7601.23457
USER32.dll  	6.1.7601.23528
LPK.dll     	6.1.7601.23587
USP10.dll   	1.626.7601.19054
VERSION.dll 	6.1.7600.16385
sfml-audio-2.dll
sfml-system-2.dll
WINMM.DLL   	6.1.7601.17514
libgcc_s_sjlj-1.dll
libwinpthread-1.dll	1.0.0.0
libstdc++-6.dll
openal32.dll
ole32.dll   	6.1.7601.23392
sfml-graphics-2.dll
sfml-window-2.dll
OPENGL32.DLL	6.1.7600.16385
GLU32.dll   	6.1.7600.16385
DDRAW.dll   	6.1.7600.16385
DCIMAN32.dll	6.1.7601.23587
SETUPAPI.dll	6.1.7601.17514
CFGMGR32.dll	6.1.7601.17621
OLEAUT32.dll	6.1.7601.23569
DEVOBJ.dll  	6.1.7601.17621
dwmapi.dll  	6.1.7601.18917
sfml-network-2.dll
WS2_32.dll  	6.1.7601.23451
NSI.dll     	6.1.7600.16385
IPHLPAPI.DLL	6.1.7601.17514
WINNSI.DLL  	6.1.7600.16385
WSOCK32.DLL 	6.1.7600.16385
IMM32.DLL   	6.1.7601.17514
MSCTF.dll   	6.1.7601.23572
DINPUT.DLL  	6.1.7600.16385
HID.DLL     	6.1.7600.16385
WINTRUST.dll	6.1.7601.23471
CRYPT32.dll 	6.1.7601.23471
MSASN1.dll  	6.1.7601.17514
uxtheme.dll 	6.1.7600.16385
CLBCatQ.DLL 	2001.12.8530.16385
PROPSYS.dll 	7.0.7601.17514
dsound.dll  	6.1.7600.16385
POWRPROF.dll	6.1.7600.16385
MMDevApi.dll	6.1.7601.17514
AUDIOSES.DLL	6.1.7601.23471
atiglpxx.dll	8.14.1.6521
atioglxx.dll	6.14.10.13447
atiadlxy.dll	7.16.30.1304
USERENV.dll 	6.1.7601.17514
profapi.dll 	6.1.7600.16385
WTSAPI32.dll	6.1.7601.17514
atigktxx.dll	8.14.1.6521
mswsock.dll 	6.1.7601.23451
wshtcpip.dll	6.1.7600.16385
dhcpcsvc6.DLL	6.1.7601.17970
dhcpcsvc.DLL	6.1.7600.16385
WININET.dll 	11.0.9600.18523
api-ms-win-downlevel-user32-l1-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-shlwapi-l1-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-version-l1-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-normaliz-l1-1-0.dll	6.2.9200.16492
normaliz.DLL	6.1.7600.16385
iertutil.dll	11.0.9600.18523
api-ms-win-downlevel-advapi32-l1-1-0.dll	6.2.9200.16492
Secur32.dll 	6.1.7601.23571
api-ms-win-downlevel-advapi32-l2-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-ole32-l1-1-0.dll	6.2.9200.16492
wship6.dll  	6.1.7600.16385
api-ms-win-downlevel-shlwapi-l2-1-0.dll	6.2.9200.16492
DNSAPI.dll  	6.1.7601.17570
urlmon.dll  	11.0.9600.18523
netprofm.dll	6.1.7600.16385
nlaapi.dll  	6.1.7601.18685
WLIDNSP.DLL 	7.250.4311.0
mdnsNSP.dll 	3.1.0.1
rasadhlp.dll	6.1.7600.16385
CRYPTSP.dll 	6.1.7601.23471
rsaenh.dll  	6.1.7600.16385
RpcRtRemote.dll	6.1.7601.17514
npmproxy.dll	6.1.7600.16385
fwpuclnt.dll	6.1.7601.18283
Comctl32.dll	6.10.7601.18837
Cabinet.dll 	6.1.7601.17514

Windows 6.1.7601
DrMingw 0.7.7

-------------------

Error occured on Sunday, December 4, 2016 at 12:53:26.

EmptyEpsilon.exe caused an Access Violation at location 00560156 in module EmptyEpsilon.exe Writing to location 00000057.

Loading symbols... done.

Registers:
eax=0000000f ebx=118cc564 ecx=0000000f edx=00000000 esi=00000001 edi=118cc564
eip=00560156 esp=0028f38c ebp=0028f3b8 iopl=0         nv up ei pl zr na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210246

AddrPC   Params
00560156 0E6493C0 00000001 0028F43B  EmptyEpsilon.exe! ??   [/home/daid/ee/EmptyEpsilon/src/gui/gui2_element.cpp @ 118]
005522F4 0E6493A0 3F800000 42C80000  EmptyEpsilon.exe!onClick  [/usr/include/c++/4.8/functional @ 2464]
00559788 44B2C000 42D3AAAB 44C80000  EmptyEpsilon.exe!onMouseUp  [/usr/include/c++/4.8/functional @ 2464]
00553CA4 08050FC8 00001514 0028F4D8  EmptyEpsilon.exe!render  [/home/daid/ee/EmptyEpsilon/src/gui/gui2_canvas.cpp @ 54]
00604F2C 08050FC8 00001514 0028F558  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/Renderable.cpp @ 21]
00604E00 08050FC8 00001514 0028F5D8  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/Renderable.cpp @ 18]
00604E00 08050FC8 00001514 0028F658  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/Renderable.cpp @ 18]
00604E00 08050FC8 00000002 0CE03138  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/Renderable.cpp @ 18]
005EDE7D 08050FC8 0028F8FC 0028F8FC  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/postProcessManager.cpp @ 42]
005EDE7D 08050FC8 00000014 00000014  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/postProcessManager.cpp @ 42]
0064FF78 3C76C69B 00000100 FFFFFFFF  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/windowManager.cpp @ 31]
0064EDC0 02140001 080E2594 0000000D  EmptyEpsilon.exe!runMainLoop  [/home/daid/ee/SeriousProton/src/engine.cpp @ 148]
0070BA46 07FF95C0 0000005B 00000001  EmptyEpsilon.exe!main  [/home/daid/ee/EmptyEpsilon/src/main.cpp @ 281]
004013E0 7EFDE000 0028FFD4 772D9902  EmptyEpsilon.exe!__tmainCRTStartup  [/build/buildd/mingw-w64-3.1.0/build/i686-w64-mingw32-i686-w64-mingw32-crt/../../mingw-w64-crt/crt/crtexe.c @ 332]
750F336A 7EFDE000 776A0B81 00000000  kernel32.dll!@BaseThreadInitThunk@12
772D9902 004014E0 7EFDE000 00000000  ntdll.dll!___RtlUserThreadStart@8
772D98D5 004014E0 7EFDE000 00000000  ntdll.dll!__RtlUserThreadStart@8

EmptyEpsilon.exe
ntdll.dll   	6.1.7601.23569
kernel32.dll	6.1.7601.23569
KERNELBASE.dll	6.1.7601.23569
exchndl.dll 	0.7.7.0
mgwhelp.dll 	0.7.7.0
dbghelp.dll 	6.3.9600.17029
msvcrt.dll  	7.0.7601.17744
ADVAPI32.dll	6.1.7601.23569
sechost.dll 	6.1.7601.18869
RPCRT4.dll  	6.1.7601.23571
SspiCli.dll 	6.1.7601.23571
CRYPTBASE.dll	6.1.7601.23571
PSAPI.DLL   	6.1.7600.16385
SHELL32.DLL 	6.1.7601.23537
SHLWAPI.dll 	6.1.7601.17514
GDI32.dll   	6.1.7601.23457
USER32.dll  	6.1.7601.23528
LPK.dll     	6.1.7601.23587
USP10.dll   	1.626.7601.19054
VERSION.dll 	6.1.7600.16385
sfml-audio-2.dll
sfml-system-2.dll
WINMM.DLL   	6.1.7601.17514
libgcc_s_sjlj-1.dll
libwinpthread-1.dll	1.0.0.0
libstdc++-6.dll
openal32.dll
ole32.dll   	6.1.7601.23392
sfml-graphics-2.dll
sfml-window-2.dll
OPENGL32.DLL	6.1.7600.16385
GLU32.dll   	6.1.7600.16385
DDRAW.dll   	6.1.7600.16385
DCIMAN32.dll	6.1.7601.23587
SETUPAPI.dll	6.1.7601.17514
CFGMGR32.dll	6.1.7601.17621
OLEAUT32.dll	6.1.7601.23569
DEVOBJ.dll  	6.1.7601.17621
dwmapi.dll  	6.1.7601.18917
sfml-network-2.dll
WS2_32.dll  	6.1.7601.23451
NSI.dll     	6.1.7600.16385
IPHLPAPI.DLL	6.1.7601.17514
WINNSI.DLL  	6.1.7600.16385
WSOCK32.DLL 	6.1.7600.16385
IMM32.DLL   	6.1.7601.17514
MSCTF.dll   	6.1.7601.23572
DINPUT.DLL  	6.1.7600.16385
HID.DLL     	6.1.7600.16385
WINTRUST.dll	6.1.7601.23471
CRYPT32.dll 	6.1.7601.23471
MSASN1.dll  	6.1.7601.17514
uxtheme.dll 	6.1.7600.16385
CLBCatQ.DLL 	2001.12.8530.16385
PROPSYS.dll 	7.0.7601.17514
dsound.dll  	6.1.7600.16385
POWRPROF.dll	6.1.7600.16385
MMDevApi.dll	6.1.7601.17514
AUDIOSES.DLL	6.1.7601.23471
atiglpxx.dll	8.14.1.6521
atioglxx.dll	6.14.10.13447
atiadlxy.dll	7.16.30.1304
USERENV.dll 	6.1.7601.17514
profapi.dll 	6.1.7600.16385
WTSAPI32.dll	6.1.7601.17514
atigktxx.dll	8.14.1.6521
mswsock.dll 	6.1.7601.23451
wshtcpip.dll	6.1.7600.16385
dhcpcsvc6.DLL	6.1.7601.17970
dhcpcsvc.DLL	6.1.7600.16385
WININET.dll 	11.0.9600.18523
api-ms-win-downlevel-user32-l1-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-shlwapi-l1-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-version-l1-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-normaliz-l1-1-0.dll	6.2.9200.16492
normaliz.DLL	6.1.7600.16385
iertutil.dll	11.0.9600.18523
api-ms-win-downlevel-advapi32-l1-1-0.dll	6.2.9200.16492
Secur32.dll 	6.1.7601.23571
api-ms-win-downlevel-advapi32-l2-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-ole32-l1-1-0.dll	6.2.9200.16492
wship6.dll  	6.1.7600.16385
api-ms-win-downlevel-shlwapi-l2-1-0.dll	6.2.9200.16492
DNSAPI.dll  	6.1.7601.17570
netprofm.dll	6.1.7600.16385
nlaapi.dll  	6.1.7601.18685
WLIDNSP.DLL 	7.250.4311.0
urlmon.dll  	11.0.9600.18523
mdnsNSP.dll 	3.1.0.1
CRYPTSP.dll 	6.1.7601.23471
rsaenh.dll  	6.1.7600.16385
RpcRtRemote.dll	6.1.7601.17514
rasadhlp.dll	6.1.7600.16385
npmproxy.dll	6.1.7600.16385
fwpuclnt.dll	6.1.7601.18283
Comctl32.dll	6.10.7601.18837

Windows 6.1.7601
DrMingw 0.7.7

-------------------

Error occured on Sunday, December 4, 2016 at 15:13:48.

EmptyEpsilon.exe caused an Access Violation at location 00560156 in module EmptyEpsilon.exe Writing to location 00000047.

Loading symbols... done.

Registers:
eax=ffffffff ebx=0e8f7f40 ecx=ffffffff edx=00000000 esi=00000001 edi=0e8f7f40
eip=00560156 esp=0028f38c ebp=0028f3b8 iopl=0         nv up ei pl zr na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210246

AddrPC   Params
00560156 0E7BA168 00000001 0028F43B  EmptyEpsilon.exe! ??   [/home/daid/ee/EmptyEpsilon/src/gui/gui2_element.cpp @ 118]
005522F4 0E7BA148 3F800000 42C80000  EmptyEpsilon.exe!onClick  [/usr/include/c++/4.8/functional @ 2464]
00559788 44B70555 42E7AAAB 44C80000  EmptyEpsilon.exe!onMouseUp  [/usr/include/c++/4.8/functional @ 2464]
00553CA4 07D80FC8 000017F8 0028F4D8  EmptyEpsilon.exe!render  [/home/daid/ee/EmptyEpsilon/src/gui/gui2_canvas.cpp @ 54]
00604F2C 07D80FC8 000017F8 0028F558  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/Renderable.cpp @ 21]
00604E00 07D80FC8 000017F8 0028F5D8  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/Renderable.cpp @ 18]
00604E00 07D80FC8 000017F8 0028F658  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/Renderable.cpp @ 18]
00604E00 07D80FC8 00000002 0D128FF8  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/Renderable.cpp @ 18]
005EDE7D 07D80FC8 0028F8FC 0028F8FC  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/postProcessManager.cpp @ 42]
005EDE7D 07D80FC8 00000014 00000014  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/postProcessManager.cpp @ 42]
0064FF78 3C8387DF 00000000 FFFFFFFF  EmptyEpsilon.exe!render  [/home/daid/ee/SeriousProton/src/windowManager.cpp @ 31]
0064EDC0 02140001 07E12594 0000000D  EmptyEpsilon.exe!runMainLoop  [/home/daid/ee/SeriousProton/src/engine.cpp @ 148]
0070BA46 07E895E0 0000005B 00000001  EmptyEpsilon.exe!main  [/home/daid/ee/EmptyEpsilon/src/main.cpp @ 281]
004013E0 7EFDE000 0028FFD4 772D9902  EmptyEpsilon.exe!__tmainCRTStartup  [/build/buildd/mingw-w64-3.1.0/build/i686-w64-mingw32-i686-w64-mingw32-crt/../../mingw-w64-crt/crt/crtexe.c @ 332]
750F336A 7EFDE000 778A1C3C 00000000  kernel32.dll!@BaseThreadInitThunk@12
772D9902 004014E0 7EFDE000 00000000  ntdll.dll!___RtlUserThreadStart@8
772D98D5 004014E0 7EFDE000 00000000  ntdll.dll!__RtlUserThreadStart@8

EmptyEpsilon.exe
ntdll.dll   	6.1.7601.23569
kernel32.dll	6.1.7601.23569
KERNELBASE.dll	6.1.7601.23569
exchndl.dll 	0.7.7.0
mgwhelp.dll 	0.7.7.0
dbghelp.dll 	6.3.9600.17029
msvcrt.dll  	7.0.7601.17744
ADVAPI32.dll	6.1.7601.23569
sechost.dll 	6.1.7601.18869
RPCRT4.dll  	6.1.7601.23571
SspiCli.dll 	6.1.7601.23571
CRYPTBASE.dll	6.1.7601.23571
PSAPI.DLL   	6.1.7600.16385
SHELL32.DLL 	6.1.7601.23537
SHLWAPI.dll 	6.1.7601.17514
GDI32.dll   	6.1.7601.23457
USER32.dll  	6.1.7601.23528
LPK.dll     	6.1.7601.23587
USP10.dll   	1.626.7601.19054
VERSION.dll 	6.1.7600.16385
sfml-audio-2.dll
sfml-system-2.dll
WINMM.DLL   	6.1.7601.17514
libgcc_s_sjlj-1.dll
libwinpthread-1.dll	1.0.0.0
libstdc++-6.dll
openal32.dll
ole32.dll   	6.1.7601.23392
sfml-graphics-2.dll
sfml-window-2.dll
OPENGL32.DLL	6.1.7600.16385
GLU32.dll   	6.1.7600.16385
DDRAW.dll   	6.1.7600.16385
DCIMAN32.dll	6.1.7601.23587
SETUPAPI.dll	6.1.7601.17514
CFGMGR32.dll	6.1.7601.17621
OLEAUT32.dll	6.1.7601.23569
DEVOBJ.dll  	6.1.7601.17621
dwmapi.dll  	6.1.7601.18917
sfml-network-2.dll
WS2_32.dll  	6.1.7601.23451
NSI.dll     	6.1.7600.16385
IPHLPAPI.DLL	6.1.7601.17514
WINNSI.DLL  	6.1.7600.16385
WSOCK32.DLL 	6.1.7600.16385
IMM32.DLL   	6.1.7601.17514
MSCTF.dll   	6.1.7601.23572
DINPUT.DLL  	6.1.7600.16385
HID.DLL     	6.1.7600.16385
WINTRUST.dll	6.1.7601.23471
CRYPT32.dll 	6.1.7601.23471
MSASN1.dll  	6.1.7601.17514
uxtheme.dll 	6.1.7600.16385
CLBCatQ.DLL 	2001.12.8530.16385
PROPSYS.dll 	7.0.7601.17514
dsound.dll  	6.1.7600.16385
POWRPROF.dll	6.1.7600.16385
MMDevApi.dll	6.1.7601.17514
AUDIOSES.DLL	6.1.7601.23471
atiglpxx.dll	8.14.1.6521
atioglxx.dll	6.14.10.13447
atiadlxy.dll	7.16.30.1304
USERENV.dll 	6.1.7601.17514
profapi.dll 	6.1.7600.16385
WTSAPI32.dll	6.1.7601.17514
atigktxx.dll	8.14.1.6521
mswsock.dll 	6.1.7601.23451
wshtcpip.dll	6.1.7600.16385
dhcpcsvc6.DLL	6.1.7601.17970
dhcpcsvc.DLL	6.1.7600.16385
WININET.dll 	11.0.9600.18523
api-ms-win-downlevel-user32-l1-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-shlwapi-l1-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-version-l1-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-normaliz-l1-1-0.dll	6.2.9200.16492
normaliz.DLL	6.1.7600.16385
iertutil.dll	11.0.9600.18523
api-ms-win-downlevel-advapi32-l1-1-0.dll	6.2.9200.16492
Secur32.dll 	6.1.7601.23571
api-ms-win-downlevel-advapi32-l2-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-ole32-l1-1-0.dll	6.2.9200.16492
wship6.dll  	6.1.7600.16385
api-ms-win-downlevel-shlwapi-l2-1-0.dll	6.2.9200.16492
DNSAPI.dll  	6.1.7601.17570
netprofm.dll	6.1.7600.16385
nlaapi.dll  	6.1.7601.18685
urlmon.dll  	11.0.9600.18523
WLIDNSP.DLL 	7.250.4311.0
mdnsNSP.dll 	3.1.0.1
CRYPTSP.dll 	6.1.7601.23471
rasadhlp.dll	6.1.7600.16385
rsaenh.dll  	6.1.7600.16385
RpcRtRemote.dll	6.1.7601.17514
npmproxy.dll	6.1.7600.16385
fwpuclnt.dll	6.1.7601.18283
Comctl32.dll	6.10.7601.18837

Windows 6.1.7601
DrMingw 0.7.7

**Comment by daid** [comment]
Most likely fixed with https://github.com/daid/EmptyEpsilon/commit/42ae3e4e5f4af730352ac78ee6a39e282c36b496
