### ISSUE TITLE
Work on new features for EE

### ISSUE THREAD

**Issue by vslotman** [daid/EmptyEpsilon#42]
The coming weeks I'll have time to do some work on the game. 

A lot will be focussed on things we´ll need for our LARP (See http://sevcol.nl/ for more info.) 
Maybe you're already working on something like it, or maybe the stuff I'm gonna make could be of use anyhow :)

Some things I wanted to work on:
- Joystick support for Helms and Weapons
- Ability to heal/damage hull and subsystems through scripting and GM-console
- Ability to control what happens when a ships health/energy drops to 0
- Jumpgates (Devices which pull in a ship like a black hole, and teleport it to a set coordinate)
- REST-client (We're building a lot of hardware which can mostly be controlled using HTTP-requests. A threaded thingy, maybe using the new hardware-API)

**Comment by ErikDeBruijn** [comment]
Hi @vslotman 
I've done some work on the joystick support:
https://github.com/ErikDeBruijn/EmptyEpsilon/commits/joystick-support

Also, as you probably already know I've created some code to use the REST API of EE for creating effects in the physical environment (smoke system, strobe and alarm signal light). This can be found here:
https://gist.github.com/ErikDeBruijn/ebef5db43fe224969b40

**Comment by daid** [comment]
Cool. I'll comment on the things to help you along!

Joystick support is also somewhere on our wish list. Joystick reading is easy:
http://www.sfml-dev.org/documentation/2.3.1/classsf_1_1Joystick.php
But getting it to work nicely with the network code might be a bit of a bitch.

Heal/damage hull trough scripting can be done already:
```
ship:setHull(ship:getHull() - 10)
```
But that won't destroy the ship when hull reached 0.

But adding script functions for the "takeDamage" and "takeHullDamage" functions of the SpaceShip class won't be bad.

I changed the "energy low" handling a while back. It used to set all the power sliders to 0.1, but that was unclear. Now it shows Low energy on all controls, and sets effectiveness of subsystems to 10% max.

Jumpgates sound more like wormholes. Then again, same thing, different graphics. Shouldn't be too hard. Add a small (or big) random factor on the output position, else multiple ships jumping after each other might cause some collision issues.

The new hardware config isn't finished yet. Didn't test it with actual hardware yet. And is the result of a request here: http://bridgesim.net/discussion/122/external-interfaces#Item_10
I'm most likely going to change a few things in how it needs to be configured in the upcoming week. As right now it does not really support "events" only "states", so having a light up when the shields are on works. But having a flash when you are hit does not.
Depending on how your hardware setup is, this could be a good or a bad thing to use. The HTTP API is more powerful, that is for sure. The idea of the new hardware config is that you can use it with stock hardware, like DMX-512 hardware.

**Comment by daid** [comment]
And for the GM screen changes. I just committed a few changes towards that. But I want to use the other half of the retrofit screen have the ability to change beam weapons.

I think another dialog which can change status of ships will be in order. So you can change damange and heat levels of systems, damage&repair shields/hull, change the energy level, and weapon storage amounts.

**Comment by vslotman** [comment]
Thanks for the comments guys! :D
I just did a pull-request for the wormholes.

I'm now looking at changing what happens when energy/hull drops to 0. 
How do I use the DamageInfo-class from scripts?

**Comment by daid** [comment]
Just pushed changes so you can tweak heat and system damage from the GM screen.

Let me work on the damageInfo from script thing, as that's where dragons are :-)

**Comment by vslotman** [comment]
Cool, thanks! :D 
I'll get to it later this week...

**Comment by amir-arad** [comment]
why rest client? why not use websocket?

**Comment by kwadroke** [comment]
@amir-arad See: https://github.com/daid/EmptyEpsilon/issues/13#issuecomment-75230860
