### ISSUE TITLE
optional www server does not serve files with correct headers (minor bug)

### ISSUE THREAD

**Issue by amir-arad** [daid/EmptyEpsilon#421]
Hi, I really like this game.

when testing out [emptyepsilon-www](https://github.com/kwadroke/emptyepsilon-www) (running a server and putting some flies in www folder), CSS files are served to the browser with `content-type:text/html` which confuses the browser and makes it ignore the styling completely. this prevents the embedded www server from supporting mainstream web technologies.

keep on the good work!

**Comment by kwadroke** [comment]
Could be something my code is doing or your browser. Which browser are you using?
It's been a while since i updated [emptyepsilon-www](https://github.com/kwadroke/emptyepsilon-www).
I had a problem with CSS a while back but either Chrome or Firefox (or both) worked with it in later code changes. I'll have to dig it out and re-upload.

**Comment by oznogon** [comment]
[Headers are hardcoded in the SP source.](https://github.com/daid/SeriousProton/blob/dc232f90c755fe001310409d4a7556e0f1d2f3b8/src/httpServer.cpp#L296)

IIRC the web server that's part of EE/SeriousProton is a convenience and not designed for any real use beyond what's necessary for the game. You can turn EE's webserver off and run a real webserver alongside it instead.

**Comment by amir-arad** [comment]
so that's a wont-fix

**Comment by oznogon** [comment]
@amir-arad Not necessarily, but you might want to file it on [daid/SeriousProton](https://github.com/daid/SeriousProton) instead since that's where the server code lives.

**Comment by daid** [comment]
The webserver is designed for small things.

Which browser gets confused by wrong mimetypes? As it seemed to work correctly for me when I tried...

**Comment by amir-arad** [comment]
@daid latest chrome
