### ISSUE TITLE
Issue for compilation

### ISSUE THREAD

**Issue by tdelc** [daid/EmptyEpsilon#427]
Hi,

With the latest commit, I have a problem with the linux and the windows compilation : 

![image](https://cloud.githubusercontent.com/assets/13868149/22668728/17e8d128-ecc2-11e6-86b8-41baf81af3f3.png)

Do you have some advices ?

Thanks

**Comment by aBlueShadow** [comment]
I have the same problem..
My workaround was downloading the latest [Release](https://github.com/daid/EmptyEpsilon/releases/tag/EE-2017.01.19), replacing the according release files by the newer ones by hand, and then compile using the release directory.

**Comment by foesi** [comment]
The Bug is known and should be fixed in #423. The new TutorialMenu.cpp has to be mentioned in the CMakeList.txt file.
A workaround, until this is merged, is to add the TuorialMenu.cpp to the CMakeList.txt file like in the mentioned pull request.
