### ISSUE TITLE
Crash in GuiElement::setVisible(bool)

### ISSUE THREAD

**Issue by honza889** [daid/EmptyEpsilon#430]
Fedora 25, EmptyEpsilon and SeriousProton build from tag **EE-2017.01.19**

Server segfauled after switching from GameMaster console to Helms console.
```
EmptyEpsilon killed by SIGSEGV
Likely crash reason: Jump to an invalid address
```

[core_backtrace.txt](https://github.com/daid/EmptyEpsilon/files/768755/core_backtrace.txt)
[game_log_tail.txt](https://github.com/daid/EmptyEpsilon/files/776736/game_log_tail.txt)

**Comment by daid** [comment]
I've seen a few reports from random crashes in the mainscreen control buttons. I'm unsure why this happens. I suspected heap corruption, but that does not seem the case.
