### ISSUE TITLE
Screen sleeping with DHCP server

### ISSUE THREAD

**Issue by tdelc** [daid/EmptyEpsilon#433]
Hi,

I use the  dhcp configuration and I would like to prevent any screen sleep. Do you have some advice to do this ?

Thomas

**Comment by daid** [comment]
I noticed this myself 2 weeks ago as well. When we ran a network booted main screen.

I haven't looked into it at detail yet, but this provides some pointers to start with:
https://wiki.archlinux.org/index.php/Display_Power_Management_Signaling

**Comment by tdelc** [comment]
Hi,

Thanks for the link.

Apparently, it works with a new file "10-monitor.conf" in the folder  /etc/X11/xorg.conf.d/

```
Section "Monitor"
    Identifier "LVDS0"
    Option "DPMS" "false"
EndSection

Section "ServerLayout"
    Identifier "ServerLayout0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime"     "0"
    Option "BlankTime"   "0"
EndSection
```

**Comment by daid** [comment]
Cool, I'll have a try soon on our setup as well and then update the script.

**Comment by tdelc** [comment]
Done
