### ISSUE TITLE
Sansation Font

### ISSUE THREAD

**Issue by paddatrapper** [daid/EmptyEpsilon#436]
Is the Sansation font used? I could not find a reference to it in the code. If it is used could it not be replaced by a freedom-respecting font that looks similar?

**Comment by daid** [comment]
It's the font that comes with the SFML examples. It was replaced by the now default font when the styling was updated, and I don't think it's used anymore.

**Comment by paddatrapper** [comment]
I am able to build and run without including it and can't find weird looking text in the GUI

**Comment by paddatrapper** [comment]
Is it possible for it to be removed then? Makes packaging easier downstream
