### ISSUE TITLE
Build Error with hotkeyConfig.h

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#438]
Whiletrying to build from the latest commit. I believe this has been doing this for a few commits now.

Building on & for Debian Linux 8 x86_64. Fresh checkout of EE and SP is up to date.

```/home/kwadroke/code/EmptyEpsilon-clean/src/gui/hotkeyConfig.cpp: In member function ‘std::vector<std::pair<string, string> > HotkeyConfig::listHotkeysByCategory(string)’:
/home/kwadroke/code/EmptyEpsilon-clean/src/gui/hotkeyConfig.cpp:268:80: error: no matching function for call to ‘std::vector<std::pair<string, string> >::push_back(<brace-enclosed initializer list>)’
                         ret.push_back({std::get<0>(item.value), key_name.first});
```

Has a new dependency been added?

**Comment by shaunEll** [comment]
Same here! First time i've tried installing. It's a fresh debian 8 64bit install

**Comment by kwadroke** [comment]
Found the fix. 
Add the following to line 6 in _src/gui/hotkeyConfig.h_
`#include <tuple>`

**Comment by dawsmart** [comment]
That fixed this error for me, too.  Buiding on Windows with Code::Blocks.  Thanks so much for posting!!

**Comment by jcc10** [comment]
So... Could we have a fix, B/C this is still happening, and it's one line.

I'm building for my first time and this has caused a lot of wasted time.

**Comment by amir-arad** [comment]
seems like one of those low hanging fruits... ;)
