### ISSUE TITLE
Build error with joystick

### ISSUE THREAD

**Issue by tdelc** [daid/EmptyEpsilon#440]
Hi,

There is a problem with combat maneuvers and joystick. Even if the ship does not have combat maneuvers, using the joystick could increase the heat of the impulse or of the manoeuver system. Could you disable it if the ship does not have this system ? 

Thomas

**Comment by amir-arad** [comment]
Some Joysticks have a slight jitter, perhaps a configurable noise reduction can improve things
This is just a suggestion based on my personal experiences with EE & Joystick

**Comment by daid** [comment]
Problem is, I don't have any joysticks. So all the code isn't tested by me and based on contributions from other people.

**Comment by tdelc** [comment]
Ok, I will test some change in the code to avoid that.
