### ISSUE TITLE
Problem with DMX variables

### ISSUE THREAD

**Issue by tdelc** [daid/EmptyEpsilon#441]
Hi,

When the warp drive is broken, it is still possible to choose WARP 1-4 in the Helm station. But when players do that, the WARP condition for the DMX protocol is on, and this was a little strange for the players.

Could it possible to check between an asked command and an effective command ?

**Comment by tdelc** [comment]
Thanks !

**Comment by daid** [comment]
I'm just glad the DMX functionality is working apparently :-) Can I ask what hardware setup you have? And if you experience any stability issues? I don't have hardware to test on.
