### ISSUE TITLE
Using other device to send keystroke

### ISSUE THREAD

**Issue by tdelc** [daid/EmptyEpsilon#444]
Hi,

I would to use touchOSC (https://hexler.net/software/touchosc) or JoyToKey to use smartphone's or joysticks' buttons shorcut in EE. Unfortunately, while these programs work for any windows application, they do not work for EE. I think that this "kind of" keys are not recognized.

Do you know how to adapt the code to be more flexible about keystroke ?

**Comment by tdelc** [comment]
Sorry, it's me, these app work perfectly in fact. This is perfect !

**Comment by amir-arad** [comment]
Thanks for the issue, though, It gave me a nice idea about integrating EE with https://github.com/jean-emmanuel/open-stage-control

**Comment by tdelc** [comment]
Wahoo ! Such a good discovery ! I will study it too. I do not understand until now how to use shaders. So if you succeed to do some station windows, please let me know how :)

**Comment by amir-arad** [comment]
I'm more into supplying a visual dashboard editor for a game master which can also integrate to external systems. it's a very raw idea, I wouldn't hold my breath.
