### ISSUE TITLE
add documentation for autoconnect

### ISSUE THREAD

**Issue by amir-arad** [daid/EmptyEpsilon#445]
Hi

I was delighted to find this seemingly undocumented feature when browsing through the code. 
I've made [a modest attempt](https://gist.github.com/amir-arad/34eb32ac991fd1c4ffbed5a6fdd6fa65) at documenting it (alas, my markdown-fu is not too impressive). 
I'd be glad to make a PR but I don't know where this kind of documentation belongs. The wiki?

**Comment by daid** [comment]
The wiki would be a good place to put this. The documentation looks right.

I'm using this feature for my netboot setup, which is pretty complex as a whole. Which is why it isn't very well documented.

**Comment by amir-arad** [comment]
will PR as soon as i figure out the damn numbering
