### ISSUE TITLE
Blank screen on Single Pilot

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#45]
After clicking ready on Single Pilot when creating a server, the screen is blank. 

Does it both on Current Git compiled on Linux was well as downloaded version EmptyEpsilon-2015.07.18-win32,

**Comment by daid** [comment]
Uhm, yes, it's on my todo list :-)

**Comment by daid** [comment]
Added the screen today, still lacks some features, but it's no longer black.
