### ISSUE TITLE
REQUEST: visible Black Hole / modify sprite rendering

### ISSUE THREAD

**Issue by aBlueShadow** [daid/EmptyEpsilon#454]
While the current solution of invisible black holes can be an interesting gameplay element, it can also be confusing.

Displaying black holes correctly would be impossible without adding relativistic physics to the engine, Distortion Filters are also tricky - but just using sprites could work.

So I propose to implement the ability to use sprites instead of models for some objects.

I did some testing using planet with atmosphere texture only, like the star in empty space. Unfortunately this did not work completly, as it seems to to use the brightness of the texture as transparency value. So instead of a black disk, the center is transparent.
![comparison](https://cloud.githubusercontent.com/assets/25465934/25632614/96a2baac-2f74-11e7-9c94-63d66d23fd8f.jpg)

(2 variants using atmosphere-only-planets, at the center is a planet with a plain black texture)

So to display it properly, the sprite rendering would need to be modified, so that it just uses the transparency from png and let the other areas opaque.

**Comment by tdelc** [comment]
I like the right one !

**Comment by CaptLapadite** [comment]
I would do a combination of the three :P 
A black circle, with a halo like the right one, and highlights overit like the left :) 

In either case, this is a great idea !

**Comment by aBlueShadow** [comment]
The left one is very simple, basicaly some painted and rotated stars, the "highlights" are just stars behind it. The right one is based on the StarsFront Texture used for the skybox, and already is completly black in the middle, its the athmosphere rendering of the game that makes it transparent. Here's the original:

![blackhole](https://cloud.githubusercontent.com/assets/25465934/25644895/b324db26-2fa9-11e7-92ea-d72d49703ab3.png)

So with a rendering that uses the alpha channel values as transparency instead of the brightness, it would look like this:

![compose](https://cloud.githubusercontent.com/assets/25465934/25644897/ba407abe-2fa9-11e7-8be8-414b2914448c.jpg)

Wich might be too opaque/bright at the outside, but that will probably have to be tweaked once it can be tested properly.

**Comment by amir-arad** [comment]
I find it hard to accept a transparent black hole. the hole itself must be pitch black.

**Comment by nallath** [comment]
You could always call it a "space anomaly"

**Comment by aBlueShadow** [comment]
> I find it hard to accept a transparent black hole. IMO the hole itself should be pitch black.

Absolutely.
I posted the first picture basically to show that it could be done with the built-in sprite renderer, but would require some modifications to it (and to get a general idea of it). Just edited the issue, hope it is now clearer.

But nallath made a point, just searching and replacing "black hole" to "space anomaly" in the code might be a workaround ;-)

**Comment by daid** [comment]
I've seen people flying into the "singularity" of Artemis, because they didn't know it represented a black hole. But I also think the name of this object is not displayed anywhere in game right? Maybe only in the science database?

**Comment by daid** [comment]
(I like the latest image btw)

**Comment by daid** [comment]
I've added this as black hole image. Looks pretty good. I hope the scale is a bit right.

Note that you can get a rendering artifact if you have 2 black holes behind each other, as the rendering order is not properly sorted and the further one can be drawn on top of the near one.
