### ISSUE TITLE
Netboot on raspberry

### ISSUE THREAD

**Issue by tdelc** [daid/EmptyEpsilon#456]
Hi,

I read that EE can not be launch on raspbian, but do you know if it can work with the netboot system ? I read that pxe can be enabled to netboot with raspberry, but i didnt succeed to do this.

Any advice ?

**Comment by daid** [comment]
So far my results of running EE on the Pi have been very unstable. So I would check that first. Setting up a PXE boot is a next level of difficulty. I have a x86 based netboot setup, which was already complex.

**Comment by tdelc** [comment]
Your actual netboot system works perfectly with all my PCs (it is a wonderfull tool !), and naively I thinked that this system could directly work for Pi.
I will investigate too if I think how to adapt the code.
