### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by tdelc** [daid/EmptyEpsilon#46]
Hi,

I did not see anything about translation of your game, so i ask this here. Would you except a multi-language support ?

If yes, and if such a "language" file exist, I think you could ask some help to the community. I know that some Artemis player have propose to help, but the Artemis creator don't want to.

I'm french, and i am ok to try to translate.

Regards,
Thomas

**Comment by nallath** [comment]
There is no language file at this moment, but I see no reason why we wouldn't accept such work. 
It would take a bit of work to set everything up, as we use hard coded strings at the moment.

**Comment by Aphorismus** [comment]
If it's just translating, I would love to translate EE into german language. So, if there's a chance that other languages are possible some day, just tell us.

Regards
Aphorismus

**Comment by daid** [comment]
I don't think anytime soon, due to the heavy scripted nature of some parts. And initial translation is usually not the problem, but keeping the translations updated is.

**Comment by elptito** [comment]
Ok, i understand that it's not a priority. So, don't hesitate to ask later when it will be nice for you.

And thanks for your work !

**Comment by Fouindor** [comment]
A little update from the translation front : support seems good for all latin-alphabet-based languages with default font, save a few exceptions (mainly thinking of Polish and Romanian). When I'll have a bit more of time, would like to try to submit a tentative first translation set, which would add French and Spanish support.

I think GUI would be quite fast to translate. Scenarios, on the other hand, would remain language-dependent.

If it is any good, I may come back to ask the community for additional translation.

**Comment by Fouindor** [comment]
Making progress :
http://i.imgur.com/TQRoq88.png
http://i.imgur.com/Dq8Ku4P.png

(My Spanish is VERY rusty so it may not make sense ^^)

**Comment by itugul** [comment]
I needed localization and I almost finished it. At the moment, only GUI.
That's what i did:
These functions, duplicating the "PreferencesManager" in many aspects, are required for translating a text into GUI . A text is translated directly before the processing in GuiElement. A composite text with several parts is an exception. Then these parts are translated before being sent to GuiElement. The string convertion to multibit format is added to GuiElement as well. The dictionary file is added to "EmptyEpsilon/resources/ru.ini". You can easily translate all the text in it by replacing the word after the "=" symbol.
In the coming days I will lay out the final version on git. If there are comments right now, I will be glad.

**Comment by lacombet** [comment]
Hi there,

Any update on the additional languages support ? I'd be happy to translate everything in French as soon as the game supports it ;)

See you,
Thomas

**Comment by itugul** [comment]
Unfortunately, I did not leave my solution here, it is probably outdated due to many additions, and besides, I seem to have lost the source. (yes yes, this is a complete failure). I’ll make a new version before the end of the month.
  If you make the same file with a translation not into Russian, but into French, it will be cool)
[ru_example.txt](https://github.com/daid/EmptyEpsilon/files/4272408/ru_example.txt)

**Comment by lacombet** [comment]
Hey, thank you for the anwser.

Does it have to be in text format ?

If it has to, I'll do it this way though

**Comment by itugul** [comment]
Yes, you can throw it right here

**Comment by lacombet** [comment]
hey,

I'm on it.

Though is there a way to test it ? Cause some translation need context to be accurate.

**Comment by itugul** [comment]
drop your mail

**Comment by lacombet** [comment]
thomas.public.trash@gmail.com

then I can share you a real one in private ;)

**Comment by gcask** [comment]
This feels addressed: https://github.com/daid/EmptyEpsilon/wiki/Translation-and-Localization

The french translation specifically is probably among the most complete, thanks to @muerteFR colossal effort - if some people here are still looking to contribute, I'm sure he'll appreciate a hand :) .

(and cherry french touch on top from @Tsht with the (proposed) language selection UI in #1423 <3 )
