### ISSUE TITLE
HTTP GET requests failing with Lua script syntax error

### ISSUE THREAD

**Issue by tom-kitchin** [daid/EmptyEpsilon#463]
Hi! 
I've recently come across the game and I've been tinkering with building a general purpose browser-based console for the Empty Epsilon HTTP server, mostly designed to be run locally. 

Unfortunately, when I hit the game HTTP console I get the response `{"ERROR": "Script error"}`, even for exact replicas of the example query.

For example, `http://localhost:8080/get.lua?14976889440102=getHull()` returns the above error.

EmptyEpsilon.log shows:
```
[ERROR] LUA: object = getPlayerShip(-1)
if object == nil then return {error = "No valid object"} end
return {14976889440102 = object:getHull(), }: [string "object = getPlayerShip(-1)..."]:3: '}' expected near '='
```
which looks to me oddly like the generated lua script is failing to build correctly, although the syntax looks fine. Is there something I'm doing wrong? I'm working with the latest binary from the downloads section of the site, so dated 2017-05-06, running on an up to date version of Windows 7.

**Comment by aBlueShadow** [comment]
You can't use numbers as variable names. 

So, try to change your example to:
`http://localhost:8080/get.lua?hull=getHull()`

**Comment by amir-arad** [comment]
hey @tom-kitchin , check out my project [here](https://github.com/CommaSword/scs/tree/master/src/empty-epsilon-client). we're building a nodejs based EE extensions server that communicates with arduino and a back-office. 
The relevant part of it is a general-purpose JS OO API for the EE server. up until now I had no reason to extract the EE API as its own npm module, but if you're into the same thing, maybe we can work together?

**Comment by tom-kitchin** [comment]
@aBlueShadow Ach, that's the reason! That's what I get for not properly checking up on Lua. The numbers I'm using are just generated unique IDs, and now I read the right bit of the Lua docs it looks like I can just stick a letter on the beginning and be good to go. Thanks!

@amir-arad I'm building something to go in the www/ directory and provide a sort of easy-use dashboard, a live update display where the user can add any values they want to the list of things to be output. I appreciate the offer, but my code for actually talking to the game server is pretty much complete, I just need to fix the IDs and get some UI sorted out. Your project sounds much more ambitious than mine :)

**Comment by amir-arad** [comment]
@tom-kitchin would love to beta-test
