### ISSUE TITLE
Gamemaster Screen - Retrofit Bug

### ISSUE THREAD

**Issue by Aphorismus** [daid/EmptyEpsilon#47]
HeyHey, I was playing with the GM Screen a little and noticed that retrofitting the weapons is'nt working correctly. F.e.: If I retrofit a Players Ship to increase the Nuke capacity, it will mess up the whole Nuke Counter.

**Comment by Wrongtown** [comment]
Just a bump to indicate this is still an issue, I haven't sat and analysed it but it has turned up in-game when the upgrade event in The Edge of Space mission was derailing the plot and I figured I'd fudge a few nukes/mines in for the crew. Lots of high-negative numbers showing up, though this might be unique to a scenario where the Player Ship has **setWeaponStorageMax** of **0** for a given weapon.
