### ISSUE TITLE
voip communication

### ISSUE THREAD

**Issue by amir-arad** [daid/EmptyEpsilon#471]
I'm planning to use EE for a larp, and it would be great to allow the game masters to play the comm officers of ships and space stations over voip communication.

How difficult is it to add this feature to the game?

**Comment by kwadroke** [comment]
Until there is I'd recommend something like Mumble as there is servers & clients for multiple OSes.

**Comment by nallath** [comment]
I've looked into it once. SFML does support voice streaming, but I never got to actually implementing it.

**Comment by amir-arad** [comment]
I'll look into Mumble. thanks!
