### ISSUE TITLE
[BUG] Main screen option not showing up

### ISSUE THREAD

**Issue by jbrain4** [daid/EmptyEpsilon#479]
The option for using a "Station" as a main screen is now gone. It used to be there, but now it is gone. The other options under "Alternative Options" are also gone. I don't know where the logs for EE are, I'll check it as soon as I find where they are. Running *EE-2017.05.06* on **Mac**. (will test on **Windows** soon)

---

## 6/5 Player Crew
![screen shot 2017-11-02 at 18 49 15](https://user-images.githubusercontent.com/19595939/32357031-bbcfb1f2-bffe-11e7-8121-c92c6e01110a.png)

## Alternative Options
![screen shot 2017-11-02 at 18 49 22](https://user-images.githubusercontent.com/19595939/32357109-46954fa4-bfff-11e7-83ec-2a16f99d0a6a.png)

**Comment by daid** [comment]
These options go missing as soon as EE detects a lack of proper OpenGL shader support. (For example, the Android version also does not display these options)
