### ISSUE TITLE
EmptyEpsilon Crashing when connecting to any EmptyEpsilon server

### ISSUE THREAD

**Issue by thatHumanJason** [daid/EmptyEpsilon#482]
When connecting EmptyEpsilon Clients (3 of them) to an EmptyEpsilon Server, it crashes as soon as the game is _Unpaused_. It sometimes crashes before connecting to the server.

I've tried using different computers, a different number of computers, different hostnames, and different passwords.

All devices have the latest versions of EmptyEpsilon (**20171111**)
All devices are Macs running Mac OS X 10.9, Mac OS X 10.11, or macOS 10.13

The only error I see when running in debug mode is `[ERROR] Failed to find ship template:`. It shows up several times.

**Comment by daid** [comment]
Failure to find ship templates generally causes crashes. Most likely it cannot read the script resource files.
(Note that I do not have any Macs, so I have no way to validate the Mac build)
