### ISSUE TITLE
request / question: share context between scripts in http api

### ISSUE THREAD

**Issue by amir-arad** [daid/EmptyEpsilon#486]
I'm using the http API to trigger long-running lua scripts (```Script():run("custom.lua")```)), and I need a way to re-gain reference to that script object so i can change its variables or destroy it.

I tried setting the script to the global context, but that didn't work.

**Comment by amir-arad** [comment]
ok, got it. using [_G](https://www.lua.org/pil/14.html#EnvironmentSec) explicitly solves the problem

**Comment by tdelc** [comment]
Can you give us a little example ? I am interested by such a fonctionnality.

**Comment by amir-arad** [comment]
I'm looking for a way to get into the game loop with custom logic.
so at some point I send this script to ```http://server:8080/exec.lua```:
```lua
_G.dScript = Script()
_G.dScript:setVariable("arg1", "foo")
_G.dScript:run("daedalus_1.lua")
```
the lines:
1. create a new script host, save it as ```dScript``` on the global context.
2. set variable ```arg1``` of the script as "foo"
3. inside the host where ```arg1`` is defined to "foo", run ```daedalus_1``` script (which has an ```update(delta)``` function that will be called inside the game loop)
from this point on, ```daedalus_1.lua``` can do stuff, and use the "foo" value as an argument.

at some later point in the game, i send this second script to ```http://server:8080/exec.lua```:
```lua
_G.dScript:setVariable("arg1", "bar")
```
so ```daedalus_1.lua``` is still running it's logic inside the game loop, but from that point on, it will use the "bar" value as its argument.

**Comment by amir-arad** [comment]
as to the functionality, I have two:
1. Cap - enforce a maximum value on a property
2. Linear change - change a value over time while some effect is in play.
