### ISSUE TITLE
Modified wrong starfighter template

### ISSUE THREAD

**Issue by Doubleumc** [daid/EmptyEpsilon#491]
https://github.com/daid/EmptyEpsilon/blob/d4d9b82ca00fded6ba6a5b3c1f86081b888f0b35/scripts/shipTemplates_StarFighters.lua#L33-L34

In the block of code meant to specify the player variation of the Hornet fighter, it instead erroneously modifies the original Hornet template.

**Comment by daid** [comment]
Well, that explains the annoying long fights with these ships :-) thanks for spotting it!
