### ISSUE TITLE
Mentioning of repairable hull in Tutorial

### ISSUE THREAD

**Issue by aBlueShadow** [daid/EmptyEpsilon#495]
The summary of the engineering tutorial claims:
"Hull damage affects the entire ship, and repair crews can always repair it, but hull repairs progress very slowly."
However I never experienced that. Yesterday I tried to get certainty by starting an empty scenario, crash into an asteroid, and let the game run overnight. Hours later, the hull was still at the exact same percentage. So either the repair is sooo slow that it is negligible :-), or the statement is incorrect.
However I am not sure if this is a bug in the game or simply a wrong description.

**Comment by kwadroke** [comment]
I believe you have to be docked for the hull to be repaired. Don't think it gets fixed on it's own.

**Comment by daid** [comment]
Yes, the tutorial is wrong here. Hull repairs happens when docked at stations.
