### ISSUE TITLE
'Cannot open audio device'

### ISSUE THREAD

**Issue by GoodOldJack12** [daid/EmptyEpsilon#497]
Me and my friends were playing this game and its great, but none of us get any sound.
I havent found any documentation on this issue. Can someone point me in the right direction?

on a second note, the program has issues recognizing beamer resolutions

**Comment by NinjaSpectre** [comment]
https://github.com/daid/EmptyEpsilon/issues/390

I can't comment much on the second part as I don't use a projector.

**Comment by aBlueShadow** [comment]
To avoid confusion: While #390 is not the same issue, it can be somehow considered its predecessor with basically the same workaround.
Back then the openal.dll caused crashes on windows 10. Therefore it was replaced. Unfortunately the new dll now cause the problem that no sound is played.

btw, I just saw that one https://github.com/SFML/SFML/pull/1260
The according issue is from june, the EE version where the dll was replaced is from may, so I wonder if we can again use the dll provided with sfml to fix both issues.

@GoodOldJack12  summary:
1. rename or delete the OpenAl.dll in the EmptyEpsilon directory
2. if EE now works and has sound, all is fine. If it does not and may not even start now, continue to 3.
3. download the file from here https://github.com/SFML/SFML/blob/master/extlibs/bin/x86/openal32.dll and put it into your EmptyEpsilon directory. **If you are using Windows 10 and that works without crashing after a few minutes, please post it here, as that information would be very valuable.**
Download and install OpenAL system-wide (you might need the version from )
4) if that also don't work, delete that file, download OpenAl from https://www.openal.org/downloads/ and install it

**Comment by NinjaSpectre** [comment]
Thanks @aBlueShadow for the explanation.
I used the DLL linked in step 3 and can confirm it works on the Windows 10 machines I'm using.
Previously I was using the installer from step 4 in order to achieve sound.

**Comment by GoodOldJack12** [comment]
Thanks for the swift reply, I'll give it a try tomorrow!
