### ISSUE TITLE
MissileVolley AI never fires

### ISSUE THREAD

**Issue by Doubleumc** [daid/EmptyEpsilon#500]
When trying out the various AIs I found that the `missilevolley` AI never actually fires its missiles.  Believe the culprit is here, if any tube is loaded it considers all tubes unloaded and never attempts to fire.
https://github.com/daid/EmptyEpsilon/blob/e10cf94132e30906830df3490a904dd050ce1755/src/ai/missileVolleyAI.cpp#L59-L63

Unrelated, when flanking left the ship guides towards 100 degrees off, rather than 120 degrees as specified everywhere else in the AI.
https://github.com/daid/EmptyEpsilon/blob/e10cf94132e30906830df3490a904dd050ce1755/src/ai/missileVolleyAI.cpp#L98

**Comment by NinjaSpectre** [comment]
When corrected it could also not fire when there are no more missiles of that type to load in a tube. 
Maybe something like the following to replace lines 56 - 64:

`bool all_loaded = false;`
`int load_count = 0;`
`int loading_count = 0;`
`for(int n = 0; n < owner->weapon_tube_count; n++) {`
`    if (owner->weapon_tube[n].isLoaded()) load_count++;`
`    else if (owner->weapon_tube[n].isLoading()) loading_count++;`
`}`
`if (load_count == owner->weapon_tube_count) all_loaded = true;`
`else if (load_count > 0 && loading_count == 0) all_loaded = true;`

This assumes that the AI will load a missile tube as soon as it is able (doesn't leave them empty).

**Comment by daid** [comment]
> When corrected it could also not fire when there are no more missiles of that type to load in a tube.
This was kinda intentional, if the ship runs out of missiles for a volley, it no longer fires at all.

But yes, this code looks buggy.

**Comment by daid** [comment]
Even worse, the code crashes if the ship runs out of missiles...

**Comment by daid** [comment]
Could make the logic still very simple. As if when the ship runs out of missiles, "has_missiles" will be false, and thus you never reach this code. Then you only need to check if any tubes are still loading, as the base AI handler will handling loading missiles for us already. If any tube is still loading we do not want to fire yet.

Crash was related to missile types being passed as tube indexes...
