### ISSUE TITLE
How to use addCustomMessageWithCallback?

### ISSUE THREAD

**Issue by Doubleumc** [daid/EmptyEpsilon#501]
I'm unable to find any description or examples of the `:addCustomMessageWithCallback()` method.  I'm not sure of its purpose or how to use it.  I've tried several variations on the following mission file:
```lua
function init()
	player1 = PlayerSpaceship():setFaction("Human Navy"):setTemplate("Atlantis")

	player1:addCustomMessageWithCallback("engineering", "CALLBACK", "callback caption", function()
		print("callback function")
		player1:destroy()
	end)
end
```
There is no script error yet none of the stations have a message appear, the console remains blank, and the ship isn't destroyed.  Nothing happens.

**Comment by daid** [comment]
Your usage is correct, there are 2 bugs in the code. The station isn't properly stored (thus always helms) and the callback doesn't work on messages only on buttons.
