### ISSUE TITLE
Reference error in CustomButtons

### ISSUE THREAD

**Issue by Doubleumc** [daid/EmptyEpsilon#502]
The following mission script produces a `??? CANNOT FIND REFERENCE BACK TO SCRIPT...` error, but only under certain conditions:
```lua
function addCoolantControls(ship)
	ship:addCustomButton("engineering", "AUTOCOOLANT", "autocoolant", function()
		-- print()
		-- dummyvar = ""
		ship.autocoolant = not ship.autocoolant
		ship:setAutoCoolant(ship.autocoolant)
	end)
end

function init()
	player1 = PlayerSpaceship():setFaction("Human Navy"):setTemplate("Atlantis")
	addCoolantControls(player1)
end
```
Note the commented out lines.
If either or both of those lines are uncommented the script works as expected.
If uncommented *but* moved to after the following `ship` lines the error returns.  
If `addCustomButton` is instead brought into `init` and acts directly on `player1`, it works with or without the commented lines, like so:
```lua
function init()
	player1 = PlayerSpaceship():setFaction("Human Navy"):setTemplate("Atlantis")
	player1:addCustomButton("engineering", "AUTOCOOLANT", "autocoolant", function()
		player1.autocoolant = not player1.autocoolant
		player1:setAutoCoolant(player1.autocoolant)
	end)
end
```
This is a lot less convenient if there are multiple ships you want to modify, or if you want to add it to a utility script.

**Comment by daid** [comment]
"CANNOT FIND REFERENCE BACK TO SCRIPT" indicates an internal error with the callback mechanism. I'll see if I can reproduce this.

**Comment by daid** [comment]
Oh, damn.
The problem is that I try to relate the callback function to the original script that created this function. However, the mechanism I use doesn't work if this function isn't accessing any globals, like the print() function or the dummy var.
