### ISSUE TITLE
Make install fail 2017.12.25 - cannot make directory

### ISSUE THREAD

**Issue by pixelclef** [daid/EmptyEpsilon#504]
I'm getting this when I make on Ubuntu 16.04:
```
[100%] Built target scriptdoc
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/share/emptyepsilon//resources
CMake Error at cmake_install.cmake:44 (file):
  file INSTALL cannot make directory
  "/usr/local/share/emptyepsilon//resources": No such file or directory


Makefile:104: recipe for target 'install' failed
make: *** [install] Error 1
```

Ideas? Suggestions?

**Comment by kwadroke** [comment]
Are you running it as root or using `sudo make install`? Standard users can't install to /usr/local/share unless you've changed the permissions to the folder (not recommended).

**Comment by pixelclef** [comment]
We ended up stomping through this manually. Creating each folder as it would barf.

I think we _were_ actually running the make as the user who was intended to run the application - thinking that the result might need some kind of permissions. Sounds like it would be easier to build as an administrator user.

Would a standard user still be able to run the game?

I think we just started out wrong and decided to bull our way through it with hamfisted stubbornness. Dad would be proud.

**Comment by kwadroke** [comment]
You should be able to build and run it as a standard user. To install, you have to have root (sudo) permissions. 

You don't have to run `make install`. You can run the binary from the EmptyEpsilon folder if you want. This is how I run it. If you're using the `_build` or `build` folder, copy the EmptyEpsilon binary to the main EmptyEpsilon folder and run from there.

**Comment by kwadroke** [comment]
See the Section called _Linux (Debian 8/Raspbian)_ on the wiki https://github.com/daid/EmptyEpsilon/wiki/Build-from-sources. That should help explain things as well.

**Comment by oznogon** [comment]
This should be closable.
