### ISSUE TITLE
GM Screen - Last 3 ships unclickable

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#52]
I was testing the latest commit today, and started playing with the Game Master console. I noticed there were 3 ships that I could not select when creating ships on the map.
My guess is that the new faction's ship made the list go off the box and you can't select items not inside the box.

**Comment by Jhovall** [comment]
I have the same problem when I am testing my new ship templates (I have 30 of them, so they go off the screen).
Your guess is correct and It'd be beneficial if the list could be longer.

**Comment by daid** [comment]
Fix shouldn't be too hard, the list just needs to be changed into a listbox (which can do scrolling)

**Comment by daid** [comment]
This change should fix it for ships. But does not fix it if you have too many station options.
