### ISSUE TITLE
Setting server

### ISSUE THREAD

**Issue by Cat107** [daid/EmptyEpsilon#523]
I can't set up internet game server on PC. When I switch from LAN To Internet, server IP doesn't changes, I don't know what to do. What I should do to set up Internet server and get it's IP?

**Comment by LHolst** [comment]
Did you set up the portforwarding as noted in

https://github.com/daid/EmptyEpsilon/wiki/Internet-Play

> TCP & UDP Port number:  35666

**Comment by Cat107** [comment]
Yes, shouldn't IP change after setting server type to Internet?

**Comment by daid** [comment]
Nope, the IP is shows is always your local one. Due to the nature of the game the focus is on LAN play.
