### ISSUE TITLE
REQUEST Areas & Labels

### ISSUE THREAD

**Issue by Nevrose** [daid/EmptyEpsilon#529]
Can you make the following objects and functions available for LUA scripting ? Thanks.
- _**Area**()_ : Creates a polygone that is displayed behind the sector grid and spaceobjects icons.
- _Area:**setView**(string view, boolean visibility)_ : for the selected view ("relay" or "science"), if visibility is true then the area is displayed, else it is hidden.
- _Area:**destroy**()_ : destroy the area.
- _Area:**setPositions**(table positions)_ : sets the area to a list of indexed positions. Points have to be ordered clockwise around the center of the area.
- _Area:**setColor**(number red, number green, number blue)_ : sets the color of the area.
- _boolean SpaceObject:**isInside**(Area area)_ : returns TRUE if the spaceOject is inside the area, else FALSE.
- _**Label**()_ : Creates a label that is displayed before the sector grid and spaceobjects icons. Label is a spaceObject without visible model.

**Comment by Nevrose** [comment]
> communications

elay

**Comment by daid** [comment]
I like this idea, it gives a lot of options to make scenarios clearer with "zones".

I guess these areas should not be hidden by "fog of war"? (Nebula/relay friend only view)

**Comment by Nevrose** [comment]
If I have to choose between the two, I'd say never hide.

Still, the ideal choice would be to control this under a parameter ( Area:setView(string view, boolean visibility, boolean fog) : if fog is true then the Area will be hidden under the fog of war, else it is always visible).

**Comment by amir-arad** [comment]
you can have them both if you alias each of them differently
say, map territory should not be subject to fog of war, but mission visual aids (that are temporal in nature) should.

**Comment by daid** [comment]
I figured, for rendering, render an outline with the color, and a transparent fill. However, the fill is a problem if the area isn't convex...

I also think "zone" might be a better name then "area". Other useful functions on those can be "getCenterPoint()" "getRandomPoint()"

**Comment by Nevrose** [comment]
Does this helps ? [http://alienryderflex.com/polygon_fill/](url)

**Comment by daid** [comment]
Not really, those algorithms work if you need to draw pixels. But I don't draw pixels, I draw triangles by the means of the GPU.
I most likely need some form of "polygon decomposition" or "polygon triangulation"

**Comment by Nevrose** [comment]
Hmm, okay. We have a [C implementation just here](http://gamma.cs.unc.edu/SEIDEL/#FIG).
[Direct link to the source code](http://gamma.cs.unc.edu/software/downloads/SEIDEL/seidel-1.0.tar.gz)

**Comment by daid** [comment]
Started work on this. Basic colored zones seem to work now, labels not yet.

Simple test:
```
    Zone():setPoints(
        -1000, -1000,
        1000, -1000,
        1000, 1000,
        -1000, 1000
    )
```

**Comment by tdelc** [comment]
Great news !

I Hope that GM screen will include this amazing feature in the end.

**Comment by daid** [comment]
The zones themselves work now. But you cannot do anything from the GM screen yet.

**Comment by tdelc** [comment]
I will test it this week end. Thank for this work.
Do you plan to add the GM functionnality later ?

**Comment by Nevrose** [comment]
Yaye \_o_/ :)

**Comment by daid** [comment]
GM support would be quite a bit of work, as you would be able to add/remove and move points. Right now, I made the GM screen ignore the zones except for drawing. As you would select and move them all the time otherwise.
