### ISSUE TITLE
Display Full Scan description in the Relay

### ISSUE THREAD

**Issue by Nevrose** [daid/EmptyEpsilon#531]
As soon as a ship is fully scanned, you can't see descriptions anymore.

**Comment by amir-arad** [comment]
probably worth combining with #349

**Comment by czenker** [comment]
Can anyone still reproduce this issue? I remember having this issue too, but I can no longer reproduce it. `setDescription`, `setDescriptions` and `setDescriptionForScanState` all work for me with a ship as I would expect.

**Comment by oznogon** [comment]
Can't reproduce on 2020.01.15
