### ISSUE TITLE
REQUEST Customizable button for each station of each player ship

### ISSUE THREAD

**Issue by Nevrose** [daid/EmptyEpsilon#538]
Add a custom button to each station.

The idea here is to give each station a mission specific eventful interface to interact with.

When the player click on the custom station button, a dialog box opens. The dialog is defined the same way that you define relay communication for a ship.

Those buttons should be linked to the player ship, so that it stays relevant in multiplayership missions, In other word, a helm station button from ship A should not display the same thing aboard ship B.

It could also be nice to be able to hide or display the button with a specific color display (so that you can inform the player that something is going on in his station).

**Comment by daid** [comment]
There is a limited version of this available already with the following script functions:
```
PlayerSpaceship:addCustomButton(ECrewPosition position, string name, string caption, ScriptSimpleCallback callback)
PlayerSpaceship:addCustomInfo(ECrewPosition position, string name, string caption)
PlayerSpaceship:addCustomMessage(ECrewPosition position, string name, string caption)
PlayerSpaceship:addCustomMessageWithCallback(ECrewPosition position, string name, string caption, ScriptSimpleCallback callback)
```

**Comment by Nevrose** [comment]
I missed it. Excellent !

**Comment by JonathanILevi** [comment]
Is this issue still disserve to be open?  It looks solved.
