### ISSUE TITLE
Idea/Question: Function to find the ship's current speed? 

### ISSUE THREAD

**Issue by RayvenMaker** [daid/EmptyEpsilon#545]
@daid I've been working on a few new ships and scenarios in my free time, and I've run into a problem with my most recent ship. I modified the single cell fuel carrier to ram into other ships as its attack--essentially, I'm using some very short range, very high damage beam weapons to make it seem like a ship is being destroyed when this ship rams into it. It has a terrible turning radius, slow acceleration, and some ridiculously powerful impulse engines, so missing ships usually sends you far away from the battlefield. It's more fun than you realize. 😂 

My only issue is trying to make this ship balanced: currently, if you ram a ship at a slower speed, the beams have the same power as if you rammed that ship at top speed. This reduces the incentive to go faster and therefore reduce your maneuverability. 

Is there any way to make the damage of the beam weapons proportional to the current speed of the ship? i.e. can I write a function to get the current speed of the ship? If I could just call a function within the ship template file, then that would work. If anyone has any ideas on how to write this in, then I'm open to them!

Current beam weapons function:
`template:setBeamWeapon(0, 120, -15, 300, 1, 100)`
`template:setBeamWeapon(1, 120,  15, 300, 1, 100)` 

How it should be 
`template:setBeamWeapon(0, 120, -15, 300, 1, getCurrentSpeed() * 10)`
`template:setBeamWeapon(1, 120,  15, 300, 1, getCurrentSpeed() * 10)`

`getCurrentSpeed()` would output in U/min, but if it has to be milliU/min, then just divide by 100 and it'll be fine.

// RayvenMaker

**Comment by daid** [comment]
/// Gets the velocity of the object, in 2D space, in meters/second
REGISTER_SCRIPT_CLASS_FUNCTION(Collisionable, getVelocity);

```
vx, vy = object:getVelocity()
speed = math.sqrt(vx*vx+vy*vy)
```
You'll have to do it in a scenario script, you cannot do "active" code in the templates, that code is only ran once.

**Comment by RayvenMaker** [comment]
Thanks, @daid! That definitely helps. 

Maybe I'll push those ship templates when I'm done with them. 

// RayvenMaker
