### ISSUE TITLE
Forums are down

### ISSUE THREAD

**Issue by msbeck** [daid/EmptyEpsilon#552]
The captcha on the forums linked from your home page are down and new users cannot sign up. It says to inform the webmaster to update it. Do you guys have contact with them?

**Comment by oznogon** [comment]
@kwadroke is the forums admin

**Comment by kwadroke** [comment]
I'll be able look into it when I get home in a few hours.

**Comment by kwadroke** [comment]
Will have to update the re-captcha.

**Comment by msbeck** [comment]
Thanks! I'm assuming questions about development and so forth are best handled there? These issues are just for legit bugs?

**Comment by kwadroke** [comment]
I did a forum upgrade. You should be able to register now.

Questions should be posted in the EmptyEpsilon Section of the forums. Issues post here.

**Comment by msbeck** [comment]
Created an account with SSO. Works now. Though, the color scheme seems to have changed and things are almost not legible.

<img width="789" alt="screen shot 2018-08-25 at 7 07 38 am" src="https://user-images.githubusercontent.com/2982395/44618128-a7fe6400-a835-11e8-8802-8a1c1a3a5e8b.png">
Grey on black postings

<img width="780" alt="screen shot 2018-08-25 at 7 08 37 am" src="https://user-images.githubusercontent.com/2982395/44618131-b77dad00-a835-11e8-9599-dcad2cfc8a55.png">
White on yellow code blocks.

**Comment by msbeck** [comment]
I am getting an errer after tryint to post a New Discussion though: 
```{ "Code": 403, "Exception": "You need the Garden.Community.Manage permission to do that.", "Class": "Gdn_UserException" }```

this pops up after I click "post discussion"

**Comment by kwadroke** [comment]
The new theme is temporary. Once I make or find one that better suites the site I'll change it.
Will look into the permissions issue.

**Comment by kwadroke** [comment]
Did you verify you account via email?
I verified your account manually. Should be able to post now

**Comment by msbeck** [comment]
Ok, thanks. I received an email and clicked A link, but it doesn't seem to have been a verify link. Thanks again.

**Comment by oznogon** [comment]
Forums have been up for a while, this should be closable.
