### ISSUE TITLE
MacOS Science/Radar Station Rendering All Objects as Black

### ISSUE THREAD

**Issue by msbeck** [daid/EmptyEpsilon#554]
<img width="2560" alt="screen shot 2018-08-24 at 7 32 19 pm" src="https://user-images.githubusercontent.com/2982395/44617964-c4e56800-a832-11e8-9020-16675f59be7a.png">

It seems as if the objects on the Radar are rendering all black in the Science station on the 1 player ship.

This was a scenario with two Macs that had built their own game from source and altered the cmake to version zero and a Windows machine at Tactical. A Mac was the server.

I haven't had the opportunity to play on other devices to confirm what it "should" look like. 

Objects are clickable and scannable, but always black and essentially invisible. You can see the outline of one rectangular object at the bottom right of the green cloudy area.

**Comment by oznogon** [comment]
See also issues #168, #233 and PR #327.

**Comment by msbeck** [comment]
Sorry about that. Coming up to speed on everything!

Am I to read properly that #327 does fix this, it just wasn't accepted into the main branch because it's a bit risky?

**Comment by msbeck** [comment]
Thanks! Local fixes with for me ^_^

**Comment by amir-arad** [comment]
sorry for forgetting to upload... hectic days. will do today

**Comment by amir-arad** [comment]
Hi
Sorry for the delay. [Here](https://github.com/amir-arad/EmptyEpsilon/tree/fix-radar-black-osx) is my branch with a fix.
What's missing to make this a PR:
1. the white transparent overlay that shows the fog of war does isn't shown in mac currently. It's still a vast improvement though.
2. I have a vague recollection of testing this on my linux machine but I definitely did NOT test it on windows, so there's that.

would love to hear if this does not break linux / windows.

another workaround we discovered at the office is that probe view works well,  so I just give them a bunch of probes and we kinda work it out.

**Comment by NinjaSpectre** [comment]
Applied your changes to a Windows 10 build.  I did not experience any difference in how the fog of war is rendered, so 👍 from me.

**Comment by daid** [comment]
I'll have to check if the intel GPU drivers have no issue with the patch, if that's the case, then it's most likely fine. (The intel drivers are pretty picky...)
