### ISSUE TITLE
Opening Communications loop

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#56]
We encountered a problem during Opening Communication with a station. The Open Communications progress bar repetitively went to 100% then went back to zero and started again. 

We disconnected the client from the server and the repetition continued. This was also displayed on another computer when we went back and selected Operations. 

Tested on a 4/3 bridge with Operations on 2015.10.23 release. Saw issue during Basic scenario.

Might be a good idea to have a cancel button to stop the Opening Comms connection in-case it was mis-clicked.

**Comment by kwadroke** [comment]
Not sure how to replicate this problem, but, I have seen it prior to last night's testing.

**Comment by daid** [comment]
Could have been the comms script bug that I fixed a while back. As I'm not seeing this happening.

**Comment by kwadroke** [comment]
It's not something that happens all the time. Will close this for now. I'll re-open if it pops up again.

**Comment by daid** [comment]
The looping like that does happen when you open comms to another player, it keeps looping till the other ship accepts or denies the request for comms.

**Comment by kwadroke** [comment]
That could have been it. Thought he tried to open comms to a station, but we could have spawned another ship and he tried to open comms with it instead. 
Would be nice if there was a way to close it if the other ship never responds.
