### ISSUE TITLE
would appreciate help with cross compiling from linux to windows

### ISSUE THREAD

**Issue by amir-arad** [daid/EmptyEpsilon#566]
I've tried making a windows build from linux but It seems like no linux compiler will satisfy windows SFML.
would apreciate help very much. Ideally, for SFML 2.5.0, I'm willing to cross compile SFML myself but I can't find how to do it propperly.

**Comment by daid** [comment]
You want the "i686-w64-mingw32-gcc" compiler under linux.

I'm using the following cmake toolchain file to compile for windows on linux (see the manual on how to use toolchain files with cmake)
```
# this one is important
SET(CMAKE_SYSTEM_NAME Windows)

# specify the cross compiler
SET(CMAKE_C_COMPILER /usr/bin/i686-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER /usr/bin/i686-w64-mingw32-g++)
SET(CMAKE_RC_COMPILER /usr/bin/i686-w64-mingw32-windres)

# where is the target environment
SET(CMAKE_FIND_ROOT_PATH /usr/i686-w64-mingw32 /home/daid/ee/win_root)

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_INSTALL_PREFIX /home/daid/ee/win_root)
```

I also have this script:
```
#!/bin/sh

TOOLSET=i686-w64-mingw32
CROSSPATH=/home/daid/ee/win_root
export CFLAGS="-I${CROSSPATH}/include"
export LDFLAGS="-L${CROSSPATH}/lib"

./configure --target=$TOOLSET --host=$TOOLSET --prefix=$CROSSPATH $@
```
Which I most likely used to configure some dependencies of SFML. But I haven't done it completely from scratch for a while.
