### ISSUE TITLE
missing tag for version 2018.09.06

### ISSUE THREAD

**Issue by sgitkene** [daid/EmptyEpsilon#575]
Hi I wanted to install empty epsilon from [aur](https://aur.archlinux.org/packages/emptyepsilon) and wondered why there was no current version, when the windows version offered from your website is 09.06, but on aur it is still 02.15. Turns out there is no tag for the most current version. could you add that so that the repository can be updated too (mabe boop the [maintainer](https://aur.archlinux.org/account/mewp) of the package, too)? I'd very much like to be able to play with my windows friends on the most current build.
kind regards

**Comment by daid** [comment]
Due to the android build failing, the tags wheren't push, did so now.
