### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by Jhovall** [daid/EmptyEpsilon#58]
So I have been 'working' on a GUI which looks more futuristic and more intiuitive. Basically: I downloaded some pictures, changed them somewhat and put them together. The picture in the middle should be the weapons radar, but it is too small at the moment :P. It is not finished yet and needs seperate buttons for fire, and something for loading the tubes etc. but it provides a general idea. Comments?

http://imgur.com/gallery/WLXsq6a/new

**Comment by daid** [comment]
The pictures that you downloaded, how is the license on that? (Because I do not want to rip off other peoples work)

**Comment by nallath** [comment]
Oh wow. That looks nice!

**Comment by IvanSanchez** [comment]
> The pictures that you downloaded, how is the license on that? 

I recognize elements ripped off the Star Trek Online GUI. :-S


> but it provides a general idea. Comments?

Disclaimer: I've worked on maritime electronics, and I know how UIs for real ships feels like.

So, I don't like it. There's way too much tiny text and graphics in antialiased shades of blue. When you're running a ship, fancy graphics are just a distraction, specially when they are small - the UI of a bridge has to be **useful, not pretty**. I do think that a spaceship should be function over form, not form over function.

Typography. I count 7 or so different typefaces on the screen, including Serif typefaces (hint: never use serifs in a futuristic anything). Using a consistent typeface is as important as using the same colour or the same line width.

Weird-shaped buttons: While these look good on alien UIs in the TV shows, complex shapes means that the code has to control weird hitboxes, and that has the potential of wasting the user's time in case of a misclick (or making the user spend more time thinking where to click).

I think you're trying to do too much at once - you're working on the whole screen. Instead, I suggest you start small: design small controls/widgets first. How does a tube load/fire/unload control work? What are the possible interactions and states? Does the shield status show a percentage, a bar, an absolute value, or something else? How is an on/off toggle different from a button? These kind of tiny things ultimately add up.

That way, you don't need to redesign the whole thing if the game changes to include one more feature in one screen.

If you're going to work on an overall design, remember to see how the UI looks on a 4:3 screen, and on 9:16 and 10:16. Different aspect ratios will force you to make an adaptable interface, which will force you to use spacers (the industry has standard screen sizes, but a game like EE runs on a variety of devices, resolutions, pixel sizes, etc).

---

So, once again, I do think that in a bridge simulator UI, function is more important than form, and the proposed screenshot is form over function.

**Comment by Jhovall** [comment]
Well, yes, there are two pictures from the star trek online GUI, the up/down slidebar and the shield/hull thingie with U.S.S. Aneas on it. 
The other ones are freely-available and downloadable pictures, which I adjusted, if I am home again I could send the license. 
The STO-UI things should be changed, but since it was a mock-up I did not feel like creating a whole new picture and used this as reference. The idea is clear.

@ Disclaimer: Well, this ain't a maritime electronics thing and if you got a better idea, make it :). Maritime electronics has way more functions than EE, the amount of actual different choices you can make with the weapons console is actually quite low. The little less-important things I added do not matter for the whole game, but gives 'colour' to the interface and could provide non-important data. 

They might for you be a distraction, but when I let people play EE at a convention, they unanimously disagree with you and say that the UI should be prettier and we should add 'stuff'. It can be that from 'reality' you would like a more boring interface, but remember that this is a game.

Typography: You are right, I added some different typefaces. I should have one typeface. Actually I changed some with paint because my photoshop needed a reinstal at the time. 

Weird shaped buttons, yes, the buttons down could be removed. Although I do not think they are weird, they look futuristic and a bit alien yes. And you have a big enough box to click on, so misclicks are not an issue, unless you have parkinson. The hitboxes are not that hard to make, since I will provide every button seperately.

I do not think I started too big. I have a clear idea what I want to work towards with the weapons console and since the actualy choice parameters are already clear I did the whole thing. I could send you my word-file which describes everything. Furthermore, it is not finished yet. 

This UI is a 4:3 interface. 

I think form is as important as function, since it is a game, which looks kind of bland at the moment.
This is not form over function, since the main options you can choose are very clear.

**Comment by sevcol** [comment]
I like the overall style of the UI! 
Altough it is a bridge simulator, it is also a game: besides accurately and effectively controlling your spaceship so you don't die, you also want to have some fun.

I like the frame around the borders and the corners, it gives a nice scifi feel without getting in your face too much. The large corners make it easy to add controlls like energy, hull etc. 

However, it is a bit bloated with useless stuff. Fancy stuff is nice, but if it stands out a lot but doesn't add any functionality, it's just a distraction. 
I would suggest starting with a minimal framing of the screen (but with the nice scifi themed elements), and then only adding the elements that you actually need.

The Missle-loading thingies on the side are also quite nice! However, I would suggest trying to integrate them in the sidebar, they get a little too much attention now. 
The wierd-looking hitbox could be solved by placing the button on top of a semi-shaded rectangle.

However, there is one big issue with this concept:
http://99villages.deviantart.com/art/Neon-Space-Rainmeter-2015-1-4-442236472
It's got a Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported license, of which the NoDerivs-part means:
NoDerivatives — If you remix, transform, or build upon the material, you may not distribute the modified material.

**Comment by Jhovall** [comment]
Yup, as vincent just pointed out, I read the licence wrong...
