### ISSUE TITLE
Send server shutdown when exiting to clients

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#59]
When the server is shutdown, the clients aren't told to disconnect/go back to menu screen.
This might be fixed by sending a server a message that the server is shutting down, and/or have the client disconnect after X number of seconds not receiving anything from server.

Something like this is especially needed with the autoconnect option in the options.ini file or via the command line/Windows shortcut.

**Comment by daid** [comment]
There is actually most code to handle this already. Disconnections are detected, but not always handled correctly yet.
Example, this code is disabled right now:
https://github.com/daid/EmptyEpsilon/blob/master/src/screens/mainScreen.cpp#L40

**Comment by kwadroke** [comment]
Looks like the send disconnect for clients is working. The client with autoconnect goes back to the waiting for server screen.
Not sure if I should open a new issue for the clients not wanting to auto-reconnect after the server has went away and came back. You have to exit EE completely on the server and restart it to have the autoconnect clients connect again. Server and client was tested on the same machine.

**Comment by daid** [comment]
Might take a while for clients to re-connect after an auto connect. If it takes longer then 30 seconds, then there is a bug there.

**Comment by kwadroke** [comment]
Looks like a bug. The autoconnect client looks like it's trying to connect, as it briefly changes from "Searching for server..." to (what I'm guessing is) connecting to server, and then back to Searching.
I ran it for several of minutes without the client re-establishing connection. When I shutdown & exit out of the server while the autoconnect client is still running, and then start EE again then create a server, the client autoreconnects fine.

**Comment by kwadroke** [comment]
Think I might have figured out the issue I am having. Looks like the connection to the server from the client is still in TIME_WAIT status. Which is causing the Server not to be able to use the same TCP Port when run on the same machine as the client. I only noticed this when I tried to run it as a headless server since the Game window wasn't covering my terminal.

output of _netstat -tapn_ when exiting the server 
```
tcp        0      0 10.0.2.15:35666         10.0.2.15:59745         TIME_WAIT   - 
```
Once the connection finally clears out, it will allow me to restart the server.

Most people will probably not notice this problem unless they run the server and the client on the same machine.

**Comment by kwadroke** [comment]
Just tested from Windows to Linux (VM): it auto-reconnects fine.

**Comment by daid** [comment]
The TIME_WAIT for server sockets is a annoying thing. It does solve itself after 2 minutes, and you can disable it on linux at a system level (but you shouldn't)

Normally you can hack around this by setting the SO_REUSEADDR flag on the listen socket, but SFML does not support this.

Problem is that EE does not handle this gracefully yet. As it should tell the user that it cannot start the server, instead of silently doing "nothing" and act like there is a server.

**Comment by daid** [comment]
Should be fixed in latest, clients properly disconnect, and you no longer need to close the server to change scenario.
