### ISSUE TITLE
Dedicated ship log

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#599]
This is not really an issue, more of a question.

It looks like there used to be a player station that was just the ship log. I know that Relay has the ship log at the bottom where you select it, it fills the screen with a scroll-able window of text, select it again and it goes back to the last line of the log at the bottom of the Relay screen.

I wonder if the ship log is still available as a dedicated screen - one where all it did was keep the ship log text in a scroll-able window, perhaps through a value you can set in autoconnect in options.ini. If it's not available (and I'm not seeing it, though I may just be missing it), how hard would it be to add or resurrect? I am particularly interested in a larger scroll-back buffer than what is currently available in Relay. I find that with longer missions, the older text is eventually truncated off the log. I know there needs to be an upper limit, I was just thinking the upper limit could be larger for the dedicated ship log if someone wants to use that.

**Comment by amir-arad** [comment]
technically it's easy. 
currently the cap is 100 entries. it is easy to change it in the code. question is, will it be merged
