### ISSUE TITLE
Input on script from server console

### ISSUE THREAD

**Issue by Jhovall** [daid/EmptyEpsilon#60]
Dear All,

For sevcol I am making a general mission which randomizes the placing of astroids, nebula's, jumpgates etc.  The script let's players travel from jumpgate to jumpgate. It basically destroys everything when a jumpgate is reached, teleports the player to a new location, spawns a jumpgate behind the players back and creates a whole new random scenario.

In between the travels (jumpgate to jumpgate) you would like to have event-scenario's. These need to be controlled by the GM screen, since the environment of the larp (a 'planet' or ship interior) needs to be set up and if the players are to quick with traveling you want to let them travel another random scenario.

What I thought was gaining keypresses from the GM-console and if the key is pressed and player go through a jumpgate the scenario will load, but this is obviously not supported. Does anybody have any Idea how the GM console could communicate with the Lua-script?. (Except for ugly work-arounds like letting the GM's spawn a ship on certain-far away coordinates if they would like to load a specific scenario?)

**Comment by kwadroke** [comment]
You could put conditions in your script. If they are met, you can load a new script. 

For instance if you have completed the mission in the current "area" and you go thru a wormhole and are near an object in the new area, load the new script.

Another way to handle it is that you could just not spawn the wormhole (or have its exit point not go anywhere) until the current mission is complete.

**Comment by Jhovall** [comment]
Thanks for the reply, but I guess you do not entirely understand what I need. (Maybe it is not clear)
Sevcol is a larp, so GM influence is necessary, both in EE and out of EE. Also a 'completion of a mission' is not something you can or want to hardcode.  If the players decide to leave without eliminating the enemy ship or the marines board and capture the enemy ship, instead of destroying the ship as expected, they should be allowed to. 

I want the GM's to decide which new (mission) area should be loaded. This decision should be made in the previous area, unconnected the previous area or any actions players do. 
If they don't decide, a random scenario/area will be loaded if the wormhole is entered by the players.

It is not an option not to spawn the wormhole, because that'd validate world-consistency.

**Comment by kwadroke** [comment]
Ok, I understand now. I don't believe there's a way to load a script from the GM screen yet. Of course daid can answer that better than I.

I am planning on doing a LARP of sorts (since basically EE and other bridgesim games are LARPs in the true-est sense) myself once I finished building my permanent bridge at home. It will be an all day mission (I hope) with mostly the same crew. I don't plan on running a GM screen as I want the script to load based off of events happening during the game with some randomness thrown in.

**Comment by Jhovall** [comment]
Hopefully Daid will read this and implement option then.

Well, If you want an idea how we do it, come to our larp :). Furthermore a GM with a  GM-Screen is better, especially in a long game. Since a game gets more interesting if there is somebody who actually responds to the players actions. (And you actually have someone to talk to).

**Comment by kwadroke** [comment]
If it wasn't so far away, I'd consider it. I'm from the US so I can't exactly drive there :)

**Comment by vslotman** [comment]
It would be ideal if we could let the GM-screen call a script-method at the press of a button, just like the update()-method is now called each game-update. 
Maybe reserve the method-names scriptMethodA till scriptMethodX for this functionality. Mission-scripts can than implement one or more of these methods. The GM screen needs some more buttons, and shouldn't crash if a method isn't implemented.

Another option might be sharing some global game-variable, but you would have to read that in the update-method of the script and then reset it if read. But I think that would be rather ugly.

**Comment by kwadroke** [comment]
Perhaps the built-in web server could be used for this. Create a local web page that submits a GET request for calling a function from the LUA script. That function could then load outside scripts.

**Comment by kwadroke** [comment]
Here's a hackish way to do it what i was talking about in the previous comment:
```
-- Name: Test
-- Description: Test script

function init()
	player=PlayerSpaceship():setFaction("Human Navy"):setShipTemplate("Player Cruiser"):setRotation(200)
end

function runscript(delta)
  local script = Script()
  script:run("test.lua")
end

function update(delta)
 if player:getDescription() == "test" then
  player:setDescription("") --Set to Blank to make sure it doesn't get run again
  runscript()
 end
	--No victory condition
end
```

Then from a browser go to this url: 
```
http://localhost:8080/set.lua?setDescription("test")
```


It will run the function runscript which you then can run whatever you put in that function or run another lua script as in this example

**Comment by Jhovall** [comment]
That... is a seriously ugly hack :). And possible if the other option will not be chosen. 

To be honest I prefer Vincent's method :P.

**Comment by daid** [comment]
I think the best solution, is to have the scenario define "GM functions" which call functions in the script. And add these functions as buttons on the GM screen.

On the script side, it can look like this:
```
function init()
    addGMFunction("Create something", function()
        SpaceStation():setTemplate('Small Station'):setFaction("Human Navy"):setPosition(500, 500)
    end)
    addGMFunction("Create more", otherFunction)
end

function otherFunction()
    SpaceStation():setTemplate('Small Station'):setFaction("Human Navy"):setPosition(500, 500)
end
```

The C++ code has "callback" functions from C++ code to scripts. But currently this is only supported on "game objects", not globally. And if you look at the SeriousProton/src/scriptInterfaceMagic.h "setcallbackFunction", you can see that there is quite some complexity in these bindings. So I'll have to think a bit on how to implement this.

**Comment by Jhovall** [comment]
Okay, Nice and thanks!
How to implement it in my Lua script? (I can also try at home, but asking it is easier than 30mins of trying).

**Comment by daid** [comment]
The above proposal I gave should work.
I tested it with:
```
    addGMFunction("Test", function()
        CpuShip():setShipTemplate("Transport5x5"):setFaction("Human Navy"):setRotation(90):setPosition(2500, 4000):orderIdle():setCallSign("T-5-5"):setScanned(true)
    end)
```
At the end of the init of the empty scenario.

**Comment by Jhovall** [comment]
Awesome.

**Comment by daid** [comment]
(You do need a new build, as the download on emptyepsilon.org isn't updated yet)

**Comment by Jhovall** [comment]
Hey,

Thanks, and now I have another idea. Could it also be possible that a keypress from a console could be determined in the script?

**Comment by daid** [comment]
Nope, keypresses happen client side, while the script runs server side. I'm not going to send all key presses to the server.

**Comment by Jhovall** [comment]
That is too bad, (and why not, it is possible in artemis and a lot of other data is send towards the server, why not keypresses?).
It would lead to more possibilities for scenario's in which you can send data, add small-minigames to enter a wormhole, etc.

**Comment by daid** [comment]
Because instead of keypresses, it would be better to have something less "low level". Like, script requests text input from a certain console, and then gets a call back when the text is entered.

**Comment by Jhovall** [comment]
Well, that is essentially for me the same, but I understand the difference.

**Comment by Jhovall** [comment]
I found a minor annoyance with the function.
When you select a NPC ship, the behavior overlays the GM buttons and you can not select the GM button anymore.
