### ISSUE TITLE
Impulse problem when far far away

### ISSUE THREAD

**Issue by tdelc** [daid/EmptyEpsilon#604]
When the position of a ship is far far away from the center, the impulse doesn't work.

For example : impulse speed 10 ; x = -3000000 ; y = - 4000000

(ok, it is a bit far, but it is good for a 2-3 days LARP ^^)

**Comment by daid** [comment]
Most likely the Box2D physics engine is running into precision errors then, that's the only thing I can think off. As that's pretty deep in the core for quite an edge case, I don't think this will ever be fixed.

**Comment by amir-arad** [comment]
@tdelc I can suggest a workaround : reduce the effectiveness of warps and jumps in your game so that your "long distance" is not that long

**Comment by tdelc** [comment]
Thanks for the comments and advice, I will be something like that @amir-arad for my next larp in two weeks, and i will try to get a solution after that (maybe by updating frequently the reference 0,0 : players will not see the difference and EE will not have to guess with such numbers).
