### ISSUE TITLE
[Feature Request] Get speeds of player ships for LUA scripts

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#61]
Allow LUA scripts to be able to access Impulse and Warp Speeds of player ships. 
This way the scripts can tell if you are moving and how fast.

Example 1: if you are going at impulse through a particular nebula (but not stopped or at warp), gain energy quicker (or take hull/shield damage).
Example 2:  if the script sees that the player ship isn't moving for X amount of minutes/seconds, spawn an enemy ship not too far away (in the same sector) to attack.

Would be nice if the these speeds are accessible through the web server as well.

**Comment by daid** [comment]
You can get an velocity already:
```
local x, y = ship:getVelocity()
local velocity = math.sqrt((x * x) + (y * y))
```

**Comment by kwadroke** [comment]
Ok, I suppose that's one way to do it. :)
