### ISSUE TITLE
Latest Android client not connecting to Server

### ISSUE THREAD

**Issue by lunerfox** [daid/EmptyEpsilon#62]
Downloaded the latest versions of Empty Epsilon on both Win32 (Version 20151116) and Android (Version 20151113); Installed both and tested that the Win32 Server is able to connect to other Win32 Clients on the same network.

Android version does not appear to auto-discover the server, nor does it allow me to manually put in an IP address when the text field is pressed.

The first issue might simply be due to version mismatch; Note that the filename for the android apk is EmptyEpsilon-2015.11.16-android.apk, but the version number is the same as EmptyEpsilon-2015.11.13-android.apk.

**Comment by lunerfox** [comment]
Newest version (20151209) fixes the issue with version mismatch causing games to not show up. Thanks!

**Comment by daid** [comment]
But now the radar views no longer work on my phone. No idea if it's a general problem or just a problem of my Android device.

**Comment by lunerfox** [comment]
Radar views (Relay and Science) still works on mine. Using Samsung Galaxy S4.

**Comment by kwadroke** [comment]
Science & Relay flickers on my Samsung Note 3. Science works fine on my VisualLand tablet, Relay is missing some details but mostly everything is there.
