### ISSUE TITLE
Usability Request: Place insertion point in password field when requesting password.

### ISSUE THREAD

**Issue by pixelclef** [daid/EmptyEpsilon#626]
Makes it smooth to enter a password.

**Comment by JonathanILevi** [comment]
What do you mean by "insertion point"?

**Comment by pixelclef** [comment]
The vertical flash i-beam that indicates where you can type text.

Without doing this, a click is required in the field, then the password must be typed.

**Comment by jandermannderkann** [comment]
So? We can close this issue right?
