### ISSUE TITLE
Display Enhancement: show the password in upper and lower case as entered

### ISSUE THREAD

**Issue by pixelclef** [daid/EmptyEpsilon#628]
There's a noticeable mental disconnection between typing:
`password`
and seeing
`PASSWORD`

... especially when the password check is case sensitive!

**Comment by amir-arad** [comment]
IMO the font in the entire game is rendered as uppercase. suggest a new font?

**Comment by JonathanILevi** [comment]
Is a reasonable solution to just make passwords not case sensitive?
@daid

**Comment by pixelclef** [comment]
> IMO the font in the entire game is rendered as uppercase. suggest a new font?

Understanding the typographical intent, I would recommend Eurostile. Close alternative would be Eurocine.

**Comment by daid** [comment]
I kinda like the font, even tough it's all caps all the time. Note that the font was changed by someone else as a pull request, by someone who did the whole styling. So making the password case-insensitive would be a 'better' solution.

**Comment by JonathanILevi** [comment]
This issue should be fixed?
