### ISSUE TITLE
Script: Using getHull() on stations returns nil

### ISSUE THREAD

**Issue by lunerfox** [daid/EmptyEpsilon#63]
Working on a scenario where I wanted to trigger a message when a station's Hull is below a certain threshold.

```lua
--Orion 5 should tell you about the escaped scientist before being destroyed.
if Orion_5_stn:getHull() < 15 then
	print ("Orion 5 distruction is immedient. Hull at Orion_5_stn:getHull().)
end
```

Console prints this error message when function is called:
```lua
[ERROR] LUA: update: [string "scenario1.lua"]:390: attempt to call a nil value (method 'getHull')
```

**Comment by daid** [comment]
https://github.com/daid/EmptyEpsilon/commit/5e91de53bd10eb27d77790c45ffc140556cfd9d7
