### ISSUE TITLE
make fails on class sf::Shader

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#630]
Scanning dependencies of target EmptyEpsilon
[  0%] Building CXX object CMakeFiles/EmptyEpsilon.dir/src/main.cpp.o
[  0%] Building CXX object CMakeFiles/EmptyEpsilon.dir/src/threatLevelEstimate.cpp.o
[  1%] Building CXX object CMakeFiles/EmptyEpsilon.dir/src/preferenceManager.cpp.o
[  1%] Building CXX object CMakeFiles/EmptyEpsilon.dir/src/pathPlanner.cpp.o
[  1%] Building CXX object CMakeFiles/EmptyEpsilon.dir/src/epsilonServer.cpp.o
[  2%] Building CXX object CMakeFiles/EmptyEpsilon.dir/src/particleEffect.cpp.o
/home/ubuntu/emptyepsilon/EmptyEpsilon/src/particleEffect.cpp: In static member function ‘static void ParticleEngine::render()’:
/home/ubuntu/emptyepsilon/EmptyEpsilon/src/particleEffect.cpp:12:50: error: ‘class sf::Shader’ has no member named ‘setUniform’
     ShaderManager::getShader("billboardShader")->setUniform("textureMap", *textureManager.getTexture("particle.png"));
                                                  ^
CMakeFiles/EmptyEpsilon.dir/build.make:182: recipe for target 'CMakeFiles/EmptyEpsilon.dir/src/particleEffect.cpp.o' failed
make[2]: *** [CMakeFiles/EmptyEpsilon.dir/src/particleEffect.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/EmptyEpsilon.dir/all' failed
make[1]: *** [CMakeFiles/EmptyEpsilon.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
[  1%] Building CXX object CMakeFiles/EmptyEpsilon.dir/src/particleEffect.cpp.o
/home/ubuntu/emptyepsilon/EmptyEpsilon/src/particleEffect.cpp: In static member function ‘static void ParticleEngine::render()’:
/home/ubuntu/emptyepsilon/EmptyEpsilon/src/particleEffect.cpp:12:50: error: ‘class sf::Shader’ has no member named ‘setUniform’
     ShaderManager::getShader("billboardShader")->setUniform("textureMap", *textureManager.getTexture("particle.png"));
                                                  ^
CMakeFiles/EmptyEpsilon.dir/build.make:182: recipe for target 'CMakeFiles/EmptyEpsilon.dir/src/particleEffect.cpp.o' failed
make[2]: *** [CMakeFiles/EmptyEpsilon.dir/src/particleEffect.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/EmptyEpsilon.dir/all' failed
make[1]: *** [CMakeFiles/EmptyEpsilon.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Xansta** [comment]
The above is the last bit showing the error message. This is the script I run on my AWS instance under Linux to get this stuff running. It's worked for several weeks now, but suddenly this morning has the above error.

#!/bin/bash
buildYear="2019"
buildMonth="01"
buildDay="19"
while getopts "h:y:m:d:" opt; do
	case $opt in
		h) echo "Optionally specify (y)ear, (m)onth and/or (d)ate of build\nExample: $0 -y2018\nScript assumes $buildYear-$buildMonth-$buildDay"
		;;
		y) buildYear="$OPTARG"
		;;
		m) buildMonth="$OPTARG"
		;;
		d) buildDay="$OPTARG"
		;;
		\?) echo "Invalid option -$OPTARG" >&2
		;;
	esac
done
sudo apt-get update
yes Y | sudo apt-get install xvfb
yes Y | sudo apt-get install git build-essential libx11-dev cmake libxrandr-dev mesa-common-dev libglu1-mesa-dev libudev-dev libglew-dev libjpeg-dev libfreetype6-dev libopenal-dev libsndfile1-dev libxcb1-dev libxcb-image0-dev
yes Y | sudo apt-get install libsfml-dev
mkdir emptyepsilon && cd emptyepsilon
git clone https://github.com/daid/SeriousProton.git
git clone https://github.com/daid/EmptyEpsilon.git
cd EmptyEpsilon && mkdir _build && cd _build
cmake .. -DSERIOUS_PROTON_DIR=$PWD/../../SeriousProton/ -DCPACK_PACKAGE_VERSION_MAJOR=$buildYear -DCPACK_PACKAGE_VERSION_MINOR=$buildMonth -DCPACK_PACKAGE_VERSION_PATCH=$buildDay
make
sudo make install
cd ..

**Comment by olivier-vm** [comment]
Concerning:
`error: ‘class sf::Shader’ has no member named ‘setUniform’`
This appears because of recent commit 4th feb: pull request #623 
This was modified because of an old deprecated function, replaced by a new one:
setParameter ->setUniform
See also doc: https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Shader.php

Double check you've got a recent version of SFML supporting this new function.
FYI, mine is 2.4.2 and last version is 2.5.1

**Comment by Xansta** [comment]
Ubuntu has 2.3.2. Looks like I need to force update to 2.5.1 as part of my initialization

**Comment by daid** [comment]
setUniform was deprecated in SFML 2.4, so you need 2.4 as minimum now. This was released a few years ago, so it's not like this change suddenly depends on bleeding edge. Gave people ample time to roll out updates.
And Ubuntu has 2.4 or newer from in Ubuntu Bionic or newer. Ubuntu Xenial has 2.3.
https://packages.ubuntu.com/search?keywords=sfml&searchon=names&suite=cosmic&section=all
