### ISSUE TITLE
Unable to see parts Helm and Weapons screen when resized

### ISSUE THREAD

**Issue by kwadroke** [daid/EmptyEpsilon#64]
When you resize the client window for Helm and Weapons and resize it where it is taller than it is wide, the top of center part of the screen stays with top of the window. The rest of the screen is centered.
The taller it is, the more noticeable it becomes.

Problem exists in Windows and Linux.

I'm guessing this is due to the new way the screen is drawn. 

Steps to reproduce: Make the game run in Windowed mode. Run as a client. Select Helm and/or weapons. Resize the window so it is taller than it is wide.

**Comment by kwadroke** [comment]
Looks like f59e6fe fixed it. Closing

**Comment by daid** [comment]
While that did fix it, I do see some graphical artifacts when this condition is met now. But better some artifacts then no radar at all :-)
