### ISSUE TITLE
[New feature] Virtual Reality for window screen ?

### ISSUE THREAD

**Issue by tdelc** [daid/EmptyEpsilon#642]
Hi,

I succed to create a window screen for any probe launched by a ship (in order to have a visual contact in long distance). But now, I would like to use android version of EE to obtain a VR window screen with a google cardboard. During the game, a player could wear the google cardboard and explore some space area in safe (because the camera will be on the probe and not in the ship).

I readed that OpenGL support VR capacity but I don't know how to begin with that. Does someone already develop VR in OpenGL and could give me some advice to develop this feature for EE ?

**Comment by daid** [comment]
While the feature would be cool, I don't think you will have much luck to get this to work.

EE uses SFML, and SFML uses OpenGL ES 1.1. Which is incompatible with the 3D rendering of EE. And that's why on Android you cannot use the main screen.

**Comment by tdelc** [comment]
Thanks for the comment. I didn't notice these features incompatibility.
But if EE uses SFML, and SFML uses OpenGL ES 1.1 and if OpenGL ES 1.1 is incompatible for the 3D rendering of EE, how the 3D rendering is done ? (out of curiosity)

**Comment by daid** [comment]
https://github.com/daid/EmptyEpsilon/blob/master/src/screenComponents/viewport3d.cpp
It uses a combination of old school OpenGL 1 with OpenGL 2.0 stuff like shaders.

**Comment by tdelc** [comment]
Ah ok, I don't really understand the differences between these versions, but at least now I know.
Thanks.

**Comment by daid** [comment]
OpenGL ES 1 is a (mostly) subset of Desktop OpenGL 1, very limited in functionality.
OpenGL ES 2 is a (mostly) subset of Desktop OpenGL 2, and not compatible with OpenGL ES 1. So you use ES 1 or ES 2, you cannot mix them.

Desktop OpenGL 1 and OpenGL 2 can be mixed without problems. And that's what EE is doing.

With SFML using OpenGL ES 1 on Android. There is no way to use OpenGL ES 2 functions in EE. And those functions are needed for the current rendering. And will also be needed for VR rendering.
