### ISSUE TITLE
[BUG] Render of atmosphere texture and color

### ISSUE THREAD

**Issue by tdelc** [daid/EmptyEpsilon#651]
In the scenario Empty Space, the sun can appear on the server main screen, but not in the client main screen. I didn't see where a member replication could be added.

![image](https://user-images.githubusercontent.com/13868149/58822305-7b367300-8637-11e9-89c1-d72449e742b0.png)

![image](https://user-images.githubusercontent.com/13868149/58822325-85587180-8637-11e9-8605-61abfb335fd2.png)

**Comment by daid** [comment]
The size wasn't replicated.
