### ISSUE TITLE
Backwards Docking

### ISSUE THREAD

**Issue by JonathanILevi** [daid/EmptyEpsilon#658]
Currently to be docked the ship merely has to be within a curtain distance of the station, despite the fact the the docking procedure turns you backwards.  I think this is unintuitive and quirky.

I would like to make it so that you are not fully docked until the docking procedure is complete (you are close enough *and* pointing away from the station).

Another benefit of having the docking only happen after you have faced away is that it gives room for a Helm Officer to get better by finding ways of getting this ship flipped quickly (e.g. jump to far side rather than the close, or timely boosting maneuvering).

What are your thoughts on this?

**Comment by daid** [comment]
Well, docking is done when the ship actually touches the station, for 95% of the cases, people don't notice this quirk and think the ship needs to turn around first to dock. You're the first to notice otherwise :-)
My crew was always looking into how to dock as fast as possible by minimizing backwards movement and rotation.

**Comment by JonathanILevi** [comment]
I didn't think it was really an intentional quirk.  It was rather frustrating when I discovered you only have to be touching.  I did not actually discover it, I think I realized when I was with a Helm Officer that did it.  

On the USN it is very known and causes weaker ingaugement and causes undesirable separation of new players.

How your groups try to minimize backward movement is precisely how it should be but it is hard when you know it doesn't work like that.

**Comment by JonathanILevi** [comment]
Oh, I just made a fix for it and was about to submit a pull-request when I see you already fixed it.  Nice.

**Comment by daid** [comment]
Well, it was intentional lazyness on my side, so that's why I fixed it, as now people apparently abuse that and that's not intentional.

**Comment by czenker** [comment]
I have to admit I'm one of the pilots who crash into stations on Warp 4 and hit the dock button. :D
