### ISSUE TITLE
Function to check if the player is already engaged in a dialogue

### ISSUE THREAD

**Issue by lunerfox** [daid/EmptyEpsilon#68]
Noticed that the Relay station will miss messages sent if it is currently displaying another message.

Not sure if a stack implementation will be used in the future (or whether it's the best idea), but perhaps a useful thing to add at this point would be to expose a variable for whether the the player ship is currently engaged in a dialogue? This would allow a script to ensure messages are seen.

```
if <conditions for triggering comm> and not player:isRelayBusy() then
   ...
end
```

Additionally, a bit exposing whether the relay station accepted or ignored the last call would also be useful:

```
if player:isRelayLastCallAccepted() then
   <Storyline 1>
else
   <Storyline 2>
end
```

**Comment by daid** [comment]
Actually, the "sendCommsMessage" will return false if it cannot send the message due to comms being blocked.

**Comment by lunerfox** [comment]
Works for me! Thanks for the heads up.

**Comment by daid** [comment]
Note that it `sendCommsMessage` still add the message to the log of comms. A new function `sendCommsMessageNoLog` has been added to prevent that log message, and should solve most usecases.
