### ISSUE TITLE
ShipTemplateBasedObject:onTakingDamage() callback broken

### ISSUE THREAD

**Issue by Triqueon** [daid/EmptyEpsilon#690]
When I try to register an onTakingDamage callback, I get an error message
`[ERROR] LUA: init: [string "scenario_00_dmg.lua"]:4: ??[convert<ScriptSimpleCallback>::param] Upvalue 1 of function is not a table...
`

Minimal example:
```
function init()

  player = PlayerSpaceship():setTemplate("MP52 Hornet")
  player:onTakingDamage(function() end)
end
```

The error message comes from SeriousProton, but since the other callbacks that use ScriptSimpleCallbacks work just fine, I'm not sure that it's an issue with SeriousProton. Sadly, my competence with templates and LUA is not sufficient to follow the control flow to find the cause myself.

**Comment by daid** [comment]
This issue happens when the callback does not reference any globals in lua. If you would do ```print(player)``` in the function it will most likely work.
