### ISSUE TITLE
EE For Raspberry Pi 4

### ISSUE THREAD

**Issue by nallath** [daid/EmptyEpsilon#692]
I vaguely remember that EE had some issues running on a Raspberry Pi 3 (?). But now that the Pi 4 is out, which is quite a lot beefier than the 3, I was wondering if anyone tried if that would run?

I'm looking to get a semi-permanent setup for EE, so being able to run all of it on PI-4's would make it a whole lot cheaper (since a single computer that can run it would be about 150 euro, so a PI 4 is easily twice as cheap).

**Comment by daid** [comment]
As the Pi4 has a beefier GPU then the Pi3/Pi2 (which had the same GPU) I would expect it to run better then the Pi2/3 (which ran it, but not at the performance you would want)

The Pi4 can also PXE boot without SD card:
https://www.raspberrypi.org/documentation/hardware/raspberrypi/booteeprom.md

Removing costs and failures for SD cards.

**Comment by aBlueShadow** [comment]
Though I don't know the performance nallath would want,  in my opinion it runs decently on Pi2/3 as long as you don't use the 3d screens. 
The Pi4 however seems to be the first PI that even  can run the mainscreen, allthough with a relativley low FPS. There is a video on youtube of an EE test with a Pi4.

**Comment by daid** [comment]
https://www.youtube.com/watch?v=KjDuZpA5W9g

**Comment by nallath** [comment]
Yeah, I know about the laptops, but those are a bit flaky. I need to run a 14 seat setup (12 stations & 2x GM), so it kinda adds up. Since it's also at a LARP event, I also really cant afford to have hardware breaking down in the middle (or well, one or two would be fine I guess, but it's something I'd want to prevent) 

Performance-wise, I just need them to run smooth-ish (eg; 30+ fps). It's mostly the stations that make things expensive (because right now I'm looking at having to buy 8 computers+, which is going to put a heavy strain on the budget, which i'd much rather spend on other stuff). 

But by the looks of it, those PI 4's run it just fine, so that's going to knock off a seizable chunk of the cost.

**Comment by nallath** [comment]
The prices on those thin clients vary quite a bit, so it depends. But good call, I hadn't considered using those. Thanks for the advice :)

**Comment by nallath** [comment]
Right now I've just budgeted for a slew of PI's, since I know those work. So depending if I can find those HP units, i might save a bit more which can then be spent on spiffy upgrades (DMX, dashboards, that kinda stuff)

**Comment by daid** [comment]
Note, you are better of spending some money on good power supplies, then getting the larger memory versions, as EE isn't that memory hungry (especially if you don't do any main screen stuff, and thus 3D model textures do not get loaded)

**Comment by kurthuwig** [comment]
I've compiled it and it works fine on my Raspberry Pi 4. You can download the Raspbian deb packages here:

https://www.huwig.de/en/de/2022/09/11/emptyepsilon-for-raspberry-pi/
