### ISSUE TITLE
emptyepsilon.log for linux

### ISSUE THREAD

**Issue by gwaland** [daid/EmptyEpsilon#696]
I'm working on a netboot version of EmptyEpsilon but I'm trying to save a game log out to /tmp/ while I troubleshoot my DMX configuration for the main screen.  I can't quite see where the log is opened for linux in the code so I'm not sure how to enable it.   The only place I saw this was in the setlogfile for windows.   

Could you point me in the right direction for enabling logging on linux in general and I'll try to work out the netboot unique portions

**Comment by daid** [comment]
If I remember right, logging on linux is done to stderr, so a simple redirect should work then.
```
./EmptyEpsilon 2> /tmp/logfile.txt
```

The reason it's not send to stderr on windows, is that writting to stderr blocks after a while on windows if buffers are full and there is no terminal attached. Yes... windows...

**Comment by nallath** [comment]
I was wondering why there was code to ensured that a logfile would only be written on windows. Wont it just be better to make this generic (eg; if the build is debug, write the logging to EmptyEpsilon.log?)

**Comment by daid** [comment]
Actually, it goes to stderr on debug on windows as well (as that has a terminal)
https://github.com/daid/EmptyEpsilon/blob/master/src/main.cpp#L98

I just like seeing the log in my terminal.

**Comment by daid** [comment]
Oh, and as the netboot enviroment is using systemd and xorg. The log is most likely in the systemd journal, or in /tmp/x.log
https://github.com/daid/EmptyEpsilon/blob/master/netboot/build_netboot_system.sh#L174
