### ISSUE TITLE
Feature wish: Differentiated Warp Jammer Circle

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#704]
Could the circle that marks the edge of the warp jammer range be a different color than the other circles that mark the radar ranges in the Science display? This suggestion came from a relatively new player on Empty Epsilon. It sounds reasonable to me. It also sounds relatively easy to implement. I'm open to ideas of other ways to distinguish the warp jammer circle from the range circles.

**Comment by daid** [comment]
Would be a easy change, but what would you confuse them with in the current color? I think it is the only thing drawing a circle this big...

**Comment by Xansta** [comment]
The player was confusing the existing range circles (5, 10, 15, 20, 25 units) with the warp jammer circle. The warp jammer range was fairly large.

**Comment by daid** [comment]
But those have a different point of origin? I understand that the warp jammers are not the clearest feature of the game. But I'm not sure if changing the color would fix the problem...

**Comment by Xansta** [comment]
I agree that they have a different point of origin. I don't have a problem telling them apart. However, I've been playing this game for a while. I'm just reporting what a new user is seeing. It's not a significant problem in my opinion, but anything that shortens the learning curve is probably good. 

In the user's post, they also complain that they can no longer see the border of the warp jammer, either when they get to a particular zoom level or when the jammer is outside of sensor range. This seems like perfectly reasonable behavior to me. I think the limiting of information in certain circumstances lends verisimilitude to the experience. I don't suggest that that screen display behavior change.

**Comment by daid** [comment]
That the circles don't render when the center is out of range is intentional. This can be fixed, but I thought it makes sense that if you cannot see the device itself, you don't know the range. It's not like you are sensing the jamming area, you are sensing the jammer itself, and plotting the jamming range from that.
