### ISSUE TITLE
Docking as a player carrier is broken

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#711]
**Version**

Reproduced in 20191101 and a master-branch build on Windows 10.

**Steps to reproduce**

1. Launch a scenario
2. Add a carrier (ie. Benedict or Kiriya classes) as a player ship
3. Join the Helms station of the carrier

**Expected behavior**

With no ships nearby, the "Request Dock" button should be disabled on the player carrier's Helms station.

With a station, ship, or other object that can be a docking target nearby, the "Request Dock" button should be enabled, and when clicked the player carrier should dock with that station/etc.

**Observed behavior**

The "Request Dock" button is always enabled on the player carrier's Helms station. When clicked, the player carrier goes on autopilot, turns to heading 90.0, and sets impulse to -100%. This continues indefinitely until "Cancel Docking" is clicked.

It feels a bit like EE thinks there's always a dockable ship (itself) in range, and "Request Dock" attempts to dock with itself.

**User issues**

Player-controlled carrier ships can't dock with stations to rearm, regain energy, or complete objectives that require it.

**Comment by daid** [comment]
I think i fixed this. Did it directly on my phone on github. So did not test it yet.

**Comment by oznogon** [comment]
@daid LGTM, the Benedict no longer tries to self-dock and docks properly with a station. Thanks!
