### ISSUE TITLE
Asteroid():setSize don't work

### ISSUE THREAD

**Issue by aBlueShadow** [daid/EmptyEpsilon#729]
Asteroid():setSize does not seem to work.

Test code:

```
    a1=Asteroid():setPosition(800,500):setSize(700)
    a2=Asteroid():setPosition(800,-500):setSize(7)
```
Both asteroids seem to have a similar visual size and collision radius.

**Comment by daid** [comment]
That code indeed doesn't look functional. I think I fixed it now.

**Comment by aBlueShadow** [comment]
Yep that works now. Might also be helpful for asteroid mining, like breaking smaller chunks off a bigger asteroid. OTOH, rocks bigger than the ship exploding on contact will probably feel silly. But nevertheless a variation of sizes is a good thing to have.

**Comment by daid** [comment]
If you do not want an asteroid to explode on contact, you could use the artifact object i think.

**Comment by aBlueShadow** [comment]
Yeah I know, and did something like that in an own script. Thing is that you can't. scale them. Although it might be sufficient to do a bunch of pre-scaled models in a loop. 

Actually, the reason why I stumbled upon this issue, was that I am currently preparing the models of SolCommand's asteroid pack for EE,as the origin points are all over the place. 
https://www.solcommand.com/2012/12/low-poly-asteroids.html
I am planning to do a PR to include them, as they work better on big sizes than the stock asteroids. (the sample picture is somewhat misleading, and shows only one of 15 models) Although I am not yet sure if that PR should replace the current asteroids add new models to use for use as artifacts, or maybe both.
