### ISSUE TITLE
Bug: objects get deleted as soon as I unpause the game

### ISSUE THREAD

**Issue by Piglit** [daid/EmptyEpsilon#733]
Hi,

When I use those lines in a scenario script, all three objects get deleted, as soon as I unpause the game. (when there are more objects, some other get deleted as well; but this seems to be a minimal working example)

```
CpuShip():setTemplate("MT52 Hornet"):setFaction("Kraylor"):setPosition(2000,2000)
CpuShip():setTemplate("MT52 Hornet"):setFaction("Human Navy"):setPosition(-1000, -1000):orderDefendLocation(0,0)
SpaceStation():setTemplate("Small Station"):setPosition(0, 0)
```

I can not find the any reasonable cause, even the log-file does not say anything valuable. Do you have any idea?

I'm running the game under Win10; EE-Version: 2020.01.15, but the bug occured also in an older fork.

I attacked my scenario file containing the upper content.

Thank you,
Pithlit

[scenario_00_buggy.lua.txt](https://github.com/daid/EmptyEpsilon/files/4093157/scenario_00_buggy.lua.txt)

**Comment by oznogon** [comment]
Also reproducible running Windows builds via Wine.

If I unpause the scenario with one of the ships selected, the infoblock for it reports a position of NAN,NAN

<img width="336" alt="Screen Shot 2020-01-21 at 5 25 12 PM" src="https://user-images.githubusercontent.com/19192104/72857646-16d22d80-3c73-11ea-805b-e3c4f3c45c8c.png">

If I create a `logs` directory for game logging, the JSON output confirms NaN:

```
{
   "type": "state",
   "time": 0,
   "new_static": [],
   "del_static": [],
   "objects": [
      {
         "type": "CpuShip",
         "id": 4,
         "position": [
            2000,
            2000
         ],
         "rotation": 145.71717834472656,
         "callsign": "CV1",
         "faction": "Kraylor",
         "ship_type": "MT52 Hornet",
         "energy_level": 1000,
         "hull": 30,
         "target": 5,
         "shield_frequency": 13,
         "shields": [
            20
         ],
         "systems": {
            "Reactor": {
               "health": 1,
               "power_level": 1,
               "power_request": 1,
               "heat": 0,
               "coolant_level": 0,
               "coolant_request": 0
            },
            "Beam Weapons": {
               "health": 1,
               "power_level": 1,
               "power_request": 1,
               "heat": 0,
               "coolant_level": 0,
               "coolant_request": 0
            },
            "Maneuvering": {
               "health": 1,
               "power_level": 1,
               "power_request": 1,
               "heat": 0,
               "coolant_level": 0,
               "coolant_request": 0
            },
            "Impulse Engines": {
               "health": 1,
               "power_level": 1,
               "power_request": 1,
               "heat": 0,
               "coolant_level": 0,
               "coolant_request": 0
            },
            "Front Shield Generator": {
               "health": 1,
               "power_level": 1,
               "power_request": 1,
               "heat": 0,
               "coolant_level": 0,
               "coolant_request": 0
            }
         },
         "input": {
            "rotation": NaN,
            "impulse": NaN
         },
         "output": {
            "impulse": 0
         },
         "config": {
            "turn_speed": 30,
            "impulse_speed": 120,
            "impulse_acceleration": 25,
            "hull": 30,
            "shields": [
               20
            ],
            "beams": [
               {
                  "arc": 30,
                  "direction": 0,
                  "range": 700,
                  "turret_arc": 0,
                  "turret_direction": 0,
                  "damage": 2,
                  "cycle_time": 4
               }
            ]
         },
         "beam_frequency": 11
      }
...
```

Note that the rotation and impulse inputs are NaN — not the position, properties, or output — at time 0.

```
...
         "position": [
            2000,
            2000
         ],
         "rotation": 145.71717834472656,
...
         "input": {
            "rotation": NaN,
            "impulse": NaN
         },
         "output": {
            "impulse": 0
         },
...
```

*Failure states*

If I spawn a player ship into the scenario, it also winds up at NaN,NaN after unpausing. Its heading is NaN and its speed is NaN.

If I change setPosition() coordinates to 1,1 or 1000,1000, ships still go to NaN.

If I move the `order` to the Kraylor Hornet, ships still go to NaN.

*Non-failure states*

If I remove the `orderDefendLocation(0,0)` order from the Human Navy Hornet, everything works fine.

**Comment by oznogon** [comment]
Might be pathing related, somehow. I recreated the scenario from scratch, line by line, and everything works until I add the SpaceStation at 0,0, at which point it crashes.

Then it looks related to memory addressing, because one of two things happen if I change the SpaceStation getPosition coords to something else (like 10000,10000):

- If I back out of the scenario on the server, return to Scenario Selection, and restart the scenario, the SpaceStation is at 10000,10000 but the same "everything goes to NaN" result happens upon unpause.
- If I quit EE, restart it, and launch the scenario, the SpaceStation is at 10000,10000 and everything works fine.

**Comment by daid** [comment]
Without testing, just looking at the code. I think it is the `vector2ToAngle` function returning NaN on a 0,0 position.

**Comment by aBlueShadow** [comment]
The problem also occurs if no position is on 0,0. For example, if the space station is at 1,1 and the defend location is at 1000,1000, all objects still get deleted when you unpause. You have to move the defend location quite a bit away to make it to work.
From the original example, if you move the defend location to 0,9033, everything works, but on 0,9032 they got deleted. That does not seem like a special number for me, but maybe that threshold is a hint.

**Comment by daid** [comment]
And some more checking shows that vector2ToAngle shouldn't return NaN on a 0,0 position. So something else is going wrong. I'll see if I can enable exceptions on NaN calculations, that at least should point to the location where the problem is.

**Comment by aBlueShadow** [comment]
interestingly, that 9032/9033 threshold is on both axes, but not in the negative direction. There it is -50**32**/-50**33**.
wich is quite weird, why should the game care about similar decimal digits, or is it just coincidence?

**Comment by daid** [comment]
I think it's just a coincidence, and more likely has to do with some math going crazy or uninitialized memory.
I think this patch: https://github.com/daid/SeriousProton/commit/7e3a0b4058268b511bf2b20abe7e55354cf666de
Will catch the point where it happens and crash instead of letting it propagate into the object positions. But I'm not at a position where I can test right now.

**Comment by aBlueShadow** [comment]
Yep, now it crashes with a floating point exception, but without further information. It happens right after clicking on "Start scenario".

Output:
```
[INFO]  Load script: scenario_01_basic-test.lua
[INFO]  Opened game state log: logs/game_log_22-01-2020_19.28.19.txt
[INFO]  Loaded: gui/icons/station-helm with 0 sprites
[INFO]  Loaded: gui/icons/station-weapons with 0 sprites
[INFO]  Loaded: gui/icons/station-engineering with 0 sprites
[INFO]  Loaded: gui/icons/station-science with 0 sprites
[INFO]  Loaded: gui/icons/station-relay with 0 sprites
[INFO]  Loaded: gui/ButtonBackground.disabled with 0 sprites
Floating point exception
```

**Comment by daid** [comment]
I guess that is with the linux version? As the windows version crashes as soon as it opens audio ;-)

**Comment by aBlueShadow** [comment]
Oh, interesting :-) Yes, it's the linux version.

**Comment by daid** [comment]
Ok. Found the bug. `firstAvoidQ` is 0,0 in the path planner. Simply put, the math that tries to find a path around the station fails, giving "no direction" to avoid around the station. Causing a division by zero, and then NaN.
Pretty much an numerical oddity that can only happen in these very specific conditions, as soon as any object slightly moves off the straight line, the code works again.

**Comment by oznogon** [comment]
7b9eef5 worked for me in a brief test with the original buggy scenario
