### ISSUE TITLE
Warp causes distorted viewport in windowed mode

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#734]
Windows 10 10.0.18363
nVidia GTX 1050 (driver 417.22 and 441.87)
EE 2020.01.15

### Steps to reproduce

1. Open a server instance in windowed mode (`EmptyEpsilon.exe fullscreen=0` or via options.ini)
1. Open a second client instance, also in windowed mode
1. On the server instance, start any scenario with a playerspaceship equipped with a warp drive and select the main screen view
1. Connect the client instance to the server and select the player ship helm station
1. Enter warp

### Expected behavior

Warp effects are applied to the viewport, but the viewport for the most part remains visible.

Windowed and full-screen views function the same.

### Observed behavior

The viewport within the window shifts and/or rescales while warp is active, typically up and to the left with part of the right side of the viewport cut off, leaving wide black edges. The main screen viewport also stops rendering 3D and turns black.

The unexpected distortion ends upon exiting warp.

In warp, with the viewports shifted:

![warp](https://user-images.githubusercontent.com/19192104/72972055-92b99c00-3d7f-11ea-86c8-0e7ef4cda53c.png)

As soon as we exit warp, with the viewports restored:

![nonwarp](https://user-images.githubusercontent.com/19192104/72972054-92b99c00-3d7f-11ea-8f96-8f4abdda9db3.png)

**Affected states**

- A main screen view of a ship in warp, running in windowed mode
- Any other running EmptyEpsilon clients also running on the same system as a windowed main screen view

**Unaffected states**

- Running in full screen mode: the main screen view renders in warp without unexpected distortion
- Not running a main screen view in a window on the same system as stations: stations of a ship in warp render without unexpected distortion

**Comment by oznogon** [comment]
Reproduced the main screen behavior on integrated Intel UHD 620 graphics in windowed warp, but unlike on the GTX 1050, the windowed stations are unaffected.

**Comment by daid** [comment]
The problem is related to intel GPU, and the way it supports render textures. It's a complex interaction between SFML and my own code.

A workaround is disabling post processing shaders in the options.ini

**Comment by oznogon** [comment]
Thanks daid, I'll close this as a dupe of #636
