### ISSUE TITLE
Custom buttons/infos on science and operations don't work

### ISSUE THREAD

**Issue by aBlueShadow** [daid/EmptyEpsilon#739]
In science and operations, custom functions are not shown. I first thought it is intentional, because there is not much soace available, but then I saw there is related code in science cpp. It seems it is supposed to snap into the sidebar somehow, which doesn't seem to work.

**Comment by NinjaSpectre** [comment]
The [sidebar_selector](https://github.com/daid/EmptyEpsilon/blob/a46fcabf103e8c0b0b7e2bfd485c1d789ac2efbe/src/screens/crew6/scienceScreen.cpp#L71)  works when I build.  I will admit it is easily overlooked though since it does not function in the same way as the other screens.  Takes a somewhat experienced Science officer to realize that they have been given a custom function.

**Comment by aBlueShadow** [comment]
Arrgh, totally missed the selector (not in the code, but on the screen for some reason.)
So should #740 be reverted then? On the other hand, I am not sure if only experienced officers should realize that there are custom functions. 
So far, I basically used them to guide the crew, and drive the plot forward, as they appeared on certain events contextually when needed. (change ship, spin up transmitter, send signal,..). 
That was the reason I even stumbled over this supposed "bug", as in my script, enigineering, wepons and relay had to press custom buttons in sequence, each one enabling the button for the next officer. I wanted to double the relay part on the operations screen as a fallback for smaller crews,.

Anyways, the big advantage of the original code is the bigger space for custom functions. So if the PR breaks existing scripts, it should definitely be reverted

**Comment by daid** [comment]
Good point, I missed that as well. I'll check out both solutions and see if the new or the old fits better.

**Comment by daid** [comment]
I liked the old one better, as it works better with more then 2 buttons/info fields.

**Comment by aBlueShadow** [comment]
> I liked the old one better, as it works better with more then 2 buttons/info 

Ah, seems like I am not the only one who still uses 4:3 screens :-)
Guess I have to think about an info system for my script then, that alerts the user when new custom functions appear - maybe via custom messages.

**Comment by daid** [comment]
Our touchscreen hardware setup has 4/3 screens, guess why the EE UI fits together so well on those 4/3 screens ;-)
