### ISSUE TITLE
Building Targeting Windows

### ISSUE THREAD

**Issue by RustyPotato** [daid/EmptyEpsilon#748]
Do you mind updating the documentation and making it more clear how to build targeting windows? I tried to follow the instructions as best I could, and was able to get regular builds working on my Ubuntu machine, but couldn't get Windows builds to work for various reasons. Do you mind updating the documentation to make it clearer. 

Thank you.

**Comment by oznogon** [comment]
I strongly recommend using https://github.com/gwaland/EmptyEpsilon-build-scripts if you're building on Ubuntu 18.04. It's what I use to build for Windows.

Otherwise we'll need to know what Ubuntu versions you're building on since (my guess is) the instructions would likely differ between releases.

**Comment by aBlueShadow** [comment]
For manual building, this instruction should be up to date:
https://bridgesim.net/index.php?p=/discussion/452/building-ee-for-windows-just-became-a-bit-easier

**Comment by oznogon** [comment]
@aBlueShadow Good to know! Testing that now, if it works I'll drop it in the wiki.

**Comment by RustyPotato** [comment]
Updated documentation works excellently. Thank you all for your assistances.
