### ISSUE TITLE
Server not detected in Android 2016.01.05 client

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#75]
Just downloaded _EmptyEpsilon-2016.01.05-win32.zip_ and _EmptyEpsilon-2016.01.05-android.apk_, tried to spin up a server on the PC and access it via Android with no success. Killed firewall entirely just to be sure but no luck so far, but don't have time for further testing right now. **Note: This means I have not attempted to access server from other PC clients at this point.** 

Raising this in case the issue is obvious and will do more testing to narrow it down and try to eliminate factors on my end later.

**Comment by kwadroke** [comment]
After seeing this issue, I tested the same files and I am also seeing this problem.
The versions of the Windows & the Android Client differs, which is keeping Android from seeing the server.
```Windows: 20160105```
```Android: 20160104```

Since they aren't the same, the client will not connect to the server.

**Comment by Wrongtown** [comment]
Thanks @kwadroke, it didn't have the feel of a spurious defect but it's always nice to get that confirmation! Sounds like it should be a pretty simple fix.

**Comment by daid** [comment]
Must be something in the build that is going wrong. I've removed the Android download to prevent confusion till I have this sorted.

**Comment by Wrongtown** [comment]
Closing this as it was an issue with the build which led to the version between windows and android build was out of sync, @daid has fixed this and provided a new release 2016-01-14.
