### ISSUE TITLE
[REQUEST] Zoom for Science!

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#76]
Some level of Zoom on the Science station would be great, especially when enemies are clustered it can be awkward to try to select each of them for scanning. Trying to constrict the view of science to an area around the ship becomes more difficult with this in place, but perhaps there's a healthy middle ground? 

For example, a "Zoom" button is added to the Science window which when selected turns the cursor into a rectangle so the user can select a portion of space that they can currently see, and they get a fixed, high-level zoom in on that section? In the mock-up attached the user is trying to view DS3.

![image](https://cloud.githubusercontent.com/assets/16337876/12136696/5dd8a148-b485-11e5-9afc-ab609157685e.png)

**Comment by Fouindor** [comment]
Although I highly second this, I don't know if the exact zoom mechanism you described is easily doable with the current radar mechanics.
A thing that would be easier is a 15/10/5 km zoom around the ship.

**Comment by Wrongtown** [comment]
True enough, I have to admit that suggestion was almost an exercise in "free writing" I like the idea of a stepped zoom around the ship though imagine the budding Science Officers out there would prefer a bit more granularity further out... Would it be much harder to allow zooming from whatever the Maximum Radar is set to down in 5km increments?

**Comment by Fouindor** [comment]
I gave the increments as an example, the tricky (for me ^^) parts I see with what you described is the fact to center the view not on the ship.  It would be tricky to retain the same aspect (and the displayed angles would be completely skewed). Another point that would be the rectangular selection. That's why I suggested to still center on the ship, even if it is not ideal, it would be easier to implement in my opinion.

**Comment by Wrongtown** [comment]
:+1: I think we agree here, keeping it centered on the ship sounds like a solid plan, besides which I think it probably could result in some nice "We need to get a bit closer if you want me to get a clean scan" moments :)

**Comment by daid** [comment]
Science used to have a zoom option, guess I forgot to re-implemented it when I totally re-did the UI code...

**Comment by Fouindor** [comment]
Submitted #81 to answer to this request. Added a button with 1x, 1.5x, 2x, 2.5x, 3x zooms.
