### ISSUE TITLE
Incorrect JSON format returned by /exec.lua API

### ISSUE THREAD

**Issue by Kilted-Klingon** [daid/EmptyEpsilon#762]
Summary:  When using jQuery .post to make a submission to the /exec.lua API, the JSON response is incorrectly formatted, thus preventing the response from being properly parsed in javascript JSON functions. 

Example:  There are 3 various objects near the coordinate origin of the playing grid.  Each have an extra, user assigned variable to plainly state the object type.  Using $.post to submit the following string to /exec.lua:
<pre>"return getObjectsInRadius(0, 0, 3500)"</pre>

results in the following response:

<pre>{1.000: {"type": "playership", "__ptr": "[OBJECT]"}, 2.000: {"type": "cpuship", "__ptr": "[OBJECT]"}, 3.000: {"type": "astroid", "__ptr": "[OBJECT]"}} </pre>

However, when attempting to put the response through a JSON parser, an error occurs at the second position as follows: "Expecting 'STRING', '}', got 'NUMBER'".  This means that each of the numbers that separate out the different objects in the data set need to be enclosed in quotes, or an alternative is to eliminate the numbers.  

For example, the first two objects returned appear thusly when broken out:
<pre>
{
    1.000: {
        "type": "playership", 
        "__ptr": "[OBJECT]"
    }
   2.000: {
        "type": "cpuship", 
        "__ptr": "[OBJECT]"
    }
}
</pre>
One optional fix is to add quotation marks around the "element" numbers as follows:
<pre>
{
    "1.000": {
        "type": "playership", 
        "__ptr": "[OBJECT]"
    }
   "2.000": {
        "type": "cpuship", 
        "__ptr": "[OBJECT]"
    }
}
</pre>
Another optional fix is to remove the "element" numbers and use beginning and ending hard brackets [ ] as follows:
<pre>
[
    {
        "type": "playership", 
        "__ptr": "[OBJECT]"
    }
   {
        "type": "cpuship", 
        "__ptr": "[OBJECT]"
    }
]
</pre>
This second fix option has the added benefit of using JSON array notation through the use of the [ ] hard brackets.

**Comment by daid** [comment]
The problem with using the array notation is that lua has no real concept of an array. It only has tables, and tables with numbers in them are used as arrays. So the simplest fix is just to always convert the keys to string, which fixes a lot of other possible problems as well. As in lua anything can be used as a key in a table, even other tables numbers or various other things.

**Comment by daid** [comment]
Note that there is another problem, strings with embedded quotes are also not properly escaped. Not sure how big of an issue this is for you, but would be good to know.

**Comment by daid** [comment]
(Didn't test the fix yet)

**Comment by pixelclef** [comment]
Another note: each element in the outer object needs to be separated by a comma. So

```[
    {
        "type": "playership", 
        "__ptr": "[OBJECT]"
    }
   {
        "type": "cpuship", 
        "__ptr": "[OBJECT]"
    }
]```

Should be:

```[
    {
        "type": "playership", 
        "__ptr": "[OBJECT]"
    },
   {
        "type": "cpuship", 
        "__ptr": "[OBJECT]"
    }
]```

In the earlier examples. I don’t know how to highlight the new comma, sorry.

**Comment by Kilted-Klingon** [comment]
Pix is correct about the comma separating each element in the outer object.  This comma is included in the response from /exec.lua as in my response example above (reprinted here):
<pre>{1.000: {"type": "playership", "__ptr": "[OBJECT]"}, 2.000: {"type": "cpuship", "__ptr": "[OBJECT]"}, 3.000: {"type": "astroid", "__ptr": "[OBJECT]"}} </pre>
I neglected to carry the comma forward in the breakout examples.  Thanks for correcting Pix!

**Comment by Kilted-Klingon** [comment]
I will do another check on data types being returned from /exec.lua and update this issue report.

Ref Daid's comment/question above concerning converting keys to strings, I'm fine with that as long as it is correctly parsed by JSON.  I can ignore elements from the response payload that are superfluous.

**Comment by Kilted-Klingon** [comment]
Sincere apologies, I inadvertently 'closed' this issue when I submitted my previous comment/update.  Didn't mean to close.  I definitely still need to have the fix.  Sorry for confusion.

**Comment by oznogon** [comment]
Tested vs. 20200218:

```
$ curl -q --data "return getObjectsInRadius(0, 0, 3500)" http://localhost:8080/exec.lua
{1.000: {"__ptr": "[OBJECT]"}, 2.000: {"__ptr": "[OBJECT]"}, 3.000: {"__ptr": "[OBJECT]"}, 4.000: {"__ptr": "[OBJECT]"}, 5.000: {"__ptr": "[OBJECT]"}}
```

Tested vs. EE and SP master branches:

```
$ curl -q --data "return getObjectsInRadius(0, 0, 3500)" http://localhost:8080/exec.lua
{"1": {"__ptr": "[OBJECT]"}, "2": {"__ptr": "[OBJECT]"}, "3": {"__ptr": "[OBJECT]"}, "4": {"__ptr": "[OBJECT]"}, "5": {"__ptr": "[OBJECT]"}}
```

**Comment by Kilted-Klingon** [comment]
I have done some additional testing and may have identified additional formatting issues.

Here is the pertinent lua code to declare 3 objects and assign some test values to them:
<pre>
	player1 = PlayerSpaceship():setTemplate("Atlantis")
		player1.call_sign = "Excalibur"
		player1.hull_value = 250
		player1.boolean = true
		player1.table_list = {"red", true, 5.678}

	player2 = PlayerSpaceship():setTemplate("Atlantis")
		player2.call_sign = "Defiant"
		player2.hull_value = 300
		player2.boolean = false
		player2.table_list = {"green", false, 0}

        station1 = SpaceStation():setTemplate("Medium Station")
		station1.call_sign = "Home Station"
		station1.game_time = 23423.34
		station1.planet_collision = true
		station1.player_ships = 8
		station1.cpu_ships = 25
</pre>
I sent the following payload to '/exec.lua' API:  <code>"return getObjectsInRadius(0,0,3000)"</code>

'/exec.lua' responded with:

<code>
{1.000: {"hull_value": 250.000, "__ptr": "[OBJECT]", "table_list": {1.000: "red", 2.000: true, 3.000: 5.678}, "boolean": true, "call_sign": "Excalibur"}, 2.000: {"hull_value": 300.000, "__ptr": "[OBJECT]", "table_list": {1.000: "green", 2.000: false, 3.000: 0.000}, "boolean": false, "call_sign": "Defiant"}, 3.000: {"cpu_ships": 25.000, "__ptr": "[OBJECT]", "planet_collision": true, "game_time": 23423.340, "player_ships": 8.000, "call_sign": "Home Station"}}
</code>


Broken out (carefully), the response is organized as follows:
<pre>
{
   1.000: {
      "hull_value": 250.000, 
      "__ptr": "[OBJECT]", 
      "table_list": {
         1.000: "red", 
         2.000: true, 
         3.000: 5.678
      }, 
      "boolean": true, 
      "call_sign": "Excalibur"
   }, 
   2.000: {
      "hull_value": 300.000, 
      "__ptr": "[OBJECT]", 
      "table_list": {
         1.000: "green", 
         2.000: false, 
         3.000: 0.000
      }, 
      "boolean": false, 
      "call_sign": "Defiant"
   }, 
   3.000: {
      "cpu_ships": 25.000, 
      "__ptr": "[OBJECT]", 
      "planet_collision": true, 
      "game_time": 23423.340, 
      "player_ships": 8.000, 
      "call_sign": "Home Station"
   }
}
</pre>
Pix, I would greatly appreciate your expertise in evaluating the response for proper (or at least acceptable) JSON format.  Again, my goal is that I should be able to use jQuery/javascript functions to automatically parse the response payload.  Thank you all.

**Comment by oznogon** [comment]
On the master branches build containing daid's fix, the response I get is valid JSON:

```
{
	"1": {
		"game_time": 23423.34,
		"cpu_ships": 25,
		"__ptr": "[OBJECT]",
		"player_ships": 8,
		"call_sign": "Home Station",
		"planet_collision": true
	},
	"2": {
		"call_sign": "Defiant",
		"table_list": {
			"1": "green",
			"2": false,
			"3": 0
		},
		"__ptr": "[OBJECT]",
		"boolean": false,
		"hull_value": 300
	},
	"3": {
		"call_sign": "Excalibur",
		"table_list": {
			"1": "red",
			"2": true,
			"3": 5.678
		},
		"__ptr": "[OBJECT]",
		"boolean": true,
		"hull_value": 250
	}
}
```

**Comment by pixelclef** [comment]
I’m encouraged by the response oznogon posted. K, I have to suspect your posted response is generated by the original unfixed code.

**Comment by daid** [comment]
Note, as json has a very tightly spec. Any online json validator should be able to check if it is correct json or not.
I think the current output is correct, as long as a string doesn't contain an embedded '"'

**Comment by Kilted-Klingon** [comment]
Ok, sorry, the lua code is obviously mal-formed.  Here's the correct version:
<pre>
	player1.table_list["one"] = "red"
	player1.table_list["two"] = true
	player1.table_list["three"] = 5.678
</pre>
Sorry for spam.

**Comment by daid** [comment]
"explicitly named indices" will be fine. Using tables as indices might cause problems.

**Comment by Kilted-Klingon** [comment]
Tks daid.  Yea, I was thinking that nested tables was a 'bridge too far' for /exec.lua responses, and was definitely planning to avoid.  Thanks again.

**Comment by daid** [comment]
Nested tables work fine. Tables as table keys will be an issue

**Comment by Kilted-Klingon** [comment]
oh, wow, ok; I will test it out at some point!

**Comment by oznogon** [comment]
@Kilted-Klingon I can't tell from the subsequent discussion whether you still wanted confirmation, but given this Lua in a scenario:

```
    player1.table_list = {}
    player1.table_list["one"] = "red"
    player1.table_list["two"] = true
    player1.table_list["three"] = 5.678
```

I got this output from the API from a master build as of March 7, where object "2" is the `player1` object:

```
{
    "1": {
        "__ptr": "[OBJECT]"
    },
    "2": {
        "table_list": {
            "two": true,
            "one": "red",
            "three": 5.678
        },
        "__ptr": "[OBJECT]"
    }
}
```
