### ISSUE TITLE
BUG - Large messages default to showing end of message when opened by Relay

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#78]
When Relay opens a message which has too much text to show at once, the message is presented as if the user has already scrolled to the bottom of the message.

Yes there's probably an argument for not writing too much text in an individual message... :unamused: 

**Relay selects Answer**
![image](https://cloud.githubusercontent.com/assets/16337876/12144711/9b45d0b6-b4c4-11e5-9d38-62ad7d4f75da.png)

**Message presentation**
![image](https://cloud.githubusercontent.com/assets/16337876/12144729/b2536570-b4c4-11e5-90a5-6c34cc4dad03.png)

**Comment by oznogon** [comment]
This appears to be resolved in current builds. If there's enough text in a comms message to force scrolling, the message windows starts at the top.

**Comment by muerteFR** [comment]
@daid This bug is obsolete !? :-)
