### ISSUE TITLE
Translation issue when using context

### ISSUE THREAD

**Issue by aBlueShadow** [daid/EmptyEpsilon#784]
There seems to be a problem on the c++ translation. Whenever a context is used, the last entry in the translation file that shares the same msgctxt has no effect, the term won't be translated.

Examples: hacking type All, variation None, Rear Shield Generator, etc.

**Comment by daid** [comment]
Should be fixed by https://github.com/daid/SeriousProton/commit/52ff931d96fbebea204d26d6271102a70eff99e6

**Comment by aBlueShadow** [comment]
Yeah that works now, thanks!
