### ISSUE TITLE
Initial VC capability test - sound only through server

### ISSUE THREAD

**Issue by Kilted-Klingon** [daid/EmptyEpsilon#791]
This was an initial test of the voice chat capability first built into EE and compiled as of UTC 2230 on 17 Mar 2020.  This issue is related to issue #792 .

Only Windows compiled versions were used in this test.

Test setup:
- EE server running in a VM in Azure cloud; desktop control through TeamViewer
- EE client running on physical machine A
- EE client running on physical machine B
- EE client running on physical machine C

Test execution:
- server ran "Empty Space" scenario with 1 playership, no AI entities
- all 3 clients connected immediately to the server with no issues
- each client was connected to a separate console

**Observation:**
- when attempting to use the "Tab" key to voice chat from a client, no matter which client is used, the voice can only be heard coming from the server; no voice is heard coming from any other client no matter which client is used

**Comment by daid** [comment]
https://github.com/daid/SeriousProton/commit/9ccf578d1524613a8134f8e31fbc7ac16ca4ece7 should fix this.
