### ISSUE TITLE
Initial VC capability test - not all clients can use VC 

### ISSUE THREAD

**Issue by Kilted-Klingon** [daid/EmptyEpsilon#792]
This was an initial test of the voice chat capability first built into EE and compiled as of UTC 2230 on 17 Mar 2020.  It is related to issue #791 .  

Only Windows compiled versions were used in this test.

Test setup:
- EE server running in a VM in Azure cloud; desktop control through TeamViewer
- EE client running on physical machine A
- EE client running on physical machine B
- EE client running on physical machine C

Test execution:
- server ran "Empty Space" scenario with 1 playership, no AI entities
- all 3 clients connected immediately to the server with no issues
- each client was connected to a separate playership console

**Observation:**
- when connecting clients to the server and testing voice chat capabilities, the VC capability of a client will sometimes be disabled when another client is connected.  The EE client itself remains connected to the server and all other functionality remains intact, just the previously usable VC becomes disabled.  I was not able to discern a specific pattern to when a client VC capability would or would not become disabled, but of the 3 clients in the test, only 2 were ever able to use VC at the same time.  I was never able to get a third client to enable VC.

**Comment by daid** [comment]
https://github.com/daid/SeriousProton/commit/9ccf578d1524613a8134f8e31fbc7ac16ca4ece7 should fix this.
