### ISSUE TITLE
Follow-on VC test - NO outbound VC through proxy server

### ISSUE THREAD

**Issue by Kilted-Klingon** [daid/EmptyEpsilon#797]
This was second test of the voice chat capability first built into EE and compiled as of UTC 2345 on 18 Mar 2020. 

A mix of Windows and Linux compiled versions were used in this test.

Test setup:

    EE server running in a VM in Azure cloud; desktop control through TeamViewer
    EE client running on physical machine A
    EE client running on physical machine B
    EE client running on physical machine C

Test execution:

    server ran "Empty Space" scenario with 1 playership, no AI entities
    all 3 clients connected immediately to the server with no issues
    each client was connected to a separate console

Observation:  previous issues #791 and #792 confirmed fixed.  Although sound does still come through the server GM console, voice does transmit to all connected clients.  There was no issue in using all 3 client VC capabilities.  I disconnected and reconnected clients to the server a number of times and noted no unusual behaviors with VC capability.  
	
Variation 1:

	I ran a proxy server in a Linux VM running in VMWare Workstation on machine A and connected the client on machine A to the proxy server which was connected to the server in the Azure VM.  
	
	Observation:  when attempting to use VC outbound from the client connected to the proxy, the sound did not transmit to the other clients, and the proxy console had the following message:  `[ERROR] Unknown command from client: 33`.  When initiating VC outbound from either of the clients on machine B or C, the voice WAS heard from the client on machine A connected to the proxy, so it appears to work inbound but NOT outbound.

**Comment by daid** [comment]
This commit should fix it: https://github.com/daid/SeriousProton/commit/e7f1827ab5ab9f95a2fe475fc0c6e7a8b9b5de85
