### ISSUE TITLE
segfault on launch

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#800]
*Regression*

Something in ba2f09f2bba7f547f3e5f5ba9a46c68b0f7e80df causes a segfault during launch on macOS. Builds before this commit work, after it fail. Will follow up to add details & if I can reproduce on other builds

*Steps to reproduce*

1. Remove any `username=` settings in `options.ini`.
2. Null any `USERNAME` environment variables. On Ubuntu and macOS, it's not set by default.
3. Run `EmptyEpsilon`.

macOS thread trace:

```
_platform_strlen
std::__1::char_traits<char>::length(char const*)
std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string<std::nullptr_t>(char const*)
string::string(char const*)
string::string(char const*)
main
start
```

No issue in Windows builds.

**Comment by aBlueShadow** [comment]
I also refuses to launch on Linux, no segfault though.

> [INFO]  Loaded: packs/msgamedev.pack with 96 files
> [INFO]  Loaded: packs/Angryfly.pack with 166 files
> [INFO]  Loaded: packs/Asteroids.pack with 30 files
> [INFO]  Loaded: Tokka_WalkingMan.png with 6 sprites
> terminate called after throwing an instance of 'std::logic_error'
>   what():  basic_string::_M_construct null not valid

So it might have to do something with the string vector?

**Comment by oznogon** [comment]
That's the error I just got on the Linux build as well running headless on Ubuntu 18.04. The macOS error report was also string related, I'm not at that system at the moment to grab the crash report.

**Comment by oznogon** [comment]
It appears to be this: https://github.com/daid/EmptyEpsilon/commit/ba2f09f2bba7f547f3e5f5ba9a46c68b0f7e80df#diff-7ec3c68a81efff79b6ca22ac1f1eabbaR188

`getenv("USERNAME")` isn't checked and returns something unexpected. On my Linux box, it's empty. If I comment out that statement, the build works.
