### ISSUE TITLE
Missing linker libraries in Makefile

### ISSUE THREAD

**Issue by Seegras** [daid/EmptyEpsilon#803]
Some libraries are not linked against.

I get errors like "undefined reference to `opus_decoder_create'"  which could be fixed by adding -lopus. But I have no idea on how to make cmake add that ;). 

I also get a load of "undefined reference to `PObject::~PObject()'" and "undefined reference to `typeinfo for PObject'" which probably means it doesn't link seriousproton. I tried to add -lseriousproton or ../../SeriousProton/build/libseriousproton.a to the linker call, but no avail. 

I also don't quite understand why I need to clone seriousproton and specify -DSERIOUS_PROTON_DIR=$PWD/../../SeriousProton/ when I have seriousproton already installed systemwide (apt install libseriousproton-dev).

**Comment by daid** [comment]
https://github.com/daid/EmptyEpsilon/wiki/Build%5CLinux%5CDebian
Follow that. Installimg seriousproton as a shared library is not supported.

Yes, it is not the "true linux way". But I do not care.

**Comment by Seegras** [comment]
It's not the point. This fails with the same linker errors. Even if I add " -lopus ../../SeriousProton/build/libseriousproton.a" to the linker call. 

Here's what a fresh build-attempt does, done exactly according to your instructions:
https://pastebin.com/6pY6C1cF

(on a related note: the reason I try to compile, is that libsfml is version 2.5 here, I don't have any 2.4 one, so your deb package doesn't work on modern Debian/Ubuntu. The package also only depends on libsfml-dev, without version)

**Comment by daid** [comment]
You sure you followed the instructions? As this happens if you build an older EE tag against master SeriousProton. Be sure to grab the same tag on both.

I am aware of the deb issue. Problem is that my build server is debian stretch (cannot upgrade for other reasons)

**Comment by Seegras** [comment]
Did compile now. Yes, it was necessary to do a "git checkout EE-2020.02.18" on both trees. You might want to clarify the build documentation.

**Comment by aBlueShadow** [comment]
It already is:

> check out the corresponding release tag, being in the SeriousProton directory:
> `git checkout EE-2020.02.18`
> and do the same for the EmptyEpsilon directory.
