### ISSUE TITLE
Build error: 

### ISSUE THREAD

**Issue by ealvarez-accedo** [daid/EmptyEpsilon#808]
When I attempt to build Empty Epsilon (branch EE-2020.02.18) from source on Slackware 14.2, I get the following error:

> ../src/scienceDatabase.cpp:139:95: error: call of overloaded ‘abs(float)’ is ambiguous

These are the packages I'm using for building this:

 - gcc-g++ 5.3.0
 - ninja 1.10.0
 - cmake 3.5.2
 - SFML 2.5.1

I'm guessing this is a compiler error

**Comment by daid** [comment]
> gcc-g++ 5.3.0

gcc 5? you sure that is right? As that's ancient.

I'm building with gcc 6.3 and 8.3, as well as clang 8.0.7 in my CI system. So, might be an issue on your side.
