### ISSUE TITLE
Script reference document contains multiple [ERROR] entries

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#817]
Examples:

SpaceObject:setPosition [ERROR]
SpaceObject:setRotation [ERROR]
SpaceObject:getPosition [ERROR]
SpaceObject:getRotation [ERROR]

SpaceObject:getVelocity [ERROR]
SpaceObject:getAngularVelocity [ERROR]

Script:run [ERROR]
Script:setVariable [ERROR]

I realize this document is automatically generated. It looks like there's something wrong with the automation. These errors were present in these previous releases:

- 20200218 
- 20200115 
- 20191101 
- 20190910

They were *not* present in the 20190521 release

**Comment by oznogon** [comment]
IIRC `[ERROR]` can mean that the function works in EE but is defined only in SeriousProton, but I thought I'd [changed that in the reference generation script](https://github.com/daid/EmptyEpsilon/commit/f92ec84b46e3e8bdedae726ccc1299cf0390ff1b#diff-722bcb54d01860470767b90b79f2cd3cR254) to be more specific (`[NOT FOUND; see SeriousProton]`), and that's what I get in my builds.

<img width="522" alt="Screen Shot 2020-03-23 at 10 02 36 AM" src="https://user-images.githubusercontent.com/19192104/77342674-c700f880-6ced-11ea-8321-5e48e85998e1.png">

**Comment by daid** [comment]
Looks like the file also wasn't updated in the release.

I've updated the release zip with an updated version. And uploaded it here: http://daid.eu/dump/script_reference.html
