### ISSUE TITLE
REQUEST getHeading/setHeading functions to compliment the existing Position & Rotation functions

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#82]
Apologies if I'm just not understanding how SpaceObject:getRotation() works, I'm still learning a lot about .lua.

In working on a script where the player ship begins with a heading of 90.00. I wanted to be able to check in as to the current heading for their ship so I created a table to store it as follows:

    a = {}
    H = "stored_heading"
    a[H] = Player:getRotation()
    print(a[H]) --Print the value recorded for debugging purposes

This mostly seems to be working, but it's offset by 90 degrees, for example:

Actual Heading | Returned Heading
------------------- | -------------------
90.00 | 0.00
80.00 | -10.00
109.00 | 19.00

I get the same results if I don't bother building a table but just use `print(Player:getRotation())` so I'm assuming my table is not the culprit here.

**Note:** I actually saw a bug in a recent play-through where the helm was using an Android phone running [2015.12.21-android.apk](http://software.ultimaker.com/EmptyEpsilon/EmptyEpsilon-2015.12.21-android.apk) and they would get negative numbers when turning counter-clockwise, but when I attempted to replicate it after that session I wasn't seeing it.

**Comment by Wrongtown** [comment]
I'm attempting a partial workaround within the script itself by setting `a[H] = 90.00` and then when I want to get and store the new value I use `a[H] = ((a[H]) + Player:getRotation())`. This sort of works, but based on the stack I'm guessing it actually saves a[H] to the bugged value (e.g. 17), then adds the most recently recorded value to it and saves *that* (e.g. 107). I'm far from confident that this wouldn't spin out of control down the line after multiple rotations of the ship or just return the wrong value somehow.

Again, if I'm misunderstanding how this should be used please give me a slap and set me in the right direction :)

**Comment by daid** [comment]
This is a difference between heading and rotation. The rotation/vector/position functions I use assume 0 degrees is to the right. While with the heading 0 degree is to the top.

**Comment by Fouindor** [comment]
I'm quite confused... why not use setRotation(0) on scenario init ?

Moreover, the players may not even be at 0/90 exactly after helm maneuvers, so checking if the angle is equal to a strict value may not be a good idea.

**Comment by daid** [comment]
Also, the getRotation function isn't limited, it's quite possible for a ship to rotate lower then 0 or higher then 360 degrees.

I'll add a getHeading function, which returns the current heading between 0 and 360 degrees.

**Comment by Wrongtown** [comment]
Ah, so it *is* a matter of me using it wrong, I should have known ;)

That would be awesome, will change the issue to reflect this is a Request not a Bug :)

**Comment by daid** [comment]
https://github.com/daid/EmptyEpsilon/blob/master/src/spaceObjects/spaceObject.cpp#L21

**Comment by Wrongtown** [comment]
@daid have I told you lately that I love your work? Because I really should do so more often.
