### ISSUE TITLE
Script function getLongRangeRadarRange gives error

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#820]
It is likely that `getLongRangeRadarRange` no longer applies since that has moved to be player ship specific. Lua scripts that refer to it get an `attempt to call a nil value (global 'getLongRangeRadarRange')` error from Lua.

It should at least be removed from the script reference document or there should be an explanation added that the function has been deprecated in favor of ...whatever the new Lua function name is (I can't find it in the script reference)

Perhaps the function should default to the ship retrieved by `getPlayerShip(-1)`. I know that is not ideal, but it would maintain semi-backward compatibility with existing Lua scripts that use `getLongRangeRadarRange`

**Comment by daid** [comment]
The script_reference wasn't properly updated. I've manually updated the windows zip to fix this.

The getLongRangeRadarRange function has been moved to the player ship. I decided against backward compatibility, as that would generally give the wrong results unintentionally.
