### ISSUE TITLE
[Bug] Warp Effect Malformed when Window Resized.

### ISSUE THREAD

**Issue by JonathanILevi** [daid/EmptyEpsilon#821]
I discovered a bug where the warping distortion is messed up after I resize the game window while in play.

My guess is that when play is started (or the first time the effect is used) some calculation is done using the window size but it is not recalculated when the window is resized.

I have not done further testing.

**Comment by oznogon** [comment]
cf. #158, #636, #645, #734

**Comment by oznogon** [comment]
The patch in daid/SeriousProton#45 seems to cause a single flicker for me right when the shader starts when running in a window.

**Comment by daid** [comment]
That is just the warp drive spinning up? ;)

**Comment by gcask** [comment]
This should be fixed by daid/SeriousProton#77 and #1376.

(probably worth closing)
