### ISSUE TITLE
Screens/crew stations aren't destroyed when exited

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#823]
When exiting a crew station or screen, it isn't destroyed until the client process ends. These screens continue to accumulate as objects over multiple sessions from one run of the client.

*Steps to reproduce*

1. Add a destructor to any screen or station (ie. `ScreenMainScreen`).
1. Add logging to the screen's constructor and destructor.
1. Start a server and scenario.
1. Join a ship's screen or station (ie. Main Screen). The constructor should now log upon being called by `spawnUI` in `PlayerInfo`.
1. Exit the screen or station.

*Expected behavior*

The screen's destructor is called.

*Observed behavior*

Screens created in `PlayerInfo` are never destroyed. Each screen persists after exiting it, as well as after exiting the scenario and stopping the server, and accumulates when joining screens in a new server during the same process. In debug builds, the object count grows when screens are joined and does not reduce when screens are exited.

Per the logging, the destructor isn't called until the EE client quits.

On initial launch and starting a server:

```
Object count:  551    3    0
[INFO]  Loaded: gui/ButtonBackground.hover with 0 sprites
[INFO]  Loaded: button.wav of 0.15 seconds
[INFO]  Creating PlayerInfo
[INFO]  Loaded: gui/LabelBackground with 0 sprites
[INFO]  Loaded: gui/SelectorBackground with 0 sprites
[INFO]  Loaded: gui/SelectorArrow with 0 sprites
[INFO]  Loaded: gui/ButtonBackground.active with 0 sprites
[INFO]  Loaded: gui/ScrollbarBackground with 0 sprites
[INFO]  Loaded: gui/ScrollbarSelection with 0 sprites
[INFO]  Loaded: gui/PanelBackground with 0 sprites
Object count:  556    5    0
[INFO]  Load script: scenario_00_basic.lua
[INFO]  Load script: util_random_transports.lua
[WARN]  Failed to open game state log file: logs/game_log_25-03-2020_22.56.20.txt
```

On joining main screen:

```
Object count: 1034   27    0
Object count: 1034   27    0
Object count: 1034   27    0
[INFO]  Spawning UI
[INFO]  Creating main screen
[INFO]  Switching to ambient music
[INFO]  Loading shader: billboardShader
...
[INFO]  Loaded: engine.wav of 4.97 seconds
Object count: 1037   29    0
Object count: 1038   29    0
```

Exiting and rejoining main screen several times:

```
Object count: 1038   29    0
[INFO]  Spawning UI
[INFO]  Creating main screen
[INFO]  Switching to ambient music
Object count: 1040   30    0
Object count: 1041   30    0
Object count: 1041   30    0
[INFO]  Spawning UI
[INFO]  Creating main screen
[INFO]  Switching to ambient music
Object count: 1044   31    0
Object count: 1044   31    0
[INFO]  Spawning UI
[INFO]  Creating main screen
[INFO]  Switching to ambient music
Object count: 1046   32    0
Object count: 1047   32    0
Object count: 1047   32    0
Object count: 1047   32    0
[INFO]  Spawning UI
[INFO]  Creating main screen
[INFO]  Switching to ambient music
Object count: 1050   33    0
```

Upon exiting to the main menu

```
Object count:  585   10    0
```

Object count is 34 more than on initial launch.

On quitting EE:

```
[INFO]  Destroying main screen
[INFO]  Destroying main screen
[INFO]  Destroying main screen
[INFO]  Destroying main screen
[INFO]  Destroying main screen
[INFO]  Destroying PlayerInfo
```

**Comment by oznogon** [comment]
Also odd: starting and then immediately closing the server destroys PlayerInfo.

```
Object count:  556    5    0
Object count:  556    3    0
[INFO]  Creating PlayerInfo
[INFO]  Destroying PlayerInfo
Object count:  558    3    0
Object count:  558    3    0
[INFO]  Creating PlayerInfo
[INFO]  Destroying PlayerInfo
Object count:  560    3    0
Object count:  560    3    0
[INFO]  Creating PlayerInfo
[INFO]  Destroying PlayerInfo
Object count:  562    3    0
Object count:  562    3    0
EOF
```

Starting the server and entering a scenario, but not joining a station, creates one PlayerInfo that isn't destroyed until EE is exited, but subsequent times starting a server and entering a scenario destroy it upon returning to the main menu:

```
[INFO]  Creating PlayerInfo
[INFO]  Loaded: gui/LabelBackground with 0 sprites
[INFO]  Loaded: gui/SelectorBackground with 0 sprites
[INFO]  Loaded: gui/SelectorArrow with 0 sprites
[INFO]  Loaded: gui/ButtonBackground.active with 0 sprites
[INFO]  Loaded: gui/ScrollbarBackground with 0 sprites
[INFO]  Loaded: gui/ScrollbarSelection with 0 sprites
[INFO]  Loaded: gui/PanelBackground with 0 sprites
Object count:  556    5    0
[INFO]  Load script: scenario_00_basic.lua
[INFO]  Load script: util_random_transports.lua
[WARN]  Failed to open game state log file: logs/game_log_25-03-2020_23.04.13.txt
[INFO]  Loaded: gui/icons/station-helm with 0 sprites
[INFO]  Loaded: gui/icons/station-weapons with 0 sprites
[INFO]  Loaded: gui/icons/station-engineering with 0 sprites
[INFO]  Loaded: gui/icons/station-science with 0 sprites
[INFO]  Loaded: gui/icons/station-relay with 0 sprites
[INFO]  Loaded: gui/ButtonBackground.disabled with 0 sprites
Object count: 1057    8    0
Object count:  571    5    0
Object count:  571    5    0
[INFO]  Creating PlayerInfo
[INFO]  Load script: scenario_00_basic.lua
[INFO]  Load script: util_random_transports.lua
[WARN]  Failed to open game state log file: logs/game_log_25-03-2020_23.04.17.txt
[INFO]  Destroying PlayerInfo
Object count: 1242   95    0
Object count: 1240    8    0
Object count:  575    5    0
Object count:  575    5    0
[INFO]  Destroying PlayerInfo
EOF
```

**Comment by daid** [comment]
The PlayerInfo object that is created when the server starts is the one that belongs to the "server player".

The problem with object lifetime is annoying. The P<> pointers to PObject subclasses are used a lot. This is a custom smart pointer to allow for requested destruction, by calling `PObject->destroy()`
However, this only sets a flag. The object is not actually destroyed until all P<> pointers no longer point to it.
This causes objects to "stay alive" as long as any P<> pointer is not re-evaluated after requesting destruction of the object.

So the reason the PlayerInfo object isn't destroyed is because the `my_player_info` P<> pointer isn't reevaluated until you start a new server or client.

**Comment by oznogon** [comment]
So basically there's no reliable expectation that PlayerInfo objects (and the screens created by them) will actually be destroyed, which complicates cleanup of, say, `unique_ptr`s that belong to screens.

That explains why I was having so much trouble with #819 — I expected screens to be destroyed on screen exit, which would clean up the `Music` pointers, but they're children of immortal PlayerInfo objects and aren't ever destroyed. It's just the Gui objects and their children that are destroyed when exiting a screen.

I don't feel as crazy now, at least. 😂

**Comment by oznogon** [comment]
This also probably explains some other weird behaviors, like music sometimes kicking in on screens that don't have it (ie. starting a server in Main Screen, backing out, switching to Top Down View, then the PlayerShip from the Main Screen switches threat_estimate and music starts playing on Top Down)

**Comment by daid** [comment]
Yeah, I noticed the music myself as well. However, the PlayerInfo object doesn't contain a reference to the created screens.

I've looked to what could be causing it, and I think the problem is caused by the joystick code addition. The screens are put in the `joystick_event_handlers` list owned by the input system here: 
https://github.com/daid/SeriousProton/blob/48de4ffefd338d4e7dee24153ffe78d0c2ea3610/src/input.cpp#L8

But this list is never iterated over or updated if there are no joystick events. Sort of the same happens to the input_event_handlers, but those events happen frequent enough that this becomes "invisible".

You could try adding:
```
input_event_handlers.update();
joystick_event_handlers.update();
```
In the `postEventsUpdate()` function in SeriousProton input.cpp, to see if my guess is correct. This update function will clear out any deleted entries from those lists.

**Comment by oznogon** [comment]
wow, just when I think I'm starting to wrap my head around it. great catch and fix

**Comment by amir-arad** [comment]
wow indeed...
