### ISSUE TITLE
Feature request: adjustable coolant flow speed

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#825]
When engineering is managing coolant, it flows at a particular speed between systems as the level is adjusted. Can that flow speed be configurable per ship? Also, can that adjustment be made accessible to Lua?

Possible applications include making larger ships have slower flows and smaller ships have faster flows. Script writers could have damage slow the coolant flow or have refit rewards speed up the coolant flow.

Just an idea

**Comment by StarryWisdom** [comment]
the same but for engineering power changes may also be interesting/useful
