### ISSUE TITLE
CRITICAL BUG Unable to build from latest master (2016-01-08 17:08 GMT)

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#86]
Code::Blocks throws the error `..\SeriousProton\src\scriptInterfaceMagic.h|50|error: no match for 'operator=' (operand types are 'std::vector<float>' and 'lua_Number {aka double}')|`

Seems to be a SeriousProton issue, see [comments on Bridgesim.net](http://bridgesim.net/discussion/comment/783/#Comment_783).

**Comment by kwadroke** [comment]
Also see http://bridgesim.net/builds/emptyepsilon/EmptyEpsilon-EXE_20160108-1125_e39e589.FAIL
For the output of make. (Probably a SeriousProton issue)

**Comment by kwadroke** [comment]
The latest update to SeriousProton fixed the compiler issue.
