### ISSUE TITLE
Provided deb-package not working in Debian 10 (Buster)

### ISSUE THREAD

**Issue by dreamwalker7** [daid/EmptyEpsilon#860]
I've just downloaded the debian build 2020.03.022, but unfortunately it is not working.

After installation it states 
"EmptyEpsilon: error while loading shared libraries: libsfml-system.so.2.4: cannot open shared object file: No such file or directory"

And that's correct as "dpkg -i" automatically downloaded libsfml-system2.5. And to me it appears as if 2.5 is the only version available in debian 10.

Any ideas what I can do?
I thought about building it from source - but afraid I might not be able to connect to my friends playing with an "official" version 

Thanks!

**Comment by aBlueShadow** [comment]
About building a version compatible with a release version:
https://github.com/daid/EmptyEpsilon/wiki/Build#a-note-about-version-numbers

**Comment by daid** [comment]
Yeah, this is currently a known problem. As SFML-2.5 is backwards compattible with SFML-2.4, I think you can get around this by adding a bunch of symlinks. But I never tried. The problem is that my build server is still on stretch, so has SFML-2.4 (the deb files where relatively new addition to the release)

**Comment by aBlueShadow** [comment]
Yes that should also work. I once made a "portable package" with libs included. 
Basically how I made it: 
- Follow the normal build instructions, without the final install part.
- Copy the executable EmptyEpsilon in _build one directory up
- (delete directories only needed on build time)
- create a "lib" subfolder, including all sfml files
- create a launcher file, containing `LD_LIBRARY_PATH=lib ./EmptyEpsilon`

**Comment by dreamwalker7** [comment]
Hi,

thanks for the help. With your excellent "Build from Source" guide and the note "about version numbers" I succeeded with a build of the 2020-03-22 version against lbsfml-2.5.

Thanks a lot!
