### ISSUE TITLE
Feature Request: Lua getPlayerShip() to return index and last

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#864]
Currently, getPlayerShip(-1) returns the first active player ship spawned. You can also get a player ship by index: getPlayerShip(index) when index is an integer with a valid player ship index value.

### Feature 1 request: return index
Add the index value of the player ship to the returned parameters. 
_Example 1:_
One player ship spawned:
`p, index = getPlayerShip(-1)  --p = the player ship object, index = 1`
_Example 2:_
One player ship spawned, player ship destroyed, another player ship spawned:
`p, index = getPlayerShip(-1)  --p = the player ship object, index = 2`

### Feature 2 request: return last
In addition to the special value of negative 1, provide another special value (perhaps zero or nil, examples use zero) telling the function to return the last active player ship in the list instead of the first
_Example 1:_
Two player ships spawned:
`p, index = getPlayerShip(0)  --p = the player ship object, index = 2`
_Example 2:_
Four player ships spawned, player ships 1 and 3 destroyed:
`p, index = getPlayerShip(0)  --p = the player ship object, index = 4`

_Example combining both features:_
Five player ships spawned, player ships 1, 3 and 5 destroyed:
`p, index = getPlayerShip(-1)  --p = the player ship object, index = 2`
`p, index = getPlayerShip(0)  --p = the player ship object, index = 4`

**Reasoning:**
The script does not know the highest player ship spawned. When looping through the player ships, there is not a criteria to stop looping. There is not an exposed table that can be use with the Lua pairs construct to loop through the player ships. Stopping the loop when an invalid or inactive player ship is found fails when a player ship in the middle of the list is destroyed because the looping would stop prematurely.

This would at least provide a way to get the boundaries rather than choosing an arbitrary upper limit.

If there is a better way to loop through player ships that would obviate this feature request, please let me know

**Comment by daid** [comment]
There is a hardcoded limit of 32 player ships. So there is an upper bound to the indexes.
https://github.com/daid/EmptyEpsilon/blob/master/src/gameGlobalInfo.h#L51

I am thinking about adding a script even when a new player ship is spawned. That helps in keeping track of all player ships.

**Comment by Kilted-Klingon** [comment]
Aha!  I did not know about the 32 max hard coded limit.  Now we have a goal... ;]

But overall, I agree with Xansta's intent - it would be helpful to have better mechanisms for managing the player ships table and the ships therein.

**Comment by Xansta** [comment]
I also was unaware of the 32 ship limit. I assume the 32 slots are not automatically reused. If the destroy() function is applied, would that reuse the slot or renumber the player ship indices beyond the destroyed player?

**Comment by Kilted-Klingon** [comment]
excellent questions.

**Comment by daid** [comment]
Slots of destroyed ships will be reused.

**Comment by Kilted-Klingon** [comment]
Tks.  Is there concatenation of the table when a ship is destroyed and the table slot becomes "open"?

**Comment by daid** [comment]
When a ship is destroyed that slot just opens up. And new ships that the first availablr slot

**Comment by Kilted-Klingon** [comment]
rgr, tks

**Comment by gcask** [comment]
> When looping through the player ships, there is not a criteria to stop looping

So... What if we exposed a `getActivePlayerShips()` instead?
Would that do it for you? This way you don't even have to worry about indices (which I feel like would lead to more problems than solutions)
