### ISSUE TITLE
GM screen requires selecting a player ship

### ISSUE THREAD

**Issue by oznogon** [daid/EmptyEpsilon#877]
After selecting the GM screen, The "Ready" button doesn't enable in the screen selection menu unless a player ship is also selected. Seems to be a regression in 2020.04.09.

<img width="1312" alt="Screen Shot 2020-04-09 at 8 57 16 PM" src="https://user-images.githubusercontent.com/19192104/78961014-b948c280-7aa4-11ea-9423-ae46bf1ddec2.png">
<img width="1312" alt="Screen Shot 2020-04-09 at 8 57 13 PM" src="https://user-images.githubusercontent.com/19192104/78961019-bcdc4980-7aa4-11ea-9c4b-69bbb7fd7d88.png">

**Comment by daid** [comment]
Livable bug complated to the tutorial crash :)

**Comment by oznogon** [comment]
Bonus: You can select a ship but no stations, click ready, and get a blank screen

<img width="1312" alt="Screen Shot 2020-04-09 at 11 31 22 PM" src="https://user-images.githubusercontent.com/19192104/78968782-464a4680-7aba-11ea-9da3-0157c031a87b.png">
<img width="1312" alt="Screen Shot 2020-04-09 at 11 31 25 PM" src="https://user-images.githubusercontent.com/19192104/78968772-434f5600-7aba-11ea-879b-062be1057c36.png">
