### ISSUE TITLE
Shortening long range radar range is not fully functional

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#889]
Start player ship at 25 units of long range radar range, increase to 35 units of long range radar range, then change it back to 25 units of long range radar range. The longer 35 unit range is still available.

The scroll wheel on the mouse cannot access it, but the zoom widget lets you zoom to 0.7 X and get the larger scan range. Also, if you're already zoomed to maximum when the range shrinks, the long range stays there if you don't fiddle with the zoom.

**Comment by daid** [comment]
Yeah, I knew the ranges could act a bit funky if you changed them while someone is looking at a station. But I think only science is problematic now.

**Comment by oznogon** [comment]
Closed by #1061?
