### ISSUE TITLE
In Lua, getVelocity() only registers along the x axis for the player ship

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#900]
Set course 90 and the velocity is accurate. set course 0 or 180 and get nothing. Set course 270 and get negative velocity.

**Comment by daid** [comment]
Getvelocity returns 2 values.
```
local x, y = player:getVelocity()
```

**Comment by Xansta** [comment]
Ah. That was not clear from the script reference. Thanks
