### ISSUE TITLE
[Bug] Red/Yellow Alert centered, when split with the main screen.

### ISSUE THREAD

**Issue by JonathanILevi** [daid/EmptyEpsilon#902]
As shown in this image the Red Alert indicator is centered on the screen rather than the interface:
![](https://cdn.discordapp.com/attachments/468130409129967631/700952750644789298/ee.PNG)

The alert indicators should logically be centered on the controls interface and not extend over the 3D view.

**Comment by oznogon** [comment]
Alert overlay is part of GuiIndicatorOverlays, added at https://github.com/daid/EmptyEpsilon/blob/d2cd3cea3ba1252a16e7cca776183abb912c652c/src/screens/crewStationScreen.cpp#L136

I'd expect it to have main_panel as a parent instead

**Comment by daid** [comment]
Good catch, didn't look this up myself, but expected something like this.

**Comment by daid** [comment]
Also put the noise overlay only on that side, so you can still see the 3D explosion of your ships destruction on the main screen part.
