### ISSUE TITLE
Application Crashing on OSX 

### ISSUE THREAD

**Issue by JulianSchneider** [daid/EmptyEpsilon#91]
Hi, 

I'm using OSX El Capitan and SFML 2.3.2.

Everything compiles but in starting up the app crashes with:

Failed to open shader file "resources/glitch.frag"
Failed to open shader file "resources/warp.frag"
Segmentation fault: 11

**Comment by nallath** [comment]
Yeah i found that issue as well. If you move the application from build into one directory higher it doesn't crash anymore.

**Comment by JulianSchneider** [comment]
My cmake never created a build directory, the EmptyEpsilon executable is created directly within the root folder. 

My working dir is the EmptyEpsilon root i then compiled with:

cmake .
make
make install
./EmptyEpsilon

**Comment by nallath** [comment]
Hmm, that is odd. @daid any ideas what could cause this? For me the fix was simple, but it seems to a tad bit more complex

**Comment by daid** [comment]
No clue. I never got the build for OSX to work properly.

**Comment by JulianSchneider** [comment]
Shame, hacker house full of macbooks and we all have to buy cheap android tablets (or bootcamp). 

Well have another look at it, if you come up with something let me know!

**Comment by kfprimm** [comment]
@JulianSchneider, please check out my [osx-app-bundle](https://github.com/kfprimm/EmptyEpsilon/tree/osx-app-bundle) branch.

```shell
git clone https://github.com/kfprimm/EmptyEpsilon
cd EmptyEpsilon
git checkout osx-app-bundle
cmake CMakeLists.txt -DSERIOUS_PROTON_DIR:STRING=.../SeriousProton
make && make install
```
I'd appreciate any feedback.

Thanks!
