### ISSUE TITLE
startpaused error

### ISSUE THREAD

**Issue by rkoe** [daid/EmptyEpsilon#924]
According to https://github.com/daid/EmptyEpsilon/wiki/Headless-Dedicated-Server, it's possible to use `startpaused=true` in options.ini to start a scenario in paused state.

But that does not work.
- `startpaused=true` is completely ignored
- only `startpaused=1` works

So, either the code or the documentation should be fixed.

**Comment by daid** [comment]
Doc fixed

**Comment by rkoe** [comment]
Not quite.
The doc still contains `If you set the startpaused option to true, run this to unpause the game:`

(It unfortunately looks like several errors in EmptyEpsilon are only fixed partially (like e.g. "hasWarp"); *at least* a 'search repository for other occurrences' should be done in such cases...)

**Comment by daid** [comment]
Note that you can edit the wiki yourself

**Comment by rkoe** [comment]
Yes, but:
- I did not want do decide, if the code or the documentation should be fixed.
- "Doc fixed" was wrong, since it was only partially fixed -- so my comment clearly belongs to the bugreport.

**Comment by daid** [comment]
As the whole wiki is written by users, it makes sense to fix it there.

I'm not very busy with actively maintaining EE. I do an occasional fix, and I review pull requests. But most of the work is done by the players, and we should be grateful for any fix they do.
