### ISSUE TITLE
DMX and Arduino Findings

### ISSUE THREAD

**Issue by fiskn** [daid/EmptyEpsilon#927]
Hi, thought I would drop a note on my findings in getting EE to talk to an Arduino to light up some ws2812B smart LED's, might be useful to go into the wiki somewhere. I can create a more complete PR if preferred?

I initially tried the DMXSerial Library which I had seen mentioned, with the hardware device configured as DMX512SerialDevice in hardware.ini.  After fiddling around with the Arduino code and EE hardware.ini for an hour, I came to the conclusion that it wasn't going to work. I'm not sure if the 250000 baud is too high for a standard Arduino chip, but the DMX code on the arduino just didn't seem to be picking up any valid DMX data.

Then I tried setting the hardware device to EnttecDMXProDevice and using this Arduino library and example code: https://github.com/DaAwesomeP/dmxusb/blob/master/examples/DMXUSB_FastLED/DMXUSB_FastLED.ino

Aside from having to correct the colours, everything worked first time. The slower 115200 baud seems to be much more compatible.

**Comment by Kilted-Klingon** [comment]
Hey @fiskn , thanks for providing your findings and thoughts here.  I haven't gotten to the stage where I'm ready to start building/adding DMX effects in our setups, but this will certainly come in handy.  

Do you mind sharing more about your particular setup and how adding DMX effects has specifically added to the overall gameplay?  What I'm trying to get to is deciding whether or not it's worth the time/investment to make it happen.  Hearing/seeing how others have done so is very helpful.  Thanks for considering.

BTW, I don't see that you're on our Discord server.  Here's a link to check it out if you're interested:
https://discordapp.com/channels/206597597455056898/206597597455056898/341469409044463618

**Comment by fiskn** [comment]
It's nothing special yet, I was hoping just to put a small string of the smart LED's up behind the MainScreen (TV) or something similar, to give a bit of ambient effect. The benefit of the Arduino/WS2812 combo is that its cheap and very simple, I wouldn't have invested the time in anything else. You can probably also run about 10-30 (Depending on colour and brightness) of them off a standard USB port, so could be good for something portable.

Thanks for the link, will check it out

**Comment by daid** [comment]
Arduino can do 2500000 with a PC, but getting it to work can be a bit tricky. Also, the DMX512SerialDevice uses a "break" mechanism to indicate start of packet, which isn't implemented on all Arduinos (especially the newer ones)

I have done some Arduino code to interface with the DMX512SerialDevice, but it relied on timeouts to detect the start of packet. The EnttecDMXProDevice is much smarter to use in this case.

I can put something together quickly if you cannot get it to work. I lost the code of my initial test.

**Comment by fiskn** [comment]
Everything seems to be working fine with the EnttecDMXProDevice option, so happy to stick with that. It sounds like running much above 115200 generally with Arduino's starts to get tricky as the error's from clock skew start to play a larger part.

**Comment by daid** [comment]
Except that the 16Mhz divides really well into 250000 and really bad into 115200 with the limited baudrate divider of the AVR. And the AVR USART isn't that bad in working with a bit of clock skew. The problem is more that you are nearing the Mhz, and that opens up more and more options for electrical interference.

Also, 250000 is a non standard baudrate, which gives all kinds of drivers and API problems.
