### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by tdelc** [daid/EmptyEpsilon#928]
Hi,

I have some problems to compile EE for debian OS. I follow the old (make) and the new (ninja) commands to compilation, and both break with this error : 
/home/thomas/EE/SeriousProton/src/multiplayer_proxy.h:12:10: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type std::unique_ptr<TcpSocket> newSocket;

for somes files. Does anyone has a advice to correct this ? Should I add "#include <memory>" into all broken files (as explain here : https://stackoverflow.com/questions/18078153/error-unique-ptr-is-not-a-member-of-std )

Thanks a lot !

PS : I use Debian GNU/Linux 8 (jessie) 32 bits (to use netboot system too)

**Comment by daid** [comment]
Adding `#include <memory>` in multiplayer_proxy.h and/or a few other header files might fix it.
Odd that I do not have this issue, my CI system build on debian...

**Comment by tdelc** [comment]
Is it a problem to add this into the vanilla version ? (Not a problem if
not, just to known if i need to fork or not). I can make the PR if yes.

**Comment by daid** [comment]
Yes, that is fine if it fixes an issue

**Comment by tdelc** [comment]
Ok, from now, I succeed to compile with adding #include <memory> into these files : 
Serious Proton : networkAudioStream.h multiplayer_proxy.h
Empty Epsilon : crewStationScreen.h mainScreen.h

I wait from one of my users to confirm that it's work form him with this to do the PR.
