### ISSUE TITLE
Voice communication

### ISSUE THREAD

**Issue by tdelc** [daid/EmptyEpsilon#929]
Hi,

I see that there is a new feature to send voice communication between ship, but I cannot use it. Can someone explain me with a short example ?

**Comment by daid** [comment]
Press and hold tilde key (next to the 1 key on standard keyboards) to talk to any other client connected to the same ship as yourself.
Press and hold the backspace key to talk to the whole server.

Note that this feature is experimental, and does not work as well as discord/teamspeak. If it proves useful it will be possible to rebind the keys.

**Comment by oznogon** [comment]
Added to the wiki: https://github.com/daid/EmptyEpsilon/wiki/Voice-chat

**Comment by tdelc** [comment]
Thanks a lot, it will be very usefull for me. it will be fine to rebind the keys (into the options.ini it will be perfect)
