### ISSUE TITLE
REQUEST - Selection of Waypoints to return Waypoint Name/Heading/Distance

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#95]
I think pretty much everyone I've seen in the Relay chair has tried to place a Waypoint and then select it in order to provide a Heading/Distance reading to the Captain and Helm where there is no known SpaceObject available for selection. Ideally allow Science to select Waypoints it can see.

**Consideration:** If selection is implemented would recommend leveraging this to change the Delete Waypoint workflow as follows: 
* Delete Waypoint button is inactive unless a Waypoint is selected.
* Select Waypoint to enable Delete Waypoint button.
* Select Delete Waypoint to delete the currently selected Waypoint.

**Nice to have**
Would be good to be able to adjust the position of the selected Waypoint, especially if a request for supplies/reinforcements has been made and the Player Ship has to move before they arrive. I assume the tug/fighter would adjust course just like ships attempting to attack a target.

**Comment by daid** [comment]
That waypoint adjustments are not really possible is by design. It requires relay to plan ahead, which adds a gameplay factor.

(The rest I pretty much agree with)

**Comment by Wrongtown** [comment]
Fair enough, I admit i suspected this might be the case.
