### ISSUE TITLE
Feature request: Be able to configure zones to ignore black holes

### ISSUE THREAD

**Issue by Xansta** [daid/EmptyEpsilon#961]
I would like for some zones to just be markers in space for regions. If the zone gets sucked into a black hole, it makes it difficult. Can there be an option to make zones immune to black holes? I'd prefer for it to be a script exposed option rather than a global "all zones must ignore black holes." I can see where zones being affected by black holes could be useful.

**Comment by daid** [comment]
> I can see where zones being affected by black holes could be useful.

Really? Because I cannot... it's more of an oversight then a feature

**Comment by Xansta** [comment]
Well, I imagine a zone following a moving target around. I guess even in that case, immunity to black holes would be fine. If it's easier to make all zones immune to black holes, that would be fine with me.

**Comment by Xansta** [comment]
Wormholes also affect zones: the zone is moved through the wormhole to the wormhole's destination target
