### ISSUE TITLE
REQUEST - Physical Probes

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#97]
As referenced in #96 the Probes launched by Relay don't "physically exist" in the game, I've had a couple of players comment "Where is our probe? Should be here but I can't see it."

A model for the probe would add to immersion, and also allow for the following mechanics to be developed:
* Destruction of probes by other forces.
* Collection of probes to re-use.
* Re-stocking probes at stations.

**Example**
```lua    
--Probe, for augmenting the normal sensor suite. There's a fine line between exploration and espionage.
    template = ShipTemplate():setName("Astrometrics Probe"):setModel("SPAAAACE_core")
    template:setHull(20) --Maybe even lower?
    template:setShields(5) --Maybe even lower?
    template:setSpeed(1000, 10, 15) --I'm not sure how fast probes currently move.
    template:setDescription([[The Astrometrics Probe is an invaluable tool for mapping out sectors where no-one has previously gone as far as we are aware. Tiny and incredibly fast, the probe is essentially a missile with a payload of sensors and a transmitter rather than destructive elements.  Due to the extremely lightweight build there's not much in the way of armor or shielding; probes discovered by hostile or defensive entities do not provide survey information for very long at all.]])
```

**Comment by daid** [comment]
Just need a proper model for them. As the "exist" and "not exist" at the same time. They are there, but do not have a 3D model.

**Comment by Wrongtown** [comment]
That was an excellent excuse for me to check out the various Artifact models (still hadn't scripted up a museum of the little blighters) but sadly none of them really fit the bill do they?

By the way if anyone has been meaning to take a look and lazy like me, I've attached a .txt copy of the lua script I created with all the unusual objects lined up for your observation. Just change the extension to .lua and drop it into the /scripts/ directory and it will be added to the bottom of the list.

[scenario_99_artifacts.txt](https://github.com/daid/EmptyEpsilon/files/88565/scenario_99_artifacts.txt)

**Comment by Fouindor** [comment]
Maybe one of SolCommand's models for communication probes :
https://public.blu.livefilestore.com/y3pa_fhFR8hiZSndVwdLoIkkAXmJBI15a0qwWIRqe_eC6SP-Eu0uNWQUHcKfe20rvGDgUfePwiAwb6FQh3zyMpmxn8wYV1QxLI99OAQSewy9QY/communication_satellite_v2.jpg?psid=1
https://public.blu.livefilestore.com/y3pcm4452I2cXJlzXRftgtei6AeFyy8lFqDPxP5w4AObKuldb5O9vFwxoVZwhRrK3I087X_GqnHEI76ktwb47_NmHxFOQJw-lfOLxJhQn1yasU/communication_satelite.jpg?psid=1

The file is in 3ds, a bit of conversion would be needed, but I think we can use it.

**Comment by daid** [comment]
But it does not have textures.

**Comment by daid** [comment]
Model for probes was added
