### ISSUE TITLE
onNewPlayerShip not always called

### ISSUE THREAD

**Issue by StarryWisdom** [daid/EmptyEpsilon#973]
currently there are 3 ways to spawn player ships
spawn player ship on the server menu
the create mode for player ships (added in about a fortnight back)
PlayerSpaceship() inside of a script

only the first calls onNewPlayerShip
I can see 2 ways of fixing it.

The first way is via editing setTemplate to call it
The upside of that is it is the only way I can think of that will catch PlayerSpaceship(). I think this is a plus as it allows script writers to use onNewPlayerShip to attach lua variables to every space ship and not be concerned they forgot any call site
The downside is it feels the wrong time to call onNewPlayerShip and as such I am concerned I may be missing a problem.
Also a playerSpaceship can have a template set 0 or 2+ times.
0 times currently causes a crash, but that is a bug that probably should be fixed
2+ times could be guarded against, though causes the soultion to be more ugly

The second way would be saying that onNewPlayerShip isnt called for lua code and fixing the object creation screen.

I like the first soultion more as a script writer, but fear there is going to be some unintended side effect.

I am happy to write either, but wanted to check which soultion was wanted and that there isnt an obvious third way I am missing

**Comment by Xansta** [comment]
The PlayerSpaceship() method does not really need to call onNewPlayerShip since the script writer can invoke that function directly if desired. Resetting or changing the template may be a feature, not a bug.

**Comment by JonathanILevi** [comment]
Is it not possible to call `onNewPlayership` in `PlayerSpaceship`?

Not calling `onNewPlayership` does seem inconsistent, but it could actually be convenient.  The current version of `onNewPlayership` is for when the player spawns their own ship.  Maybe `onNewPlayership` should just be renamed to `onSpawnedPlayership` or `onPlayerSpawnedPlayership`, or just a comment/documentation specifying what "new playership" is referring to.

**Comment by StarryWisdom** [comment]
putting the call to onNewPlayerSpaceship in the PlayerSpaceship constructor was my first attempt, daid pointed out that if it is there the PlayerSpaceship has not yet had a template assigned to it, which makes it much harder to do useful things with it. Indeed I'm struggling to think of many things that could be done when you dont know the class it will become.

**Comment by StarryWisdom** [comment]
tom made a comment on discord that maybe there should be a different callback for spawning ships via the gm menu.
Initally I didnt see any use, but there may be minor use as the gm can select a location where as the spawn button cant (and thus may need a more sensible default location).
I am unsure that is worth a different callback, but if that is what is wanted I can write that easily
