### ISSUE TITLE
REQUEST - Probe Stock Count

### ISSUE THREAD

**Issue by Wrongtown** [daid/EmptyEpsilon#98]
Independent but complimentary to Issues #96 & #97 I'd like to see an indicator of the number of probes aboard the ship for Relay. In a recent session one crewman got a little bit probe-happy after his first attempt at utilizing them and roughly 40 seconds later the ship was completely out.

**Comment by lunerfox** [comment]
With probes being a scriptable, limited quantity, it might be okay from a balancing perspective to allow probes to either:

A) Assisted Scanning: Reduce the difficulty of Science console scanning by 1 level (So a detailed scan would only have 1 scan bar, if the probe is within range. 

B) Automatic Scanning: probes automatically perform basic scans of surrounding ships. Each probe scans one ship at a time until all ships have been identified

**Comment by zorilya** [comment]
Having messed around with probes a little now I feel like they don't have a maximum range. Am I mistaken? If not then I propose a maximum range from the ship... a large one, but still something to avoid just probing hundreds of thousands of Km into space. 

perhaps there could be multiple kinds of probes, some allowing for greater distance. E.g the kind that s ship is fitted with normally could probe out to 50,000 Km while a more well equipped version (that a station might have for instance) would be able to probe 500,000 Km or something like that.

**Comment by Wrongtown** [comment]
Was going to close this as the original change request was addressed and is in the current release. @daid @lunerfox & @zorilya are you happy with that and suggestions around additional probe functionality & maximum range can be raised as new issues? 

Seems like there's a risk of having a bunch of sub-stories hanging off issue names which have been resolved. Don't want them to get ignored but not much point having a Probe Count item still sitting here a month after probe count was delivered!
