### ISSUE TITLE
BUG/REQUEST - Docking procedure

### ISSUE THREAD

**Issue by matthiaswlkp** [daid/EmptyEpsilon#99]
BUG: When you approach the base station at warp, option for docking still becomes available. If you click it, the ships turns to reverse AFTER it slows down from warp, which can take a longer while. Then you are stuck with your ship on 50% reverse for a VERY long time. Maybe docking should be disabled untill Warp is 0?

Somewhat related to that:

REQUEST: Would it be possible to somehow break the docking procedure?

Hello by the way. I'm sorry if I missed the above in other posts...

I have some mileage in Artemis and my group is getting more and more interested in alternatives. This project simply looks great! We hope to use it more :).

**Comment by zorilya** [comment]
Noticed the same issue last night... perhaps when a change in impulse is registered above 0% docking could be aborted?

**Comment by daid** [comment]
Docking can be canceled in the latest version. Does that solve this?

**Comment by amir-arad** [comment]
@daid sounds like a closed issue to me
